### ISSUE TITLE
Missing relations group filter

### ISSUE THREAD

**Issue by jmediamanager** [ShokoAnime/ShokoServer#1]
Create a new group filter which shows anime related to anime in your collection, which you don't have yet.
For example: you have the first season in your collection, but don't have any episodes from the second season

**Comment by ElementalCrisis** [comment]
If I'm reading this right, this would just add a whole bunch of empty series to your collection right? I don't think a filter would be the best way to do this.

Instead, this idea can be  used and expanded on in Desktop 2 with Shoko Lists, we could auto-populate a list with this information. 

Closing this issue for now.

**Comment by bigretromike** [comment]
adding empty series is not as bad idea as you would think;
the only thing would need to be added that is the information if this series is 'fake' aka 'empty' or not; 

that way you could list all those releated series in filter and see (by different color etc) that the group of series you want to watch (or already watching) is BIG, HUGE or small and contain 1-2 series. And using different thing like 'shoko lists' would end up that you have series information in both lists and later if added in series; 
Imo the first thing is so easy to add and require just adding 1 column to serie with 'fake' indicator -> from there you could build upon it; like adding serie to 'fake' series make it `real`, show all wanted series that you want to download - something like bookmarkes did in past; 

What you think @ElementalCrisis

**Comment by ElementalCrisis** [comment]
I have no problem with empty series, when I mention Shoko Lists I'm talking about a new feature that's part of Desktop 2 that allows users to create lists such as "To Download" or "To Replace". We'll also include some auto-populated lists using user and community data. 

But yeah, Shoko Lists are the evolution of Bookmarks in current Desktop.

**Comment by bigretromike** [comment]
so they will store series id ?

**Comment by ElementalCrisis** [comment]
Sure, I don't see why not.
