### ISSUE TITLE
Issue with '<' and '>' in Series Title

### ISSUE THREAD

**Issue by natyusha** [ShokoAnime/ShokoServer#1000]
## VERSION INFORMATION

Server Version: latest daily

Desktop Version: latest daily

## DESCRIPTION

Encountered an issue with a title that had greater than and less than signs in it appearing as html formatted "&gt;" and "&lt;" respectively.

## STEPS TO REPRODUCE

Add a file from a show with greater than and less than signs in the title such as: https://anidb.net/anime/12228

Look at the title in Shoko Desktop's Collection and observe how `&lt;` and `&gt;` will be used in place of `<` and `>`

**Comment by da3dsoul** [comment]
Thanks I'll check it out. I'll ping you when a daily addresses it

**Comment by da3dsoul** [comment]
https://github.com/ShokoAnime/ShokoServer/commit/fb4ccfe48c9512d66468940abc25489887bc8442
