### ISSUE TITLE
Default Renamer Does Not Rename Subtitle Files

### ISSUE THREAD

**Issue by ElementalCrisis** [ShokoAnime/ShokoServer#1001]
## VERSION INFORMATION

Server Version:  4.1.2
Desktop Version: 4.1.2

## DESCRIPTION

As mentioned on Discord, the default renamer does not rename sub files in the same folder, it does apparently rename them on move per @da3dsoul but I did not test this. 

## STEPS TO REPRODUCE

Rename a series that has external sub files.

**Comment by Mik1ll** [comment]
I haven't tested lately, but there is logic to rename them [here](https://github.com/ShokoAnime/ShokoServer/blob/6cd38c353fcfe84ad6ff8326216952f0fabf5d58/Shoko.Server/Models/SVR_VideoLocal_Place.cs#L133-L155). This relies on mediainfo reading files with the same base name in the folder for textstreams [here](https://github.com/ShokoAnime/ShokoServer/blob/6cd38c353fcfe84ad6ff8326216952f0fabf5d58/Shoko.Server/FileHelper/Subtitles/SubtitleHelper.cs#L18). A [problem](https://github.com/ShokoAnime/ShokoServer/pull/873) I found a long time ago was that mediainfo could not handle subtitle files with some encodings, causing it to fail to detect the text streams and ignore the files. This may be the reason.
I believe that a dumber file extension based approach may be more appropriate here.

**Comment by ElementalCrisis** [comment]
Yeah just seems like a bug at this point. Wanna give it a go and see if you can fix it?
