### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by TheBinaryLoop** [ShokoAnime/ShokoServer#1014]
## VERSION INFORMATION

Server Version: dev

Desktop Version: latest

If you've compiled your own version, please use the last commit you compiled.

## LOG FILE

N/A

## DESCRIPTION

Hi shoko-Teams,
I would like to contribute to the project and couldn't find documentation on how to do so. Is there a documentation about the different modules? Anything to help someone like me getting started helping this project?

## STEPS TO REPRODUCE

N/A

**Comment by da3dsoul** [comment]
Not really. Shoko is old, so any documentation written about the layout of the code would probably be time better spent on refactoring the code to make more sense.
If you want to get started, the first step is getting it building.
To pull, fork it obviously, then do a `git clone` with `--recurse-submodules`.
To build, you'll want the .net 6 SDK, but then the solution should build without any complications.
As for where to start, hop on discord... Like you did as I was typing this sentence.... Nice. I'll continue there

**Comment by revam** [comment]
@da3dsoul can we close this issue now? 🤔
