### ISSUE TITLE
Add misc/episode type to tags in rename scripts

### ISSUE THREAD

**Issue by papaj-na-wrotkach** [ShokoAnime/ShokoServer#1038]
Hello, I wanted to use file renaming scripts to cleanup my collection and I'm missing this one feature. On anidb every episode has it's type:
- Regular Episode
- Special
- Opening/Ending
- Trailer/Promo/Ads
- Parody/Fandub
- Other

It would be nice to have information about the type of episode in filename. In my case I would like to name my episodes like the episodes are displayed on anidb:

![image](https://user-images.githubusercontent.com/29522138/215264127-f9cb8f9e-e88d-4830-8e08-d0604fa1d2f4.png)

i.e.:
- Regular Episode - "01.mkv"
- Special - "S01.mkv"
- Opening - "OP01.mkv" (also "OP01b.mkv")
- Ending - "ED01.mkv" (also "ED01b.mkv")
- Trailer/Promo/Ads - "T01.mkv"
- Other - "O01.mkv"

Is there possibly already a way to achieve this?

**Comment by da3dsoul** [comment]
Closing this so I don't forget. You can continue replying to it if you need more help.

**Comment by papaj-na-wrotkach** [comment]
Thank you! That's exactly what I needed. Btw is there a documentation for the rename scripts apart from the mentioned file?

**Comment by da3dsoul** [comment]
Kind of. This isn't complete, as we've added things like H() to it, but this is what it was based on.
https://wiki.anidb.net/WebAOM#Scripting

**Comment by papaj-na-wrotkach** [comment]
Thank you again. And also why `special` and `credit` types have the prefix added by default?

I tried
```
IF H(E) DO ADD 'E%enr'
IF H(S) DO ADD 'S%enr'
IF H(T) DO ADD 'T%enr'
IF H(C) DO ADD 'C%enr'
IF H(P) DO ADD 'P%enr'
IF H(O) DO ADD 'O%enr'
```
but it renamed `SP01.mkv` to `SS01.mkv` and `OP01.mkv` to `CC01.mkv`

When i tried:
```
IF H(E) DO ADD 'E%enr'
IF H(S) DO ADD '%enr'
IF H(T) DO ADD 'T%enr'
IF H(C) DO ADD '%enr'
IF H(P) DO ADD 'P%enr'
IF H(O) DO ADD 'O%enr'
```

it worked as expected:
![image](https://user-images.githubusercontent.com/29522138/215270866-7971f9cb-a040-4212-9f55-06b340a6352c.png)

**Comment by da3dsoul** [comment]
Facepalm...
It already adds the type for anything but a normal episode. That was my bad for not checking. Personally, I would add the episode name to Credits, as those will just be things like Opening, Ending 1, etc

https://github.com/ShokoAnime/ShokoServer/blob/3c92e6a8663be31c0b4ab3c8d34968a4d783b1c0/Shoko.Server/Renamer/LegacyRenamer.cs#L1602

**Comment by revam** [comment]
We also have other renamers you can use if you don't like the AOM script environment.

**Comment by papaj-na-wrotkach** [comment]
Basically `%enr` for specials and credits returns not only a number but a number with prefix. I think it's because the API returns prefixed string. I don't know about UDP API, but for http API it's like this (the `epno` tag):
```
...
<episode id="136268" update="2012-01-10">
  <epno type="4">T4</epno>
  <length>3</length>
  <airdate>2012-01-09</airdate>
  <title xml:lang="en">PV 4</title>
</episode>
<episode id="136357" update="2012-03-26">
  <epno type="3">C2</epno>
  <length>2</length>
  <airdate>2012-01-13</airdate>
  <rating votes="6">6.99</rating>
  <title xml:lang="en">Ending 2</title>
</episode>
<episode id="136358" update="2012-03-26">
  <epno type="3">C1</epno>
  <length>2</length>
  <airdate>2012-01-13</airdate>
  <rating votes="3">3.94</rating>
  <title xml:lang="en">Opening</title>
</episode>
...
```

Now the question is if the `%enr` should be pre-parsed by Shoko or should the parsing be a done in renamer script like this:
```
IF H(E) DO ADD 'episode'
IF H(S) DO ADD 'special'
IF H(T) DO ADD 'trailer'
IF H(C) DO ADD 'credit'
IF H(P) DO ADD 'parody'
IF H(O) DO ADD 'other'

DO ADD '_%enr'

//  Remove prefix before episode number: "special_S01" => "special_01"
IF H(S) DO REPLACE 'special_S' 'special_'
IF H(T) DO REPLACE 'trailer_T' 'trailer_'
IF H(C) DO REPLACE 'credit_C' 'credit_'
IF H(P) DO REPLACE 'parody_P' 'parody_'
IF H(O) DO REPLACE 'other_O' 'other_'
```

**Comment by papaj-na-wrotkach** [comment]
> Facepalm... It already adds the type for anything but a normal episode. That was my bad for not checking. Personally, I would add the episode name to Credits, as those will just be things like Opening, Ending 1, etc
> 
> https://github.com/ShokoAnime/ShokoServer/blob/3c92e6a8663be31c0b4ab3c8d34968a4d783b1c0/Shoko.Server/Renamer/LegacyRenamer.cs#L1602

The episode name is good solution as it also solves my problem with separating openings and endings from credits type episodes. The question is if they are always things as simple as `Opening 1` or `Ending 2b`...

**Comment by papaj-na-wrotkach** [comment]
> We also have other renamers you can use if you don't like the WebAOM script environment.

Do you mean the [GroupAwareSortingRenamer](https://github.com/ShokoAnime/ShokoServer/blob/master/Shoko.Server/Renamer/GroupAwareSortingRenamer.cs) or something entirely different?

**Comment by da3dsoul** [comment]
The episode name will only be that simple for Credits.

No, he means things like https://github.com/Mik1ll/LuaRenamer

**Comment by da3dsoul** [comment]
Wrong button

**Comment by papaj-na-wrotkach** [comment]
> The episode name will only be that simple for Credits.

Not always. Today I found [this one](https://anidb.net/e66498) which is not...
Well, I guess I'll use the other renamer because it should have more options and it should allow me to parse openings/endings filenames.

You could also add functionality to detect credit episode type by its relations:
![image](https://user-images.githubusercontent.com/29522138/215320523-c0bc719f-b274-4001-98c3-04296479c332.png)

It could be done by taking first relation or by counting how many opening and how many ending relations it has (and choosing `opening` if there are more opening relations or `ending` - if there are more ending relations).

It won't work for every credit episode though - e.g. that episode I mentioned before has no relations. In such cases the type could be `null` or `credit` so user can detect it and e.g. try to parse title, just use title or use the `credit` as 3rd type of credit episodes (however strange it sounds).

**Comment by da3dsoul** [comment]
We can't get the song relations from the API. When I said credits, that's what the C stands for in episode types, it is generally reserved for creditless versions of the OP/ED.
That appears to be an exception. Usually that would have it's own special, not a Credits episode

**Comment by papaj-na-wrotkach** [comment]
I understand how `credit` episodes work, this one certainly is an exception from other `credit` type episodes - it's only fanservice + some music (maybe that's why someone added it as a opening/ending). I agree that "The episode name will only be that simple for Credits." but my point is that they could be anything.

I didn't know that the API doesn't provide info about episode-song relation though.

Thank you for your support. Have a great day!

**Comment by da3dsoul** [comment]
Yep np. I prefer to over-explain if there seems to be a miscommunication somewhere. Our community is very international with English as a second or third language being common
