### ISSUE TITLE
Task for files missing group info

### ISSUE THREAD

**Issue by Terrails** [ShokoAnime/ShokoServer#1044]
Currently if a file is missing group info on import, there is no way to automatically fetch new data when/if it is changed. It would be great to add a task to fetch group info on an interval from the API on these files again.

**Comment by revam** [comment]
Already added in 4.2.0. Idr which commit.

![Screenshot_20230407_051241_Samsung Internet](https://user-images.githubusercontent.com/7761729/230533677-5bfe5465-2a11-4f02-b1cd-1a581cf61f01.png)

**Comment by revam** [comment]
Or did you mean a scheduled task? If yes then you ca  reopen this issue.
