### ISSUE TITLE
Series Without a Japanese Trascription for the Main Title are Unsearchable

### ISSUE THREAD

**Issue by natyusha** [ShokoAnime/ShokoServer#1046]
## VERSION INFORMATION

Latest (https://github.com/ShokoAnime/ShokoServer/commit/253918fa65702019677d4f4494567f37122e22bd)

## DESCRIPTION

Series which do not have an `x-jat` Main Title on AniDB do not show up in searches. In practice, this means that anything that has a Main Title which is a Korean (`x-ko`), Chinese (`x-zht`). or Unknown (`unk`) transcription won't show up unless searching for synonyms instead of the main title. This causes various issues such as auto matching failing in Plex if using the Main Title and not a Synonym or series being harder to find in Desktop.

## STEPS TO REPRODUCE

1. Find a series without a Japanese transcription for the title.
2. Attempt to search for it in Desktop or through the API (using the main title and not a synonym).

A few examples of series that meet the above criteria are linked below:

https://anidb.net/anime/12560
https://anidb.net/anime/12843
https://anidb.net/anime/15683

## EXAMPLE
Using 'Wu Shan Wu Xing' as an example running the search below will not return any results for the series:

`/api/v3/Series/AniDB/Search/Wu%20Shan%20Wu%20Xing?includeTitles=true&pageSize=1&page=1`

## WORKAROUND
For series that are effected by this issue one can simply search for a synonym to find it. Using 'Wu Shan Wu Xing' as an example once again; but instead searching for the synonym 'Fog Hill of Five Elements' the series will show in the search.

 `/api/v3/Series/AniDB/Search/Fog%20Hill%20of%20Five%20Elements?includeTitles=true&pageSize=1&page=1`

**Comment by da3dsoul** [comment]
Interesting. We can add some fallbacks. I didn't even know x-ko existed

**Comment by natyusha** [comment]
Now that you mention it `x-ko` might not actually be used since i'm looking through here: [South Korean production](https://anidb.net/tag/6166/animetb) and it seems like they are all just set to `unk`

**Comment by revam** [comment]
English and romanji should be searchable, plus any language in the user's global language preference.

@natyusha can you try to add Korean transcription in the language preference then searching for the title?

**Comment by natyusha** [comment]
I don't see Korean (or Chinese) transcription as an option to add to the language settings. But that wouldn't matter anyways as shows using Korean transcriptions seem to be set to `unk` (as mentioned [here](https://github.com/ShokoAnime/ShokoServer/issues/1046#issuecomment-1460289960))

**Comment by revam** [comment]
@natyusha  Add `unk` (and any other languages like `x-zh`) to your preferred languages list in the json settings (or select them in the list in the web ui or desktop) and it should work… I hope.

**Comment by revam** [comment]
Actually, the main title is always added to the searchable titles for the series now, so you might not need to do that to search for the main title.

**Comment by revam** [comment]
So searching for the main title is working in the latest daily, regardless of the language preference set in the settings.

E.g. searching for the example used in the OP in v2 and v3 (which both uses the same internals now);
![image](https://user-images.githubusercontent.com/7761729/233850541-2e88f928-69c3-4fdc-b34b-a17fb537490a.png)
![image](https://user-images.githubusercontent.com/7761729/233850593-0bccffe8-d13f-4639-8d62-6ab9c5dce4d4.png)
![image](https://user-images.githubusercontent.com/7761729/233850695-20950e9c-725d-401f-9fe2-36abf66c44af.png)
