### ISSUE TITLE
Trakt error 400 Bad request

### ISSUE THREAD

**Issue by Thomiehawk** [ShokoAnime/ShokoServer#1062]
## VERSION INFORMATION

Server Version: 4.2.2

Desktop Version: 4.2.1

If you've compiled your own version, please use the last commit you compiled.

## LOG FILE

https://logpaste.com/v9vtI9lb

## DESCRIPTION
Trakt scrobbling is not working and throws an error syncing watched states doesn't work either

## STEPS TO REPRODUCE

Link Shoko to trakt.tv with the activation code, app shows up in linked apps on trakt.tv
When starting playback of an episode the error 400 bad request is displayed, syncing trakt watched status throws errors too

**Comment by krbrs** [comment]
Can not reproduce this, scrobbling is working fine here, e.g.:

```
16:52:19| PlexWebhook --- media.stop: com.plexapp.agents.shoko://2676/1/2?lang=en
16:52:19| TraktTVRateLimiter --- TraktTVRateLimiter#5d8777cb-9a10-4297-ba81-a49e447ff5eb: Time since last request is 10491 ms, not throttling.
16:52:19| TraktTVHelper --- Trakt SEND Data\nVerb: POST\nuri: https://api.trakt.tv/scrobble/stop\njson: {"episode":{"season":1,"number":2,"title":null,"ids":{"trakt":"1011154","tvdb":null,"imdb":null,"tmdb":null,"slug":"heidi","tvrage":null}},"progress":0.0}
16:52:19| TraktTVHelper --- Trakt SEND Data - Response
Status Code:201
Response: {"id":0,"action":"pause","progress":0.0,"sharing":{"facebook":false,"twitter":false,"tumblr":false},"episode":{"season":1,"number":2,"title":"Grampa's Mountain Cabin","ids":{"trakt":1011154,"tvdb":385685,"imdb":null,"tmdb":969965,"tvrage":null}},"show":{"title":"Heidi","year":1974,"ids":{"trakt":61328,"slug":"heidi","tvdb":82927,"imdb":"tt0070968","tmdb":29452,"tvrage":null}}}
```

Can you please verify that the series is linked to a Trakt series?

**Comment by Thomiehawk** [comment]
The series is linked to trakt with the episode number of Anidb matched to Trakt's. Tried scrobbling via the internal mpv player and plex, (I got plex pass) both without success

**Comment by Thomiehawk** [comment]
I've tried uninstalling and re-installing twice but that didn't work
