### ISSUE TITLE
Manual episode TvDB linking not possible for specific series/episodes

### ISSUE THREAD

**Issue by shigins** [ShokoAnime/ShokoServer#1063]
## VERSION INFORMATION

Server Version: 4.2.2.0

Desktop Version: 4.2.1.0

## LOG FILE
Log taken from after the screencaps below, showing output from requesting fresh TvDB data for the series, and relinking it.
These actions did not resolve it, nor did restarting Shoko. 
https://logpaste.com/bnBwfDbn

## DESCRIPTION

Specific series have incomplete TVDB data which prevents accurate TvDB linking of these series. The issue is visible when viewing TvDB matches or attempting to override the TvDB link.
When attempting to override a link, the only options given in the dropdown are those that correspond to episodes visible within the TvDB portion of the AniDB-TvDB matches chart, this makes establishing an accurate link impossible.
Downloading fresh TvDB data and unlinking/relinking does not resolve the issue.

## STEPS TO REPRODUCE

1. On Shoko Desktop, view the "Preview TvDB Matches" table on the page of certain series, or attempt to override the TvDB link for an episode within the series.

Barkamon (AniDB Series ID: 10111) was one of these series that another member of the discord was able to reproduce the issue with. Only a handful of specials were options when it came to overriding episode links. 

Image showing the described issue using Barakamon as an example:
![image](https://github.com/ShokoAnime/ShokoServer/assets/100189488/e3bba3d4-4354-4e17-b848-1d7740cd743d)
![image](https://github.com/ShokoAnime/ShokoServer/assets/100189488/b373914e-b710-4b99-a2f4-d983ddd997b0)

The following series also gave me a similar issue:

-_Series, AniDB Series ID, TvDB Series ID, Issue_
-Naruto, 239, 78857, Season 1 is not available
-My Hero Academia(S05), 15484, 305074, episodes 4-15 of season 05 are not available
-Demon Slayer, 14107, 348545, Only episodes from Demon Slayer: Swordsmith Village Arc are available for linking
-Demon Slayer: Mugen Train Arc, 16803, 348545, Only episodes from Demon Slayer: Swordsmith Village Arc are available for linking
-Demon Slayer: Entertainment District Arc, 16054, 348545, Only episodes from Demon Slayer: Swordsmith Village Arc are available for linking
-No Game No Life, 9998, 278155, Only a few specials and NCOP/ED are available
-Jujutsu Kaisen, 15275, 377543, Only couple episodes and specials available
-Attack on Titan The Final Season (2023), 17303, 267440, Only specials are availabe
-Deadman Wonderland, 7902, 247997, Only episodes 09-12 are available
-Re:Zero - Starting Life in Another World, 11370, 305089, Season 1 is not available
-Food Wars! Shokugeki no Soma, 10901, 289909, Season 1 is not available
-Food Wars! The Second Plate, 11828, 289909, Episodes 1-9 are not available
-Food Wars! The Third Plate: Totsuki Train Arc, 13658, 289909, Only episodes from  Food Wars! The Fifth Plate are available

**Comment by harshithmohan** [comment]
Works on daily server and desktop 🤔

**Comment by shigins** [comment]
Switching to daily server did resolve the issue. Previously, refreshing the TvDB data had no affect on these options for me (was using Latest, not Daily). 

Before refreshing TvDB data
![image](https://github.com/ShokoAnime/ShokoServer/assets/100189488/e762ea4f-8c78-4fae-82b2-d2cd71caf034)
After refreshing TvDB data
![image](https://github.com/ShokoAnime/ShokoServer/assets/100189488/92a49cb5-707f-4d89-b9fe-226396442187)

Before refreshing TvDB data
![image](https://github.com/ShokoAnime/ShokoServer/assets/100189488/00870714-0e87-4bce-a297-df4c983a164e)
After refreshing TvDB data
![image](https://github.com/ShokoAnime/ShokoServer/assets/100189488/d777690c-5ac4-40d0-b4f6-8a9931770512)

Thanks
