### ISSUE TITLE
Groups created with "Short" name instead of "Main"

### ISSUE THREAD

**Issue by krbrs** [ShokoAnime/ShokoServer#1065]
## VERSION INFORMATION

Server Version: latest daily

Desktop Version: latest daily

## DESCRIPTION

After adding a series I found a weird group name like this (I could not say from the start which series it is):

<img width="1042" alt="groupname_1" src="https://github.com/ShokoAnime/ShokoServer/assets/57227244/330eb12e-f80e-47ca-b1d7-77f565d496d5">

<img width="805" alt="groupname_2" src="https://github.com/ShokoAnime/ShokoServer/assets/57227244/33a1675a-260e-432e-a627-5ab4e2fd14bf">

I found this to be the short name of the series instead of the "main" name. It's these two series for me which did cause this:

https://anidb.net/perl-bin/animedb.pl?show=anime&aid=13171
https://anidb.net/perl-bin/animedb.pl?show=anime&aid=14572
https://anidb.net/perl-bin/animedb.pl?show=anime&aid=12560

## STEPS TO REPRODUCE

Just add these series to Shoko, the groups need to be not present before.

**Comment by krbrs** [comment]
Found use that while talking to @revam, that "use synonyms" makes it do that. 

Also my prefs are missing "x-zht", which is why that happens in the first place.

I will tinker around what language is "x-zht" in the language options as it's not present as "Pinyin" on Shoko webui + desktop and note it down here later (+ might make a pr for changing it when I have time again)

I would like it to default to "main" instead of "short" tho, if none of the preferred options are available, then resort to the synonym which seems to be the "short" name. Will removing "use synonyms" do that?

**Comment by revam** [comment]
Removing "use synonyms" will make it default to the main title if no main or official title in any of the preferred languages are set for a series, yes. "Use synonyms" makes it so it doesn an additional check for _any_ title in the preferred languages and uses that if any are found.

**Comment by krbrs** [comment]
I will close this issue now as the commits should provide the desired behavior in the future.
Also after disabling the synonyms series were renamed as expected. 

For ShokoDesktop a manual daily build needs to be triggered after the Commons changed - it's not automatically done (at least it seems like this from the actions).
