### ISSUE TITLE
Images pulled from MovieDB inaccessible from desktop app

### ISSUE THREAD

**Issue by Altereno** [ShokoAnime/ShokoServer#1072]
## VERSION INFORMATION
Server Version: Daily with Docker

Desktop Version: Daily

## LOG FILE
`System.NullReferenceException: Object reference not set to an instance of an object. at Shoko.Server.Providers.MovieDB_Movie_Result.Populate(Movie movie, ImagesWithId imgs) in /usr/src/app/source/Shoko.Server/Providers/MovieDB/MovieDB_Movie_Result.cs:line 31: System.NullReferenceException: Object reference not set to an instance of an object. at Shoko.Server.Providers.MovieDB.MovieDB_movie_Result.Populate(Movie movie, ImagesWithId imgs) in /usr/src/app/source/Shoko.Server/Providers/MovieDB/MovieDB_movie_Result.cs:line 31`

## DESCRIPTION
Fanart pulled from the MovieDB have no preview, and are not able to be opened by the desktop app. Syncing the images to Jellyfin shows that the some of the images pull are not related to the series. Pressing the update MovieDB images button on a specific series on the desktop app results in an error in the logs.

![Screenshot 2023-06-23 142306](https://github.com/ShokoAnime/ShokoServer/assets/68705413/b14e9219-11c9-40ba-a556-9c18e463bd7d)
![Screenshot 2023-07-14 165759](https://github.com/ShokoAnime/ShokoServer/assets/68705413/48697df2-478f-498f-8446-0c081fb9cc48)

## STEPS TO REPRODUCE
Import a series with a MovieDB link.

**Comment by ElementalCrisis** [comment]
@revam tagging you just for consideration for your TMDB PR.

**Comment by harshithmohan** [comment]
> @revam tagging you just for consideration for your TMDB PR.

It's a desktop only issue, do we really need to consider it?

**Comment by ElementalCrisis** [comment]
More for just keeping in mind when grabbing images from TMDB.

**Comment by revam** [comment]
i fixed up all tmdb v1 endpoints for backwards compatibility, so if it just relies on shoko server to function then it should work. it shouldn't be an issue..  next year.
