### ISSUE TITLE
Sort the directories in the "Select Import Folder" of the WebUI by name (human-readable preferably)

### ISSUE THREAD

**Issue by EcceGratum** [ShokoAnime/ShokoServer#1095]
Everything is in the title, here is an example :

![image](https://github.com/ShokoAnime/Shoko-WebUI/assets/13237633/3f156ea9-fa53-49c1-bb5c-741712aff235)

**Comment by harshithmohan** [comment]
Moved to ShokoServer
API needs to return the folders in sorted order.

**Comment by revam** [comment]
forgot tonclose this. fixed in daiky server.
