### ISSUE TITLE
Auto Install of MySQL Option

### ISSUE THREAD

**Issue by jmediamanager** [ShokoAnime/ShokoServer#11]
**Reported by techmasterjoe, May 12, 2012**

http://dev.mysql.com/doc/refman/5.1/en/windows-installer-msi-quiet.html
link gives info on how easy MySQL and be put in to silent mode

hope the gives you some ideas.

**Comment by bigretromike** [comment]
We dont ship database solution with server, right ? @ElementalCrisis

**Comment by da3dsoul** [comment]
We can, but it's not a priority. I say let it sit until we know for sure if it's a good idea

**Comment by ElementalCrisis** [comment]
Maybe before when SQLite had issues but SQLite performance has improved so much over the past year alone that its should work just as well as MySQL and SQL Server. 

Plus, when that request was made, the MySQL installer was a lot more complicated then it is now.

**Comment by bigretromike** [comment]
Yeah, there is a tone create documentation on ShokoDocs and Mysql Docs that its a trivial like Next,Next,Next,Finish
