### ISSUE TITLE
Blue Exorcist Not Grouping Properly

### ISSUE THREAD

**Issue by lbux** [ShokoAnime/ShokoServer#1101]
## VERSION INFORMATION

Server Version: 4.2.2.0 (312802f)

Desktop Version: N/A

If you've compiled your own version, please use the last commit you compiled.

## LOG FILE

[2024-01-31.log](https://github.com/ShokoAnime/ShokoServer/files/14108345/2024-01-31.log)

## DESCRIPTION

[Blue Exorcist](https://anidb.net/anime/8148) is not being marked as the main series after recreating all shoko groups. [Blue Exorcist: Kyoto Saga](https://anidb.net/anime/12240) is the one being marked as the main series despite it being listed as a "side story" on AniDB. These are my relation settings.
![image](https://github.com/ShokoAnime/ShokoServer/assets/30765968/4d5929eb-6df5-4a9e-9a2c-2e0c4452b6d1) 

There was some troubleshooting done in the [discord](https://discord.com/channels/96234011612958720/96235819366371328/1202124878153793547) regarding my issue, but the steps did not resolve it. The logs show my most recent attempt of removing the Kyoto Saga from Shoko, recreating the group (and it working properly), and then rehashing the Kyoto Saga just for the issue to come back.

## STEPS TO REPRODUCE

Download Blue Exorcist, Blue Exorcist: The Movie, Blue Exorcist: Kyoto Saga, Blue Exorcist: Shimane Illuminati Saga. Wait for shoko to ceate/update groups. Download Blue Exorcist: Kyoto Saga. Wait for shoko to update groups. Recreate all groups and the main series should now be Blue Exorcist: Kyoto Saga.

**Comment by lbux** [comment]
AniDB had 12240 and 17786 as a bidirectional prequel relation. Setting 17786 as the sequel to 12240 in the XML, updating anidb data from XML, and then recreating the group fixes the issue.

**Comment by da3dsoul** [comment]
Oh fun. I'll keep an eye out for that
