### ISSUE TITLE
"Remove Missing Files (Keep in MyList)" action removes entries from MyList

### ISSUE THREAD

**Issue by krbrs** [ShokoAnime/ShokoServer#1102]
## VERSION INFORMATION

Server Version: latest daily

Desktop Version: latest daily

## DESCRIPTION

EC asked me to open a server issue for it.

Clicking on "Remove Missing Files (Keep in MyList)" in Beta WebUI, it is expected to remove entries from the database but not from MyList.

Contrary to the description of the command, AniDB commands are queued and entries removed from MyList one after another. 

## STEPS TO REPRODUCE

Remove files from your Library, click "Remove Missing Files (Keep in MyList)" and see the "Magic" happen in the logs.

**Comment by da3dsoul** [comment]
Lovely

**Comment by harshithmohan** [comment]
Fixed in daily
