### ISSUE TITLE
TypeError: exclusions.split is not a function

### ISSUE THREAD

**Issue by gacekssj4** [ShokoAnime/ShokoServer#1106]
## VERSION INFORMATION

Server Version: 4.2.2.0 (WebUI 1.1.6)
Desktop Version:  -

## LOG FILE

ERROR

You broke the Web UI, congratulations.

Hopefully useful information:
```
TypeError: exclusions.split is not a function

Trace:
    in RelationSettings
    in Connect(RelationSettings)
    in div
    in Resizable
    in DraggableCore
    in GridItem
    in div
    in ReactGridLayout
    in ResponsiveReactGridLayout
    in WidthProvider
    in SettingsTab
    in Connect(SettingsTab)
    in div
    in div
    in div
    in MainPage
    in Connect(MainPage)
    in Route
    in AuthenticatedRoute
    in Connect(AuthenticatedRoute)
    in Switch
    in Router
    in ConnectedRouter
    in ConnectedRouterWithContext
    in Connect(ConnectedRouterWithContext)
    in div
    in Unknown
    in Connect(Component)
    in ErrorBoundary
    in ErrorBoundary
    in components_Provider
    in app
```
## DESCRIPTION

I get error when entering settings menu. Only clearing cookies and browser storage allows to fix webui. 

It happend on older version. So i Upgraded to daily (like one week ago). 
Today I updated to newest daily and its still same. Settings tab does not work.

## STEPS TO REPRODUCE

For me: Enter Settings menu

**Comment by revam** [comment]
**Note**: _Copy-pasted from our discord server_;

# How to revert the Web UI back to a working __stable__ version 101

- Open Swagger by navigating to `http://<shoko host>:8111/swagger/index.html?urls.primaryName=3.0` or `http://<shoko host>:8111/swagger/index.html?urls.primaryName=V3` depending on your version of the server.  Be sure to replace `<shoko host>` with the IP or DNS name of your Shoko entry. (If in doubt, use the first URL.)

- Generate an API key to use by executing `POST /api/auth`, found under the "**Auth**" section in Swagger.
  Press the "Try it out" button, enter your username for `user`, your password for `pass`, and `"swagger"` for `device`, and press "**Execute**". Copy the API key (the value of the `"apikey"` field from the response).

- Assign the API key to the `ApiKey` field under the "**Authorize**" menu found at the top of the page.

- Execute `GET /api/v{version}/WebUI/Update`, found under the "**WebUI**" section in Swagger, making sure to select `Stable` for the `channel` and input `3` for the `version` if the `version` field is present.

- Reset the Web UI. Close the current tab, and open a new tab. Do not refresh the page. If you enabled "Remember Me" then you also have to clear the local storage in your browser for the site.

## How to clear local storage 102

- Open the **DevTools** in your browser. (You can do this by pressing **F12** or by going into the browser menu at the far right on the browser toolbar, then entering the "**More Tools**" sub-menu, and pressing "**Developer tools**" in **Chromium-based browsers** or "**Web Developer Tools**" in **Firefox-based browsers**.)

- Navigate to the "**Application**" tab in **Chromium-based browsers**, and "**Storage**" in **Firefox-based browsers**.

- Find "**Local Storage**" in the side-bar to the left and click it to reveal the available sites.

- Find the site matching the current site you're on (e.g. `http://localhost:8111`, etc.), and click it.

- **Chromium-based browsers**: In the panel to the right, click the ":no_entry_sign:" button between the "Filter" box and the ":x:" button. **Firefox-based browsers**: Right-click on any of the items in the right panel, then press "**Delete All**". If there are no entries on the page then you don't need to do anything.

And you're done, you can now close the tab and open a new tab and it should work as expected.

**Comment by gacekssj4** [comment]
Thank you. I searched discord for "exclusions.split". Thank you very much.
