### ISSUE TITLE
Feature Request: Configure number of workers from WebUI

### ISSUE THREAD

**Issue by WrayOfSunshine** [ShokoAnime/ShokoServer#1110]
## VERSION INFORMATION

Server Version: 4.2.2.0
[(d1807ea)](https://github.com/ShokoAnime/ShokoServer/compare/d1807ea...master)

Desktop Version: Not using Shoko Desktop.

## LOG FILE

N/A

## DESCRIPTION

I have no desire to use Shoko Desktop via Wine/etc, so I'd like to see more functions integrated into the WebUI. This feature request is to allow for modifying the number of worker threads in Shoko Server from the WebUI.

## STEPS TO REPRODUCE

N/A

**Comment by da3dsoul** [comment]
Unfortunately, I'm not sure it's possible, as Quartz creates the thread pool at startup from the config, and I know of no way to re-initialize it

**Comment by WrayOfSunshine** [comment]
Dang. Couldn't even just update the config and kick off a restart of the server as a workaround?

**Comment by da3dsoul** [comment]
We don't have a way to restart the server from the application

**Comment by ElementalCrisis** [comment]
I'd rather not see this added to the Web UI, if it's even possible as our users tend to leap first without looking, especially our Linux users, 

Just seems like a ton of extra troubleshooting to me.
