### ISSUE TITLE
Feature Request: Ability to decide which sites to use for connectivity testing.

### ISSUE THREAD

**Issue by xNinjaKittyx** [ShokoAnime/ShokoServer#1125]
﻿## PLEASE READ BEFORE POSTING YOUR ISSUE

Please create GitHub issues only for bugs and feature requests. If you need help with using Shoko or have a question, join us on Discord.

https://discord.gg/vpeHDsg

===== Guidelines ====

- Make sure you are using the latest **Stable** or **Daily** version of Shoko Server otherwise your issue will be closed.
- Search this repository (top of the page) for the issue or feature you are reporting, make sure it has not been fixed or reported before.
- If reporting an issue, then you must attach the relevant Shoko Server and Shoko Desktop **LOG FILE**. 
- If requesting a new feature, please explain in detail the feature itself and the benefits of it being added.
- If requesting cosmetic changes, please explain in detail why they should be made. 
- The template below **MUST BE USED** when submitting an issue, no exceptions.

## VERSION INFORMATION

Server Version: `Shoko Server Version: v4.2.2.0, Channel: Dev, Tag: (null), Commit: 9011cbac26428d49cebd4fdbee391113138ba5e1`

Using docker daily.

Desktop Version: N/A

If you've compiled your own version, please use the last commit you compiled.

## LOG FILE

```
2024-05-04T20:33:40.5798591Z
Info
Checking WAN Connectivity…
2024-05-04T20:33:40.5798591Z
Trace
Trying to connect to CloudFlare
2024-05-04T20:33:40.5798591Z
Trace
Trying to connect to Microsoft
2024-05-04T20:33:40.5798591Z
Trace
Trying to connect to Mozilla
2024-05-04T20:33:40.5798591Z
Trace
Trying to connect to WeChat
2024-05-04T20:33:40.7113372Z
```

## DESCRIPTION

This might sound a little silly, but I personally don't want Shoko to be pinging wechat repeatedly when doing Connectivity testing.
It would be nice to have a way to be able to configure which sites to use to test connectivity. Whether it's dynamic configuration or just a one time read at the start of Shoko, either is fine. I think the defaults can be left the same for everyone, but some may want to customize it to tailor their network.

## STEPS TO REPRODUCE

Being as detailed as possible, please list all steps need to reproduce the issue, if we can't reproduce it then we can't fix it.

**Comment by da3dsoul** [comment]
In your settings-server.json file, there's a line called `DisabledConnectivityServices`. It's a list. Add `"WeChat"` to it, so that the line looks like `"DisabledMonitorServices": [ "WeChat" ]`

**Comment by harshithmohan** [comment]
It's not silly. I had to disable wechat because it's banned here and it would always fail.

**Comment by xNinjaKittyx** [comment]
> In your settings-server.json file, there's a line called DisabledMonitorServices. It's a list. Add "WeChat" to it, so that the line looks like "DisabledMonitorServices": [ "WeChat" ]

Thanks a lot, that worked.
