### ISSUE TITLE
Server not piciking certain anime when scanned. (Armitage III)

### ISSUE THREAD

**Issue by SegaGameBoyStation** [ShokoAnime/ShokoServer#1133]
﻿## PLEASE READ BEFORE POSTING YOUR ISSUE

Please create GitHub issues only for bugs and feature requests. If you need help with using Shoko or have a question, join us on Discord.

https://discord.gg/vpeHDsg

===== Guidelines ====

- Make sure you are using the latest **Stable** or **Daily** version of Shoko Server otherwise your issue will be closed.
- Search this repository (top of the page) for the issue or feature you are reporting, make sure it has not been fixed or reported before.
- If reporting an issue, then you must attach the relevant Shoko Server and Shoko Desktop **LOG FILE**. 
- If requesting a new feature, please explain in detail the feature itself and the benefits of it being added.
- If requesting cosmetic changes, please explain in detail why they should be made. 
- The template below **MUST BE USED** when submitting an issue, no exceptions.

## VERSION INFORMATION

Server Version: 4.2.2.0 (9277b85)

WebUI Version: 2.1.0-dev.180

If you've compiled your own version, please use the last commit you compiled.

## LOG FILE

ATTACH YOUR LOGS HERE

## DESCRIPTION

Some anime not being picked up when scanned. Confirmed anime for now is Armitage III OVA.
I will test with other anime to see if it isn't just this one when I have time.

## STEPS TO REPRODUCE

Have Armitage III OVA series in Shoko anime folder. Scan anime folder. It doesn't show up in collection.

**Comment by Cazzar** [comment]
Are you able to provide logs for this so we can investigate further -  if you prefer we can troubleshoot in a more live manner on discord too

**Comment by SegaGameBoyStation** [comment]
I overlooked the log thing on the form. I will poke around and try to find the logs.

**Comment by SegaGameBoyStation** [comment]
[2024-06-07.zip](https://github.com/user-attachments/files/15738799/2024-06-07.zip)
Here is the log.
I am not sure how but those OVA files ended up read only, would that be a contributing factor?

**Comment by SegaGameBoyStation** [comment]
Strange, I changed Linux file permissions on the files for the OVA for "others" from Read to Write/Modify and they scanned in.
But all the rest of my files have "others" as Read and they scanned in fine. 
So there is some strange behaviour going on here.

**Comment by da3dsoul** [comment]
LGenerally, Shoko wants exclusive file access during import. If you want it to rename or organize your files, it'll need write perms. Due to the likelihood of acquisition software getting in the way, it's common to use a script to hardlink files into a folder for Shoko to manage. Then, you can also have settings to automatically delete seeding files after a certain amount of time or ratio.
