### ISSUE TITLE
Collection getting renamed when updating Shoko Server daily

### ISSUE THREAD

**Issue by TheOne320** [ShokoAnime/ShokoServer#1157]
Server Version: 4.2.2.0 (187d643)

Desktop Version: Daily build from 17 April 2024

## LOG FILE

[2024-07-29.log](https://github.com/user-attachments/files/16420032/2024-07-29.log)
[2024-07-28.log](https://github.com/user-attachments/files/16420033/2024-07-28.log)
[2024-07-30.log](https://github.com/user-attachments/files/16420034/2024-07-30.log)

## DESCRIPTION

I set a custom name for my collection "Magical Girl Lyrical Nanoha" in Shoko because on AniDB the English title of "Magical Girl Lyrical Nanoha The Movie 2nd A`s" is set to "nam2" and I did not want the collection to be called nam2 in Plex. This worked fine and Plex saw the collection name as "Magical Girl Lyrical Nanoha". After getting a new daily build for Shoko Server, I noticed that after scanning in Plex it suddenly changed the name to "nam2" and so I checked in Shoko Server and the custom name got reset back to nam2 after changing server version. That means it must not be saved correctly. I reported this problem on 28. July 2024 in the discord and "re: vam" may have found something but I did not get a message, so I am reporting it here.
re: vam wrote it may be this document causing the error:
https://github.com/ShokoAnime/Shoko-WebUI/blob/e0de33390574f3504004e441fa434f4c01a9e278/src/components/Collection/Group/EditGroupTabs/NameTab.tsx#L44-L45

## STEPS TO REPRODUCE

Get "Magical Girl Lyrical Nanoha The Movie 2nd A`s". Set the Shoko series and group language to English. This movie is then called "nam2". I also have all Nanoha series in a collection. For some reason when changing daily server version, the collection name changes to "nam2"

I am on discord the whole time in case there are any questions or you need some other logs.

**Comment by ElementalCrisis** [comment]
@revam I don't see how the Web UI could cause this issue if the name was reset on update. However, as far as I recall, a series name/group is reset to default via a number of actions like Recreate All Groups or even when switching languages.

**Comment by revam** [comment]
'recreate all groups' will reset it, 'rename all groyps' won't if the group name is locked

**Comment by TheOne320** [comment]
Got an update. It does not only happen when I update the server version. My server just got hung up scanning a file, so I just stopped and restarted the server and it reset the name of the collection back to "nam2".

**Comment by harshithmohan** [comment]
I'm sad to report that I seem to have the same issue 😔

**Comment by harshithmohan** [comment]
For anyone looking into it.
The group name got updated to the main series title in `AnimeGroupService.UpdateStats`. That can only happen if `IsManuallyNamed` is 0 on the group which it shouldn't be..... I couldn't figure out why it might have been reset to 0. When we rename a group, it is set to 1.

**Comment by harshithmohan** [comment]
I forgot to remove the label :pensive:

**Comment by TheOne320** [comment]
This does not happen in version 5 anymore.
