### ISSUE TITLE
Installer does not ask where to install Server, and install it on Desktop !?

### ISSUE THREAD

**Issue by bigretromike** [ShokoAnime/ShokoServer#1158]
﻿
## VERSION INFORMATION

Server Version: 4.2.2

Desktop Version: None

## LOG FILE

- none

## DESCRIPTION

When installing ShokoServer-4.2.2-Win.exe installer don't ask where do I want to install shoko, and it install shoko on desktop of current user inside "ss" folder.

## STEPS TO REPRODUCE

1. download ShokoServer-4.2.2-Win.exe
2. run ShokoServer-4.2.2-Win.exe
3. /ss/ folder is created on Desktop

**Comment by ElementalCrisis** [comment]
For first time users, it will ask where you want to install it, otherwise is uses the install path in the registry to "update" the previously installed version. 

Maybe in the past you installed it there?

**Comment by bigretromike** [comment]
> For first time users, it will ask where you want to install it, otherwise is uses the install path in the registry to "update" the previously installed version.
> 
> Maybe in the past you installed it there?

Could you point me to that registry ? - I don't denied that I did not install it some years ago on this machine on desktop just for quick check as this was never my main shoko server machine.

If you say its only that way because it was "updating" old (missing) installation then im fine with it, that's behaviour I would expect from installer, maybe "update" instead of install information but yeah, working good.

**Comment by ElementalCrisis** [comment]
Look for the following UUID in the registry. 

{0BA2D22B-A0B7-48F8-8AA1-BAAEFC2034CB

**Comment by bigretromike** [comment]
> Look for the following UUID in the registry.
> 
> {0BA2D22B-A0B7-48F8-8AA1-BAAEFC2034CB

`HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\{0BA2D22B-A0B7-48F8-8AA1-BAAEFC2034CB}_is1`

got it, thanks
