### ISSUE TITLE
Languages with country codes not working

### ISSUE THREAD

**Issue by tamodolo** [ShokoAnime/ShokoServer#1173]
This is an issue for a reported problem on discord support channel related to languages with country codes like pt-br being ignored.

As TMDB is the largest database in pt-br I found this bug because the language wasn't being shown in webui. Here is some prints:

![image](https://github.com/user-attachments/assets/591b9dfa-9bfd-4a0b-9766-80ef2e8b87eb)
![image](https://github.com/user-attachments/assets/44332dd9-0872-4649-af89-56f17fc7e714)
![image](https://github.com/user-attachments/assets/76f53512-b267-43ab-be7a-df76bee135b6)

Also imagens shared by re: vam at the time:

![image](https://github.com/user-attachments/assets/21473e30-15d4-49c6-a27c-e9927955221f)
![image](https://github.com/user-attachments/assets/1a00d58a-0d54-4342-8fcd-562cf259e655)

## VERSION INFORMATION

Server Version: 4.2.2.67

**Comment by ElementalCrisis** [comment]
First screenshot shows you have EN higher than PT-BR for episode descriptions. 

Fix this and refresh TMDB data.

**Comment by tamodolo** [comment]
> First screenshot shows you have EN higher than PT-BR for episode descriptions.
> 
> Fix this and refresh TMDB data.

The image is wrong actually. I'll glady provide extra info if needed. This issue was opened after talking with @revam about it on discord. The last 2 screen was his.

**Comment by harshithmohan** [comment]
> First screenshot shows you have EN higher than PT-BR for episode descriptions.
> 
> Fix this and refresh TMDB data.

The problem is with titles. We have PT-BR (which is equivalent to "BrazilianPortuguese" in the code) in shoko but TMDB data has the language as Portuguese and the country code as "BR" in two separate.
The titles are not added because "BrazilianPortuguese" != "Portuguese". The code doesn't check for the country code... yet

**Comment by tamodolo** [comment]
I know that Shoko has some important features in the making and this is considered minor for non afected languages. For me that know english this is not a problem too but it is for my child niece that don't know english (yet). For her this issue is a major one. If this is not asking too much please give some atention to this issue. Thank you very much for this great software!

**Comment by da3dsoul** [comment]
I know someone was working on this. I'm not sure if it was fixed. @revam can you comment?

**Comment by revam** [comment]
Impo then the language support in Shoko needs to be overhauled to have more "_proper_" support for language & countey codes, but in the short-term i can throw in a few ~~permanent~~ _temporary_ measures to fix it for 'pt-br' and any other language code (e.g. 'pt') + countey code (e.g. 'br')  combinations we have mapped to title languages in our current system.

I'll see if I can get those measures in this weekend ~~before I forget again~~.

**Comment by tamodolo** [comment]
> Impo then the language support in Shoko needs to be overhauled to have more "_proper_" support for language & countey codes, but in the short-term i can throw in a few ~permanent~ _temporary_ measures to fix it for 'pt-br' and any other language code (e.g. 'pt') + countey code (e.g. 'br') combinations we have mapped to title languages in our current system.
> 
> I'll see if I can get those measures in this weekend ~before I forget again~.

Real thank you all! I can see my niece already vibrating hahaha!

**Comment by tamodolo** [comment]
Thank you very much!
