### ISSUE TITLE
[DEV- Daily] Renamer Script always fails (even preview)

### ISSUE THREAD

**Issue by t0815** [ShokoAnime/ShokoServer#1181]
## VERSION INFORMATION

Server Version:  4.2.2.176 /a2c0340

Desktop Version:  n/a

Web-UI Version: 2.1.0-dev.316

## LOG FILE
n/a

## DESCRIPTION

Renamer-Scripts always fail, even when generating preview. Did try the following script:

```
DO ADD '%sna'

```

Tested other scripts too, but same result. The option "Move Files" was not checked.

![grafik](https://github.com/user-attachments/assets/2b5074ec-084f-45d2-9b9c-d2f77c2cfd2a)

ShokoError- log does show nothing. In dev tools, the request returns 200, and the response is:

```
...
  {
    "FileID": 76031,
    "FileLocationID": 135474,
    "ConfigName": "Rename to Orig",
    "IsSuccess": false,
    "ErrorMessage": "Not relocating file as it is not in a drop source or drop destination."
  },
...
```

The request was:

![grafik](https://github.com/user-attachments/assets/25c652fb-81a1-48eb-9040-b07be6e3ea43)

```
/api/v3/Renamer/Config/Rename%20to%20Orig/Relocate?deleteEmptyDirectories=true&move=false&rename=true
```

## STEPS TO REPRODUCE

1. Add files to renamer
2. use the sample script or any other default script

**Comment by revam** [comment]
The files you're trying to rename/move are in an import folder with the type set to 'none,' which excludes it and it's files from being used in the renaming/move system **at all**. Set the type to 'destination' or 'both' depending on if you want ro perform a one tune operation or have files automagically moved/renamed on import. If you had or have multiple import folders then you would mark all your sources of files to be moved as 'source' (or 'both' if they're also a destination import folder) and all import folders you would want as destinations as 'destination' (or 'both' if they're also a source import folder).
