### ISSUE TITLE
Incorrect VA / character mappings

### ISSUE THREAD

**Issue by revam** [ShokoAnime/ShokoServer#1183]
## VERSION INFORMATION

Server Version: `4.2.2.190`

Desktop Version: N/A 

If you've compiled your own version, please use the last commit you compiled.

## The Issue

AniDB currently stores VA/character mappings _per anime_. We on the other hand store it globally. So, when we have a character that appears in multiple anime, but with different VA for each, then we will currently store the last known VA/character mappings for a character from the last anime that was refreshed and contained the character.

### Example

An example explaining it using the following character; [Roronoa Zoro](https://anidb.net/character/475)

If we refresh [One Piece](https://anidb.net/anime/69), then we will have two mappings for the character, one to [Nakai Kazuya](https://anidb.net/creator/259) and one to [Urawa Megumi](https://anidb.net/creator/5342). If we instead refresh [One Piece (2000)](https://anidb.net/anime/411), then we will only have a mapping to **Nakai Kazuya**. And last, if we refresh [One Piece: Taose! Kaizoku Ganzack](https://anidb.net/anime/2736), then we will only have a mapping to [Takagi Wataru](https://anidb.net/creator/335) stored.

## Proposed solution

Start storing VA/character mappings per anime, and also add a database/startup migration to regenerate all mappings from scratch again using the locally available xml files.

**Comment by bigretromike** [comment]
storing those per series is the most sane way. I can imagine (as not so long ago) many original VA will pass away, and will be replace with new ones. then it would wipe mapping of are original VA.
