### ISSUE TITLE
[Feature Request] New Filter "Has Preferred Image"

### ISSUE THREAD

**Issue by RedRain77** [ShokoAnime/ShokoServer#1187]
## VERSION INFORMATION

**Server Version:** [5.0.0](https://github.com/ShokoAnime/ShokoServer/releases/tag/v5.0.0) (Windows 10)  

## DESCRIPTION

I'm going through all the series in my collection and adjusting the posters to include the title. I think a filter to exclude the ones I’ve already updated would be really helpful, as scrolling through 3,000+ series is a bit of a pain.  

Additionally, is there a way to set a custom image without uploading it to TMDB? I’ve noticed that the TMDB scraper only pulls the main posters and doesn’t scrape season posters.

**Comment by da3dsoul** [comment]
Point 1, that's doable. 
Point 2, that's planned for the future image system, but there is not currently a way to add images to Shoko manually

**Comment by natyusha** [comment]
It should also be noted that Shoko already scrapes TMDB season posters, they just aren't shown in the webui. Clients like Plex for example can access those posters just fine.

**Comment by revam** [comment]
point 1 would be easy. and as nat said, we do have season posters, they're just not shown in the (~~stable [\*_peak_\*](https://github.com/ShokoAnime/ShokoServer/commit/0cfc5d4bf5b4f642e651f4e1ba981ff7b4981507)~~) web ui.

**Comment by harshithmohan** [comment]
> point 1 would be easy. and as nat said, we do have season posters, they're just not shown in the (~stable [*_peak_*](https://github.com/ShokoAnime/ShokoServer/commit/0cfc5d4bf5b4f642e651f4e1ba981ff7b4981507)~) web ui.

The correct way to do it would be to consider the season posters as part of series posters too. Otherwise, we can't set them.  Because what is the point of showing season posters in the webui if we don't have a way to see the seasons nor set them as series poster. (Oh wait, I can't link to that commit since it doesn't exist)

**Comment by revam** [comment]
> point 1 would be easy. and as nat said, we do have season posters, they're just not shown in the (~stable [*_peak_*](https://github.com/ShokoAnime/ShokoServer/commit/0cfc5d4bf5b4f642e651f4e1ba981ff7b4981507)~) web ui.

Correction; meant to say shown in the web UI with a stable server. It was already "fixed" in dailies a few days ago.
