### ISSUE TITLE
File Info for episode result in empty 

### ISSUE THREAD

**Issue by Rand-Random** [ShokoAnime/ShokoServer#1189]
Versions in use
5.0.0.7 [(ac81733)](https://github.com/ShokoAnime/ShokoServer/compare/ac81733...master)
2.1.2-dev.1 [(2.1.2-dev.1)](https://github.com/ShokoAnime/Shoko-WebUI/compare/2.1.2-dev.1...master)

![image](https://github.com/user-attachments/assets/b343c364-b69d-40ee-a6fc-bee3bc14ad2f)

Is the same on every series, every episode.

**Comment by harshithmohan** [comment]
Fixed in latest daily

**Comment by revam** [comment]
was fixed in 5.0.0.12
