### ISSUE TITLE
Virus detected

### ISSUE THREAD

**Issue by Rand-Random** [ShokoAnime/ShokoServer#1208]
Downloading
https://files.shokoanime.com/files/shoko-server/daily/ShokoServer.zip

gives a message a virus is detected.

Microsoft Defender says (hope the german user interface is understandable)
![image](https://github.com/user-attachments/assets/08de4fa1-35b4-494c-9eed-abe758cbbe69)

though virustotal reports all clean 
https://www.virustotal.com/gui/url/36c2f42429cf46b80bf86c926cc107873165c678c48acacd73c413f95fd40fdd/detection

![image](https://github.com/user-attachments/assets/2c29b236-10ed-4b7a-b626-a45fb9f8e96d)

**Comment by Cazzar** [comment]
This would need to be reported as a false positive, @Rand-Random which version of defender are you using? (windows 10/11)

**Comment by Cazzar** [comment]
Also is it a specific file in the archive that is registered?

**Comment by Rand-Random** [comment]
No, the zip it self.

1) Downloaded it with firefox which didn’t automatically delete it like edge, chrome, opera did.
2) Opened it with WinRar. (the windows native zip tool, refused to open it)
3) Extracted the files with WinRar.
4) Scanned the files with Microsoft Defender, it reported everything is okay

**Comment by Cazzar** [comment]
Submitted a false-positive report to microsoft, link for my own reference: https://www.microsoft.com/en-us/wdsi/submission/e36ffd54-91c9-49ca-a8de-faa4821542fc

**Comment by Rand-Random** [comment]
Microsoft seems to have updated their signatures and it once again downloads without issues.
