### ISSUE TITLE
Check newer version files

### ISSUE THREAD

**Issue by Stonedestroyer** [ShokoAnime/ShokoServer#123]
Is it possible to get a check for example if you have a file to check if there is a revision 2 of that file?

For example if you take commie they have rev 1 and rev 2 on some animes, it would be nice if there was a notification if there was a rev 2. I don't know if anidb api supports this. But it would be nice to have as a feature.

**Comment by misakitchi** [comment]
I agree! :)

**Comment by jmediamanager** [comment]
will investigate

**Comment by ElementalCrisis** [comment]
This was discussed but I don't recall if possible or not, @da3dsoul?

**Comment by da3dsoul** [comment]
Not really, we can check if files have been marked as deprecated when the files are updated, but that's about it
