### ISSUE TITLE
Folder exclusion by name

### ISSUE THREAD

**Issue by alimbada** [ShokoAnime/ShokoServer#127]
Is it possible to exclude certain folders such as `.AppleDouble` directories from the import. These folders are generated by OS X when browsing an AFP share and contain files of the same name in the parent folder, but they only contain metadata. However, since they have the same name (including the extension) of the original files JMM attempts to import them and they end up in the "Unrecognized" category thus creating noise as I'd have to go through each file and check it's path to see if it's a real file or not.

Being able to exclude folders by name would be a great way to prevent importing these files in the first place, but I can't seem to find any documentation on exclusions.

Additionally, these files also create noise for the File Renaming feature (which is what I'm interested in doing) as I'm not interested in renaming metadata files.

**Comment by jmediamanager** [comment]
Yup sounds reasonable

**Comment by alimbada** [comment]
Ah, thanks for the quick response. So the feature doesn't exist currently... I'll have to find a way around it for now then. :-)

**Comment by xmodx10** [comment]
@ElementalCrisis or @Cazzar , this issue can be closed, feature implemented in #838 

Could add ".AppleDouble" to the default init list if you think its worth it, or the users could just add it themselves if required.
