### ISSUE TITLE
new contracts (API) in REST/json format and Improve JMMServer maintainability

### ISSUE THREAD

**Issue by maxpiva** [ShokoAnime/ShokoServer#130]
Currently, they're a lots of contracts all client WebServices has different contracts, which generate maintainability kaos.

Step 1) Generate a new rest API, generate new contracts that include all the information than previous contracts need. Ej, GetAnime, GetGroup, episode, etc. 
Step 2) Migrate current clients to the new API.

[suggestion] Optional IF DB Migration to a NOSQL DB is approved. (Maybe i have some time at the end of the year)

Step 3) Those new contracts made them poco entities and use a NOSQL DB to store them. After that refactor JMM Server to use that DB instead the original one.

**Comment by bigretromike** [comment]
anywork maded to this new API you refer ?

**Comment by maxpiva** [comment]
Check my repo under new database

**Comment by bigretromike** [comment]
@maxpiva im looking at your fork repo but im not sure where should i look to be honest. Fell free to post direct link ;-)

**Comment by ElementalCrisis** [comment]
I believe he's talking about https://github.com/maxpiva/jmmserver/tree/New-Database/.

**Comment by bmfrosty** [comment]
@maxpiva Why the new database in addition to the new API?  I see you're moving from a transactional database to an object store.  Can I get the reasoning on that?

**Comment by bmfrosty** [comment]
Said transactional.  Meant relational.  Must be tired.

**Comment by maxpiva** [comment]
Check...
https://github.com/japanesemediamanager/jmmserver/issues/73

**Comment by maxpiva** [comment]
Warning, the NEw Database fork is only starting, is not compilable, you
should FORK JMMSERVER main.

**Comment by bigretromike** [comment]
Ok, you tring to add new database at the backend, but that still not connected to API. And the Issue you post is also connected to databases. I see you tring to rework backend for datastorage - great, but that dont answerd my initial question ;-)
I dont see any changes in your REST.cs file

**Comment by maxpiva** [comment]
Well, there is no work on this yet. Because. The rest interface will be
based on the poco models(JMMModels) and they're a work in progress. The
REST interface will be based on those models, and transversal cuts of those
models,

Any extra data inferred from those models, are included as method
extensions for the clients to consume.

**Comment by ElementalCrisis** [comment]
This can be closed with the addition of Nancy right?

**Comment by bigretromike** [comment]
@ElementalCrisis I think.
