### ISSUE TITLE
Unrecognized episodes no longer listed, after deleting one Folder in Server

### ISSUE THREAD

**Issue by miracle152004** [ShokoAnime/ShokoServer#134]
Hi,

I deleted one folder on the server after moving the data to a new location and retiering the hard disc.
After the deletion new unrecognized episodes would no longer be listed in the client.

After analysing the database I found one entry in the localvideos, which would return no filepath and an ImportFolderID of -1.

All unrecognized episodes after this entry. would not be listed the client.
After deleting the entry everything worked fine.

Is there a routine to clean or prevent such situations?

Best regards
miracle152004

**Comment by ElementalCrisis** [comment]
@da3dsoul I believe this was fixed long ago, can you confirm?

**Comment by revam** [comment]
i don't think this is relevant anymore. they can reopen the issue if they're still using JMM/Shoko and are encountering itnon the latest release (4.2.2 at the time of writing).
