### ISSUE TITLE
JMM Server hangs when loading files saved in bad sectors.

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoServer#157]
JMM Server hangs when loading files saved in bad sectors.
i have a bad HDD that is dying very slowly that has bad sectors in it.
JMM locks up when its loading/hashing files like that. most other programs does the same.
only way to stop it is to close JMM server and delete the file (obv doing that) but i think the JMM server should have a timer or something that makes it move on to the next file in the hashing queue if it fails to load or does not make progress.

**Comment by maxpiva** [comment]
Killing the hasher.dll on timeout will give us an unhandled exception. Hasher will stop on error,

**Comment by Cazzar** [comment]
As this seems to happen rarely/if at all I am going to close this issue.
