### ISSUE TITLE
[Requests] Posters of Series

### ISSUE THREAD

**Issue by misakitchi** [ShokoAnime/ShokoServer#161]
Hi!
I have some little requests

1) Archived Posters (Keep all Posters Images)
Sometime AniDB change the image of a serie to a new image... but sometime i prefere the old image... can you do something to keep all image of a serie?

2) "Image of Serie" sometime Fanart
Most of the time i want to use the "Poster" for the image of a serie, but sometime i want to use the "Fanart" image, its possible?

3) Display size "when mouse on it"
In "Display settings" we can change the display size of "Posters/Episode/Group" image, but we can't chose the size when we put the mouse on it (when a new image pop-up (zoomed image))
For example when the mouse is on a poster image of a serie, i want that it display it using most of my screen!!
So can you add option to say "when mouse is on serie poster/episode" poped image zoomed 3x 4x or use 1920px/1650px/1280px
If you don't understand what i want, just tell me...

**Comment by AreFinstad** [comment]
there is a workaround to changing the picture of your series, you can do it by renaming the file you want to whatever file JMM is using ATM, restart the program and it will start using the file you renamed.
even tho its not officially supported ATM, its a workaround (tho a bit slow and some hassle)

**Comment by jmediamanager** [comment]
1. This is pretty hard since I can't tell when AniDB change their posters.
The best solution is that you use TvDB, and if you like a particular poster just add it there.

2. Yup can do

3. Yup can do

**Comment by misakitchi** [comment]
1. When JMM take a new file for the poster of the serie, it compare old and new file, if new file is different, then old file is archived... Thx!

2. Thx!

3. Thx!

^_^

**Comment by ElementalCrisis** [comment]
No longer relevant as this applied to Desktop.
