### ISSUE TITLE
[Feature] Auto "Run Import" Timer

### ISSUE THREAD

**Issue by misakitchi** [ShokoAnime/ShokoServer#174]
Hello!
Can you add a Auto "Run Import" Timer feature?
Example each 6H/12H/24H/1Week/1Month a import is done
Because my PC and JMM is always running (24h/7)
Thx!

**Comment by AreFinstad** [comment]
to specify in more detail, do you mean you want an ETA timer for when they next import will start?
i also think it should be a part of this issue in the first place IMO. https://github.com/japanesemediamanager/jmmserver/issues/136

**Comment by misakitchi** [comment]
What is ETA? My english is pretty bad...
What i want is that every 6H/12H/24H/1Week/1Month a import is done
Because my PC and JMM is always running (24h/7), so actualy my JMM only do one import...
So i must clic on Import button of JMMServer to do a import
Correct the title if its not correct

**Comment by ElementalCrisis** [comment]
If I understand correctly, you're asking for the ability to schedule imports in certain intervals, for example Run Import every 12 hours. 

Also ETA is Estimated Time of Arrival.

**Comment by misakitchi** [comment]
Yes! For example, every 24h a import is done. (I don't need to click on import button its automatic)

**Comment by SL-Gundam** [comment]
Would it not be easier to enable "Watch for new files" on your import folder(s)?

**Comment by misakitchi** [comment]
"Watch for new files" is not working properly with me...
1) utorrent create a file "anime.mkv.!ut"
2) when download complete utorrent rename the file to "anime.mkv"
3) for jmm its not a new file...

**Comment by AreFinstad** [comment]
its weird that i never had an issue with that setup when i was doing local torrents.
in anycase, you can always set uTorrent to move the file to another folder, easy fix that works.

**Comment by misakitchi** [comment]
Hi! Any news on the "Auto Import"? :)

**Comment by revam** [comment]
We have this now.
