### ISSUE TITLE
[Feature] "Unrecognized Files" Timer

### ISSUE THREAD

**Issue by misakitchi** [ShokoAnime/ShokoServer#175]
My issue is simple: each time i launch JMM Server, the "Unrecognized Files" are added to the "General queue" but i don't want that...
Can you add a Timer to say when we want ask for the "Unrecognized Files"?
Solution1: 6H/12H/24H/1Week/1Month
Solution2: if a "Unrecognized File" have been asked more than 10 times, then for this file only ask every 1month/3month/6month...
Thx!

**Comment by AreFinstad** [comment]
while talking about unrecognized files, made a new issue in JMMD that also might be of use.
https://github.com/japanesemediamanager/jmmclient/issues/254


comment on this issue, maybe we could be able to mark unrecognized files with a tag so they wont be searched for in the next import, or auto remove items from the queue that has a parsed crc but does not match it (we should have a list of those IMO where we can delete/download again)

**Comment by jmediamanager** [comment]
Note - there is already an option for this (the bottom selection)
I will remove it from the initial import when JMM server starts though

![image](https://cloud.githubusercontent.com/assets/6645153/10568101/328349bc-765f-11e5-8e8a-1ba4dd30c6dc.png)

**Comment by misakitchi** [comment]
Say me if i m wrong but "Files with Missing Info" and "Unrecognized Files" are not the same...
I speak of the "Unrecognized Files"...

**Comment by jmediamanager** [comment]
Files with Missing Info includes Unrecognized files

**Comment by misakitchi** [comment]
OK so can you do different timers? One for "Files with Missing Info" and one for "Unrecognized Files"?
Because "Files with Missing Info" are mostly "new" files, and need to be updated often, every 24h for example.
But "Unrecognized Files" are mostly (for me) "old" files and only need to be updated once a week...

**Comment by revam** [comment]
It should stop asking for an auto-match after 15 retries now. (That's over a week of trying ~~and failing~~ if you leave it on auto at 12h intervals)

**Comment by revam** [comment]
Also, the exact number of retries is configurable.
