### ISSUE TITLE
[Feature] Easier migrating from other AniDB clients to JMM

### ISSUE THREAD

**Issue by SL-Gundam** [ShokoAnime/ShokoServer#194]
AniDB supports exporting your mylist.

If JMM would be able to import the data in those exports, a lot less data would need to be retrieved through the UDP API. This way migrating to JMM would be easier and less sensitive to banning since most users will have significant collections.

**Comment by AreFinstad** [comment]
if this gets ever added a guide either with a tooltip or in the tab in question aswell as on the website is needed IMO.

**Comment by jmediamanager** [comment]
I don't think this would really work in the way you have described.

The MyList export doesn't export actual file info from AniDB.
You would still to look up every file from AniDB.

The only thing that would be useful is exporting Ed2K hashes -> FileID pairs, which might save on the hashing of files

**Comment by SL-Gundam** [comment]
Exports might differ based on the one you choose

The one i choose is: html-anidbstyle

It contains stuff like this in .js files. Thats file info if i'm not mistaken. What other file information do you need?

var f490795 = new Object();
e1.fnums.push (490795 );
f490795.id = 490795;
f490795.sizeBytes = "243.763.719";
f490795.sizeMB = "232 MB";
f490795.filetype = "mkv";
f490795.crc = "9aeeef22";
f490795.md5 = "9506e10b505de6065174f3697c068bdb";
f490795.sha = "bc83e000866a4bf70aa481bf9e283b183265b900";
f490795.ed2kLink = "ed2k://|file|RahXephon_-_S1_-_Over_Lord_-_[COR].mkv|243763719|363f8d7bf9e46dfdf7cb67668828b59b|";
f490795.ed2kHash = "363f8d7bf9e46dfdf7cb67668828b59b";
f490795.ed2kName = "RahXephon - S1 - Over Lord - [COR].mkv";
f490795.groupID = 3375;
f490795.groupName = "CitadelofTheRaven";
f490795.groupShort = "COR";
f490795.longReleased = "-";
f490795.shortReleased = "";
f490795.qualID = 2;
f490795.qualName = "very high";
f490795.resName = "640x480";
f490795.audioBr = 89;
f490795.audioCodecID = 9;
f490795.audioCodecName = "AAC";
f490795.videoBr = 1126;
f490795.videoCodecID = 22;
f490795.videoCodecName = "H264/AVC";
f490795.langID = 2;
f490795.langName = "japanese";
f490795.subID = 4;
f490795.subName = "english";
f490795.typeID = 7;
f490795.typeName = "DVD";
f490795.other = "";
f490795.longDate = "31.08.2008 12:21";
f490795.shortDate = "31.08.08";
f490795.longUpdate = "22.09.2008 11:22";
f490795.shortUpdate = "22.09.08";
f490795.storage = "";
f490795.source = "";
f490795.longViewdate = "01.05.2011 15:29";
f490795.shortViewdate = "01.05.11";
f490795.state = 1;
f490795.stateIcon = "<a class=\"i_icon i_state_onhdd\" title=\"File with status: internal storage (hdd)\" href=\"://wiki.anidb.net/w/Filestates\" data-anidb-rel=\"anidb::wiki\"><span>SI</span></a>";
f490795.mystate = "1";
f490795.mystatename = "internal storage (hdd)";
f490795.myfilestate = "0";
f490795.myfilestatename = "normal/original";
f490795.isCRCOK = true;
f490795.isCRCNO = false;
f490795.isCRCUN = false;
f490795.isWatched = true;
f490795.isV2 = false;
f490795.isV3 = false;
f490795.isV4 = false;
f490795.isV5 = false;
f490795.hasStorage = false;
f490795.hasSource = false;
f490795.hasComment = false;
f490795.isGeneric = false;

**Comment by ElementalCrisis** [comment]
I thought exporting via HTML was broken? https://anidb.net/perl-bin/animedb.pl?show=cmt&id=55136

**Comment by SL-Gundam** [comment]
Broken is a strong word... I would say "It works but has issues". Depending on how you use it you might never run into these issues

**Comment by ElementalCrisis** [comment]
No one has asked since this issue was created and I don't recall ever seeing any other AniDB clients mentioned in chat.
