### ISSUE TITLE
Allow browse for folder on import folder

### ISSUE THREAD

**Issue by jmediamanager** [ShokoAnime/ShokoServer#2]
Instead of just entering an import folder path using copy and paste, create a 'browse for folder' button.

When doing from JMM Desktop, it will need to browse folders on that remote server.

**Comment by bigretromike** [comment]
If I recall the similar functionality is added to APIv2 as /api/os/ thing when you can browser server drives from client.

**Comment by bigretromike** [comment]
@ElementalCrisis this is already and also with all the cloud support etc.

**Comment by ElementalCrisis** [comment]
Perfect, closed! :)

**Comment by da3dsoul** [comment]
Indeed

**Comment by da3dsoul** [comment]
Haha
