### ISSUE TITLE
[Request] Voting for single episode 

### ISSUE THREAD

**Issue by bigretromike** [ShokoAnime/ShokoServer#200]
Voting is great, but some of us like to vote also on episodes and not only overall series.

If not voted on series, then it would make a overall vote for series on base of the episode counts as a hint, so You could use that as the Vote value or pick yourself one. That would be usefull if he series is super long and we dont watch it in one shoot.

And voting per episode would give us clue if we liked it before or not :+1:

**Comment by jmediamanager** [comment]
From memory the API didn't support voting on episodes, but I will take a look when the wiki is back up

**Comment by bigretromike** [comment]
@jmediamanager but what IF we would make that for JMM use only ?:-) like you would have option to show this or not in client? It all depend of community - if they want it or not :-) And later on if we add other tracking pages support maybe we could sync that info. Just asking ;-)

Oh and YAY its 200 issues! :+1:

**Comment by bigretromike** [comment]
Strange because I get rating per episode from ServiceImplementation, so I was thinking it is supported?

**Comment by jmediamanager** [comment]
yes have confirmed the API support it
