### ISSUE TITLE
split up the hasher queue into a file finder and a file hasher

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoServer#207]
i think that splitting up the hasher queue into one that looks for files and one that hashes the files is a good way to speed things up when moving files to a new location and so on.
that way the file finder will not have to wait its turn for the hasher to figure out that it has already hashed the file.
this is great for slower drives and machines and large queues.... also for those that host files online as hashing is much slower.

**Comment by ElementalCrisis** [comment]
Adding the request from https://github.com/japanesemediamanager/jmmclient/issues/79 here as its similar and seems like these two suggestions would work nicely together, 

> @themountain632 commented on Aug 21, 2014
> 
> It would be nice if the hasher.dll ran multiple instances (for files on other drives) instead of doing > things sequentially regardless of where the files are located.

**Comment by ElementalCrisis** [comment]
Closing as #433 will be our main issue for the Command Worker refactoring.
