### ISSUE TITLE
Truncate file name  during renaming

### ISSUE THREAD

**Issue by saitoh183** [ShokoAnime/ShokoServer#209]
Yesterday i came across a few episode of Gintama that i was unable to rename because the episode name was too long and with the title + episode number, it goes pass the 488 character limit. Would it be possible to add truncate command in the scripting so that we can specify the number of characaters to stop at? 

I had to create a anidb request to get the names changed so that i could use get jmm to work but saying that the request is for a renaming client is a valid reason, the recommendation was truncating. Since the anidb clients can do it, i figure i should ask here if you could add that feature :).

**Comment by da3dsoul** [comment]
#504

**Comment by ElementalCrisis** [comment]
I believe @da3dsoul has already fixed this.

**Comment by da3dsoul** [comment]
Kind of not really

**Comment by Cazzar** [comment]
This is done now.
