### ISSUE TITLE
Group filter - Video Resolution

### ISSUE THREAD

**Issue by jmediamanager** [ShokoAnime/ShokoServer#21]
**Reported by werndlymob, Aug 9, 2012**

New group filter for video resolution

e.g 1080p = 1920
720p = 1280

**Comment by bigretromike** [comment]
@da3dsoul aint there something like that? you are the group filter master - any clue ?

**Comment by da3dsoul** [comment]
No not yet. It wouldn't be hard to add

**Comment by ElementalCrisis** [comment]
I can see the benefits of having a condition for Video Resolution, especially if you're looking to update.

**Comment by bigretromike** [comment]
But that probably go great with #102

**Comment by revam** [comment]
@da3dsoul implemented this a while back. Don't remember the commit or date, but last year during the group filter to filter preset refactor.
