### ISSUE TITLE
Ability to search for dropped (stalled) groups

### ISSUE THREAD

**Issue by jmediamanager** [ShokoAnime/ShokoServer#23]
**Reported by werndlymob, Aug 15, 2012**

Ability to search for dropped (stalled) groups
This is where a release group has stopped subbing a series.

**Comment by ElementalCrisis** [comment]
I don't believe this is possible, right @da3dsoul?

**Comment by da3dsoul** [comment]
Maybe.

**Comment by revam** [comment]
Still a maybe? @da3dsoul
