### ISSUE TITLE
Allow multiple anidb shows linked to one MAL show

### ISSUE THREAD

**Issue by CtrlAltDefeat94** [ShokoAnime/ShokoServer#230]
On anidb there's there's Fairy Tail (2014) and Fairy Tail Zero, MAL however considers it as one show.
Because Fairy Tail (2014) on AniDB is already linked to Fairy Tail (2014) on MAL(ep 1-90), I can't link Fairy Tail Zero on AniDB to Fairy Tail (2014) on MAL (starting at ep 91) 
![rru8ric 1](https://cloud.githubusercontent.com/assets/5640470/13725366/95f721e6-e89f-11e5-86e4-14c0f1630c80.png)

I think this should be considered a bug.
I think that, just like a starting ep# we need a ending ep#

**Comment by Urlryn** [comment]
Additional series with the same MAL linking issue:

Kidou Senshi Gundam SEED Destiny
- Jiyuu no Daishou
- Kudakareta Sekai
- Sorezore no Tsurugi
- Sadame no Gouka
