### ISSUE TITLE
A test for the existing file name in File Renaming utility.

### ISSUE THREAD

**Issue by naarcissus** [ShokoAnime/ShokoServer#234]
Ex. for use with files I've edited or are otherwise not in AniDB.

**IF** **F(**_[NRC]_**)** **DO ADD** [NRC]. Where **F()** is the file name, and _[NRC]_ is the searched for text.

Edit:
May also be a good idea to be able to test against the file path. As a separate test or as a single test representing both path and name. 

Edit 2: 
In fact this could be possibly be used to set up a test for over-long paths. Stupid Windows!

**Comment by da3dsoul** [comment]
Windows is only stupid in that it handles long file names poorly. The NTFS filesystem is the limitation for length.

**Comment by naarcissus** [comment]
Hmm. From what I've read. NTFS can handle long paths without issue. It's the APIs that can't. Some compatiblity reason or something. They declared back in the 90's that a path would never be long than 260 characters. Changing it could lead to buffer issues in many programs.

**Comment by da3dsoul** [comment]
I see. It could be one of those "rules" not defined by specification, but just a bad idea due to compatibility. Like fat32 on 2TB drives, it works... Kind of.

**Comment by da3dsoul** [comment]
#504
