### ISSUE TITLE
Changing name of self create group

### ISSUE THREAD

**Issue by bigretromike** [ShokoAnime/ShokoServer#240]
Is taking to long.. it looks like it remake/recheck entire group instead of changing name of it. It take same amount of time to rename group as it take to make same one with different name

**Comment by ElementalCrisis** [comment]
@bigretromike is this still an issue?

**Comment by bigretromike** [comment]
will check at home and give you info;

**Comment by ElementalCrisis** [comment]
No issues for me, @bigretromike can you check?
