### ISSUE TITLE
Drop Destination not available during Import process

### ISSUE THREAD

**Issue by Rand-Random** [ShokoAnime/ShokoServer#258]
Hi.

It happens to me frequently that my drop destination isn't available because I forgot to turn on my NAS or other reasons and if thats the case JMM Server will leave the files at the drop source which is good, but JMM Server seems to never check when my drop destination is available and will try to move the files to its destination.

So I am using the following SQL Script:

```
insert into CommandRequest (Priority, CommandType, CommandID, CommandDetails, DateTimeUpdated)
select 3, 1, 'CommandRequest_ProcessFile_' + cast(VideoLocalID as nvarchar(max)), '<CommandRequest_ProcessFile><VideoLocalID>'+cast(VideoLocalID as nvarchar(max))+'</VideoLocalID><ForceAniDB>false</ForceAniDB></CommandRequest_ProcessFile>', GETDATE() 
from VideoLocal where ImportFolderID in (select ImportFolderID from ImportFolder where IsDropDestination = 0) and VideoLocal.Hash in (select xref.Hash from CrossRef_File_Episode xref)
```

and restart JMM Server upon start JMM Server will start copying the files to the destination.

**Comment by maxpiva** [comment]
Scan drop folder or Run Import, will do what you want.

**Comment by Rand-Random** [comment]
I tried "Run Import" not really sure where I could find "Scan drop folder" ?!?

**Comment by ElementalCrisis** [comment]
Click the import folder icon to the right of the import folder's name.
