### ISSUE TITLE
Staff and Seiyuu group filters

### ISSUE THREAD

**Issue by da3dsoul** [ShokoAnime/ShokoServer#264]
Seiyuu would take some work. It could have two options: Main Character and Other. Staff we don't even have a db for. We download some info for it, but not much. The amount would still be enough for my needs, as it includes Original Author, Music, and Director.

**Comment by bigretromike** [comment]
@da3dsoul we do, now right - we can search so we got that;

**Comment by da3dsoul** [comment]
I don't think I'll make a group filter for this
