### ISSUE TITLE
Store login credentials for import folders if needed.

### ISSUE THREAD

**Issue by craige1** [ShokoAnime/ShokoServer#267]
For import folders that require login, store these credentials. 
Would have to be stored securely (don't want username/passwords stored in plain text)
Would have to be sent to clients securely.

**Comment by bigretromike** [comment]
@ElementalCrisis this should and is handle by OS (all of them).

**Comment by da3dsoul** [comment]
@bigretromike not samba, which is the most used

**Comment by bigretromike** [comment]
samba (winshare) is stored within current user on Windows and you mount those as folder on *nix

**Comment by ElementalCrisis** [comment]
There is no demand for this as this issue is the only time I've ever seen this request. Also would require a lot for work and testing for something I don't see being widely used.

**Comment by bigretromike** [comment]
yeah, because we would have to implement samba handler (smbclient support for linux) and some `net` script hacks for windows. While now we use OS to handle it.
