### ISSUE TITLE
Backup databases automatically as part of JMM Server

### ISSUE THREAD

**Issue by jmediamanager** [ShokoAnime/ShokoServer#27]
**Reported by werndlymob, Sep 18, 2012**

Backup databases automatically as part of JMM Server

Option to import/export databases as well.

**Comment by ElementalCrisis** [comment]
Backup database is now done before JMM updates itself. An option to manually run this command and have it on a timer needs to be added.

Import/Export still needs to be added.

**Comment by Cazzar** [comment]
This doesn't seem, to be a pressing issue, so I am going to close this.
