### ISSUE TITLE
SQL Schema difference between SQL Server and MySQL

### ISSUE THREAD

**Issue by SL-Gundam** [ShokoAnime/ShokoServer#275]
I did a test conversion from MySQL to SQL Server and i found that there was a difference in the schemas that might not have been intended

It concerns the AniDB_Character table
The column CharName is in MySQL of the type "text" while in SQL Server it is NVARCHAR(200)

Based on https://github.com/japanesemediamanager/jmmserver/blob/master/JMMServer/Databases/MySQL.cs i see that the MySQL version used to be the same but was changed in an alter table statement on line 510

Please evaluate whether this alter table statement should have been in the SQL Server schema as well

**Comment by ElementalCrisis** [comment]
Any input @maxpiva?

**Comment by bigretromike** [comment]
@ElementalCrisis probably not valid any more as max did revamp with patch system;

**Comment by ElementalCrisis** [comment]
Good point, if you encounter any issues @SL-Gundam, lets us know.

**Comment by SL-Gundam** [comment]
Correct. Seems to have been corrected here: https://github.com/ShokoAnime/ShokoServer/blob/ef1cda5a0232ef90b0d75bc8e0ad523330f0adde/Shoko.Server/Databases/SQLServer.cs#L558
