### ISSUE TITLE
Add Storage state "remote storage"

### ISSUE THREAD

**Issue by kerberos-git** [ShokoAnime/ShokoServer#312]
Anidb now has the option to select "remote storage" which is cloud/nas/... storage.
Would be great if this could be added to the MyList Options in a future release.

**Comment by maxpiva** [comment]
Cloud is alredy here

**Comment by ElementalCrisis** [comment]
I've re-opened this, I believe @kerberos-git was asking for the MyList option "Remote Storage" to be added.

![image](https://cloud.githubusercontent.com/assets/9443295/18774514/cd5ead18-810e-11e6-8e37-58e13e7c12a9.png)

**Comment by Jimmyson** [comment]
Is this just an issue for Shoko Desktop?
Seems that Remote option is already available as a Enum, which is also processed by "AniDBCommand_AddFile"

**Comment by ElementalCrisis** [comment]
Probably as you can only set the storage type in Desktop.
