### ISSUE TITLE
Options to rename groups when a new series is added

### ISSUE THREAD

**Issue by jmediamanager** [ShokoAnime/ShokoServer#34]
**Reported by inferknox, Nov 22, 2012**

I would like to recommend that for the grouping function, JMM checks the collection, then for series/movies takes the name of the original series from AniDB and sets that as the group title, then sets the original (if present, or sequel closest to original) series as the default series within the group.
For example, if a collection has Naruto: Shippuuden and various movies and OVAs from that and the original series, JMM will group them under the original series name, Naruto, and make Naruto: Shippuuden the default series in the group. If the original Naruto series is later added to the series, it is automatically made the original Naruto series the default series for that group, unless another series/movie/ova was set as default manually by the user.
Alternatively, the priority for the default series in the group could be the latest released TV series sequel in that group, for example, if there's Naruto TV series 1, Naruto TV series 2 and Naruto TV series 3 in the group, then the priority would fall to the latest, Naruto TV series 3.

The overall priority perhaps being TV Series, OVA/Alternative Series, Movies.

**Comment by da3dsoul** [comment]
With @pmcleish's improvements to the naming in groups. This is mostly completed. We could easily add some options like naming after the Latest Series, but I don't see why you'd want that.

**Comment by revam** [comment]
Actually implemented. Didn't know this was an open issue.
