### ISSUE TITLE
Guest account for collection comparison/sharing

### ISSUE THREAD

**Issue by jmediamanager** [ShokoAnime/ShokoServer#36]
**Reported by inferknox, Nov 23, 2012**

I would like to recommend a built in guest account that can be enabled/disabled by admin. Perhaps an admin could also be able to edit the groups (under collection) in the guest account.

This would be in order to allow one to connect to another's collection perhaps for the sake of comparison, sharing or exchange, where one person that has their own collection, instead connects their JMM Desktop to another the collection of another's computer in a temporary LAN.

Recommendations for the guest account (when compared to one I made manually under "settings>users" with all options unchecked) would be:
###### Globally
- disable watched/unwatched list and hiding of all such buttons.
- disable of playlists and hiding of all such buttons.
###### on Dashboard
- absence of "Continue Watching" section.
- absence of "Recently Watched Episodes" section.
- (perhaps) absence of "Friend Activity" section.
###### on Collection
- inability to make any changes to the groups.
- under series > series info,
  top: removal of add to playlist, edit, move series, update AniDB info and delete series.
     : addition of a "copy to" button.
  More info > TvDB & other Non AniDB Links: removal of "delete" and "switch season" buttons.
  File Summary: replacement of "delete all" buttons, with "copy to" buttons.
- under series > episodes > + (on individual episodes), removal of "delete link" (for manually linked episodes), "delete", "is variation" & perhaps some options under "more info..." and making the hash fields read-only. Addition of "copy to" button.
###### (perhaps) removal of Bookmarks section (unless it could be useful from a guest perspective)

In order to make it easier to use this feature, to add a simplified method (like a button) to allow one to quickly access another collection on another computer as a guest, comparable to how it's easy for one to switch user account (by clicking user button at bottom of JMM desktop). Perhaps making a "Scout" button next to the user button that when moused over would show a pop-up saying something like, "Allows you to look through another collection as a guest and compare and/or share anime," and when pressed would brings up a dialogue asking for the hostname or IP of the computer with the other collection.
Also, to perhaps add a question of whether one wants to "scout" another collection as a temporary guest, in the dialogue that pops up when JMM desktop is launched but can't find it's server set as default.

That's all I can think of for now. The main idea is to being able to browse, copy from, and not edit the scouted collection, as well as disabling all unnecessary sections/fields/options. :)

Had an extended thought on the idea.
To allow easier comparison of one's one collection against another:
In the case that one was logged into their default set server, when they click the "scout" button and connect to another collection, to have have the "scout" button change it's name to "scouting" and colour (to indicate a change in state), and become a drop-down of buttons with the buttons in the drop-down being:
- switch back - to quickly jump back to one's own collection to compare, etc.
  (this would change to "scout more" when browsing one's own collection, so that when selected again, would take one back to scouting the other collection)
- done scouting - to disconnect from other collection and switch back to one's own collection.

On the condition that one was not originally connected to their default collection, to have only the "done scouting" button present in the drop-down.

On all conditions, when clicking "done scouting" to have an 'are you sure?' dialogue with the buttons [yes] [no] [scout another], where the last button disconnects from this other collection and pops up the dialogue to enter the hostname/ip of another collection to 'scout', thus allowing quicker switching between scouted computers.

Also, I'd like to recommend having this guest account optionally (to admin) available to the local JMM desktop, such that one could allow another person to log into the guest account in JMM desktop on their computer to look through their collection. This will let one user give access to his collection to another user without risk of changes, even if the other user doesn't have JMM desktop installed on their own computer, or don't have their own computer present.

Just tell me to clarify if anything I said is confusing or mis-said. :)

**Comment by ElementalCrisis** [comment]
This is outside the scope of the project.
