### ISSUE TITLE
Put production company in plot summary

### ISSUE THREAD

**Issue by da3dsoul** [ShokoAnime/ShokoServer#364]
... So that I know when key is the production company before becoming emotionally attached to a character _cough_

**Comment by da3dsoul** [comment]
This will be for after as Nancy will make this easier. Also, this info isn't provided by JMM yet, so that will be needed

**Comment by da3dsoul** [comment]
I meant for this to go in Nakamori. But it does still need to be provided, maybe with a crew tag similar to role

**Comment by maxpiva** [comment]
Does production company come from AniDB?, last time i check it was a nono

**Comment by bigretromike** [comment]
mal support that (as I remamber) do we scrap from mal ?

**Comment by da3dsoul** [comment]
I thought AniDB gave that. I'll check

**Comment by da3dsoul** [comment]
Okay it's listed on AniDB, I'll need to check the dump cache in the server. Wait I have an FTP server now. Gimme a sec.

**Comment by da3dsoul** [comment]
It's in the creators tag. Usually "Animation Work". Looking through, there was one that didn't have that tag, and listed it as "Work" for some reason

**Comment by da3dsoul** [comment]
I'll write a little script to go down the list and print the contents of the Animation Work tag and if it's missing, print the rest

**Comment by da3dsoul** [comment]
That should help as AniDB cares much less about that section's info than some other things

**Comment by da3dsoul** [comment]
Planetarian has that tag as a person. Unfortunately, it looks like an mal scraper is necessary if we want a reliable source for that

**Comment by bigretromike** [comment]
This shouldn't be as hard as we already have ref_anidb_mal

**Comment by bigretromike** [comment]
and we could scrap any missing info and store it in new db table :-)

**Comment by revam** [comment]
Exposed in web ui (and jellyfin through shokofin, and plex through shoko metadata (at leadt the v3 rewrite)).
