### ISSUE TITLE
Generate Thumbs

### ISSUE THREAD

**Issue by da3dsoul** [ShokoAnime/ShokoServer#373]
With the talk of including MPV as an internal player, it occurred to me we can easily generate our own thumbs rather than using the TVDb or something. This way, we won't eat bandwidth (I don't really care. I have fiber), but more importantly, we will never have missing or incorrect thumbnails. _Cough_ OVAs _Cough_

**Comment by maxpiva** [comment]
Well, actually, the Thumb generation should be in the server, there is
already a wrapper around ffmpeg that MediaPortal uses, but we need to
include ffmpeg in the distribution.

**Comment by da3dsoul** [comment]
Right mpv is in desktop, I spaced that. Anyway, I think it'd be cool if we could use a web cache to store timestamps of screenshots. Then you could sync and generate a thumbnail that is not a spoiler for one and actually has something in it for two. Thumbnails based on percent or exact timing sometimes ends up with nothing there.

**Comment by da3dsoul** [comment]
Even better if TvDB provides the timestamp for theirs, but doubtful
