### ISSUE TITLE
Drop Destinations Sorting and HDD "freezing"

### ISSUE THREAD

**Issue by SaiZaro** [ShokoAnime/ShokoServer#385]
Its not an issue but more an enchantment to JMM, first the Drop Destination function, as I using external HDDs and I got a my anime sorted alphabetically e.g. "Y:\Anime S" so adding a option to assign a first letter of the anime title to a specific path for drop destination would make it easier to organise.

Another option that is related to this is ability to "freeze" the drive/path so once I unplug the drive JMM will still "see" it but will ignore it until it has been unfrozen (so it won't confuse the JMM when drive is not connected)

**Comment by bigretromike** [comment]
the destination folder is similar to type-one, and if someone will add this support should add both in one run: https://github.com/japanesemediamanager/jmmserver/issues/51

**Comment by da3dsoul** [comment]
#504 would be relevant. It would something in the script along the lines of Destination.IsOK
