### ISSUE TITLE
"Run import" is not same as "scan folder"

### ISSUE THREAD

**Issue by bigretromike** [ShokoAnime/ShokoServer#401]
I left source folder full of series, and started "Run import"
after night, i went back to see that more than half of series are still there
i rerun jmmserver, rerun "run import" but nothing started to scan

when i run "scan folder" icon next to source folder it started to scan and finding series from source folder.

**Comment by ElementalCrisis** [comment]
Hmm, not a bug as I don't think it's setup that way but Run Import should should scan the DS, and Watched folders and move as required.

**Comment by da3dsoul** [comment]
It does. It was broken and didn't scan folders, and I fixed it

**Comment by ElementalCrisis** [comment]
If you fixed it before, something might have changed with the cloud support merge.

**Comment by da3dsoul** [comment]
True enough I can check

**Comment by bigretromike** [comment]
Just giving the info as I add more and more series to collection and would love to use source-destiny method as I dont want to rename each folder ;-) and few of series have wrong episode names like ep172.avi and I dont have the info what series is it anyway ;-)

**Comment by bigretromike** [comment]
@da3dsoul you probably checked but didn't have time noticing us. @ElementalCrisis good for close ?
