### ISSUE TITLE
Using external db to link episodes between (xref)

### ISSUE THREAD

**Issue by bigretromike** [ShokoAnime/ShokoServer#424]
> been thinking about the community admin linking and so on. while we have a great system in place. maybe we should have a way to use another import source like this xml for example? https://github.com/ScudLee/anime-lists/ this is the list hama uses to link anidb <-> TVDB links and even tmdb. this is alot more updated it seems, while we might not want to import theses automatically and whitelist those links 100%. it would be a nice start to link the series atleast (and moving over to episodes later) more thoughts on links. dont the trakt api support tvdb id searching? if so then that can be used to link trakt flawlessly from the tvdb links. importing and dumping this each month atleast. without any confirmation. putting it in the admin approval list and so on.
> this isnt something needed at all for the full program, this is just needed to be done once to the JMM cache server.
> having good links is important for the user experience after all
> CuddleBear (Are) on Discord

Also we could exchange our database with other as PR or else.

**Comment by ElementalCrisis** [comment]
> been thinking about the community admin linking and so on. while we have a great system in place. maybe we should have a way to use another import source like this xml for example? https://github.com/ScudLee/anime-lists/ this is the list hama uses to link anidb <-> TVDB links and even tmdb. this is alot more updated it seems, while we might not want to import theses automatically and whitelist those links 100%. it would be a nice start to link the series atleast (and moving over to episodes later)

Took a quick look, it seems it just matches the name which is what JMM already does. It also suffers from the same issue I reported in https://github.com/japanesemediamanager/jmmclient/issues/400 with episode/special listing discrepancies between AniDB and TvDB.

 > dont the trakt api support tvdb id searching? if so then that can be used to link trakt flawlessly from the tvdb links. importing and dumping this each month atleast. without any confirmation. putting it in the admin approval list and so on.

Seem they do, http://docs.trakt.apiary.io/#introduction/website-media-links.

**Comment by AreFinstad** [comment]
since trakt is pretty much a mirror of tvdb. i think manual episode links for specials and other things manually linked in the cache should be mirrored (maybe not confirmed though) of what tvdb links are on trakt.

this should be really close to flawless doing it that way with the tvdb id searching in the trakt api talked about above.

**Comment by bigretromike** [comment]
@da3dsoul this also provide Studio information that we miss that much

**Comment by da3dsoul** [comment]
Cool, I think this was already in the issues list

**Comment by da3dsoul** [comment]
Nope it was this one...didn't notice it was old. Still want that MAL scraper haha. Dub cast!

**Comment by ElementalCrisis** [comment]
@revam and @da3dsoul have put a ton of work into our auto-magic linking system. I don't think we'll be using an external service.
