### ISSUE TITLE
MAL Scraper - additional information about series

### ISSUE THREAD

**Issue by bigretromike** [ShokoAnime/ShokoServer#425]
MAL contain some information that AniDB is lacking 
for example: Studio 

We could add some additional info to ours databases 
by utilizing API or simple scrapper 

This could be done via CacheServer - as only once ever or by jmmserver when needed.
A cacheserver script could run and harvest those information and jmm would use those as input to avoid stressing out MAL servers - or if the API is working use that instead to free up Cache.

**Comment by bigretromike** [comment]
@da3dsoul would love this ;-)

**Comment by da3dsoul** [comment]
Did I not have an issue for this?

**Comment by da3dsoul** [comment]
Guess not

**Comment by bigretromike** [comment]
I didnt find any so I made it so it wont be forgotten ;-)

**Comment by ElementalCrisis** [comment]
MAL API is fun to work with, just ask @hidden4003. :)

Well it can be a pain I'd prefer we use it over some third-party source. Also there are over a dozen issues related to MAL so we'll probably need a "main" issue for MAL.

**Comment by da3dsoul** [comment]
https://jikan.me/docs

**Comment by bigretromike** [comment]
omg! studio! licensor! we need this !

**Comment by bigretromike** [comment]
the question would be: we doing it inside shoko-server or via web-cache

**Comment by da3dsoul** [comment]
Inside

**Comment by da3dsoul** [comment]
Inside

**Comment by bigretromike** [comment]
you want to port jiken into c#, and maintain it ? wouldn't it be better to do it via web-cache ? so someone else would update it and we could contribute to jiken ?and if project would die we would replace it but leave web-cache structure intact ?

**Comment by da3dsoul** [comment]
It's already hosted, we don't need to

**Comment by bigretromike** [comment]
so what data we got now added ? Studios ?

**Comment by da3dsoul** [comment]
Nothing. We're dropping MAL Support. We're going with AniList

**Comment by bigretromike** [comment]
https://github.com/ShokoAnime/ShokoServer/issues/738  ok
this is the issue you refer as "drop support" https://github.com/ShokoAnime/ShokoServer/issues/739

**Comment by ElementalCrisis** [comment]
That's just the checklist, MAL has pretty much forced all third-parties devs to drop them. They completely removed their API and have no plans to bring it back as they are working on a "new" one that we should see sometime in the next millennia.
