### ISSUE TITLE
Allow marking episodes with missing files as watched

### ISSUE THREAD

**Issue by jmediamanager** [ShokoAnime/ShokoServer#43]
**Reported by Craige1Emmott, Jan 14, 2013**

As title.

**Comment by maxpiva** [comment]
It sounds like a lot of refactor is needed for this, cant figure out yet, Milestone 7.1 if possible,
The main problem is some episodes do not get populated if you don't have the file. The input process requieres a file to start, the file hashes, the file is recognized, the episode is downloaded, the anime is downloaded, etc.

**Comment by da3dsoul** [comment]
This would require moving the watched state out of videolocal. I don't think that is plausible for 3.7 right now.

**Comment by ElementalCrisis** [comment]
@da3dsoul is this possible now?

**Comment by revam** [comment]
I'm not da3d, but the tl;dr is still "no, not in our current system."

**Comment by ElementalCrisis** [comment]
Closing for now then since the work required outweighs the benefits.
