### ISSUE TITLE
Cloud temp Download Cache

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoServer#437]
while we now have great support for the cloud and everything, some people might not be able to use it because of limited download speeds, slow connection to the server or even too high of an bitrate.
having a cache folder that we self choose that JMM will download to and save to would be nice for those times. 

there should be a quick way to view whats in this cache folder from JMM (ofc JMM will hash this folder as normal aswell) and a quick way to remove everything in that folder. 

it should not be limited by folder location as people can use as much space as they wish for this.

i can also see this is great for people that are on trips and so on aswell with a slower connection than their home connection.

Cache downloads, like the Plex Sync function.
- user set folders.
- starts import of folder automatically on download completion.
- quick way to clear cache folder on per series/group basis or everything.
- Option to delete cached file after watch? (like a popup like the votes maybe?)

**Comment by bigretromike** [comment]
If I understand you want same functionality as native clients from cloud providers? If I recall most native cloud clients have ability to pick which folder you want to sync. I understand the concept but wouldn't this be against having Cloud Drives as Import Folders?

Im not against it as I see the point, but isint it redundant to most cloud clients?

**Comment by ElementalCrisis** [comment]
Cloud support is being removed from Shoko, will need to use another program to mount cloud as HDD.
