### ISSUE TITLE
Enable a periodic file scan for new files in import folders under the "watch for new files" option

### ISSUE THREAD

**Issue by jmediamanager** [ShokoAnime/ShokoServer#44]
**Reported by Craige1Emmott, Jan 14, 2013**

I'm not sure that this is already in JMM, but I'm pretty sure that the watch for new files option on anime import folders uses windows file change notifications. Unfortunate this does not work on import folders on a NAS. Adding the option to have the import folders check for new files on a periodic bases would solve this.

**Comment by ElementalCrisis** [comment]
Pretty sure this works as intended, @da3dsoul?

**Comment by da3dsoul** [comment]
See other issue

**Comment by ElementalCrisis** [comment]
For reference, https://github.com/ShokoAnime/ShokoServer/issues/98.
