### ISSUE TITLE
DefaultImagePoster is Poorly Designed and Doesn't Provide All Poster Sources

### ISSUE THREAD

**Issue by bigretromike** [ShokoAnime/ShokoServer#454]
When asking for contract_animeserie you end up with something like this:

```
anidb_id=8606
...
aniedbanime -> anidbanime: 
   defaultImagePoster: AnimeID = 8606, tvFanart=null, tvPoster=null, Imagetype=1
   ...
   fanart=null
   picname=48946.jpg

tvdb_series:
   banner=graphical/79099-g.jpg
   fanart=fanart/original/79099-8.jpg
   poster=posters/79099-3.jpg
```

Isn't this somehow broken - I would think that "defaultimageposter" should store default images from across all sites but it dosn't then it store same anidb id as the series.

Is this deprecated or broken ?

**Comment by da3dsoul** [comment]
It's poorly designed to begin with. Fanart and banner were rewritten by me to handle randomizing on request without making a bunch of db calls. I left poster alone as most people prefer the poster to be consistent.

**Comment by bigretromike** [comment]
How then I can get poster/fanart/banner/anything for given serie_id ?

**Comment by da3dsoul** [comment]
Via code or web?

**Comment by bigretromike** [comment]
via jmm objects.

**Comment by da3dsoul** [comment]
For fanart and banner, you use AnimeSeries contract and iterate the fanarts and banners objects. For posters, I haven't done that yet, so it's really slow

**Comment by da3dsoul** [comment]
AniDB.GetDefaultPosterNoBlanks is the method though

**Comment by maxpiva** [comment]
Proposal to refactor image database:
We leave the image provider database alone. But we add an extra Images table, this table contains the references to all images, with column defining their type (banner, fanart, poster, episode, etc). size, source, and source ID, anidb id, etc. 
On Provider table (Example Trakt_ImagePoster) modification (save or) delete, we change/add or delete the image from the image table.

For consumption, we only query the image database.

**Comment by bigretromike** [comment]
Wouldnt it duplicate content ? The concept look solid but also redundant. 

On October 4, 2016 4:07:26 AM GMT+02:00, Maximo Piva <notifications@github.com> wrote:
>Proposal to refactor image database:
>We leave the image provider database alone. But we add an extra Images
>table, this table contains the references to all images, with column
>defining their type (banner, fanart, poster, episode, etc). size,
>source, and source ID, anidb id, etc. 
>On Provider table (Example Trakt_ImagePoster) modification (save or)
>delete, we change/add or delete the image from the image table.
>
>For consumption, we only query the image database.
>
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/japanesemediamanager/jmmserver/issues/454#issuecomment-251277574

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by maxpiva** [comment]
Content, no of course not. We only store the links to the content, Redundant is the mother of NOSQL. NOSQL has no joins, you have to copy the data over and over. We could restructure the whole image system, to use only one table for all, but that will be expensive in code time. We could do this as a patch, then we we have time remove every other database, but that will require to change how every providers store the data in the database.
In fact, NOSQL fits JMMServer needs, but the refactor to that kind of database system is extremely big. I started it one year ago. and drop it because the time needed.

**Comment by bigretromike** [comment]
The patch thing and moving to one table sound rational. We have like 4-5 providers to update that way

On October 4, 2016 6:44:01 AM GMT+02:00, Maximo Piva <notifications@github.com> wrote:
>Content, no of course not. We only store the links to the content,
>Redundant is the mother of NOSQL. NOSQL has no joins, you have to copy
>the data over and over. We could restructure the whole image system, to
>use only one table for all, but that will be expensive in code time. We
>could do this as a patch, then we we have time remove every other
>database, but that will require to change how every providers store the
>data in the database.
>In fact, NOSQL fits JMMServer needs, but the refactor to that kind of
>database system is extremely big. I started it one year ago. and drop
>it because the time needed.
>
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/japanesemediamanager/jmmserver/issues/454#issuecomment-251294589

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ElementalCrisis** [comment]
@bigretromike was your recent commit related to this?

**Comment by bigretromike** [comment]
no, my update was related to pass more images thru api; not populate refactoring image database

**Comment by ElementalCrisis** [comment]
Is this still an issue @da3dsoul or @bigretromike?

**Comment by da3dsoul** [comment]
We have an issue for image management
