### ISSUE TITLE
JMM always rehashes files on a network share/mapped drive

### ISSUE THREAD

**Issue by hidden4003** [ShokoAnime/ShokoServer#458]
Steps to reproduce: 
Add network share as a mapped drive or UNC path.

that's where it fails:
https://github.com/japanesemediamanager/jmmserver/blob/master/JMMServer/Importer.cs#L256

fileName is "Z:\\Ecchi-Pack\\Astarotte no Omocha! EX\\[Morai-Subs] Astarotte no Omocha EX - OVA [BF8EB403].mp4"
but key is stored as Z:\Ecchi-Pack\Astarotte no Omocha! EX[Morai-Subs] Astarotte no Omocha EX - OVA [BF8EB403].mp4

**Comment by RickDB** [comment]
Could you check the logs and post what it reports just before the hashing, mainly this one:

"ImportFolder: {0} || {1}"

Something is re-adding a extra slash after Z:\ there but we already check for that so wondering where that one is getting re-added:

https://github.com/japanesemediamanager/jmmserver/blob/master/JMMServer/Entities/ImportFolder.cs#L210

**Comment by hidden4003** [comment]
I tried to reproduce it and can't, only Baine has this issue.

**Comment by Baine** [comment]
@RickDB unfortunately it does not report such a line. directly starts with the listing, and immediately adds the files to the hasher queue

**Comment by da3dsoul** [comment]
#474 will at least help deliberate what the hasher is doing.

**Comment by bigretromike** [comment]
@hidden4003 is this still there ?
@ElementalCrisis who was working on this as you set `in progress` ? 
@da3dsoul did it helped ?

I didn't encounter this error on few daily build earlier, is this still an issue ?

**Comment by ElementalCrisis** [comment]
Marked as In Progress due to the changes in #474.

**Comment by da3dsoul** [comment]
I don't know anything about this, am not working on it, nor plan to. I don't use network drives. I was just saying more info should help.

**Comment by Jimmyson** [comment]
I use network drives to access my Anime files stored on a remote file server, to my Shoko Instance. I have not been able to recreate this issue.
Files that have not moved location in a mapped drive do not get rescanned. Only when moved to another mapped drive.

**Comment by ElementalCrisis** [comment]
Ok, will close for now. If anyone can reproduce we can re-open it.
