### ISSUE TITLE
Updating database phases 

### ISSUE THREAD

**Issue by bigretromike** [ShokoAnime/ShokoServer#493]
This is issue that I found while debugging cause of #492 

`version` should be updated as fast as possible - when the updating table function end up 
not after caching 

This made specific issue occur: 
- updating db
- caching db
- caching taking to long mysql timeout jmm and lock it out 
- jmm restart/reconnect by hand
- jmm read `version` without update 
- jmm thinks that db is older version
- jmm apply same fixes on db as before

Until caching is finished the version table isn't updated

**Comment by maxpiva** [comment]
ll DatabaseRepositories, including the ones with caching (Not the versions case), Updating is immediate.  The cache is using for read fast not for writing.
All The Database schema changes, are executed one by one, and after successfully execute  impact the versions table.

The only possible way, the update was executed and the versions table not, is with visual studio, break the execution between these two parts.

Part 1

```
        public Tuple<bool, string> ExecuteCommand(T connection, DatabaseCommand cmd)
        {
            if (cmd.Version != 0 && cmd.Revision != 0)
            {
                if (AllVersions.ContainsKey(cmd.Version.ToString()) &&
                    AllVersions[cmd.Version.ToString()].ContainsKey(cmd.Revision.ToString()))
                    return new Tuple<bool, string>(true, null);
            }
            Tuple<bool, string> ret;

            switch (cmd.Type)
            {
                case DatabaseCommandType.CodedCommand:
                    ret = cmd.UpdateCommand(connection);
                    break;
                case DatabaseCommandType.PostDatabaseFix:
                    try
                    {
                        AddFix(cmd);
                        ret = new Tuple<bool, string>(true, null);
                    }
                    catch (Exception e)
                    {
                        ret = new Tuple<bool, string>(false, e.ToString());
                    }
                    break;
                default:
                    ret = ExecuteCommand(connection, cmd.Command);
                    break;
            }

```



Part 2


```
if (cmd.Version != 0 && ret.Item1 && cmd.Type!=DatabaseCommandType.PostDatabaseFix)
            {
                AddVersion(cmd.Version.ToString(), cmd.Revision.ToString(), cmd.CommandName);
            }
            return ret;
        }
```

**Comment by bigretromike** [comment]
Im unsure which part failed but ```version``` didnt get updated after update run and i had to restart jmm because of time out of db and end up with db after update but without proper rows in db

**Comment by maxpiva** [comment]
All DatabaseRepositories, including the ones with caching (Not the versions
case), Updating is immediate.  The cache is using for read fast not for
writing.
All The Database schema changes, are executed one by one, and after
successfully execute  impact the versions table.

The only possible way, the update was executed and the versions table not,
is with visual studio, break the execution between these two parts.

Part 1

    *    public Tuple<bool, string> ExecuteCommand(T connection,
DatabaseCommand cmd)*
*        {*
*            if (cmd.Version != 0 && cmd.Revision != 0)*
*            {*
*                if (AllVersions.ContainsKey(cmd.Version.ToString()) &&*
*
AllVersions[cmd.Version.ToString()].ContainsKey(cmd.Revision.ToString()))*
*                    return new Tuple<bool, string>(true, null);*
*            }*
*            Tuple<bool, string> ret;*

*            switch (cmd.Type)*
*            {*
*                case DatabaseCommandType.CodedCommand:*
*                    ret = cmd.UpdateCommand(connection);*
*                    break;*
*                case DatabaseCommandType.PostDatabaseFix:*
*                    try*
*                    {*
*                        AddFix(cmd);*
*                        ret = new Tuple<bool, string>(true, null);*
*                    }*
*                    catch (Exception e)*
*                    {*
*                        ret = new Tuple<bool, string>(false,
e.ToString());*
*                    }*
*                    break;*
*                default:*
*                    ret = ExecuteCommand(connection, cmd.Command);*
*                    break;*
*            }*




Part 2

*            if (cmd.Version != 0 && ret.Item1 &&
cmd.Type!=DatabaseCommandType.PostDatabaseFix)*
*            {*
*                AddVersion(cmd.Version.ToString(),
cmd.Revision.ToString(), cmd.CommandName);*
*            }*
*            return ret;*
*        }*

**Comment by bigretromike** [comment]
There weren't any breaks inside debugger which make it scary.
The timeout of database should matter because as you wrote it is done right away .

Could any of those elements change the outcome ? 
``` cmd.Version ``` couldn't be 0
``` cmd.Type ``` should be DatabaseCommandType.PostDatabaseFix (but i dunno this) maybe there were a logic bomb somewhere?
``` ret.Item1 ``` could this be a ```False``` ? then it wouldn't execute Part2

That's why I posted. 
Who knows maybe space rays hit that one bit and flip it - how big are changes... anyway as it was strange I report it, if you don't see a possible in code for that to happen then please close the issue as this was one-time-only issue.

**Comment by maxpiva** [comment]
Hmm, there could be a bug.
But
PostDatabaseFix, are the database updates but using code (Fill data, replace data, etc), they execute after database initialization, so, they're not executed right away.
ret.Item1 is the result of the executing command, if it fails it return false, if sucess true.

We leave it open, so we can monitor if other user has the same problem.

**Comment by da3dsoul** [comment]
As we are seeing if anyone else has this issue, we don't want to hold up releasing on it. Removing from 3.7 Milestone
