### ISSUE TITLE
settings.json get reset and lock down jmm

### ISSUE THREAD

**Issue by bigretromike** [ShokoAnime/ShokoServer#503]
I remember someone having same issue as this.

Build few jmm few times and running in DEBUG sometimes (had this issue first time after discord chat)
wipe config and not every setting is readded to file  - Why it wipe out config file ?!
I didn't save that setting file but I recall that it only had 1,5 KB or less.
It lacked information about database etc.

The worst part is that the exception is not handled and shutdown jmm with error about null ref.

As currently this happen first time when using DEBUG mode I cannot exclude this from happening on RELEASE build.

**Comment by maxpiva** [comment]
I remember having this problem. I did a special case inside the save to not
save the config in case the number of config items where less than 2. It
only happens in debug and alas putting a breakpoint in there will no hit
seems a side effect of manual stopping the debug. I was unable to pinpoint
the cause but seems when you stop somehow it tries to save the already
disposed object.

**Comment by bigretromike** [comment]
@maxpiva if its a case for only 2 items, than my config had more than 2 items only;
oh. So its because of exiting debug manually when he try to save config back ?
Maybe he should try to save new config to new file like settings_new.json and as last function to 
```File.Move("settings_new.json","settings.json")```
That was manual stoping it or unexpected crash wont overwrite config
