### ISSUE TITLE
Running JMM with network shear but without saved creditials

### ISSUE THREAD

**Issue by bigretromike** [ShokoAnime/ShokoServer#505]
When running JMM (master) with big collection that is stored on NAS and access is not saved - so when trying to enter it you need to enter user/pass each time - "videolocal_dbregen" - which is just checking file paths as I was told, is taking a lot of time.

20 or more second per 10 items (~2s/item) 
with NAS access it takes 1sec to proceed 10items (0.1s/item)

Is there anything we could add to make it go faster?

**Comment by bigretromike** [comment]
Also I could add issue related with this which is probably Windows 8.1 fault. 
When using same NAS with same non saved credentials after some time  when starting JMM it looks like dbregen hanged or is not accessing file, but when entering same NAS via explorer/file manager windows magically remember path and cred and dbregen boost up.
Strange thing but probably Windows related than anything else - file explorer trigger something in windows that jmm don't.

**Comment by ElementalCrisis** [comment]
@bigretromike maybe an issue you'd like to tackle? :)

**Comment by Cazzar** [comment]
At this point, given the Linux support we now have, just run it on the NAS directly.
