### ISSUE TITLE
Specify Drop Destination depending on media type

### ISSUE THREAD

**Issue by jmediamanager** [ShokoAnime/ShokoServer#51]
**Reported by CatmanIX, Mar 10, 2013**

Say someone sets M:\Anime\Movies for all movies to be moved to and M:\Anime\Series for all series. Have it entirely configurable so one could say put OVA's and Series in \Series or however else a user would want it.

**Comment by da3dsoul** [comment]
+1

**Comment by revam** [comment]
Technically speaking then this can be achieved trhough the current renaming system, so I'm closing this.
