### ISSUE TITLE
hashes not getting saved in db on some cloud files. 

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoServer#520]
Seems some hashes dont get saved at all when "hashing" from the cloud.

Personally got 434 files that does not list hashes in the desktop client or the database of 2435 file in total of unrecognized files. 

"Seems file is being processed followed by the user getting an 405 Error - Method not found." said Elemental Crisis.

![](http://i.imgur.com/U715Q93.png)
![](http://i.imgur.com/eEcw62o.png)
![](http://i.imgur.com/RpKhCE2.png)

"[2016-11-23 15:49:16:683] Error|VideoLocal_Place.RefreshMediaInfo => AzureWebAPI.Get_Media => AzureWebAPI.GetDataJson Error(1) in AzureWebAPI.GetData: System.Net.WebException: The remote server returned an error: (405) Method Not Allowed.
   at System.Net.HttpWebRequest.GetResponse()
   at JMMServer.Providers.Azure.AzureWebAPI.GetDataJson(String uri) in D:\My Files\Documents\GitHub\jmmserver\JMMServer\Providers\Azure\AzureWebAPI.cs:line 568"

**Comment by maxpiva** [comment]
Hmm, Remember Empty hashes is a possible outcome of the current system, if the file is not in the web crosshash, or in your database. It will have an empty hash.

What we need to do, is add a utils, to recheck those files. in case, the web cache crosshash got populated or you hashed it locally.

**Comment by ElementalCrisis** [comment]
Ah that's right, I completely forgot about that. We could also have an option to have the utility temporarily download the file, hash it and then delete the temporary download.

**Comment by AreFinstad** [comment]
if you are doing that then i want it to be able to avdump aswell @ElementalCrisis

**Comment by da3dsoul** [comment]
This is probably fixed
