### ISSUE TITLE
File sare not moved from Drop Source to Drop Destionation

### ISSUE THREAD

**Issue by kusco123** [ShokoAnime/ShokoServer#524]
Ok - did a complete new import of my Collection, tried to import some files - still they are not moved from the dropfolder ...

In the test it's about SoulBuster 1 to 5 (so a new series) and Servamp 10-12 (so an already existing Series)

After the import I can see the path in the Collection View pointing to the Dropfolder file.

JMMServer 3.7.0.0 - but the issue started suddenly with the last 3.6 version

[2016-12-04.zip](https://github.com/japanesemediamanager/ShokoServer/files/629202/2016-12-04.zip)

**Comment by kusco123** [comment]
[3.7.0.9004.zip](https://github.com/japanesemediamanager/ShokoServer/files/629214/3.7.0.9004.zip)

Same with last Beta Version. Added some files for testing.

**Comment by maxpiva** [comment]
Seems your files are not moving, because there is no such release on AniDB. JMM Detect files by hash against anidb, if you want your files recognized. You have two paths:
1) Use ShokoClient and add manually to the series in the utilities section.
2) use anidb avdump and add not recognized files to anidb.

**Comment by kusco123** [comment]
Sorry but that's simply not right. The files are recognised by anidb and they are nit visble in the Utilities section - I attach a screenshot - the files are not manually added.

Also I am using avdump since it is availible every time when I recreate teh database I have to add the same unrecognised files again and again and again ...

And - I see tons of errors like this in the log:

`[2016-12-04 11:39:03:235] Error|VideoLocal.ToContract => VideoLocal.GetMediaFromUser => VideoLocal_Place.RefreshMediaInfo File \\192.168.0.3\Anime\_LongSeries\Naruto\Naruto Shippuuden\[HorribleSubs] Naruto Shippuuden - 409 [720p].mkv does not exist, unable to read media information from it`

But when I enter the path in teh Explorer on teh machine shoko server is installed on it plays immediatky ...

![jmm_3](https://cloud.githubusercontent.com/assets/22934156/20865597/0b316d6a-ba17-11e6-9366-405454fa9eba.png)
![jmm_1](https://cloud.githubusercontent.com/assets/22934156/20865512/2fad8e8c-ba15-11e6-88a6-a6399db58010.png)

**Comment by da3dsoul** [comment]
Yeah, I'll reopen this for now.

**Comment by da3dsoul** [comment]
Considering that is a network path, it may be related to #495

**Comment by kusco123** [comment]
Could be - but I the NAS is online always connected over a Trunk and even I restart the server rather often for testing so the only thing I could happen would be that the server is starting before teh network is active but this isn't the case either. I think it started with the last major release but I can't say for sure :(

**Comment by ElementalCrisis** [comment]
As far as I'm aware we don't have anyone on the team that has a NAS Setup so is hard to test. Are your import folders mapped to the actual location or a mapped drive?

**Comment by Animeimp** [comment]
I am setup on a NAS (Synology), mapped to drive Z in windows.  Both the
Import folder and Drop folder are on the NAS, but they are listed as UNC
rather than the mapped drive, so the import folder is
\\DISKSTATION\Storage\Anime\Unprocessed, and the drop folder is
\\DISKSTATION\Anime.  The rename script does not reference any paths
directly, taking them from JMM instead.

The local paths under JMM Server and Workstation are the UNC paths.

**Comment by ElementalCrisis** [comment]
@hidden4003 and @RickDB might be able to help as they were helping another user before. I believe @Baine also has some experience with this.

**Comment by kusco123** [comment]
Ok - some updates ...

I have now created a new databse and only added one yearfloder (_2016) ass dropp destination and _Drop as dropsource - and files are moved ...

So - any idea if teh size of teh collection might be an issue?

What I also can see is that the automatic import is not starting (in previous versions it started immediatly when a file was moved to the dropfolder) - I need to start "Run Import"
[2016-12-08.zip](https://github.com/japanesemediamanager/ShokoServer/files/640258/2016-12-08.zip)

**Comment by da3dsoul** [comment]
All of the above works fine for me. Size doesn't matter.

**Comment by kusco123** [comment]
you sure that none that neither number of folders / subfolders / files nor total size of the collection does have any impact?

**Comment by ElementalCrisis** [comment]
Yeah, we have users who have collections over 20TB. Folder limitations exists but that's at the OS level, same with length of filename.

**Comment by RickDB** [comment]
Tested here as well and couldn't find any issues with it, code wise looks correct so not sure what would cause this.

**Comment by ElementalCrisis** [comment]
@kusco123 is this still an issue?

**Comment by bond4u** [comment]
I have bunch of files that are recognized and appear in collection, but files themselves are still in drop source.
"Seishun Anime Zenshuu" episodes for example.

![image](https://user-images.githubusercontent.com/66413/29497196-5fe9c5cc-85ec-11e7-895f-13ea96870331.png)

GetDestinationFolder returns empty string as "newFullPath" and nothing is done and reported.

**Comment by da3dsoul** [comment]
Wonderful. Is it consistent? Or do they move after hitting 'scan folder' on an import folder

**Comment by bond4u** [comment]
All episodes of this series are in drop source folder.
I guess there have been there since they were created - 5th july 2017.
Server log just shows that rename was skipped since it already matched the pattern.
```
[2017-08-20 21:14:12:515] Info|SVR_VideoLocal_Place.RenameAndMoveAsRequired => SVR_VideoLocal_Place.RenameIfRequired => SVR_VideoLocal_Place.RenameFile Renaming file From (G:\_torrentz\_removed\_2017\07\[ARR] Seishun Anime Zenshuu - 31  [B5EC1A76].mp4) to (G:\_torrentz\_removed\_2017\07\[ARR] Seishun Anime Zenshuu - 31  [B5EC1A76].mp4)....
[2017-08-20 21:14:12:515] Info|SVR_VideoLocal_Place.RenameAndMoveAsRequired => SVR_VideoLocal_Place.RenameIfRequired => SVR_VideoLocal_Place.RenameFile Renaming file SKIPPED! no change From (G:\_torrentz\_removed\_2017\07\[ARR] Seishun Anime Zenshuu - 31  [B5EC1A76].mp4) to (G:\_torrentz\_removed\_2017\07\[ARR] Seishun Anime Zenshuu - 31  [B5EC1A76].mp4)
```
Couple of different release groups - ARR, archivisth, Unknown.
LegacyRenamer seems to think that `string thisFileName = place?.FilePath;` "thisFileName contains folder, but in this case it doesn't.

**Comment by Cazzar** [comment]
Going to close this issue for now, it can be re-raised if it is still a problem.
