### ISSUE TITLE
Error merging dll

### ISSUE THREAD

**Issue by da3dsoul** [ShokoAnime/ShokoServer#526]
I've never seen this before, and it only happened since https://github.com/japanesemediamanager/ShokoServer/commit/2ec9a8ea79bb484559ad65d37fabdcdb36f913c6 but there didn't seem to be any changes affecting it, so idk.

```
2>  Unresolved assembly reference not allowed: PresentationFramework.
2>     at System.Compiler.Ir2md.GetAssemblyRefIndex(AssemblyNode assembly)
2>     at System.Compiler.Ir2md.GetTypeRefIndex(TypeNode type)
2>     at System.Compiler.Ir2md.VisitMethodCall(MethodCall call)
2>     at System.Compiler.Ir2md.VisitMethodCall(MethodCall call)
2>     at System.Compiler.Ir2md.VisitBlock(Block block)
2>     at System.Compiler.Ir2md.VisitBlock(Block block)
2>     at System.Compiler.Ir2md.VisitMethodBody(Method method)
2>     at System.Compiler.Ir2md.VisitMethod(Method method)
2>     at System.Compiler.Ir2md.VisitClass(Class Class)
2>     at System.Compiler.Ir2md.VisitModule(Module module)
2>     at System.Compiler.Ir2md.SetupMetadataWriter(String debugSymbolsLocation)
2>     at System.Compiler.Ir2md.WritePE(Module module, String debugSymbolsLocation, BinaryWriter writer)
2>     at System.Compiler.Writer.WritePE(String location, Boolean writeDebugSymbols, Module module, Boolean delaySign, String keyFileName, String keyName)
2>     at System.Compiler.Writer.WritePE(CompilerParameters compilerParameters, Module module)
2>     at ILMerging.ILMerge.Merge()
2>     at ILMerging.ILMerge.Main(String[] args)
```

**Comment by da3dsoul** [comment]
@japanesemediamanager/developers

**Comment by maxpiva** [comment]
Restore JMMServer.csproj
<https://github.com/japanesemediamanager/ShokoServer/commit/2ec9a8ea79bb484559ad65d37fabdcdb36f913c6#diff-224858b6bf71e2fe379d187161b4b7c5>
just
in case.
Add TamedFileWatcher at hand.
It probably has something to do with  Visual 2017 RC.

**Comment by da3dsoul** [comment]
I'd expect that as well, so I tried it with no luck. Tried VS2017 with no luck.

**Comment by da3dsoul** [comment]
http://stackoverflow.com/questions/3371583/serious-trouble-with-ilmerge-and-net-4-0

**Comment by da3dsoul** [comment]
According to that, I'm not sure how it ever worked or just now stopped working...

**Comment by Cazzar** [comment]
Do we use ILMerge any more with .net core?

**Comment by da3dsoul** [comment]
We haven't used it for a while, as it stopped working and I couldn't figure it out
