### ISSUE TITLE
Parent System for Command Queue

### ISSUE THREAD

**Issue by da3dsoul** [ShokoAnime/ShokoServer#533]
When creating a command request, we can specify a parent command to be dependent upon. This can allow us to safely skip commands in case of error or ban. This may also be combined with ideas from the queue factory concept, so that we still have multiple queues, but rather than General, images, hashing, etc, we can have queues dependent on what the task is. This can also help make some things more synchronous.

**Comment by maxpiva** [comment]
Refer to #433
