### ISSUE TITLE
Destination folder being ignored - is it a feature ?

### ISSUE THREAD

**Issue by bigretromike** [ShokoAnime/ShokoServer#536]
As I always though source folder is folder where I put anime to being recognized and destination folder is where those recognized series should be transfer, any other folder is just for storage.

But today (using 3.7.0.1) I put series in Source folder, it was series that I already had on "normal" folder - but by other fan-group. 
The files had been recognized and move to "normal" folder instead of Destination folder.
Is this something new ? as I usually have low space on "normal" folders and tend to move series out of destination folder by hand - and eventually use "duplicate" tool inside client.

**Comment by ElementalCrisis** [comment]
If that folder was previously set as a destination folder and series had been moved to it, then those series will always move to the folder even if you update the destination folder.

**Comment by bigretromike** [comment]
No it wasnt destination folder ( if i recall corectly ) any way to check that ? But i dought about it being destination 
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by hidden4003** [comment]
It was always there, if series already has a folder then it adds files there, new folder is only created if you do not have any files. Strictly speaking it is not necessarily true, I don't remember exactly how it determines path but I think it takes videolocal from series with highest id, i.e. latest series added, so if you move that file somewhere and Run import or change path in DB then all newly recognized files will be moved to that folder.

**Comment by bigretromike** [comment]
But if it the intended way ? Basically all import folders are also destination folders for known series... what if folder is shear only ?

I don't mind this "hidden feature" like this one - which could be documented better ;-) (or I don't recall readying about this ;-) )

**Comment by hidden4003** [comment]
There is no simple solution to this, if we use your logic then users will end up with series scattered over multiple destination folders. As far as I understand your logic is - check destination folder if no folder for series create one and put file there.
Other way could be, if new file is added but series exist but it is not in the destination folder then existing series files moved into new destination folder and file added there.

**Comment by bigretromike** [comment]
And the second option is what i wpuld pick as current method dont imply having dest folders. Also this could be tied to a request from other issue to have src-dest correlation for anime,ecchi,hentai,etc... 

On January 4, 2017 6:38:14 PM GMT+01:00, hidden4003 <notifications@github.com> wrote:
>There is no simple solution to this, if we use your logic then users
>will end up with series scattered over multiple destination folders. As
>far as I understand your logic is - check destination folder if no
>folder for series create one and put file there.
>Other way could be, if new file is added but series exist but it is not
>in the destination folder then existing series files moved into new
>destination folder and file added there.
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/japanesemediamanager/ShokoServer/issues/536#issuecomment-270434113

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
