### ISSUE TITLE
Save and start server without filling all fields greys out save and start button

### ISSUE THREAD

**Issue by xsystematic** [ShokoAnime/ShokoServer#537]
So after the "Fill all fields" notice (for not entering a database name) I can no longer change database type or start server after entering a database name unless I restart Shoko

![untitled](https://cloud.githubusercontent.com/assets/10373766/21580072/7e16e148-cfcf-11e6-8c5a-5449e22a4267.png)

Unsure if by design. 
Found this when not entering a database name (as it's blank by default) after upgrading to 3.7

**Comment by ElementalCrisis** [comment]
MySQL and SQL Server have been deprecated; SQLite is now default for all new users.
