### ISSUE TITLE
improvement idea - confirming unrecognized files

### ISSUE THREAD

**Issue by bond4u** [ShokoAnime/ShokoServer#549]
Confirming unrecognized files is quite a chore.
I've been thinking for a while that there could be option to link file search and series search, so that I don't need to type twice.
Next step would be to store the search pattern(s) and apply it to new files thus improving recognize feature.
Of course it would not work so easily with long-running-multiple-seasons anime.

![image](https://cloud.githubusercontent.com/assets/66413/21962684/8dcaa6ea-db34-11e6-9f62-181ecdaadde1.png)

**Comment by revam** [comment]
The new (beta) web ui have a better flow for manually linking unrecognized files. And since desktop is in maintenance mode then I'm closing this.
