### ISSUE TITLE
MySQL statistics show a lot of changedb commands

### ISSUE THREAD

**Issue by SL-Gundam** [ShokoAnime/ShokoServer#550]
My MySQL server runs almost exclusively the Shoko database.

Phpmyadmin shows this after starting a empty Shoko database and importing 2.5TiB of Anime
![image](https://cloud.githubusercontent.com/assets/912973/22045320/cf48ea28-dd19-11e6-98ee-4573db7997e7.png)

I've got almost as much change db commands as select queries. Now i'm not certain about the impact of redundant change db commands on performance
But none the less i thought i report it since to my knowledge Shoko keeps around 3 connections active constantly to the database. so if those 3 handle the queries then only 3 change db commands would be needed. Unless Shoko is connecting and disconnecting constantly

**Comment by da3dsoul** [comment]
It's likely due to the way we use upgrade patches to set up the DB. Rather than initializing the DB in just a few commands, one per table, we make the table as it was long ago and apply all the patches up until now. There shouldn't be any more after initial import.

**Comment by SL-Gundam** [comment]
I'm pretty sure it has nothing with the upgrade patches as both values in question have increased by ~300 at the moment

Previously with JMM server when i checked these values they were always more or less evenly split between select and change db

**Comment by SL-Gundam** [comment]
This seems to be fixed by now (tested on Shoko 3.9.4)
