### ISSUE TITLE
Integrity check does't check current record after start of process

### ISSUE THREAD

**Issue by Animeimp** [ShokoAnime/ShokoServer#555]
Running 3.7.03, and kicked off a Integrity check, then while in the Shoko client, proceeded to remove some multiple files from groups.  As the Integrity check reached the groups I had cleaned, it reported them as missing entries.  It appears the Integrity makes a list of files to check, and works off that, rather than activity checking the database after the check has started.

**Comment by ElementalCrisis** [comment]
Closing this issue, Integrity Check utility is no longer available and needs to be redone and added to the Web UI.
