### ISSUE TITLE
Support for proxies

### ISSUE THREAD

**Issue by jmediamanager** [ShokoAnime/ShokoServer#56]
**Reported by Qscholtzzz, May 6, 2013**

Im at.a university and need to use proxifier for.applications that does not have a buolt in proxy login thing.But anyway when im connecting most of the functions work but looking at the server logs its seen that when it searches anidb for file information using the api it does not work the connection times out,if you can shed some,light i will be gratefull,i defenitly know everything works when im at home using my parents internet.And it could be awsome if you can add proxy,support for https someday but anyway thx

**May 15, 2013 Craige1Emmott**

The best option here would be for JMM to pull the system internet options by default, its also what a good behaving program should do. This would cover the situation given.

**Comment by ElementalCrisis** [comment]
This is in progress, right @Cazzar and @da3dsoul?

**Comment by da3dsoul** [comment]
Yes

**Comment by ElementalCrisis** [comment]
@da3dsoul was there ever implemented?

**Comment by da3dsoul** [comment]
No, use a vpn
