### ISSUE TITLE
Shoko Server forgets custom image files location

### ISSUE THREAD

**Issue by TheOne320** [ShokoAnime/ShokoServer#561]
I set a custom location for my image files, but sometimes when I open Shoko server it starts migrating and moves all the images from my custom location to the default location. I then have to set the custom location again and move all the image files back and restart Shoko server. I have no idea what could be causing this.

**Comment by ElementalCrisis** [comment]
Next time please follow the template that was loaded when you created an issue as the items we ask are needed for potentially fixing the issue.

Please attach your server log. 

Does this happen every-time you restart Server?

**Comment by TheOne320** [comment]
[2017-01-28.txt](https://github.com/japanesemediamanager/ShokoServer/files/736843/2017-01-28.txt)

No, it happened at the beginning when I started using 3.7.0.3 after upgrading from 3.6 and it happened again today. I attached today's log.

**Comment by ElementalCrisis** [comment]
Got it, what probably happens is during the migration check Shoko detects the images are not in programdata so it moves them. @maxpiva can you take a look when you have a moment?

**Comment by hidden4003** [comment]
@ElementalCrisis I remember this, he is probably running server as administrator not as user, migration code never runs under normal privileges.

**Comment by TheOne320** [comment]
No, I am running it with my normal user account.

**Comment by TheOne320** [comment]
It started migrating again today. I just started it normally like always. Did you find anything? Her is another log file.
[2017-02-02.txt](https://github.com/japanesemediamanager/ShokoServer/files/748524/2017-02-02.txt)

**Comment by ElementalCrisis** [comment]
Yeah, server check and notices images are missing so it wants to migrate them. Looks like we need to add a check in the migration for if a custom location is used.

**Comment by Jimmyson** [comment]
This seems to relate to a larger issue: **LoadSettingsFromFile**
https://github.com/ShokoAnime/ShokoDesktop/issues/546 also has a similar nature issue on **LoadLegacySettingsFromFile**

Digging around seems to identify something. The Registry Uninstall GUID may not match one this is on the client machine. Mine is `{0BA2D22B-A0B7-48F8-8AA1-BAAEFC2034CB}_is1`.

I would suggest making this GUID value dynamic.

**LoadLegacySettingsFromFile** also seems to run when invalid settings are detected

**Comment by Cazzar** [comment]
That would refer to when it was JMM not Shoko
We are using that to detect if JMM is installed

**Comment by bond4u** [comment]
My settings.json has following entries:

  "BaseImagesPathIsDefault": "False",
  "BaseImagesPath": "D:\\Tools\\jmm\\images",
  "ImagesPath": "E:\\Tools\\jmm\\images",

When I start server, server settings shows "D:\" one, even thou I have repeatedly changed it to "E:\" one.
