### ISSUE TITLE
Importing stop on empty disk

### ISSUE THREAD

**Issue by bigretromike** [ShokoAnime/ShokoServer#568]
## Description

When using source-destination folders and series is in other folder than destination shoko try to move it to that folder. But if that folder have no space on disk then shoko stop (crash?) and don't scan anything after that - it cancel out the import task

## STEPS TO REPRODUCE

add folder with Serie X on disk 
fill up the disk with series X
add source folder from disk Y
add destination folder on disk Y
put serie X from different group on source folder Y
put other series in source folder Y that names are after name of serie X
start import

**Comment by da3dsoul** [comment]
#504 is considered the fix for this. As to how to handle it with drop folders, it has been a topic of debate

**Comment by bigretromike** [comment]
#504 or something for now :-) 
But I would like to see that #504 being implemented

**Comment by da3dsoul** [comment]
In my case, I've never experienced such a thing.
![screenie](https://dl.dropboxusercontent.com/u/31454410/Github%20Issues/Screenshot%202017-02-01%2013.11.24.png)

**Comment by revam** [comment]
Can probably close this too for the same reason as #504 — we have renamer plugins that can do this now (if configured properly to handle it).

I'll let you be the judge @da3dsoul
