### ISSUE TITLE
Login rate limiter

### ISSUE THREAD

**Issue by Stonedestroyer** [ShokoAnime/ShokoServer#573]
## LOG FILE

https://github.com/japanesemediamanager/ShokoServer/files/750183/2017-02-03.txt

## Description

Trying to switch database and each time it logs into AniDB getting me banned.

## STEPS TO REPRODUCE
Keep switching database and logs you in each time, I think shutdown is affected by same thing.

**Comment by Cazzar** [comment]
Ultimately as well, the login prompt shouldn't appear on a banned response.

**Comment by bond4u** [comment]
Is this about "anidb login failed" popup? It pop up way too often. I just confirmed my login and minute later it pops up again. I think it pop ups on any (connection) error, not just failed login.

**Comment by ElementalCrisis** [comment]
Is still an issue on Daily?

**Comment by Cazzar** [comment]
I would say this is fixed, as the login command is forced through the ratelimiter.
As for the login popup stuff, #644

**Comment by bigretromike** [comment]
Fresh install with 3.8, fresh db. After scanning my database I end up with ban, that is now 2 days long... wtf

**Comment by Cazzar** [comment]
@bigretromike adding logs would be useful, as I rehashed my entire library after all the ratelimit code was modified, and have not had this.

**Comment by ElementalCrisis** [comment]
Keep in mind that failing a login I believe twice gets you banned as well. But I just tested logging in 10+ times and had no issues.

**Comment by bigretromike** [comment]
Need full or the ban part?

**Comment by hidden4003** [comment]
I beleive this can be closed, could've been leech protect on anidb side kicking in as all depends on the order you added anime to db. 

Also you didn't specify UDP or HTTP ban as those are different. Anyways reopen as a separate issue in case it happens again.
