### ISSUE TITLE
Should a file count as a duplicate if on a separate drive (but not cloud)?

### ISSUE THREAD

**Issue by da3dsoul** [ShokoAnime/ShokoServer#592]
@japanesemediamanager/developers this is a discussion.
I would vote yes, as I have no need for more than one copy on a separate drive.
I can however see this as being disputed due to people having messed up smb vs local cache setups, which would at this point look like two different cloud filesystems, just that both are local.

**Comment by Cazzar** [comment]
Ultimately, unless we are taking automatic action on duplicate files, there shouldn't be much information required, it'd be up to the user to  take action on duplicates that they have.

**Comment by maxpiva** [comment]
On this issue and mostly duplicated files and management, i think we should add a folder group to Import Folders. By default, The folder group will be The based Cloud File System plugin used (Amazon, OneDrive, Google, Local File system). But user could add or modify that Group. Repeated files in the same group will be considered duplicates.

**Comment by ElementalCrisis** [comment]
Six years later, as no one else has commented I believe we can close this issue.

**Comment by Cazzar** [comment]
Cloud is no longer supported, so this is getting closed.
