### ISSUE TITLE
Search by Character, Seiyuu, and Staff

### ISSUE THREAD

**Issue by da3dsoul** [ShokoAnime/ShokoServer#595]
This has been brought up several times (mostly by me).
We'll need to make an xref table for speedup and fuzzy searching. The xref table should have AniDB ID, MainTitle, Character ID, Character Name, Seiyuu ID, Seiyuu Name, and an int Enum representing the importance of the role. The Character and Seiyuu ID's can be omitted, as they won't really provide much if any useful info. We may also just drop and merge the AniDB_Character, AniDB_Anime_Character, AniDB_Seiyuu, and AniDB_Character_Seiyuu into Character and Seiyuu. There may be multiple mappings either way, 2 seiyuu per character or 2 characters for a seiyuu.
Staff is more of a future thing, for when we either use what little info anidb has for us, or when we finally get an MAL scraper for some useful cast and staff listing.

The Example uses Hanazawa Kana. The end result should allow fuzzy searching, with corrections for name ordering, romanization differences, and simple misspellings. An example of a simple misspelling is my habit of saying Kanazawa Hana....

The example also gives a basic outline of the Enum.
```
use JMMServer
select anime.MainTitle as 'Series Name', chars.CharName as 'Character Name', anime2char.CharType as 'Role', va.SeiyuuName as 'Seiyuu'
from AniDB_Anime anime
inner join AniDB_Anime_Character anime2char on anime2char.AnimeID = anime.AnimeID
inner join AniDB_Character chars on chars.CharID = anime2char.CharID
inner join AniDB_Character_Seiyuu vas on vas.CharID = chars.CharID
inner join AniDB_Seiyuu va on va.SeiyuuID = vas.SeiyuuID
where SeiyuuName like 'Hanazawa Kana'
order by case
when CharType like 'main character in' then '1'
when CharType like 'secondary cast in' then '2'
when CharType like 'appears in' then '3'
when CharType like 'cameo appearance in' then '4'
else CharType end asc, MainTitle
```

**Comment by ElementalCrisis** [comment]
Agreed, seeing how were adding  more visibility to Characters and Seiyuu in Client V2, this will immensely help.

**Comment by da3dsoul** [comment]
@maxpiva 
from 594

> Getting characters takes 2 whole seconds. This needs to be cut, and the best way is a db refactor of those tables.
> ![image](https://cloud.githubusercontent.com/assets/5205810/24559509/f407643a-160c-11e7-98da-f8ac23aa1d11.png)

**Comment by bigretromike** [comment]
Anything ?:-) any chance this hit 3.8 @da3dsoul ?

**Comment by da3dsoul** [comment]
Nope

**Comment by Jimmyson** [comment]
If long SELECT statements with Inner joins are causing long fetching times, wouldn't indexing more ID columns help?

**Comment by da3dsoul** [comment]
They already are afaik

**Comment by Jimmyson** [comment]
For "anidb_anime_character". I can see that CharID has been indexed, but only with AnimeID.
Finding a Character will be quick if the inner join was to include the AnimeID in the join statement, but I believe since that it is being missed, its just using the PRIMARY index.

(I'm going off the production version for my assumption)

![image](https://user-images.githubusercontent.com/8276052/28992339-52259ee6-79dc-11e7-8ec7-6de6066153dc.png)

**Comment by da3dsoul** [comment]
Okay, it's not like it'll break your DB. Plus if you encounter an error, you'll know how to fix it without or help

**Comment by Jimmyson** [comment]
Implementing the index, and running the above query on my data, I was able to yield a 40% deceased query duration. It was the only missing index needed for that query out of all the tables.

**Comment by da3dsoul** [comment]
Okay, so with the advent of possible other sources, I'm planning on moving cast and staff to internal models with more possible info and better layout for performance. An ID for these is assumed and not printed.
```
Character
    Name
    AlternateName (Kanji Name usually)
    AniDB_CharacterID
    MAL_CharacterID
    ...sourceID (if we find more)
    Description
```
```
CharacterImage
    CharacterID
    Source (AniDB, MAL, etc)
    Path
```
```
Staff
    Name
    AlternateName (Staff may not be a person. By Default, it'll be KanjiName)
```
```
StaffImage
    StaffID
    Source (AniDB, MAL, etc)
    Path
```
```
enum StaffRoleType
    Seiyuu,
    Studio,
    Producer,
    Licensor,
    Director,
    Composer,
    OriginalAuthor,
    Writer, (This can mean storyboard, script, etc)
    CharacterDesign,
    ThemeMusic
```
This one gets tricky. You can have staff specific to an anime, for example a different seiyuu in a remake. It doesn't always have a character to seiyuu map that makes sense, so I chose anime to staff. You can get all characters in an anime with RoleID. This is set up this way as Anime <-> Staff <-> Character are all many to many.
```
CrossRef_Anime_Staff
    AniDB_AnimeID [int]
    StaffID [int]
    Role [string] (Character role type, or any other details about the role they filled)
    RoleID [int] (For seiyuus, it'll be character ID.)
    RoleType [int] (an enum as defined, which states the kind of role they fill)
    Language [string or int idk yet] (Default Japanese, only different if it is dub specific staff)
```

**Comment by bigretromike** [comment]
It would be awesome

On October 27, 2017 2:54:52 PM GMT+02:00, Thomas Baer <notifications@github.com> wrote:
>Okay, so with the advent of possible other sources, I'm planning on
>moving cast and staff to internal models with more possible info and
>better layout for performance. An ID for these is assumed and not
>printed.
>```
>Character
>    Name
>    AlternateName (Kanji Name usually)
>    AniDB_CharacterID
>    MAL_CharacterID
>    ...sourceID (if we find more)
>    Description
>```
>```
>CharacterImage
>    CharacterID
>    Source (AniDB, MAL, etc)
>    Path
>```
>```
>Staff
>    Name
>AlternateName (Staff may not be a person. By Default, it'll be
>KanjiName)
>```
>```
>StaffImage
>    StaffID
>    Source (AniDB, MAL, etc)
>    Path
>```
>```
>enum StaffRoleType
>    Seiyuu,
>    Studio,
>    Producer,
>    Licensor,
>    Director,
>    Composer,
>    OriginalAuthor,
>    Writer, (This can mean storyboard, script, etc)
>    CharacterDesign,
>    ThemeMusic
>```
>This one gets tricky. You can have staff specific to an anime, for
>example a different seiyuu in a remake. It doesn't always have a
>character to seiyuu map that makes sense, so I chose anime to staff.
>You can get all characters in an anime with RoleID. This is set up this
>way as Anime <-> Staff <-> Character are all many to many.
>```
>CrossRef_Anime_Staff
>    AniDB_AnimeID [int]
>    StaffID [int]
>Role [string] (Character role type, or any other details about the role
>they filled)
>    RoleID [int] (For seiyuus, it'll be character ID.)
>RoleType [int] (an enum as defined, which states the kind of role they
>fill)
>Language [string or int idk yet] (Default Japanese, only different if
>it is dub specific staff)
>```
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/ShokoAnime/ShokoServer/issues/595#issuecomment-339963354

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by da3dsoul** [comment]
Mk, first part done. It's super fast. Now on to search and menu friendly API
