### ISSUE TITLE
plex webhooks to sync watchstates across both servers

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoServer#605]
i think the plex webhooks should be looked into a bit more for the watch state syncing of the plex server.
seems the webhook events could push when:

Media starts playing (media.play). An appropriate poster is attached.
Media playback pauses (media.pause)
Media playback resumes (media.resume)
Media playback stops (media.stop)
Media is viewed (played past the 90% mark) (media.scrobble)
Media is rated (media.rate). A poster is also attached to this event.

https://support.plex.tv/hc/en-us/articles/115002267687

having something like this would allow Shoko to update its watchstates in an alternative way. dont know if its better than the system we have now but...
plus you could also build it into the Shoko v2 Client with latest plex usage too. (or merged general usage)

**Comment by Cazzar** [comment]
There, is already basic syncing for watched syncing, `http://shoko:port/plex/` Though, actually grabbing episode information from this API isn't the best, as that can depend on how well it matches.

I am looking for better ways to expand [PlexWebhook.cs](https://github.com/japanesemediamanager/ShokoServer/blob/master/Shoko.Server/API/v2/Modules/PlexWebhook.cs#L26-L39) as that's where most of the plex stuff is actually housed as of right now.

We also have a bit better intergration which is in current master, which includes bi-directional syncing of plex, effectively if watched on either side it will propogate to either shoko or plex itself.

**Comment by Cazzar** [comment]
Further thoughts on the following events:

- media.play
- media.pause
- media.resume
- media.stop

Other than approxinating the time that was played, (kinda hard as I have seen cases where the hook was delayed by 5-10 min) I don't see much of a use.
Though adding usage of `media.rate` would be nice.

**Comment by AreFinstad** [comment]
isnt this mosty done @Cazzar ?

**Comment by AreFinstad** [comment]
i guess it is missing sending scobbling to trakt maybe.

**Comment by Cazzar** [comment]
This should be considered feature-complete as of now.
