### ISSUE TITLE
Group Filter to be User Specific

### ISSUE THREAD

**Issue by jmediamanager** [ShokoAnime/ShokoServer#61]
**Reported by Are.Torrentbytes, Jun 17, 2013**

Group Filter to be User Specific, as the title says. an Group Filter List for each User or ability to hide it from another user.

**Jun 19, 2013 windfury000**

T-up for this!

Yeah, that would be very useful. The hide categories for the users feature is nice but there are times you'd only want to block specific groups/series.

**Comment by ElementalCrisis** [comment]
Outside the scope of the project.
