### ISSUE TITLE
Add summary mode to API /serie/byfolder for Web UI

### ISSUE THREAD

**Issue by hidden4003** [ShokoAnime/ShokoServer#619]
@japanesemediamanager/api 

WebUI Import folders tab was using API /serie/byfolder to show list of series in a folder with their filesizes, series strorage was calculated as total of all videolocals. 

Current version has no filesizes and returns a lot of stuff I don't need.
I don't know which is better adding a mode here or making new api call.

**Comment by da3dsoul** [comment]
I'd say we should make a new module targeting stats. It'll have minimal info, but stats tend to have separate use case with speed taking priority. Having a separate module targeting it would reduce the code complexity.

**Comment by bigretromike** [comment]
/serie/ should return info about serie. current thing should show file size with proper `level` deep, but that would also give alot of info about serie. You probably want something like `ls` or `dir` command. 

What info you need to be return so we can thing of filter for current api or add new command to list series in folders.

But probably like @da3dsoul new module for stats could be good idea as it would be speed over amount of info. the main question would be how fast will those command runs, as we could end up iterating by same objects on both api's ending up with same speed...

**Comment by hidden4003** [comment]
Web UI has import folders tab where it shows a list:
Import folder (select at the top) 
Series name - 1.23 GB
Series name2 - 500MB

What can be improved is probably to show number of videolocals vs total number of videolocals. I am thinking about a series being split into two separate foldes so you would see something like:

Series name (20 files of 35) - 1.23 GB

Web UI screeen I am talking about
![image](https://cloud.githubusercontent.com/assets/197087/26028239/2593a538-3825-11e7-9af5-ddd6710610df.png)

**Comment by da3dsoul** [comment]
Preferably in tree form

**Comment by hidden4003** [comment]
An array of Series each having:

- Title
- Total number of files (videolocals) in all import folders
- Number of videolocals in selected folder
- Total filesize in bytes (sum of Videolocal.Filesize fields) in selected folder

**Comment by bigretromike** [comment]
You want series. So we looking for `Serie` based on folder you select. Basicly to calculate size of serie you need to know what files you have there, you need `Episode`s of that `Serie` having all `Episode`s you need all `RawFile`s to have them you need to be on `level=2` so basicly it will take same time as `api/serie/byfolder?level=2` . Just saying. Until some db rework (or that factory thing) it wont be faster;

**Comment by hidden4003** [comment]
Added in https://github.com/japanesemediamanager/ShokoServer-WebUI/commit/5e45a51f1a4328e46ce46b4e368e53629fda4db0

**Comment by da3dsoul** [comment]
This broke at some point.

**Comment by hidden4003** [comment]
Performance is very bad, for my collection (3890 files, 246 series) it took 2 minutes. 

![image](https://user-images.githubusercontent.com/197087/36736603-b92c2a90-1be1-11e8-86f3-cb2497e6a02e.png)
![image](https://user-images.githubusercontent.com/197087/36736640-cd6fddda-1be1-11e8-8489-028affc1ecdc.png)

**Comment by ElementalCrisis** [comment]
It's also supposed to show number of files for that series. Old mockup but should get the point across. 

![import folders - mockup](https://user-images.githubusercontent.com/9443295/36736821-58997500-1b8e-11e8-8c4e-c8c0de4a8776.png)

**Comment by bigretromike** [comment]
@hidden4003 its slow because its simple iteration over vlocal folde, serie inside folder, episode inside serie; this was needed because you wanted size of each serie in that folder; without pre-populating static values like if you add/remove series some static table would get updated so you get almost 'identical' results in just a manner of miliseconds you need to iterate over it all the time you want the info - or we could just that info to vlocal folder so if you query folder the folder know its 'content' and that would work also for cloud based/external drives which would be fun. but then again we would have to iterate over vlocal series to get episode or if we store local count of files we could get that. 

@ElementalCrisis you are probably right, but that was never the case - that function never did return those information;

@da3dsoul how did it broke? I query it and its all the same as it was when added - ultra slow, but working;

**Comment by Cazzar** [comment]
ultra slow is kinda an understatement:

```
[cayde@aoki-lapis ~]$ time curl -s -H 'Accept: application/json' -H "apikey: $apikey" 'http://localhost:8111/api/serie/infobyfolder?id=2&limit=999999' | jq '. | length'

700

real    21m11.824s
user    0m0.000s
sys     0m0.050s
```

**Comment by da3dsoul** [comment]
And then we'll see my rewrite cut it down to milliseconds

**Comment by hidden4003** [comment]
Query like this

`select sum(v.FileSize)/1048576, COUNT(*),  cf.AnimeID, vu.JMMUserID from VideoLocal_User vu, VideoLocal v, VideoLocal_Place vp, CrossRef_File_Episode cf
where vu.VideoLocalID = v.VideoLocalID and v.VideoLocalID = vp.VideoLocalID and vp.ImportFolderID = 1 and v.Hash = cf.Hash
group by vu.JMMUserID, cf.AnimeID` 

result seems to make sense at least its close: 
![image](https://user-images.githubusercontent.com/197087/36776323-0f42d834-1c6e-11e8-8571-6fbd9e047e5c.png)

against my SQLite DB it returns almost instantly so it is definitely possible, sure it is not all info, only sizes and counts, series name calculation is complex but those objects are cached and it probably won't be 21 minutes.

**Comment by da3dsoul** [comment]
I'm not going to use custom SQL just yet, since max is refactoring DB stuff

**Comment by Cazzar** [comment]
The issue itself I believe may revolve around https://github.com/ShokoAnime/ShokoServer/blob/8df4ff8ed29eccdcc6eaa66bced9121096a89bef/Shoko.Server/API/v2/Modules/Common.cs#L2032

**Comment by bigretromike** [comment]
@da3dsoul you are some kind on ninja-coder 👍 
@hidden4003 yeah, not as trivial but as I recall we dont use sql query because we use NHibernate to make those
@Cazzar this and the fact its iterate over each row, but @da3dsoul know some shinigamis tricks to profile those xD as usually 
@da3dsoul didn't he refactored it before ? is there end with those refactoring ?:P maybe we should have "Make full documentation before of refactoring DB before applying" that would stop most people from refactoring thing that often. I know he does it with good intentions.

**Comment by Cazzar** [comment]
This has been resolved by https://github.com/ShokoAnime/ShokoServer/commit/8a547670a832def7cf691d81367974e78720bf71

```
[cayde@aoki-lapis]$ time curl -s -H 'Accept: application/json' -H "apikey: $apikey" 'http://localhost:8111/api/serie/infobyfolder?id=2' -o /dev/null

real    0m0.131s
user    0m0.000s
sys     0m0.000s
```

though @bigretromike I do know how to do profiling as well, and it turned out that my suspicions were true, generating the contract for every episode... not that clean of a way to do it to begin with.

**Comment by da3dsoul** [comment]
Reclosed

**Comment by bigretromike** [comment]
https://github.com/ShokoAnime/ShokoServer/commit/8a547670a832def7cf691d81367974e78720bf71 does it respect user access levels (aka Family friendly etc),
also the `limit` arg was removed preventing from pagining support.
@da3dsoul could you re-add those ? I see we missed `offset` there for full pagining;

**Comment by bigretromike** [comment]
@Cazzar I also dont know how profiling works - but I understand that its better to add slow but working code just because it will help to develop in this case webui than to don't add nothing and make project stale; And as always @da3dsoul did not failed in making it stupidly-fast;

**Comment by da3dsoul** [comment]
It doesn't need paginating. It's a stats listing. It also doesn't respect user levels, it's a stats listing

**Comment by bigretromike** [comment]
so it way to bypass collection restrictions then ?
also I why would you want to throw 2000 or 50000 series list onto webui/api client when there is space for 5, 10 rows?

**Comment by da3dsoul** [comment]
No it's just the purpose of it is to list very little info on everything for totals

**Comment by bigretromike** [comment]
are we talking about same api endpoint ? it return series inside give import folder.
name of serie, size, ep count. that not 'very little'. I easily hit few 100 of items in one folder.

**Comment by bigretromike** [comment]
Ok, if it is to much I will do it later myself, no point it pushing this so long.

**Comment by da3dsoul** [comment]
It gives exactly what he asked for in the OP, nothing more except ID.

**Comment by da3dsoul** [comment]
Please don't touch it, it works great

**Comment by da3dsoul** [comment]
It's serie/infobyfolder

**Comment by bigretromike** [comment]
then please add `limit` and `offset`

**Comment by da3dsoul** [comment]
Nope it's getting changed as soon as max merges his latest project anyway. We are starting APIv3 at that point. Making it more standardized

**Comment by da3dsoul** [comment]
No one except avael uses it, so I'm not concerned

**Comment by bigretromike** [comment]
if no one use it.. why did you care to fix it in first place?

**Comment by da3dsoul** [comment]
"No except avael" because we love avael, and I'll fix things for the future of WebUI and ClientV2
