### ISSUE TITLE
Separate destination folder for R18 groups

### ISSUE THREAD

**Issue by jmediamanager** [ShokoAnime/ShokoServer#62]
**Reported by techmasterjoe, Jun 26, 2013**

simple
when something in drop folder is found to have a R18 or adult rating.
store it separate from other anime

like my drives
E:\Anime1 (des)
F:\Anime2
G:\Anime3
F:\Drop (Drop folder rss feeds dump into from utorrent)

add a option like 
E:\R18 (desR18) for all R18 rated crap 
i don't have much but i do want it away from reg anime

i have been doing this the hard way for like ever.
i must admit jmm has made my life easy i don't even think twice about renaming a group now.

if you fixed up the site and marketed this stuff at anime expo and disabled a lot of the features so people had to pay something small like 5~10$ i know a lot of people that will do it

just passed the 12,000 file mark at 4.61TB on 24.7TB raid 6 array avg read speed is over 700MBs writes even faster Jmm can re hash every file in less then 8mins with MSSQL 9mins for MYSQL 11mins with SQLite(on dual SSD raid 0)
If only Anidb.net was faster takes a full day or more talking to anidb

**Jun 27, 2013 werndlymob**

Long time no see Joe :)

I still need to do the moving rules, which is another open issue.
I'll make this more generic to allow selecting by tag.

I can't do much about AniDB, but we can keep on hoping

**Comment by da3dsoul** [comment]
+1

**Comment by Cazzar** [comment]
This can be done with a custom renamer now.

**Comment by da3dsoul** [comment]
The Group Aware Sorter already does, too. Just name an import folder Hentai

**Comment by bigretromike** [comment]
Any tutorial ?
