### ISSUE TITLE
some improvements/suggestions

### ISSUE THREAD

**Issue by mspykerez** [ShokoAnime/ShokoServer#626]
This is a improvement/feature request for Shoko that was asked me to post here.

1) First I would like to have the option to add links to streaming episodes from a selected series be it from crunchyroll or something else. I know that anidb and many other sites provide such links so it should not be that hard to gather the required information.

2) Second is to add 2 more community sites to pull data from. The first is anime-planet.com which is well known for years for its recommendations as the site itself states "Anime-Planet is the world's first and most trusted recommendation database" so I'm asking in addition to anidb recommendations to add support for anime-planet recommendations as well. The other site that I have in mind is anisearch.com which is originally a german site but with also an english counterpart. The great thing about it is the images it provides for every single series out there including hentai (need to register) to be more exact it provides tons of screenshots that might be very useful to take a look at instead of the current images that shoko pulls this would be a great alternative.

3) Last but not least is me asking you guys to talk with the anidb guys to allow access to the site TCP API instead of the current UDP that you use, more info here https://wiki.anidb.net/w/API AFAIK anidb was looking for someone to take over their now obsolete anidb O Matic which is the only client that uses TCP API http://anidb.net/perl-bin/animedb.pl?show=cmt&id=55697 more info here http://anidb.net/perl-bin/animedb.pl?show=cmt&id=55697 
It would be just great to work with the entire anidb database offline with shoko, it would open many possibilities.

**Comment by da3dsoul** [comment]
Anime Planet might be feasible.
```
[
  {
    "AniDB_AnimeID": 1534,
    "AnimeID": 11857,
    "EpisodeCount": 12,
    "AirDate": "2017-04-07 00:00:00.000",
    "EndDate": null,
    "URL": "http://www.tbs.co.jp/anime/cp/",
    "Picname": "196072.jpg",
    "BeginYear": 2017,
    "EndYear": 0,
    "AnimeType": 2,
    "MainTitle": "Clockwork Planet",
    "AllTitles": "Clockwork Planet|クロックワーク・プラネット|Clockwork Planet|클락워크 플래닛",
    "AllTags": "military|shounen|android|robot|target audience|themes|original work|elements|mecha|novel|action|science fiction|fantasy|politics|steampunk|disaster|conspiracy|dystopia|rotten world|human-android love|evil military",
    "Description": "This news may seem sudden... but this world died long ago.\nEarth died a thousand years ago, and a legendary clockmaker known only as \"Y\" rebuilt it using clockwork. Naoto Miura, a failing high school student, encounters RyuZU, an automaton that \"Y\" left behind, and the genius clockmaker Marie. When the abilities of these three come together, the gears of fate begin to turn. The cycle of failure and success repeats endlessly as the three of them work to repair the endangered \"Clockwork Planet\" in this clockpunk fantasy!\nSource: crunchyroll",
    "EpisodeCountNormal": 12,
    "EpisodeCountSpecial": 0,
    "Rating": 331,
    "VoteCount": 77,
    "TempRating": 553,
    "TempVoteCount": 81,
    "AvgReviewRating": 0,
    "ReviewCount": 0,
    "DateTimeUpdated": "2017-06-02 08:24:37.000",
    "DateTimeDescUpdated": "2017-06-02 08:24:37.000",
    "ImageEnabled": 1,
    "AwardList": "",
    "Restricted": 0,
    "AnimePlanetID": 0,
    "ANNID": 0,
    "AllCinemaID": 0,
    "AnimeNfo": null,
    "LatestEpisodeNumber": 9,
    "DisableExternalLinksFlag": 0
    }
]
```
The Values don't appear to be parsed, but we already have slots in the DB

**Comment by maxpiva** [comment]
1) We might include the links, but no direct streaming support.
2) Seems feasible after da3dsoul diggin.
3) Not happening, AniDB-O-Matic and anidb uses a custom encrypted requests, to download the entire AniDB database, and that, is not open to third parties like us.

**Comment by mspykerez** [comment]
3. Have you asked the anidb staff? They might grant you permission...

**Comment by maxpiva** [comment]
They probably not, you can pest them if you want, but for that to work, we should store anidb data encrypted and that is out of scope.

**Comment by da3dsoul** [comment]
#738

**Comment by ElementalCrisis** [comment]
1. We already have the links if AniDB has them. No plans for custom links.
2. Only AniList is planned.
3. Been discussed and this is a path we will not be taking.
