### ISSUE TITLE
Ability to update file states

### ISSUE THREAD

**Issue by Mik1ll** [ShokoAnime/ShokoServer#634]
Feature improvement request :

Ability to update the file state of files in the DB.  

Files that are imported but are already in the AniDB MyList do not get their file state updated, if their file state is marked 'Deleted' in MyList when the file is added, it will not be changed to the correct storage state.  

Another reason to add this :  Over time, the states of files in the MyList can become unsynced, E.g. some files may have the storage state of 'Internal(HDD)', when they should be marked 'Deleted'.  This could be fixed by this feature by setting the file state of all files to 'Deleted' in AniDB, then going to Shoko and updating the file state of all files in the DB.

**Comment by ElementalCrisis** [comment]
This sounds like a bug, @japanesemediamanager/developers can one of you take a look?

**Comment by Jimmyson** [comment]
https://github.com/ShokoAnime/ShokoServer/blob/master/Shoko.Server/Commands/AniDB/CommandRequest_SyncMyList.cs
From my observation:
- If a file already exists on MyList, process of that file is skipped
- Files are ignored when marked as deleted
- Only processes Deleted and Watched states

**Comment by da3dsoul** [comment]
I literally just rewrote that. The first one shouldn't be the case, the other two are plausible

**Comment by Jimmyson** [comment]
`if (onlineFiles.ContainsKey(fileID)) continue;`?

It's that a good opportunity to check the file medium state?

**Comment by da3dsoul** [comment]
That would be the case. That'd be where we should check if it's marked as deleted

**Comment by da3dsoul** [comment]
I'll look at this again
