### ISSUE TITLE
Season Group Filter

### ISSUE THREAD

**Issue by da3dsoul** [ShokoAnime/ShokoServer#641]
Leaving this here as notes. No feedback needed unless there's an error in my logic.

An anime year is broken into 4 seasons called cours. They start in January, April, July, and October.
```
SELECT MainTitle, DATENAME(MONTH, AirDate)
FROM AniDB_Anime
WHERE DATENAME(MONTH, AirDate) NOT IN ('January', 'April', 'July', 'October') AND AnimeType = 2
```
returned too many results, so I'm thinking of making it fuzzy of up to half of a month. Only normal shows apply, as OVAs, ONAs, Movies, etc don't follow standard release schedule and therefore don't apply.

The Filter will be an IN, NOTIN filter, with the standard comma separated format.
It will have two comboboxes for Season and Year, followed by an ADD button:
```
Winter
Spring
Summer
Fall
```
```
2014
2015
2016
...
```
For long running shows, they will continue to show up in the filter until they stop airing or become a separate listing on AniDB (AniDB lists things as being separate if they are broken into chunks, rather than shows like D.Gray-man which started and just kept going)

I know this has been requested, at the very least by me, but there was no issue for it, so I figured I'd make one while my brain is capable of planning.

**Comment by ElementalCrisis** [comment]
Yoy could always have one drop down for the season and an input box for the year.

**Comment by da3dsoul** [comment]
That's an idea.

**Comment by da3dsoul** [comment]
https://github.com/japanesemediamanager/ShokoServer/commit/7b3a9e71997989cfe49627ed496cf224467926c7

**Comment by da3dsoul** [comment]
Hmm, rather than making this something to add manually, should I make it like the years filter?

**Comment by maxpiva** [comment]
Great idea :)
Will add 15 days before the season, since some show starts before the first
of the month...

**Comment by da3dsoul** [comment]
Yeah. I had to add functionality because winter lands on the border of the year

**Comment by ElementalCrisis** [comment]
Yeah good idea @da3dsoul, make it easier to set the filter condition up.

**Comment by da3dsoul** [comment]
![screenie](https://www.dropbox.com/s/mrqcwbezjt6seq0/Screenshot%202017-07-14%2022.19.59.png?raw=1)

**Comment by da3dsoul** [comment]
I'm done for today. Things that need doing:
- [ ] Proper sorting in Desktop (already made a string comparator, just need to somehow work it into the main list sorting)
- [ ] Adding it to the Group Filter Condition form
...I think that's it actually.

**Comment by misakitchi** [comment]
I want a Season Group Filter too! Thanks!! :)

**Comment by da3dsoul** [comment]
Right I was going to possibly make the ui for this...and the year filter.
