### ISSUE TITLE
Can't sync more than one item from my list on anidb to shoko

### ISSUE THREAD

**Issue by Kezxo** [ShokoAnime/ShokoServer#642]
## LOG FILE
https://pastebin.com/CeRfUdNU
## Description

When I mark files watched on anidb they don't show up as watched on shoko. I click the sync mylist button and it only adds one thing to the queue and that's it. Marking files watched on shoko works fine.
Notes from @ElementalCrisis on discord : "Will only sync the first marked item on AniDB. Unmarking an item on AniDB does not sync."

## STEPS TO REPRODUCE

Mark a bunch of files as watched on anidb, maybe 50 or something.
Click the Sync Mylist button in shoko server.
See if shoko knows they are watched.

**Comment by da3dsoul** [comment]
Ima close this. Any more issues about this can be spoken to me on discord.
