### ISSUE TITLE
SQLite permission issues

### ISSUE THREAD

**Issue by Cazzar** [ShokoAnime/ShokoServer#647]
![image](https://user-images.githubusercontent.com/994214/28752341-e5744ef8-755f-11e7-8555-755e4faaef3a.png)

## DESCRIPTION

When initially starting a SQLite environment, the current permissions might not allow the system to write to the SQLite `.db` file, this will make exceptions like above.

**Comment by Cazzar** [comment]
Currently there is a workaround of setting yourself write permission to said directory.

**Comment by ElementalCrisis** [comment]
Fixed by @maxpiva.
