### ISSUE TITLE
API returns image links with hardcoded port.

### ISSUE THREAD

**Issue by KingJ** [ShokoAnime/ShokoServer#648]
## VERSION INFORMATION

Server Version: Docker ShokoAnime/ShokoServer@9c54542947b8d86b5ca73927e7e66a2c3a3d524e

Desktop Version: Cazzar/ShokoMetadata.bundle@554103e63d4b79b8119ad84d9ac51d4eec56b0e2

If you've compiled your own version, please use the last commit you compiled.

## LOG FILE

From ShokoMetadata;
2017-07-30 23:25:08,490 (888c) :  DEBUG (networking:166) - Requesting 'http://shoko:80/api/auth'
2017-07-30 23:25:08,500 (888c) :  DEBUG (logkit:13) - Got API KEY: xxx
2017-07-30 23:25:08,500 (888c) :  DEBUG (networking:166) - Requesting 'http://shoko:80/api/serie?id=4&level=3&allpics=1&apikey=xxx'
2017-07-30 23:25:08,621 (888c) :  INFO (logkit:16) - [metadata_add] :: Adding metadata http://shoko:8111/api/image/1/2002 (index 0)
2017-07-30 23:25:08,621 (888c) :  DEBUG (networking:166) - Requesting 'http://shoko:8111/api/image/1/2002'

## DESCRIPTION

The call to `/api/serie` returns information about the series, including links to poster etc images. However, the poster image URLs that are returned explicitly use the default port (8111) instead of a relative port. Therefore, if the server is being run behind a reverse proxy, images cannot be downloaded.

## STEPS TO REPRODUCE

1. Run ShokoServer behind a reverse proxy (nginx, haproxy etc).
2. Send a query to the `/api/serie` endpoint.
3. Look at any picture result returned by the query. All images, including posters, banners, thumbs, actor pictures etc will have port 8111 in the URL instead of the configured port.

**Comment by Cazzar** [comment]
In this case, it might be best for us to return relative urls for URLs, because in the case where running from docker and external NAT, the port could be redirected

-- just for noting

**Comment by KingJ** [comment]
Apologies, i've just done some additional checking and Shoko is indeed running on the default 8111 port (I had confused the "Shoko Server" settings in Settings > Essential on the Desktop client with ShokoServer's _actual_ settings). However - I am running Shoko behind a reverse proxy which is proxying port 80 to 8111. Sorry for the error in the bug report.

**Comment by da3dsoul** [comment]
That's what I thought. In this case, the server is running correctly. We don't support proxies, at least right now. Clients should handle the base URL anyway since the client knows exactly what it needs to be. @cazzar had an ok solution, but it'll require rewriting all of the clients. It'd be mostly annoying for me since Nakamori is backwards compatible and I prefer to keep that way for the time being.

**Comment by Cazzar** [comment]
Http parameters exist...

**Comment by da3dsoul** [comment]
Don't know what those are by name! I'm not really interested, since I don't use a proxy, and if I were to use one, it'd be a VPN->proxy from my router so applications don't need to worry about it

**Comment by bigretromike** [comment]
API return same number for images as the requested one `Request.Url.Port` it looks like docker is replacing your 80 with default 8111, but the respond give you 8111; If I recall correctly this would make problems for plex also.
Also its already there 👍 let me test it
I'm also agree with that API should return relative urls - as we need anyway know url:port to make connection.

**Comment by Cazzar** [comment]
My own approach:
 - If on the same server, use relative.
 - if on another, use absolute.

**Comment by Cazzar** [comment]
Though with the comment this will make issues for plex @bigretromike that's how @KingJ found it.

**Comment by bigretromike** [comment]
@Cazzar why would we want absolute path anyway? also you cannot distinguished if server is same ;-) only by localhost/127.0.0.1/::1. Its easier for everyone to have it always relative, imo; @ShokoAnime/api

**Comment by bigretromike** [comment]
imo, we should end up with most thing to be relative, which cut data and problems. 👍

**Comment by Cazzar** [comment]
@bigretromike namely if it was shokoserver returning an anidb link we cannot use relative, that's what I mean.

**Comment by KingJ** [comment]
Thanks for committing this fix in @bigretromike . @Cazzar , would you be able to merge master into the linux branch and trigger an update of the Docker container?

**Comment by da3dsoul** [comment]
@Cazzar we don't ever give an AniDB link. We handle all interaction with AniDB. That's not really an issue
