### ISSUE TITLE
Files In Import Folder That Are Not In A Folder Are Not Processed

### ISSUE THREAD

**Issue by ElementalCrisis** [ShokoAnime/ShokoServer#659]
## VERSION INFORMATION

Server Version: https://github.com/ShokoAnime/ShokoServer/commit/109562c624f597c76ed5a93f0d8cfd95211a32e4
Desktop Version: https://github.com/ShokoAnime/ShokoDesktop/commit/64dff8ddd9669a8b7ed4007a8e7d998992dd3783

## LOG FILE

The only thing in the log related to the file.

```
[2017-08-27 01:52:06:467] Info|CommandProcessorHasher.WorkerCommands_DoWork => CommandRequest_HashFile.ProcessCommand => CommandRequest_HashFile.ProcessFile_LocalInfo Hashing File: E:\Anime1\[Hiryuu] High School DxD BorN - 01 [720p H264 AAC][3051D92B] (2).mkv
```

## DESCRIPTION

Files that are not in a folder that are in your Import Folder are not added into your collection. After the initial check, Shoko all but ignores the file.

## STEPS TO REPRODUCE

1. Have Shoko Server running.
2. Drop files into your Import Folder.

**Comment by da3dsoul** [comment]
I can't reproduce

**Comment by ElementalCrisis** [comment]
I'm not using a DS or DD, just Watch for New Files.

**Comment by da3dsoul** [comment]
I have D:\Finished as a drop source and watched import folder. Anything that goes in there is scanned appropriately.

**Comment by da3dsoul** [comment]
Hmm I wonder. When a drop folder is set up, they are always in a folder in the destination. That could be part of it

**Comment by da3dsoul** [comment]
You have no errors, correct? It just finishes and moves on?

**Comment by ElementalCrisis** [comment]
Yep, the only thing in the log is what I posted above.

**Comment by da3dsoul** [comment]
Okay I'll look into it

**Comment by da3dsoul** [comment]
Do me a favor. Enable Trace logging and import one file, then post the log
