### ISSUE TITLE
+MyList button - Not working as expected

### ISSUE THREAD

**Issue by nspiegl** [ShokoAnime/ShokoServer#664]
## VERSION INFORMATION

Server Version: 3.7.0.6

Desktop Version: 3.7.0.4

## LOG FILE

[Shoko Server Log](https://github.com/ShokoAnime/ShokoServer/files/1271931/Shoko_Server.zip)

[Shoko Desktop Log](https://github.com/ShokoAnime/ShokoServer/files/1271932/Shoko_Desktop.zip)

## DESCRIPTION

After importing a number of new files and then attempting to add them to my AniDB mylist using the +MyList button under "More Info" section of the file it did not seem to work if the "Add Files" setting was not enabled under Settings > AniDB > AniDB MyList Options.

The help text states "Forcefully add this file to your list on AniDB" so therefor I would expect this action to work irrespective of what the "Add Files" setting is set to.

Correlated server log events by time::

 > 3 attempts made at the following times while the "Add Files" was turned off
[2017-09-02 13:56:24:695]
[2017-09-02 13:56:37:872]
[2017-09-02 13:57:03:100]

> After turning on the setting
[2017-09-02 14:00:04:801]
> Command now sent to AniDB as expected
[2017-09-02 14:00:09:970]

The button / test file>
![image](https://user-images.githubusercontent.com/25097788/29993324-c1fd61ac-8fe6-11e7-9c19-baa24c8beaae.png)

The "Add Files" setting>
![image](https://user-images.githubusercontent.com/25097788/29993333-e54e70f6-8fe6-11e7-9eab-ca185a255f0a.png)

## STEPS TO REPRODUCE

1. Turn add files setting off
2. Import a file not already in your AniDB MyList
3. Attempt to manually add it using the +MyList button

**Comment by Cazzar** [comment]
Has this been attempted in the latest beta? As there has been a lot of changes in the backend.

**Comment by ElementalCrisis** [comment]
As I recall, its always been tied to the AniDB MyList settings.

**Comment by nspiegl** [comment]
Installed both Desktop and Server version 3.8.0.902, tested and got the same result.

**Comment by da3dsoul** [comment]
Fixed and improved watch state handling
