### ISSUE TITLE
File Renaming - %eps (Episode Count) not working

### ISSUE THREAD

**Issue by nspiegl** [ShokoAnime/ShokoServer#665]
## VERSION INFORMATION

Server Version: 3.8.0.902

Desktop Version: 3.8.0.902

## LOG FILE

[Shoko Server Log ](https://github.com/ShokoAnime/ShokoServer/files/1271974/Shoko.Server.BETA.zip)

## DESCRIPTION

I am attempting to use the "Episode Count" tag in my renaming script but it does not seem to work as can be seen below:

![image](https://user-images.githubusercontent.com/25097788/29993677-3fee519e-8ff0-11e7-8de9-9c04eea626db.png)

![image](https://user-images.githubusercontent.com/25097788/29993686-716a8aee-8ff0-11e7-9777-b61bdb13f756.png)

I assume this should be working ?

## STEPS TO REPRODUCE

-Use the Episode Count tag in a renaming script

**Comment by da3dsoul** [comment]
It was missing for some reason. Fixed
