### ISSUE TITLE
Double anidb login windows

### ISSUE THREAD

**Issue by bigretromike** [ShokoAnime/ShokoServer#668]
## VERSION INFORMATION

Server Version: 3.8.0.0

## DESCRIPTION & ## STEPS TO REPRODUCE

When clean installing 3.8.0.0 after initial db setup anidb window popup. I enter wrong data and hit 'test' it spawn another window that was mirroring the thing I put in textbox but the 'test' button didn't work, i had to close it and the one that left work ok with proper password.

**Comment by ElementalCrisis** [comment]
Hmm I can't reproduce but I've noticed that the window sometimes pop up behind the Server GUI which makes it so I can't click on anything. Any input @RickDB?

**Comment by bigretromike** [comment]
This is Windows 8 (not 8.1, not 10) this could be related with WIndows, because sometimes loaders tend to duplicate window the same way, but this happend for me first time with shoko 3.8.0.0 never saw this before.

**Comment by Cazzar** [comment]
I know what the error would be, there's an event called by the base code
that in shoko.ui displays the login popup, though we should make it check
for only one showing at a time.

**Comment by hidden4003** [comment]
But what is the proposed fix? 
Kill the popup and just log error and disable AniDB until fixed?

Also from recent reports it seems our code is not super reliable in terms of transient network issue it assumes that login data is bad and combined with this fix might create. 

Also it seems to be duplicate of #644

**Comment by bigretromike** [comment]
This window popup not at banned or with network issue but on bad creditentials :-) @hidden4003 so its not that of duplicate as you would think :-) but I see the point.

But why this was close is unknow for me...

**Comment by Cazzar** [comment]
Because I implemented a fix, that's why

**Comment by bigretromike** [comment]
Oh, didnt saw that one. Sorry. 
Will wait 1 day until I get unbanned to test it out,.

**Comment by bigretromike** [comment]
![double](https://user-images.githubusercontent.com/6052025/30250438-9da3d39a-964e-11e7-87d0-492464deaedc.png)

This is not still fixed. 

I use the latest daily build as for now;

**Comment by bigretromike** [comment]
This is windows8 issue. Most of people stick with 7 or 10.
I was unable to reproduce this on 7 and 10.

**Comment by da3dsoul** [comment]
Right I think this was fixed a while back. Thanks for closing it.
