### ISSUE TITLE
Better MAL management

### ISSUE THREAD

**Issue by jmediamanager** [ShokoAnime/ShokoServer#67]
**Reported by Are.Torrentbytes, Jul 3, 2013**

just a small thing. when you add something that is linked with MAL it will be set to "Currently Watching" list instead of "Plan to Watch" list.

i think there should be a move of the series to the "Currently Watching" list when JMM see that there is atleast one episode or file that have a watched state im JMM.

as of now have my JMM server added all my Anime (over 1300 series) into the "Currently Watching" list.
this might just be a little error. but when newer sites like http://hummingbird.me/ is using MAL and such it is needed to be updated.

i hope this is a simple fix for you and im always looking forward for your updates :D

**Comment by CatmanIX** [comment]
My recommendation would be that anything added defaults to "Plan to Watch" until at least one episode is watched.

As well, user configurable, anything that is currently marked "Watching" be switched to "On Hold" if you haven't watched an episode for 'x' amount of time (perhaps ignoring series that are currently airing). This might be pretty heavy on processing, as i imagine it would require regularly checking your entire collection for candidates, so it may not be practical.

Another option that's much more practical though, marking any uncompleted series you delete from your collection as "Dropped".

The same being done for any other list services should they be added of course.
