### ISSUE TITLE
Missing hasher inside 3.8.0.0 installer

### ISSUE THREAD

**Issue by bigretromike** [ShokoAnime/ShokoServer#670]
It looks like there is hasher dll missing/mismatch:
`
Error|CommandRequest_HashFile.ProcessCommand => CommandRequest_HashFile.ProcessFile_LocalInfo => Hasher.CalculateHashes Error using DLL to get hash (Functon returned 1), trying C# code instead: 1
`

**Comment by bigretromike** [comment]
`ShokoServer/x64` and `ShokoServer/x86` include those (crc32 included)
```
x64\hasher.dll C2F262F1
x64\libcurl.dll E06C89F3
x64\MediaInfo.dll 1D08D810
x64\SQLite.Interop.dll 1D5E04A2
x86\hasher.dll C36E4BAE
x86\libcurl.dll AEA60C9E
x86\MediaInfo.dll DDB4AB48
x86\SQLite.Interop.dll 092C05F6
```

**Comment by ElementalCrisis** [comment]
Hmm, looks like the installers setup correctly. I'll have to double-check when I get home. Can you check to make sure they are getting built and included in the release folder?

**Comment by bigretromike** [comment]
Im unable to test compilation on this machine. I remamber that most of the time there was 'different' build of hasher that had to be included in those directories. Im unable to tell why there is an error .
Im not using default Install directory but I hope no one hard coded hasher.dll location to C:/ drive. 

I notice this as Im importing my NAS and its been 22h as shoko is running hasher on it... so yeah...

**Comment by Cazzar** [comment]
On my own test rig earlier a build was having this issue, didn't have time
to look into it

**Comment by bigretromike** [comment]
Thanks for confirmation.

**Comment by da3dsoul** [comment]
I've not had this issue on dailies

**Comment by bigretromike** [comment]
I wouldn't mind install daily on top of that but sadly  I used what average user would do - I downloaded official installer from official site :-(

On September 7, 2017 7:47:50 PM GMT+02:00, da3dsoul <notifications@github.com> wrote:
>I've not had this issue on dailies
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ShokoAnime/ShokoServer/issues/670#issuecomment-327870403

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ElementalCrisis** [comment]
Ok checked, everything is included in installer and files are present in my install.

**Comment by Cazzar** [comment]
Do you use UNC paths by chance @bigretromike?

**Comment by Cazzar** [comment]
Also, as @hidden4003 mentioned in the discord, any reason we need to keep the C++ hasher, as ultimately file identification is E2DK based, and running on linux, the C# hasher still beats AniDB speeds.

**Comment by hidden4003** [comment]
I said in discord already that I see no point in keeping unsafe C version of hasher no one ever looks at, one less dependency to distribute is a win. Also I have to download whole C build tools just for one file which is annoying, especially in Rider.

We are limited by AniDB request rates anyways and with cloud support it is not an issue at all, as cloud computes hashes for you.

**Comment by Cazzar** [comment]
That should fix the issue, but leaving this open for further discussion about the need for the native hasher.

**Comment by bigretromike** [comment]
Yes, I used UNC as I stated I used NAS 👍 
Also I agree with @hidden4003 
Also @Cazzar we could easly use any hasher from linux repo. just point to it (by name?. path) Im sure they will easly with the speed race. but if not, its like hidden said, we are limited by AniDB anyway.

**Comment by Cazzar** [comment]
@bigretromike I'm not even talking about linux in this case, hasher adds speed to where it isn't needed.

**Comment by hidden4003** [comment]
@maxpiva @da3dsoul cast your vote on removing native hasher

**Comment by maxpiva** [comment]
why we should remove from windows installations, perfomance of the native
hasher is at least two times the .net one, and probably 3 times in the x86
part (100% assembly used), i understand not to include in linux, and if
there a problem with unc path, we simple check for unc path before invoking
the hasher, if unc use C# if not use native.

**Comment by Cazzar** [comment]
The previous discussion mentioned why it wasn't absolutely necessary,
namely being the anidb API limitations are the slow point

**Comment by maxpiva** [comment]
On that matter, if we enable webcaching of anidb entities, anidb will not
be the bottleneck anymore, then the hasher will get the spotlight.

**Comment by da3dsoul** [comment]
Plus I'd rather have my CPU clocks used elsewhere. It's not like Shoko is the only thing our computers run.

**Comment by bigretromike** [comment]
Buy better CPU. 

On September 28, 2017 8:20:06 PM GMT+02:00, da3dsoul <notifications@github.com> wrote:
>Plus I'd rather have my CPU clocks used elsewhere. It's not like Shoko
>is the only thing our computers run.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/ShokoAnime/ShokoServer/issues/670#issuecomment-332921609

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by da3dsoul** [comment]
Hahahaha I walked into that one. Nice one @bigretromike. I will at some point.

**Comment by bigretromike** [comment]
funny how anidb limit access but `shoko` will handle it... you know people could start using that `webcache` as way to bypass anidb limits. #bypassanidb #anidbproxy 
@hidden4003 is right in 100% with this. why not remove it out of package, and all people that want will just add they dll into shoko folder and done. You will have your super quick hasher that don't give any benefits for current shoko as like @hidden4003 stated the limit is from AniDB, so even with having hash for file you wont know what it is until anidb return info and other will use default one or other hashers.. 

It could be resolve as module so both sides would be happy

**Comment by maxpiva** [comment]
The webcache will need authentication there will be no public endpoint for
this functionality. This will not stop to a programmer to look at our code
and replicate the functionality, but it’ll stop enough, after all we’re not
a public api. Rogue user applications cannot be stopped if coded, only ban
the anidb user,  normal apps will need our permission

**Comment by bigretromike** [comment]
The point here is not about webcache either way. Its about hasher ;-)
But as you wrote, what authentication ? the only authentication you can make is for shoko users - so its same one login/password/token/pick_any_authmethod that would be in code. If it wont be in code you would need to inject it before compiling making it even more  complicated to build.
But I think that would be discussion about webcache should have its own issue.
@hidden4003 stated and I fully support that current hasher is all ok but make someproces more difficul that it should, Its super fast but it wont give any advance over c# hasher because of anidb limits and speed. 
Plus that we could move it out of shoko and add it as module for those who NEED super fast hasher - but thats me.

**Comment by ElementalCrisis** [comment]
I believe @maxpiva is referring to the plans we've outlined on Discord.

**Comment by hidden4003** [comment]
@maxpiva @bigretromike I am not insisting on removing it entirely but at least moving hasher into separate nuget/package/solution so that I don't have to install 1.5 GB of VC++ toolchain to build 1 assembly file.

**Comment by da3dsoul** [comment]
That's fair. We almost never make any changes to it

**Comment by Cazzar** [comment]
Given it seems to be going towards doing a P/invoke based off something
maybe like OpenSSL libcrypto

**Comment by Cazzar** [comment]
b5b0dfc56d151477dda007116224186290500b05
33bd52aab7d1f180b365be7edbde64415490526e

`rhash` is now what I have moved the hasher too.
@hidden4003 you might like the fact we no longer need the VC++
And for the linux users, this means that we actually have a cross platform native hasher.

**Comment by bigretromike** [comment]
good job
