### ISSUE TITLE
AniDB Ban after 22,5h of importing data

### ISSUE THREAD

**Issue by bigretromike** [ShokoAnime/ShokoServer#673]
Same as #671 

It have this few times

```
[2017-09-07 16:50:16:053] Error|AniDBHelper.GetMyListFileStatus => AniDBCommand_GetMyListFileInfo.Process => AniDBUDPCommand.ProcessCommand System.Net.Sockets.SocketException (0x80004005): Pr󢡠poӹczenia nie powiodԡ siꬠponiewaߠpoӹczona strona nie odpowiedziaԡ poprawnie po ustalonym okresie czasu lub utworzone poӹczenie nie powiodԯ siꬠponiewaߠpoӹczony host nie odpowiedziaӍ
   at System.Net.Sockets.Socket.ReceiveFrom(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint& remoteEP)
   at AniDBAPI.Commands.AniDBUDPCommand.ProcessCommand(Socket& soUDP, IPEndPoint& remoteIpEndPoint, String sessionID, Encoding enc) in D:\Documents\GitHub\ShokoServer\Shoko.Server\AniDB_API\Commands\AniDBUDPCommand.cs:line 36
```

**Comment by bigretromike** [comment]
This result in Pause and BAN

**Comment by ElementalCrisis** [comment]
Yeah we're not quite sure what is going on, @da3dsoul and @cazzar know more but I don't think it's something we can fix as it's on AniDB's side.

**Comment by bigretromike** [comment]
we can prevent this.. if its because of LONG running uptime.. its not like I was spaming them because of slow hasher. I think it could be related with fact that it was over 22h of using straight. 

Maybe they try to disconnect before Banning, or the BAN = disconnect. 
I would try to save start-time, and if its near 20h just wait 30minuts or 1h  and restart connection.

**Comment by bigretromike** [comment]
Also none of any device have logged to AniDB via anything. Its only this PC that was running Shoko. No web checking, no other Shoko. 

Just to be sure.

**Comment by ElementalCrisis** [comment]
That socket issue has been popping up for awhile now and we follow all limits set by AniDB,  @hidden4003 any input?

**Comment by bigretromike** [comment]
You cannot follow all limits, because some are "common sense" maybe this one is that "Common sense: when connection is longer than 22h (exceeded use)" 
Maybe this is that one, that dev dont want to reveal ;-)

**Comment by Cazzar** [comment]
I do recall when setting up with the Linux branch I had 3 days straight of
hashing and data downloading. So I'm not too sure if it's anidb saying
close your sockets down.

**Comment by bigretromike** [comment]
that was first thing that came to my mind, after 22h straight. As shoko is hashing still and sending requests. Not sure how was your doing :-) because 22h isin't normal anyway.
But you probably know better, imo

**Comment by hidden4003** [comment]
Are you sure it is a UDP ban ?
If you look at https://github.com/ShokoAnime/ShokoServer/blob/master/Shoko.Server/AniDB_API/Commands/AniDBUDPCommand.cs#L272 you can see that there is an exact response code in case of ban, socket error is not a ban, if it gets interpreted like this then it is an error.

**Comment by bigretromike** [comment]
Im sure.. 
I got that error you saw. 
The queue got PAUSEd. 
I waited like 15minuts. 
and GOT paused again with "BANNED" in shoko.gui

**Comment by bigretromike** [comment]
I talked with `Omnia` (sorry if I typed wrong), we talked and it looked like It wasn't BAN. It look like somehow Shoko get me banned for typing wrong creds (or to many relogins), and it was that `Excess` ban on login.
Not sure if its same as normal UDP ban;

So it looked like that the unable to connect trigger (? or not) re-login that made to many attempts and get login-ban. 

Can't tell, he just told me  that he can confirm that I had only ban on login.

**Comment by bigretromike** [comment]
I just got same thing with JMM Server Version: v3.8.0.1024, as before with clean database after 20h+ of scanning.

Maybe this is because of ping-pong ? or maybe we need to relog into api after excess time ?

**Comment by Cazzar** [comment]
I highly doubt that, also as I've mentioned this hasn't been the case, here's just some of my old graphs I had for queue states
![image](https://user-images.githubusercontent.com/994214/30388113-04c02c68-98f2-11e7-8e81-c71b3490ab14.png)
![image](https://user-images.githubusercontent.com/994214/30388127-122e7a62-98f2-11e7-821e-9cee53d8c013.png)

**Comment by bigretromike** [comment]
this is twice in a row. also dunno whats you isp, maybe mine drop something in middle. dunno. maybe out of region ip got it own rules. can tell... 
also I dont see any  log related to ban info in gui but im unable to get queue started again, even after waiting 20minuts and restarting shoko... Ommina is currently offline to confirm the ban - maybe shoko fake ban , can see because there is no relevant log about it - only the 'disconnected, cant establish connection"

**Comment by bigretromike** [comment]
currently im at 40k jobs in general queue... and that not even half my collection.

**Comment by Cazzar** [comment]
We live in different countries and I know my ISP well enough to not drop
any data at all if possible

**Comment by bigretromike** [comment]
And I know that my ISP is sh*t face that drops connection some times.

**Comment by bigretromike** [comment]
ok, ban if off now. also while playing with anidb lib on python im sure that there is needed ping-pong functionality, so the connection is not ended. maybe this is was is happening here. 

We dont ping-pong (or lost it, its udp after all), then I send FileInfo and server tell "Stop partner, You didnt ping-pong me, I dont know you anymore, you send me your user but I dont see correct authentication method, I say stop- for 15minuts"

The main questions would be, do we PING-PONG @hidden4003 ?

**Comment by Cazzar** [comment]
We do ping pong.

**Comment by bigretromike** [comment]
...  Then I have no clue ... 
But the problem is there - and I think that its related to 'unable to establish connection' from other issue.

**Comment by Cazzar** [comment]
Ultimately at this point you're the only one reporting this others have had
no issues, the only other bans we have seen recently are http.
At this point I'm speculating something that's network related outside of
Shoko

**Comment by bigretromike** [comment]
I never had similar problems like this with other anidbLib implementations. and thats the problem.

also the only BAN is see is that in GUI, i dont see anything ban related in logs (shouldn't there be info) so maybe this is false-ban trigger system in shoko ? 

When I see "BAN " in gui and get PAUSE for general, I get same thing after hiting RESUME. 

The only solution is wait more than 15minut (which should be time that ban is lifted but never worked my  experiments now) about 20-30 minut, restart shoko, and then I dont have ban. 

I wanted to confirm if BAN is even on server or just faked by shoko, but Dev was afk.

**Comment by hidden4003** [comment]
It is not the anidb libs problems it is your network or pc that is the problem, there is no way you can make Shoko send Anidb packets faster than once per 2.5 sec and unless you have some problem with clock or multiple instances of Shoko on that pc I don't see how it is possible.

**Comment by bigretromike** [comment]
So no....
I tested this on 2 different machines...

As I stated before, I cannot confirm its AniDB BAN.
I currently suspect its Shoko-anti-Ban-system and I dont use multi-shoko setup. 

Shoko dont handle AniDB connection and assume I get ban and prevent me from forcing it (so I dont get perma ban) -Is that possible @hidden4003  ?

**Comment by hidden4003** [comment]
I can only suspect it being login related, but we never had confirmed successful login bans, I remember @ElementalCrisis said he tested login 10 times in a row and didn't get banned.

**Comment by bigretromike** [comment]
I can confirm that first time this happened (the initial issue) was confirm by Ommina that it was a login ban, which should be gone after 15minuts.
Sadly our TimeZone is so much split that It would miracle to synchronize next ban with me and him being online in same time.
But will try to look for him when I get it once again. 

The only part that if curiose to me is that I dont see anything AniDB/UDP/Http error related in log except that 'cannot connect' some time before Shoko cut me off. 
Maybe we could get better logging in logger for this ? (error code?, respond? last time connected?) dunno, thats a blind shot

**Comment by bigretromike** [comment]
Once again. Shoko tells me that im banned. - I contacted Ommina will give you info if there was ban and why (if he can tell )

**Comment by Cazzar** [comment]
Tell me, if you hit: http://<ip>:8111/v1/Server.json does it give you `"IsBanned": true` or any other information.?

**Comment by Cazzar** [comment]
Because from looking at all code that can trigger a ban to show in the UI, that should be reflected.

**Comment by bigretromike** [comment]
HashQueueCount | 0
-- | --
HashQueueState | "Idle"
HashQueueStateId | 16
HashQueueStateParams |  
GeneralQueueCount | 3970
GeneralQueueState | "Paused"
GeneralQueueStateId | 17
GeneralQueueStateParams |  
ImagesQueueCount | 0
ImagesQueueState | "Idle"
ImagesQueueStateId | 16
ImagesQueueStateParams |  
IsBanned | false
BanReason | "2017-09-14 16:48:10"
BanOrigin | ""

BAN is not displayed it vanished

**Comment by ElementalCrisis** [comment]
Hmm, the interesting thing is I imported a couple hundred files a couple nights ago that include multiples, I even had everything set to download and never got a ban. The only ban I've ever seen was an http ban for during my initial upload due to downloading multiple images a second. 

The fact that no one else is reporting issues makes me wonder if this might be an edge case.

**Comment by bigretromike** [comment]
|  
-- | --
HashQueueCount | 0
HashQueueState | "Idle"
HashQueueStateId | 16
HashQueueStateParams |  
GeneralQueueCount | 3971
GeneralQueueState | "Paused"
GeneralQueueStateId | 17
GeneralQueueStateParams |  
ImagesQueueCount | 0
ImagesQueueState | "Idle"
ImagesQueueStateId | 16
ImagesQueueStateParams |  
IsBanned | true
BanReason | "2017-09-14 17:01:05"
BanOrigin | "HTTP"

After hitting RESUME

**Comment by Cazzar** [comment]
Ok then there's the issue.
HTTP bans.

**Comment by bigretromike** [comment]
Also I can login to anidb via page

**Comment by Cazzar** [comment]
.... HTTP API

**Comment by bigretromike** [comment]
ok... we know that its http api ban...

**Comment by bigretromike** [comment]
As I see look thru the info that @hidden4003 gave me year ago https://anidb.net/perl-bin/animedb.pl?show=cmt&id=56257#c404190  I see that this is because of Flooding.. so it is shoko fault then somehow... as I understand the Ommina replay.

**Comment by ElementalCrisis** [comment]
If it's an HTTP ban then it's probably because of the images, especially if you have characters and Seiyuus selected.

**Comment by bigretromike** [comment]
So we could add mimigating mechanism... Right? 

On September 14, 2017 7:10:54 PM GMT+02:00, ElementalCrisis <notifications@github.com> wrote:
>If it's an HTTP ban then it's probably because of the images,
>especially if you have characters and Seiyuus selected.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ShokoAnime/ShokoServer/issues/673#issuecomment-329548237

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ElementalCrisis** [comment]
I believe @hidden4003 said he would add the rate limiter to images.

**Comment by hidden4003** [comment]
@bigretromike need feedback, are you still getting bans with this change or not?

**Comment by bigretromike** [comment]
@hidden4003 I would have to reimport my collection to tell you for sure :-) you know 24h+ to trigger it. But as many thing was broken/missing when I init import I think I will be fine with last time importing all of this... 
But looking on the code you submit, that should help a lot ! 

I wont lie, that Im currently out of free time for some time but will report back after importing if this is still broken. 
For now the commit is good enough thank you a lot !
