### ISSUE TITLE
New API doesn't have a RescanUnlinkedFiles like the old binary API

### ISSUE THREAD

**Issue by nettosama** [ShokoAnime/ShokoServer#675]
Shoko Version 3.8.0.0.

**Comment by da3dsoul** [comment]
Indeed. We have a scan single file and get unlinked files. I'll add this as it's a simple and useful endpoint

**Comment by da3dsoul** [comment]
Okay, I am adding /api/rescanunlinked, /api/rehashunlinked, /api/rescanmanuallinks, and /api/rehashmanuallinks
As with all hash operations, if you call rehash, it will be automatically rescanned after hashing.
