### ISSUE TITLE
Watched counter / unwatched status that's not synced

### ISSUE THREAD

**Issue by jmediamanager** [ShokoAnime/ShokoServer#68]
**Reported by Wonne16ef, Jul 9, 2013**

currently i'm rewatching a show ... but it's hard to remember at which episode i stopped last time ... is it possible to create a counter or an unwatched status that's not synced with anidb [maybe just for playlists or so]

**Jul 13, 2013 buzzplayerProblem**

why not just set the files as unwatched before you rewatch a show?

**Jul 13, 2013 Wonne16ef**

because e.g. 
- i want to keep my original watched date at anidb
- i'm lazy

**Jul 15, 2013 jbsoum**

I agree with this. I have always thought that this is an inherent flaw with other media software. You shouldn't have to set a series to unwatched to rewatch it. There should be a separate status for rewatching something.

**Comment by ElementalCrisis** [comment]
So internal tracking for watched history. This might be possible down the road, so I'll keep the issue open for now.

**Comment by revam** [comment]
already implemented though. our next-up endpoint even supports filtering out or showing rewatching.

**Comment by revam** [comment]
i needed it to keep track of watch counts and last watched date separately for prooer watch state syncing with jellyfin, so it was changed around that time.

**Comment by revam** [comment]
as for the syncing to anidb part, that will still occur on every change, but we will know locally if it'sa rewatching session or not. so open this again if we want to do it exactly as the OP wanted.
