### ISSUE TITLE
Clearing big queue of command make GUI freeze

### ISSUE THREAD

**Issue by bigretromike** [ShokoAnime/ShokoServer#680]
When I pause hasher/general queue and hit 'clear' button, the GUI is not responsive and freeze.
Eventualy when queue is cleared gui is back responsive. 

It happens with queue with 7000+ commands. And take A BIT of time to finish (like few good minutes 10-15minuts)

EDIT: Its probably iterating or something, this shouldn't take that long..

EDIT2: general clear take LOOOONNNGER THAN HASHER.... when I send longer I mean (for 7000+ (or more dunno because I paused when it was increasing it )) it takes now more than 30minuts...

**Comment by bigretromike** [comment]
Update. After 30+ minutes of waiting to clear general queue (which I did after cleaning hasher queue) I force shutdown shoko. Reopen, now it had 15000 of commands in general queue, but Pausing + clearinig was instantly. 
Maybe something to do with cache ? as it was first thing I did after restarting

**Comment by ElementalCrisis** [comment]
Try again in the dailies, @hidden4003 did some work on this.

**Comment by bigretromike** [comment]
will do

**Comment by hidden4003** [comment]
That was fixed, not sure how it would work for you but there was error locking up ui. If not fixed then your issue is something else.

**Comment by bigretromike** [comment]
I don't usually pause and clear queue, but If I will I will issue this again. 
I did it on daily, so it wasn't the thing you fixed (3.8.0.1024) if you fix it after then its good as closed;

**Comment by hidden4003** [comment]
It doesn't matter whether you pause queue or not, pausing it was a guaranteed lock up, clearing running queue wasn't as bad. Also clear code itself is not optimal since it first retrieves all commands from db only then deleted them, not sure whether NHibernate deletes with one query or each item separately but your issue might be  that.

**Comment by da3dsoul** [comment]
There's got to be a more native and performant SQL for that. Running `Delete From CommandRequest where...` is way faster, at like 0.5s on a full queue

**Comment by hidden4003** [comment]
@da3dsoul correct, but current implementation doesn't do that. If you know how to fix it that would be great, otherwise I will look into it as I don't have much experience with NHibernate.

**Comment by da3dsoul** [comment]
I was just going to Google it as well.

**Comment by da3dsoul** [comment]
Btw can you build me a list of what endpoints you need for webui setup wizard? I did the big part of getting that ready today

**Comment by hidden4003** [comment]
Sure, I will make separate issue in a few hours.
