### ISSUE TITLE
Repeating identical HTTP API calls resulting in ban

### ISSUE THREAD

**Issue by CtrlAltDefeat94** [ShokoAnime/ShokoServer#682]
version: db22fbad67714be428f338b81fd37fa451a1f207

When trying to import Symphogear S4 episodes Shoko does a HTTP call requesting the show info for every file that's being processed and fails to every time. In log below you can see me getting banned after 7 attempts.
http://anidb.net/perl-bin/animedb.pl?show=anime&aid=11955

Reproduction steps:
- Add Symphogear S4 files to your import folder
- Let Shoko attempt to import them
- Wait for things to finish
- You should be banned now

Interesting notes:
- It seems that the files **do** get moved on processing, even though the fetching of show data fails, resulting in files in VideoLocal(_Place) being hooked up to no shows
- I've had this problem since the week of the 23rd of July

LOG:
https://gist.github.com/CtrlAltDefeat94/060544036e71cb17cbff7b0aea78be7c

**Comment by da3dsoul** [comment]
Try with latest

**Comment by CtrlAltDefeat94** [comment]
Same on 8dd96dd57b20801a75297ecdfc2a3f9898c01269

Log:
https://gist.github.com/CtrlAltDefeat94/e806c933b3e9bb131be356e6103d9802

**Comment by CtrlAltDefeat94** [comment]
Updated to d9ba51341f484733e92d6951f874acd521662f6f

Log:
https://gist.github.com/CtrlAltDefeat94/6135281b0a12ef10fba68e59e967728a

**Comment by ElementalCrisis** [comment]
Seeing how @da3dsoul had no issues adding the series and it's files. Maybe something related to your setup? The only differences as far as I know between your setup and his is you're using the Linux Alpha.

**Comment by da3dsoul** [comment]
I checked the code difference between Linux and master, there's no differences in the import process except path conversion

**Comment by da3dsoul** [comment]
@CtrlAltDefeat94 I'm tempted to have you debug this and step through it checking for null of SVR_AniDB_Anime.Description. I can't find a code path where it could be null. On the plus side, it looks like I fixed it retrying indefinitely.

**Comment by da3dsoul** [comment]
Also change your launch parameters to load debug symbols, you're just lucky that I know that code so well that I'm just now bothering you about it.

**Comment by CtrlAltDefeat94** [comment]
c9f8743ae4c219780a6a70d4a031b6fe5cb7fc94

now with the --debug parameter added to launch
Log
https://gist.github.com/CtrlAltDefeat94/779c45e44f96faf868db9dc9f00297b9

**Comment by CtrlAltDefeat94** [comment]
I'd say this can be closed now
