### ISSUE TITLE
Mini Calendar Update

### ISSUE THREAD

**Issue by SuzuyaJuuzoudesu** [ShokoAnime/ShokoServer#683]
I set my Mini Calendar to 100 days, yet it goes only as far as https://anidb.net/perl-bin/animedb.pl?show=anime&aid=12567, which is in 1 month, and its been like that since 3.8 stable was released. Now I use the latest daily and still have the same issue. Update Calendar Data does not load additional shows.

**Comment by ElementalCrisis** [comment]
I was unable to reproduce the issue, set my calendar to 60 days and it updated past the Code Geass movie. @da3dsoul can you try?

**Comment by bigretromike** [comment]
@ElementalCrisis in progress?
@SuzuyaJuuzoudesu do you still have issue with mini calendar ?
