### ISSUE TITLE
API for first run wizard

### ISSUE THREAD

**Issue by hidden4003** [ShokoAnime/ShokoServer#684]
To implement first run wizard https://github.com/ShokoAnime/ShokoServer-WebUI/issues/4 I need some API calls to find out whether it is a first run or not. @Cazzar mentioned there is a config setting for that.
So I need the following:

- /api/version call to return a flag whether it is a first run or not
- new api call to setup the db, for the rest of the screens I can use the existing api since after db setup is done I will be able to get a token and work with normal API

I am not sure how to implement progress messages as well, can be donw with polling ofc, then some parameters will be needed for the db init api call or separate calls to get progress and chack if it has finished and success status.

**Comment by ElementalCrisis** [comment]
@da3dsoul said before he'll work on this.

**Comment by da3dsoul** [comment]
Okay so I was imagining the flow of the wizard something like:

Check for init
Check for first run
If first run, show the wizard.
If init and not first run, then poll startup state until started, if startup fails, then run the wizard.
If not first run, then show a window with the startup progress.

First we choose a database type and connect.
Then, we enter AniDB credentials.
Progress for database init.
Import Folders.
Basic settings like if you want to use Trakt or MAL, Language settings, etc.
Run Import.

What do you guys think?

**Comment by ElementalCrisis** [comment]
Here's the issue on the Wizard in the WebUI repo.
https://github.com/ShokoAnime/ShokoServer-WebUI/issues/4

**Comment by da3dsoul** [comment]
Ah ha. Basically what I imagined. Those mockups were clearly just tossed together. I can see many things to complain about, but they get a basic thought across. How necessary is the local account thing? It'd take some refactoring to support it, but it's not unreasonable. I think we need more discussion on the exact details, as we'll need to think about how each part is going to work on the back end.

**Comment by hidden4003** [comment]
Sounds like a good plan. Technically local account is not necessary but it makes it less confusing for the user, i.e. they don't have to go to the docs to lookup default username, or remember default username. For us it is not hard to implement either as new user id should be always 1 or we can make it that after initial db creation it will return the id of the user, so the username dialog will just update existing user.

**Comment by ElementalCrisis** [comment]
Local account is needed as its the "Master" account. Since we plan to support multiple accounts with varying permissions we need one account that's above them all. Also like @hidden4003 said, way too many people get stuck at the enter username/password window so allowing them to customize it will solve this.

**Comment by da3dsoul** [comment]
Okay. I totally forgot the Database connection endpoints. Other than that, most if not all of the endpoints are there.

# Flow of calls for startup: (This is where a flowchart would be useful, but meh I hate them)
api/init/serverstatus <- this will give the startup status, such as if the server is running or first run, etc
if not (first run or startup failed) and not server running, show progress (poll server status for updates)
if not (first run or startup failed) and server running, go to dashboard/login
else show first run wizard
Almost all endpoints have gets to fill in defaults or if it's not first run

get anidb credentials
if user is blank: prompt, set, and test
else test
if failed: prompt, set, and test

get database settings. this can be done by asking for the full config and searching
do basic validation of db settings
test db connection <- what I forgot to write
if failed, repeat

set Default user credentials
store them for later

start server

poll server status until started or failed
if failed: handle failure, it'll give a message
I should probably make an enum so we can automatically switch to the section that caused a failure.

if not failed:
most of the endpoints in init will now be disabled
auth with the api using the stored credentials (we only auto login this first time)

Open the Import Folders, add them, etc
Open basic settings like language, MAL, Trakt, Grouping, etc
Run Import (we do this after so that the above settings are in effect during import)

Open dashboard

**Comment by da3dsoul** [comment]
Added database endpoints.

**Comment by da3dsoul** [comment]
This can basically be closed, but I'll leave it open for reference, as it has some planning stuff

**Comment by bigretromike** [comment]
Just asking: did any one remembered that they were endpoint from time where we argue about wizard content ? https://github.com/ShokoAnime/ShokoServer/blob/0eaef8ea51b8ce6068fc81d58c715815d9c4bc8d/Shoko.Server/API/v2/Modules/Database.cs

**Comment by da3dsoul** [comment]
Yes...I forgot that existed. I'll probably rewrite it. I made the file to match the settings.json names. The important thing is that init can't require auth, as the DB doesn't exist yet, but it can't be available after init.

**Comment by bigretromike** [comment]
thats what "firstrun" did ... but what ever. just remove the non-used code so it wont confuse anyone that look up the code.

**Comment by da3dsoul** [comment]
Yeah. I am doing it now. That module  didn't work, so no one will be affected by its loss.

**Comment by bigretromike** [comment]
That module did work, when I wrote it. I dont know what happend with him after you refactored it or someone change internaly something. Sorry, but that time I did put effort to test it out 👍

**Comment by da3dsoul** [comment]
No it didn't work. The only time to change database settings is when the database isn't started, but it was marked with RequiresAuthentication. Auth requires the database to be started, as users are stored in the database. You could change the settings, sure, but there's no point to change the settings if you already have a database created.

**Comment by bigretromike** [comment]
You could change setting when firstrun was in settings marked as true. 
if so it would bypass the need of use auth.

**Comment by da3dsoul** [comment]
True, if that worked, then cool, but it didn't look like it would from skimming the code. The new system is bigger and designed to handle the entire first time setup process.

**Comment by bigretromike** [comment]
Remamber to remove `FirstRun` from setting if we dont use it anymore.

**Comment by da3dsoul** [comment]
We do. It's still needed. I really only reorganized and improved what you had to be easier to interact with as a client during setup.

**Comment by hidden4003** [comment]
When I call API /init/startserver, it responds ok but server crashes shortly thereafter. 
Logfile [2017-10-12.txt](https://github.com/ShokoAnime/ShokoServer/files/1379279/2017-10-12.txt)

![image](https://user-images.githubusercontent.com/197087/31496021-704c5d22-af62-11e7-8703-36e91fc2f848.png)

**Comment by da3dsoul** [comment]
That's a pain.... We need an ObservableCollection that automatically switches the proper dispatcher for changes. @maxpiva @Cazzar any ideas?

**Comment by da3dsoul** [comment]
Another option would be to use the BackgroundWorker's ReportProgress method, but it'd get messy quick and wouldn't work in every instance

**Comment by da3dsoul** [comment]
Hopefully, that makes the calls run from the main thread, and thus makes the need for dispatcher switching moot.

**Comment by hidden4003** [comment]
Tried it, still breaks on https://github.com/ShokoAnime/ShokoServer/blob/c4ff493c51391061436c58580b10b517b1247e3d/Shoko.Server/ShokoServer.cs#L563 with message that collection cannot be accessed from different thread. I guess that is because that collection is bound to UI so GUI thread locks it.

**Comment by hidden4003** [comment]
Crash is fixed, well done. 
There is another problem, AniDB endpoints don't work and I suspect default user as well, they respond with:

code | 400
-- | --
message | You may only do this before server init

And you kinda need server to be initialized to work with DB :)

**Comment by da3dsoul** [comment]
You don't need DB for AniDB init. The required information is stored in settings, not DB

**Comment by hidden4003** [comment]
@da3dsoul so you suggest configure user and AniDB accounts first and only then DB and start server in 3rd step ?

**Comment by da3dsoul** [comment]
Yeah. If you don't, you'll need to set them up with other endpoints, which I have not actually checked the existence of

**Comment by da3dsoul** [comment]
After init, you can Auth and then use any other endpoints

**Comment by ElementalCrisis** [comment]
@hidden4003 correct me if I'm wrong but doing DB last creates more work during the initial setup process right? It just makes more sense to do DB first, then Local & AniDB user. 

The process as originally outlined was:

1. DB.
2. AniDB / Local.
3. AniDB settings
4. Option to jump to Dashboard or continue with additional settings.
5. TvDB settings.
6. MAL and MAL settings.
7. Trakt and Trakt settings.

**Comment by da3dsoul** [comment]
@ElementalCrisis local user needs to be before DB, unless we want to do a bunch of refactoring on init that'll introduce more pointless issues. The users, Filters, etc are so created in DB init

**Comment by hidden4003** [comment]
It makes it somewhat harder as I need to additionally track the tab that fails, but its not that much extra work, refactoring server is probably more work.

I can keep the flow as @ElementalCrisis specified, just there will be extra button on step 3, "Start server"

**Comment by da3dsoul** [comment]
That's the way it should be. At least until the DB is started, each tab shouldn't progress further unless all input is valid. Without properly specifying the users, Shoko can't do anything. Without setting up the DB, Shoko can't do anything. Etc
I made endpoints to validate the input at each step for a reason.

**Comment by bigretromike** [comment]
This was added in latest, right ?

**Comment by da3dsoul** [comment]
Should be. I don't know if it's fully functional, though. The API for it is complete as far as I recall

**Comment by bigretromike** [comment]
@hidden4003 any info about this?

**Comment by hidden4003** [comment]
Basic DB setup should be in latest release, all is left are settlings pages.

**Comment by bigretromike** [comment]
Good job! Can't wait to test that one out !

**Comment by bigretromike** [comment]
Any way to test it ? 
I assume I wont be able to test it out in docker right... so I need clean shoko server installation and when I start it and run webui it should work, right ?

**Comment by bigretromike** [comment]
last time I tried it, it was not working with docker - so I just asked how could I test it - maybe something change... while im waiting in between anidb bans....
