### ISSUE TITLE
Not getting served any thumbnails in ShokoOnPlex

### ISSUE THREAD

**Issue by SuperFlue** [ShokoAnime/ShokoServer#688]
Hi, i am not getting any thumbnails in ShokoOnPlex.

![image](https://user-images.githubusercontent.com/6199507/31574882-8369c7aa-b0d9-11e7-9d59-d4f6c1621c78.png)

My setup is this:
Docker host with Shoko server and Plex Media Server running in containers.
Both containers are connected to each other and the rest of the network via a macvlan docker network.
So both containers have their own dedicated IP in the network.
Shoko server is also connected to a MariaDB container with an internal network if relevant.
Am also using a Windows DNS for name resolution in the network.
Shoko Docker image is from the daily branch and last pull and update is 35 hours ago according to Docker.

What i have found out so far:
When looking into the XML files that is available under more info on the media files, i found that the thumbnails are supposed to be served with this URL (using dotHack GU trilogy as example):
http://shokoserver:8111/api/Image/Thumb/1/5459/0.6667
When opening this address in a browser i am served a 1x1px image (placeholder?).
But if i modify the URL to:
http://shokoserver:8111/api/Image/1/5459
I am served the image for the series\movie.

[2017-10-14.txt](https://github.com/ShokoAnime/ShokoServer/files/1384584/2017-10-14.txt)
Log from Shoko server is here, but it looks to me like the errors is mostly from me messing with the api url....

**Comment by da3dsoul** [comment]
Thank you. That bit about the URLs is what I needed to fix it

**Comment by da3dsoul** [comment]
Stand by for said fix

**Comment by da3dsoul** [comment]
Fixed in 5962a822416636826131a44ac3607d6cc0751b5a

**Comment by SuperFlue** [comment]
Pulled latest docker image, can confirm that it is fixed here.
