### ISSUE TITLE
Unable To Run Remove Missing Files In Succession 

### ISSUE THREAD

**Issue by ElementalCrisis** [ShokoAnime/ShokoServer#691]
Something I've noticed while cleaning up my collection, if I remove some files and then run Remove Missing Files, those files are removed from my collection. However if I remove more files and then rerun Remove Missing Files, nothing happens, I have to restart Server in order for Shoko to detect the removed files.

**Comment by da3dsoul** [comment]
What version

**Comment by da3dsoul** [comment]
Should be fixed in latest

**Comment by ElementalCrisis** [comment]
Ah, I was running 3.8.1 so I'll try again with latest when I'm done importing.

**Comment by da3dsoul** [comment]
@ElementalCrisis any news?

**Comment by ElementalCrisis** [comment]
Haven't tried on daily yet, will report back when I do.

**Comment by da3dsoul** [comment]
@ElementalCrisis can you check this so that we can close it?

**Comment by ElementalCrisis** [comment]
No longer an issue.

The only thing I would recommend we change is the fact that Shoko leaves an empty group behind if you delete all episodes from a series.

**Comment by da3dsoul** [comment]
That can be arranged
