### ISSUE TITLE
Export Manual/Ignored/Multiple File Settings

### ISSUE THREAD

**Issue by ElementalCrisis** [ShokoAnime/ShokoServer#693]
In older versions, you're Manually Linked files were sent to the WebCache so if you switched DB types or started over, the links were downloaded and automatically applied for you, provided you didn't change your AniDB name. 

While this no longer happens, I think we should introduce a feature that allows the user to export their Manual Linked Files, Ignored Files and Multiple Files for use with a new DB. If we're still on track, this will definitely be helpful for users when we drop support for MySQL and SQL Server. 

The data is already there and when importing we can use the Unrecognized files list and compare hashes and if found, apply the user selected option, either Manual Link or Ignore.

**Comment by da3dsoul** [comment]
I'm closing this in favor of a different issue. I'll look it up and link it upon closing.

**Comment by da3dsoul** [comment]
https://github.com/ShokoAnime/ShokoServer/issues/370
