### ISSUE TITLE
"Mark ALL Watched" - AniDB update not working

### ISSUE THREAD

**Issue by xmodx10** [ShokoAnime/ShokoServer#694]
## VERSION INFORMATION

Server Version: 3.8.2

Desktop Version: 3.8.2

## LOG FILE

[Shoko Server LOG](https://github.com/ShokoAnime/ShokoServer/files/1585926/Shoko_Server.txt)

## DESCRIPTION

I wanted to mark all the episode of an anime as "watched" so I used the button in the below screenshot >>

![image](https://user-images.githubusercontent.com/25097788/34340616-67b0edb4-e9c2-11e7-956d-506f0bbb07be.png)

This seemed to mark all the episodes watched within the local DB but did not update my AniDB mylist as I would expect it to.

## STEPS TO REPRODUCE

1. Select an anime with no episodes marked as watched.
2. Use the "Mark ALL Watched" button.
3. Check AniDB mylist

**Comment by da3dsoul** [comment]
Screenshot your MyList settings. Also, make sure the queue is empty

**Comment by da3dsoul** [comment]
If the queue is empty and your settings are correct, then I'll ask for a clean log (close, rename the log, start, reproduce, let the queue clear, post).

**Comment by nspiegl** [comment]
Okay, I think I have figured out the cause. It seems nothing works in terms of updating watched status when I have the "Add Files" option un-ticked. This should not be the case as I still have "Set Watched & Set Unwatched" selected.

These are my settings >> 
![image](https://user-images.githubusercontent.com/25097788/34340754-f8798e8a-e9c4-11e7-9b6f-532581e85ee9.png)

![image](https://user-images.githubusercontent.com/25097788/34340768-3aee1902-e9c5-11e7-9d0c-d1fdc39ca750.png)

Let me know if you need logs

**Comment by da3dsoul** [comment]
Nope, that's good. Hmm. I don't wanna fix that. I'll need to make a cache on the MyList to properly obey the settings. If you don't add the file to MyList, then you can't update the watched state. There's no way to keep track of which files are in MyList as of now.

**Comment by nspiegl** [comment]
The reason I dont always have it ticked is because sometimes I dont want it to automatically add files to my AniDB mylist.

Not sure what you mean by making a cache but what about a field in the local DB indicating if the episode has been added to the users AniDB mylist ? It could be set on sync and/or import.

**Comment by da3dsoul** [comment]
Because if I'm going that far, I might as well cache what the status is so that we don't spam AniDB

**Comment by nspiegl** [comment]
ah yep, I understand now. Makes sense.

**Comment by ElementalCrisis** [comment]
@da3dsoul I know this is a back-and-forth issue for us, are we still having MyList related issues?

**Comment by da3dsoul** [comment]
We are still generally having MyList issues, but this issue can be closed

**Comment by bigretromike** [comment]
Maybe add one issue and pin it with mylist related issue?
