### ISSUE TITLE
ad an option to put the path to the imageFolder in by hand

### ISSUE THREAD

**Issue by kusco123** [ShokoAnime/ShokoServer#695]
I would like to have the option to put the path to teh imagefolder in by hand in addition to existing selection menue.

The reason is that it would be great to put the images an a central share to have them availible for several machines using shokoserver like MediaPortal, Codi and ShokoDeksktop on Windows Tablet without the need of mapping a share to a driveletter

**Comment by ElementalCrisis** [comment]
Here's the locations (Tab - Section) to make the changes @Baine. 

Settings - Import Folders
Settings - Import Settings
