### ISSUE TITLE
Feature to call a process/script when a new file is added

### ISSUE THREAD

**Issue by nettosama** [ShokoAnime/ShokoServer#698]
﻿I would like a way to call a script or executable in general when a new file is added to the library, kinda how Transmission lets you run a script when a torrent finishes. The process should get some environment variables regarding this file, like FILEPATH, SERIES, STATUS, etc. This would make it easier to integrate Shoko with other services like Plex, Emby, etc.

**Comment by da3dsoul** [comment]
I'm going to say this is one of those things best implemented by a plugin when the plugin system is implemented.

**Comment by revam** [comment]
We have plugin events to detect when a file is discovered, hashed, matched/not-matched/deleted now.
