### ISSUE TITLE
Speed up - Hashing and moving file over network

### ISSUE THREAD

**Issue by jmediamanager** [ShokoAnime/ShokoServer#70]
**Reported by buzzplayerProblem, Sep 25, 2013**

If I am not totally wrong, JMMServer hashes the files over the network which probably result in the file getting stored in some random temp folder (or maybe even in the RAM...), and after its done hashing the file it tries to copy the file to the drop location - if you have configured JMMServer this way.

Windows (the SMB Protokol) will than again download the file to a temp folder just to upload it to the destination folder.

So in my believe it would be faster, if JMMServer figures out that its working with Networkdrives as source/drop location. 
Than download a copy of the file from source destination to a random temp folder, do the hashing locally (which should also be faster - and alot faster with the tempfolder being on SSD instead of a network drive) after it was successfully hashed upload it to drop location and delete the file in the source location aswell as in the temp folder.

With this method, you kill the purpose of downloading the file twice.
Once during the hashing progress and once during the move to the drop location. Considering movies with 4 GB plus this can be alot of time saved.

If I am totally wrong and just impatient with JMMServer hashing 5900 files right now, than just say so. :)

**Aug 5, 2014 werndlymob**

The hasher actually loads the file in chunks (and does the hashing in memory)
It is possible that copying the file locally first would improve performance though, so I will investigate it

**Comment by bigretromike** [comment]
@ElementalCrisis there was so many improvement also max contributed with cloud support.

**Comment by ElementalCrisis** [comment]
Yeah he's even working on making it faster. 

Closing.
