### ISSUE TITLE
Non English OS overwrite "default" account name

### ISSUE THREAD

**Issue by bigretromike** [ShokoAnime/ShokoServer#700]
Starting stable on non English OS results in name aka username being named after "default" word translated to that language, while "Family Friendly" is left intact.

This is not welcome behavior as this results in unable to connect thru api because of lack of "username"

**Comment by da3dsoul** [comment]
Fair, but eventually, we'd like to add custom usernames. It's in the back end, but only web UI uses it

**Comment by bigretromike** [comment]
Im not against custom names but give option to change default name and not overwrite it. without DB access I wouldn't be able to login because username was WAY off. 
This prevent me from login in into API also (all APIv2 using addons are affected)

**Comment by bigretromike** [comment]
@da3dsoul while you are fixing world, could you fix this one? I took me few tries until I noticed that it was not fault of Kodi but Shoko itself, also I forgot that Shoko cache everything and I had to restart it to load new username; 'default' is ok, which isn't present form non English Language Setting Systems.

**Comment by bigretromike** [comment]
https://github.com/ShokoAnime/ShokoServer/commit/fcee05cf25baa85459080d5288c31f6c4c03f5ba thank you my good men
