### ISSUE TITLE
MAL Links and Rogue Missing Episode

### ISSUE THREAD

**Issue by Urlryn** [ShokoAnime/ShokoServer#701]
﻿## VERSION INFORMATION

Server Version: 3.8.2.1011 (Latest Daily)

Desktop Version: 3.8.2.1003 (Latest Daily)

## Logs
Server Logs
[2018-01-26.zip](https://github.com/ShokoAnime/ShokoServer/files/1668746/2018-01-26.zip)

## DESCRIPTION

First Issue: MAL Linking Query
When attempting to remove the broken MAL Links that were created from a previous issue, you are unable to due to the Query Did Not Return A  Unique Result.
![mal_linking1](https://user-images.githubusercontent.com/33221884/35453696-c61d4118-0290-11e8-91af-60c5402b378a.png)
![mal_query_error](https://user-images.githubusercontent.com/33221884/35453761-ffe33812-0290-11e8-9c18-fafb5f8b1b4a.png)

Second Issue:
Shoko is showing that a series has a missing episode when in fact it does not.  In my database this is the only series affected by this issue.  Ginga Eiyuu Densetsu Gaiden (1999)

![ginga1](https://user-images.githubusercontent.com/33221884/35453726-dd63bd98-0290-11e8-999c-308664802f6a.PNG)
![ginga2](https://user-images.githubusercontent.com/33221884/35453728-e020d82c-0290-11e8-9482-c68bf3445b6f.PNG)
![ginga_group](https://user-images.githubusercontent.com/33221884/35453736-e4e65602-0290-11e8-9727-283a73cb3943.PNG)

Issue Three:
Rebuilding Groups - Object reference not set to an instance of an object
See logs (last entry)

Issue Four:
Unable to add multiple links to a series.  Attempting to add a second link results in the original one being overwritten.

## STEPS TO REPRODUCE
First Issue:
In the Link section in desktop.....Click the remove button on any of the multiple links

Second Issue:
Unable to reproduce this on any series other than this one. 
Deleted Series from Desktop
Re-imported...did not fix

Ran SQL script provided by da3soul to delete series
Re-imported....did not fix

Downloaded a newer version of the series by a different subgroup
Re-imported....did not fix

Third Issue
Click rebuild groups

**Comment by bigretromike** [comment]
https://github.com/ShokoAnime/ShokoServer/issues/739

**Comment by bigretromike** [comment]
@da3dsoul you probably fixed it before, and we could close it ?

**Comment by da3dsoul** [comment]
I think the missing episode is related to another issue. It's not fixed

**Comment by da3dsoul** [comment]
#733

**Comment by ElementalCrisis** [comment]
MAL support is super limited now, we just show the links so this is no longer an issue.
