### ISSUE TITLE
API /api/group images not populating for certain series

### ISSUE THREAD

**Issue by hidden4003** [ShokoAnime/ShokoServer#704]
Server Version: 3.8.2 release

Using API call: /api/group?nocast=1&tagfilter=63

Relevant JSON from the response:
```
name:"Shinseiki Evangelion Gekijouban: The End of Evangelion"
art: {banner: [], fanart: [], thumb: [{url: "/api/image/1/202", index: 0}]}
banner:[]
fanart:[]
thumb:[{url: "/api/image/1/202", index: 0}]
```

Images not provided despite series having the images available.
![image](https://user-images.githubusercontent.com/197087/35769693-4f63f674-0917-11e8-83ec-d91a23388399.png)

**Comment by bigretromike** [comment]
could you try: `/api/group?nocast=1&tagfilter=63&level=2`

**Comment by da3dsoul** [comment]
It's fine @bigretromike. I know enough to fix it fun discord

**Comment by bigretromike** [comment]
ok; I didnt saw you were assigned;

**Comment by hidden4003** [comment]
As I mentioned on Discord seems to only affect movies.

**Comment by hidden4003** [comment]
I tried with 3.8.3 release and regenerated the contracts it is still showing 404.

**Comment by da3dsoul** [comment]
Specifically, it needs AniDB_Anime regenerated.

**Comment by bigretromike** [comment]
@da3dsoul remamber to add that regeneration to patch, so all new people will have this fix'd in new version

**Comment by da3dsoul** [comment]
too late

**Comment by hidden4003** [comment]
Yep after regenerating AniDB_Anime it works.
