### ISSUE TITLE
Shoko Server not showing any cloud providers in "Add Cloud Account" window

### ISSUE THREAD

**Issue by ripdog** [ShokoAnime/ShokoServer#708]
## VERSION INFORMATION

Server Version: 3.8.3.42091

Desktop Version: N/A

## LOG FILE

[2018-02-12.zip](https://github.com/ShokoAnime/ShokoServer/files/1714472/2018-02-12.zip)

## DESCRIPTION

This is a brand new install of shoko server. When I set it up with SQLite, I then select the Cloud Accounts tab, Add Account. In the add cloud account window, the list of providers has only one entry - Local File System.

**Comment by Cazzar** [comment]
This may be an artifact of the UI split, from an initial suspicion.
