### ISSUE TITLE
Repurpose /api/dashboard for client-v2

### ISSUE THREAD

**Issue by hidden4003** [ShokoAnime/ShokoServer#716]
Since I don't use this anywhere but client-v2 I think we can repurpose it to return data for stats section.
![image](https://user-images.githubusercontent.com/197087/37358237-419d0e82-26f3-11e8-80f5-73cfdea065c7.png)
Currently I have only series and files count, everything extra like last files I don't need, they are available from different call and since dashboard is modular they might not be needed at all.
So I need:

- Action items
Now this one is from new queue system that is planned so this can be 0 for now.
- Collection size in GB/TB
- Hours watched
- Episodes watched (count)
- Series completed (count)
- Popular tags 
Whatever doesn't kill performance will do.

**Comment by da3dsoul** [comment]
For the tags, do you want a list of common tags or what?

**Comment by da3dsoul** [comment]
Like I can do a top 10. But popular tags is really vague

**Comment by hidden4003** [comment]
@da3dsoul I have no idea what @ElementalCrisis meant by this but my guess would be just top xx by count from the series user has, so a simple top10 would work I guess.

**Comment by ElementalCrisis** [comment]
For tags the idea was to show a tag-cloud when clicked when the most popular tags in the users collection.
