### ISSUE TITLE
Inconsistencies between Database Schemas (nullability primarily)

### ISSUE THREAD

**Issue by nettosama** [ShokoAnime/ShokoServer#717]
## VERSION INFORMATION

Server Version: daily 141f2036c6 Windows (3/13/2018)

## DESCRIPTION

When migrating data from SQLServer to MySQL, some rows cannot be migrated because of incompatibilities.
I found this:

TvDB_Episode.Filename: nullable in SQL Server, not null in MySQL
TvDB_Episode.EpisodeName: nullable in SQL Server, not null in MySQL
TvDB_Series.SeriesName: nullable in SQL Server, not null in MySQL
AniDB_Recommendation.RecommendationText: column should be utf8mb4 (if not, throws errors when inserting emojis and other characters.). I changed the character set manually, but I think it can be forced if the column is changed to varchar, because that works in "AniDB_ReleaseGroup.Picname".

## STEPS TO REPRODUCE

Start shokoserver using MySQL as a backend.
After the DB is created, stop shoko.
Use a program to help migrate data from SQLServer to MySQL (I used MySQL Workbench).
Check the errors.

**Comment by bigretromike** [comment]
MySQL is right. 
Those columns must be not nullable; 
You cannot have image info without file attached to it aka `filename`
You cannot have tvdb episode without name aka `EpisodeName` 
You cannot have TvDB series without name aka `SeriesName`

Im not using MSSQL but if those allow nullable and you didn't change that by hand then there is a problem there. 
I would suggest to delete all nullable rows there on mssql and then migrate it. and then hit that image refresh button on server to it will check all of it;

**Comment by ElementalCrisis** [comment]
@revam or @da3dsoul, one of you worked on this recently, right?
