### ISSUE TITLE
/api/file/recent always empty

### ISSUE THREAD

**Issue by hidden4003** [ShokoAnime/ShokoServer#723]
Server Version: b693933dc8e006c40058c9f27b61630ca157b23a

Always returns empty list.

**Comment by da3dsoul** [comment]
It was a single inverted if....

**Comment by hidden4003** [comment]
Ok I will use those for dashboard in v2, just grabbed url from webui and was surprised it didn't work. WebUI uses just as I wrote '/api/file/recent' no extra params, should I change it as well ?
