### ISSUE TITLE
Drag and Drop Scanning

### ISSUE THREAD

**Issue by da3dsoul** [ShokoAnime/ShokoServer#727]
There are situations where you may want to rescan a folder, but just that folder. The idea is to drag and drop the folder into the server or desktop UI and shoko will scan it if it is in an import folder.

**Comment by bigretromike** [comment]
Why not use WatchDog - when something change it will scan only that folder.

**Comment by Cazzar** [comment]
With us moving to WebUI primarily as our interaction, this is no longer feasible.
