### ISSUE TITLE
Better TvDB episode matching

### ISSUE THREAD

**Issue by da3dsoul** [ShokoAnime/ShokoServer#728]
Okay, so I've improved the matching from before, but it still has annoying edge cases that I'm finding. I've also gotten complaints about how they give warnings in stupid places, which is fair.

My new idea is as such:
```
These all apply to normal episodes mainly.
It will fail for specials (BD will cause most to have the same air date).

if the episodes are 1-1:
  Try to match air date.
  if no match:
    match to the next episode after the previous match (starting at one)
  if two episodes air on the same day:
    match in order of episode, grouped by air date

if the episodes are not 1-1:
  try to match air date.
  group episodes in order by air date
  if two episodes air on the same day on both sides:
    split them as equally as possible, these will likely need manually overriden
  if no match:
    if all episodes belong to the same season:
      split episodes equally and increment from previous match. these will almost definitely need overriden
    else:
      increment and hope for the best...
```

**Comment by da3dsoul** [comment]
#593 #424

**Comment by ElementalCrisis** [comment]
This is related, https://github.com/ShokoAnime/ShokoDesktop/issues/400

**Comment by da3dsoul** [comment]
Okay after some thought, for now I'm going to assume OVAs are specials and try to match them.
In the future, I'll try to match to specials first, then normal episodes, and take whichever one matches better.

The next thing I plan is to update the UI to be less confusing, and then the OVA matching.

**Comment by da3dsoul** [comment]
Desktop stuff is done. I'll write some migration stuff for OVAs, and this will be done
