### ISSUE TITLE
New tvdb link generation

### ISSUE THREAD

**Issue by hidden4003** [ShokoAnime/ShokoServer#731]
Here you can see how it hops all over the seasons with the 3rd season, other seasons of this show seem to match ok.

> file: E:\Anime\Zero no Tsukaima։ Princess no Rondo\[JacobSwaggedUp] Zero no Tsukaima - Princesses no Rondo - 01 (BD 1280x720).mp4
> Requesting: api/ep/getbyfilename?filename=%5BJacobSwaggedUp%5D%20Zero%20no%20Tsukaima%20-%20Princesses%20no%20Rondo%20-%2001%20%28BD%201280x720%29.mp4
> Got API KEY: 5b265e63-49b2-4592-a908-46efe6d568de
> Requesting: api/serie/fromep?id=7393&nocast=1&notag=1
> show title: Zero no Tsukaima: Princess no Rondo
> season number: 3
> episode number: 1
> vid: Zero no Tsukaima: Princess no Rondo (season 3, episode: 1) => [] starting at 0
> file: E:\Anime\Zero no Tsukaima։ Princess no Rondo\[JacobSwaggedUp] Zero no Tsukaima - Princesses no Rondo - 02 (BD 1280x720).mp4
> Requesting: api/ep/getbyfilename?filename=%5BJacobSwaggedUp%5D%20Zero%20no%20Tsukaima%20-%20Princesses%20no%20Rondo%20-%2002%20%28BD%201280x720%29.mp4
> Requesting: api/serie/fromep?id=7394&nocast=1&notag=1
> show title: Zero no Tsukaima: Princess no Rondo
> season number: 3
> episode number: 2
> vid: Zero no Tsukaima: Princess no Rondo (season 3, episode: 2) => [] starting at 0
> file: E:\Anime\Zero no Tsukaima։ Princess no Rondo\[JacobSwaggedUp] Zero no Tsukaima - Princesses no Rondo - 03 (BD 1280x720).mp4
> Requesting: api/ep/getbyfilename?filename=%5BJacobSwaggedUp%5D%20Zero%20no%20Tsukaima%20-%20Princesses%20no%20Rondo%20-%2003%20%28BD%201280x720%29.mp4
> Requesting: api/serie/fromep?id=7396&nocast=1&notag=1
> show title: Zero no Tsukaima: Princess no Rondo
> season number: 1
> episode number: 3
> vid: Zero no Tsukaima: Princess no Rondo (season 1, episode: 3) => [] starting at 0
> file: E:\Anime\Zero no Tsukaima։ Princess no Rondo\[JacobSwaggedUp] Zero no Tsukaima - Princesses no Rondo - 04 (BD 1280x720).mp4
> Requesting: api/ep/getbyfilename?filename=%5BJacobSwaggedUp%5D%20Zero%20no%20Tsukaima%20-%20Princesses%20no%20Rondo%20-%2004%20%28BD%201280x720%29.mp4
> Requesting: api/serie/fromep?id=7397&nocast=1&notag=1
> show title: Zero no Tsukaima: Princess no Rondo
> season number: 3
> episode number: 4
> vid: Zero no Tsukaima: Princess no Rondo (season 3, episode: 4) => [] starting at 0
> file: E:\Anime\Zero no Tsukaima։ Princess no Rondo\[JacobSwaggedUp] Zero no Tsukaima - Princesses no Rondo - 05 (BD 1280x720).mp4
> Requesting: api/ep/getbyfilename?filename=%5BJacobSwaggedUp%5D%20Zero%20no%20Tsukaima%20-%20Princesses%20no%20Rondo%20-%2005%20%28BD%201280x720%29.mp4
> Requesting: api/serie/fromep?id=7398&nocast=1&notag=1
> show title: Zero no Tsukaima: Princess no Rondo
> season number: 1
> episode number: 5
> vid: Zero no Tsukaima: Princess no Rondo (season 1, episode: 5) => [] starting at 0
> file: E:\Anime\Zero no Tsukaima։ Princess no Rondo\[JacobSwaggedUp] Zero no Tsukaima - Princesses no Rondo - 06 (BD 1280x720).mp4
> Requesting: api/ep/getbyfilename?filename=%5BJacobSwaggedUp%5D%20Zero%20no%20Tsukaima%20-%20Princesses%20no%20Rondo%20-%2006%20%28BD%201280x720%29.mp4
> Requesting: api/serie/fromep?id=7399&nocast=1&notag=1
> show title: Zero no Tsukaima: Princess no Rondo
> season number: 1
> episode number: 6
> vid: Zero no Tsukaima: Princess no Rondo (season 1, episode: 6) => [] starting at 0
> file: E:\Anime\Zero no Tsukaima։ Princess no Rondo\[JacobSwaggedUp] Zero no Tsukaima - Princesses no Rondo - 07 (BD 1280x720).mp4
> Requesting: api/ep/getbyfilename?filename=%5BJacobSwaggedUp%5D%20Zero%20no%20Tsukaima%20-%20Princesses%20no%20Rondo%20-%2007%20%28BD%201280x720%29.mp4
> Requesting: api/serie/fromep?id=7400&nocast=1&notag=1
> show title: Zero no Tsukaima: Princess no Rondo
> season number: 2
> episode number: 7
> vid: Zero no Tsukaima: Princess no Rondo (season 2, episode: 7) => [] starting at 0
> file: E:\Anime\Zero no Tsukaima։ Princess no Rondo\[JacobSwaggedUp] Zero no Tsukaima - Princesses no Rondo - 08 (BD 1280x720).mp4
> Requesting: api/ep/getbyfilename?filename=%5BJacobSwaggedUp%5D%20Zero%20no%20Tsukaima%20-%20Princesses%20no%20Rondo%20-%2008%20%28BD%201280x720%29.mp4
> Requesting: api/serie/fromep?id=7401&nocast=1&notag=1
> show title: Zero no Tsukaima: Princess no Rondo
> season number: 2
> episode number: 8
> vid: Zero no Tsukaima: Princess no Rondo (season 2, episode: 8) => [] starting at 0
> file: E:\Anime\Zero no Tsukaima։ Princess no Rondo\[JacobSwaggedUp] Zero no Tsukaima - Princesses no Rondo - 09 (BD 1280x720).mp4
> Requesting: api/ep/getbyfilename?filename=%5BJacobSwaggedUp%5D%20Zero%20no%20Tsukaima%20-%20Princesses%20no%20Rondo%20-%2009%20%28BD%201280x720%29.mp4
> Requesting: api/serie/fromep?id=7402&nocast=1&notag=1
> show title: Zero no Tsukaima: Princess no Rondo
> season number: 2
> episode number: 9
> vid: Zero no Tsukaima: Princess no Rondo (season 2, episode: 9) => [] starting at 0
> file: E:\Anime\Zero no Tsukaima։ Princess no Rondo\[JacobSwaggedUp] Zero no Tsukaima - Princesses no Rondo - 10 (BD 1280x720).mp4
> Requesting: api/ep/getbyfilename?filename=%5BJacobSwaggedUp%5D%20Zero%20no%20Tsukaima%20-%20Princesses%20no%20Rondo%20-%2010%20%28BD%201280x720%29.mp4
> Requesting: api/serie/fromep?id=7403&nocast=1&notag=1
> show title: Zero no Tsukaima: Princess no Rondo
> season number: 3
> episode number: 10
> vid: Zero no Tsukaima: Princess no Rondo (season 3, episode: 10) => [] starting at 0
> file: E:\Anime\Zero no Tsukaima։ Princess no Rondo\[JacobSwaggedUp] Zero no Tsukaima - Princesses no Rondo - 11 (BD 1280x720).mp4
> Requesting: api/ep/getbyfilename?filename=%5BJacobSwaggedUp%5D%20Zero%20no%20Tsukaima%20-%20Princesses%20no%20Rondo%20-%2011%20%28BD%201280x720%29.mp4
> Requesting: api/serie/fromep?id=7404&nocast=1&notag=1
> show title: Zero no Tsukaima: Princess no Rondo
> season number: 3
> episode number: 11
> vid: Zero no Tsukaima: Princess no Rondo (season 3, episode: 11) => [] starting at 0
> file: E:\Anime\Zero no Tsukaima։ Princess no Rondo\[JacobSwaggedUp] Zero no Tsukaima - Princesses no Rondo - 12 (BD 1280x720).mp4
> Requesting: api/ep/getbyfilename?filename=%5BJacobSwaggedUp%5D%20Zero%20no%20Tsukaima%20-%20Princesses%20no%20Rondo%20-%2012%20%28BD%201280x720%29.mp4
> Requesting: api/serie/fromep?id=7405&nocast=1&notag=1
> show title: Zero no Tsukaima: Princess no Rondo
> season number: 3
> episode number: 12
> vid: Zero no Tsukaima: Princess no Rondo (season 3, episode: 12) => [] starting at 0
> file: E:\Anime\Zero no Tsukaima։ Princess no Rondo\[JacobSwaggedUp] Zero no Tsukaima - Princesses no Rondo - OVA (BD 1280x720).mp4
> Requesting: api/ep/getbyfilename?filename=%5BJacobSwaggedUp%5D%20Zero%20no%20Tsukaima%20-%20Princesses%20no%20Rondo%20-%20OVA%20%28BD%201280x720%29.mp4
> Requesting: api/serie/fromep?id=7406&nocast=1&notag=1
> show title: Zero no Tsukaima: Princess no Rondo
> season number: 0
> episode number: 1

**Comment by da3dsoul** [comment]
Type 1 is Episode, 3 is Special

| MainTitle                            | AniType | AniNumber | TVSeason | TVNumber | 
|--------------------------------------|---------|-----------|----------|----------| 
| Zero no Tsukaima                     | 1       | 1         | 1        | 1        | 
| Zero no Tsukaima                     | 1       | 2         | 1        | 2        | 
| Zero no Tsukaima                     | 1       | 3         | 1        | 3        | 
| Zero no Tsukaima                     | 1       | 4         | 1        | 4        | 
| Zero no Tsukaima                     | 1       | 5         | 1        | 5        | 
| Zero no Tsukaima                     | 1       | 6         | 1        | 6        | 
| Zero no Tsukaima                     | 1       | 7         | 1        | 7        | 
| Zero no Tsukaima                     | 1       | 8         | 1        | 8        | 
| Zero no Tsukaima                     | 1       | 9         | 1        | 9        | 
| Zero no Tsukaima                     | 1       | 10        | 1        | 10       | 
| Zero no Tsukaima                     | 1       | 11        | 1        | 11       | 
| Zero no Tsukaima                     | 1       | 12        | 1        | 12       | 
| Zero no Tsukaima                     | 1       | 13        | 1        | 13       | 
| Zero no Tsukaima                     | 3       | 1         | 0        | 1        | 
| Zero no Tsukaima                     | 3       | 2         | 0        | 2        | 
| Zero no Tsukaima                     | 3       | 3         | 0        | 3        | 
| Zero no Tsukaima                     | 3       | 4         | 0        | 4        | 
| Zero no Tsukaima                     | 3       | 5         | 0        | 5        | 
| Zero no Tsukaima                     | 3       | 6         | 0        | 6        | 
| Zero no Tsukaima                     | 3       | 7         | 0        | 7        | 
| Zero no Tsukaima                     | 3       | 8         | 0        | 8        | 
| Zero no Tsukaima                     | 3       | 9         |          |          | 
| Zero no Tsukaima                     | 3       | 10        |          |          | 
| Zero no Tsukaima                     | 3       | 11        |          |          | 
| Zero no Tsukaima                     | 3       | 12        |          |          | 
| Zero no Tsukaima: Futatsuki no Kishi | 1       | 1         | 2        | 1        | 
| Zero no Tsukaima: Futatsuki no Kishi | 1       | 2         | 2        | 2        | 
| Zero no Tsukaima: Futatsuki no Kishi | 1       | 3         | 2        | 3        | 
| Zero no Tsukaima: Futatsuki no Kishi | 1       | 4         | 2        | 4        | 
| Zero no Tsukaima: Futatsuki no Kishi | 1       | 5         | 2        | 5        | 
| Zero no Tsukaima: Futatsuki no Kishi | 1       | 6         | 2        | 6        | 
| Zero no Tsukaima: Futatsuki no Kishi | 1       | 7         | 2        | 7        | 
| Zero no Tsukaima: Futatsuki no Kishi | 1       | 8         | 2        | 8        | 
| Zero no Tsukaima: Futatsuki no Kishi | 1       | 9         | 2        | 9        | 
| Zero no Tsukaima: Futatsuki no Kishi | 1       | 10        | 2        | 10       | 
| Zero no Tsukaima: Futatsuki no Kishi | 1       | 11        | 2        | 11       | 
| Zero no Tsukaima: Futatsuki no Kishi | 1       | 12        | 2        | 12       | 
| Zero no Tsukaima: Princess no Rondo  | 1       | 1         | 3        | 1        | 
| Zero no Tsukaima: Princess no Rondo  | 1       | 2         | 3        | 2        | 
| Zero no Tsukaima: Princess no Rondo  | 1       | 3         | 3        | 3        | 
| Zero no Tsukaima: Princess no Rondo  | 1       | 4         | 3        | 4        | 
| Zero no Tsukaima: Princess no Rondo  | 1       | 5         | 3        | 5        | 
| Zero no Tsukaima: Princess no Rondo  | 1       | 6         | 3        | 6        | 
| Zero no Tsukaima: Princess no Rondo  | 1       | 7         | 3        | 7        | 
| Zero no Tsukaima: Princess no Rondo  | 1       | 8         | 3        | 8        | 
| Zero no Tsukaima: Princess no Rondo  | 1       | 9         | 3        | 9        | 
| Zero no Tsukaima: Princess no Rondo  | 1       | 10        | 3        | 10       | 
| Zero no Tsukaima: Princess no Rondo  | 1       | 11        | 3        | 11       | 
| Zero no Tsukaima: Princess no Rondo  | 1       | 12        | 3        | 12       | 
| Zero no Tsukaima: Princess no Rondo  | 3       | 1         | 0        | 1        | 
| Zero no Tsukaima: Princess no Rondo  | 3       | 2         | 0        | 2        | 
| Zero no Tsukaima: Princess no Rondo  | 3       | 3         | 0        | 3        | 
| Zero no Tsukaima: Princess no Rondo  | 3       | 4         | 0        | 4        | 
| Zero no Tsukaima: Princess no Rondo  | 3       | 5         | 0        | 5        | 
| Zero no Tsukaima: Princess no Rondo  | 3       | 6         | 0        | 6        | 
| Zero no Tsukaima: Princess no Rondo  | 3       | 7         | 0        | 7        | 
| Zero no Tsukaima: Princess no Rondo  | 3       | 8         | 0        | 8        | 
| Zero no Tsukaima: Princess no Rondo  | 3       | 9         |          |          | 
| Zero no Tsukaima F                   | 1       | 1         | 4        | 1        | 
| Zero no Tsukaima F                   | 1       | 2         | 4        | 2        | 
| Zero no Tsukaima F                   | 1       | 3         | 4        | 3        | 
| Zero no Tsukaima F                   | 1       | 4         | 4        | 4        | 
| Zero no Tsukaima F                   | 1       | 5         | 4        | 5        | 
| Zero no Tsukaima F                   | 1       | 6         | 4        | 6        | 
| Zero no Tsukaima F                   | 1       | 7         | 4        | 7        | 
| Zero no Tsukaima F                   | 1       | 8         | 4        | 8        | 
| Zero no Tsukaima F                   | 1       | 9         | 4        | 9        | 
| Zero no Tsukaima F                   | 1       | 10        | 4        | 10       | 
| Zero no Tsukaima F                   | 1       | 11        | 4        | 11       | 
| Zero no Tsukaima F                   | 1       | 12        | 4        | 12       |

**Comment by da3dsoul** [comment]
SELECT MainTitle, aniep.EpisodeType as AniType, aniep.EpisodeNumber as AniNumber, tvep.SeasonNumber as TvSeason, tvep.EpisodeNumber as TVNumber
FROM AniDB_Episode aniep
  INNER JOIN AniDB_Anime ani on ani.AnimeID = aniep.AnimeID
  LEFT JOIN CrossRef_AniDB_TvDB_Episode xref on xref.AniDBEpisodeID = aniep.EpisodeID
  LEFT JOIN TvDB_Episode tvep on tvep.Id = xref.TvDBEpisodeID
WHERE ani.AnimeID in (4146, 4915, 8593, 5635) AND (aniep.EpisodeType = 1 OR aniep.EpisodeType = 3)
ORDER BY ani.AnimeID, aniep.EpisodeType, aniep.EpisodeNumber


SELECT AnimeSeriesID, AnimeID, MainTitle FROM AniDB_Anime INNER JOIN AnimeSeries on AnimeID = AniDB_ID WHERE CHARINDEX('Zero no Tsukaima', MainTitle) > 0

those are the queries

**Comment by hidden4003** [comment]
|                                      |   |    |      |      | 
|--------------------------------------|---|----|------|------| 
| Zero no Tsukaima                     | 1 | 1  | 1    | 1    | 
| Zero no Tsukaima                     | 1 | 2  | 1    | 2    | 
| Zero no Tsukaima                     | 1 | 3  | 1    | 3    | 
| Zero no Tsukaima                     | 1 | 3  | 2    | 1    | 
| Zero no Tsukaima                     | 1 | 4  | 1    | 4    | 
| Zero no Tsukaima                     | 1 | 4  | 2    | 2    | 
| Zero no Tsukaima                     | 1 | 5  | 1    | 5    | 
| Zero no Tsukaima                     | 1 | 6  | 1    | 6    | 
| Zero no Tsukaima                     | 1 | 6  | 2    | 4    | 
| Zero no Tsukaima                     | 1 | 7  | 1    | 7    | 
| Zero no Tsukaima                     | 1 | 7  | 3    | 1    | 
| Zero no Tsukaima                     | 1 | 8  | 1    | 8    | 
| Zero no Tsukaima                     | 1 | 8  | 3    | 2    | 
| Zero no Tsukaima                     | 1 | 9  | 1    | 9    | 
| Zero no Tsukaima                     | 1 | 9  | 3    | 4    | 
| Zero no Tsukaima                     | 1 | 10 | 1    | 10   | 
| Zero no Tsukaima                     | 1 | 10 | 3    | 5    | 
| Zero no Tsukaima                     | 1 | 11 | 1    | 11   | 
| Zero no Tsukaima                     | 1 | 11 | 4    | 1    | 
| Zero no Tsukaima                     | 1 | 12 | 1    | 12   | 
| Zero no Tsukaima                     | 1 | 12 | 4    | 2    | 
| Zero no Tsukaima                     | 1 | 13 | 1    | 13   | 
| Zero no Tsukaima                     | 1 | 13 | 4    | 4    | 
| Zero no Tsukaima                     | 3 | 1  | 0    | 1    | 
| Zero no Tsukaima                     | 3 | 2  | 0    | 2    | 
| Zero no Tsukaima                     | 3 | 3  | 0    | 3    | 
| Zero no Tsukaima                     | 3 | 3  | 0    | 4    | 
| Zero no Tsukaima                     | 3 | 4  | 0    | 4    | 
| Zero no Tsukaima                     | 3 | 4  | 0    | 5    | 
| Zero no Tsukaima                     | 3 | 5  | 0    | 5    | 
| Zero no Tsukaima                     | 3 | 5  | 0    | 6    | 
| Zero no Tsukaima                     | 3 | 6  | 0    | 6    | 
| Zero no Tsukaima                     | 3 | 6  | 0    | 7    | 
| Zero no Tsukaima                     | 3 | 7  | 0    | 7    | 
| Zero no Tsukaima                     | 3 | 7  | 0    | 8    | 
| Zero no Tsukaima                     | 3 | 8  | 0    | 8    | 
| Zero no Tsukaima                     | 3 | 9  | NULL | NULL | 
| Zero no Tsukaima                     | 3 | 10 | NULL | NULL | 
| Zero no Tsukaima                     | 3 | 11 | NULL | NULL | 
| Zero no Tsukaima                     | 3 | 12 | NULL | NULL | 
| Zero no Tsukaima: Futatsuki no Kishi | 1 | 1  | 2    | 1    | 
| Zero no Tsukaima: Futatsuki no Kishi | 1 | 2  | 2    | 2    | 
| Zero no Tsukaima: Futatsuki no Kishi | 1 | 3  | 1    | 1    | 
| Zero no Tsukaima: Futatsuki no Kishi | 1 | 3  | 2    | 3    | 
| Zero no Tsukaima: Futatsuki no Kishi | 1 | 4  | 2    | 4    | 
| Zero no Tsukaima: Futatsuki no Kishi | 1 | 5  | 1    | 2    | 
| Zero no Tsukaima: Futatsuki no Kishi | 1 | 5  | 2    | 5    | 
| Zero no Tsukaima: Futatsuki no Kishi | 1 | 6  | 1    | 5    | 
| Zero no Tsukaima: Futatsuki no Kishi | 1 | 6  | 2    | 6    | 
| Zero no Tsukaima: Futatsuki no Kishi | 1 | 7  | 3    | 1    | 
| Zero no Tsukaima: Futatsuki no Kishi | 1 | 7  | 2    | 7    | 
| Zero no Tsukaima: Futatsuki no Kishi | 1 | 8  | 3    | 2    | 
| Zero no Tsukaima: Futatsuki no Kishi | 1 | 8  | 2    | 8    | 
| Zero no Tsukaima: Futatsuki no Kishi | 1 | 9  | 3    | 4    | 
| Zero no Tsukaima: Futatsuki no Kishi | 1 | 9  | 2    | 9    | 
| Zero no Tsukaima: Futatsuki no Kishi | 1 | 10 | 2    | 10   | 
| Zero no Tsukaima: Futatsuki no Kishi | 1 | 10 | 4    | 1    | 
| Zero no Tsukaima: Futatsuki no Kishi | 1 | 11 | 2    | 11   | 
| Zero no Tsukaima: Futatsuki no Kishi | 1 | 11 | 4    | 2    | 
| Zero no Tsukaima: Futatsuki no Kishi | 1 | 12 | 2    | 12   | 
| Zero no Tsukaima: Futatsuki no Kishi | 1 | 12 | 4    | 4    | 
| Zero no Tsukaima: Princess no Rondo  | 1 | 1  | 3    | 1    | 
| Zero no Tsukaima: Princess no Rondo  | 1 | 2  | 3    | 2    | 
| Zero no Tsukaima: Princess no Rondo  | 1 | 3  | 1    | 1    | 
| Zero no Tsukaima: Princess no Rondo  | 1 | 3  | 3    | 3    | 
| Zero no Tsukaima: Princess no Rondo  | 1 | 4  | 3    | 4    | 
| Zero no Tsukaima: Princess no Rondo  | 1 | 5  | 1    | 2    | 
| Zero no Tsukaima: Princess no Rondo  | 1 | 5  | 3    | 5    | 
| Zero no Tsukaima: Princess no Rondo  | 1 | 6  | 1    | 5    | 
| Zero no Tsukaima: Princess no Rondo  | 1 | 6  | 3    | 6    | 
| Zero no Tsukaima: Princess no Rondo  | 1 | 7  | 2    | 1    | 
| Zero no Tsukaima: Princess no Rondo  | 1 | 7  | 3    | 7    | 
| Zero no Tsukaima: Princess no Rondo  | 1 | 8  | 2    | 2    | 
| Zero no Tsukaima: Princess no Rondo  | 1 | 8  | 3    | 8    | 
| Zero no Tsukaima: Princess no Rondo  | 1 | 9  | 2    | 4    | 
| Zero no Tsukaima: Princess no Rondo  | 1 | 9  | 3    | 9    | 
| Zero no Tsukaima: Princess no Rondo  | 1 | 10 | 3    | 10   | 
| Zero no Tsukaima: Princess no Rondo  | 1 | 10 | 4    | 1    | 
| Zero no Tsukaima: Princess no Rondo  | 1 | 11 | 3    | 11   | 
| Zero no Tsukaima: Princess no Rondo  | 1 | 11 | 4    | 2    | 
| Zero no Tsukaima: Princess no Rondo  | 1 | 12 | 3    | 12   | 
| Zero no Tsukaima: Princess no Rondo  | 1 | 12 | 4    | 4    | 
| Zero no Tsukaima: Princess no Rondo  | 3 | 1  | 0    | 1    | 
| Zero no Tsukaima: Princess no Rondo  | 3 | 2  | 0    | 2    | 
| Zero no Tsukaima: Princess no Rondo  | 3 | 3  | 0    | 3    | 
| Zero no Tsukaima: Princess no Rondo  | 3 | 4  | 0    | 4    | 
| Zero no Tsukaima: Princess no Rondo  | 3 | 5  | 0    | 5    | 
| Zero no Tsukaima: Princess no Rondo  | 3 | 6  | 0    | 6    | 
| Zero no Tsukaima: Princess no Rondo  | 3 | 7  | 0    | 7    | 
| Zero no Tsukaima: Princess no Rondo  | 3 | 8  | 0    | 8    | 
| Zero no Tsukaima: Princess no Rondo  | 3 | 9  | NULL | NULL | 
| Zero no Tsukaima F                   | 1 | 1  | 1    | 13   | 
| Zero no Tsukaima F                   | 1 | 1  | 4    | 1    | 
| Zero no Tsukaima F                   | 1 | 2  | 1    | 1    | 
| Zero no Tsukaima F                   | 1 | 2  | 4    | 2    | 
| Zero no Tsukaima F                   | 1 | 3  | 1    | 1    | 
| Zero no Tsukaima F                   | 1 | 3  | 1    | 2    | 
| Zero no Tsukaima F                   | 1 | 3  | 4    | 3    | 
| Zero no Tsukaima F                   | 1 | 4  | 1    | 3    | 
| Zero no Tsukaima F                   | 1 | 4  | 4    | 4    | 
| Zero no Tsukaima F                   | 1 | 5  | 1    | 2    | 
| Zero no Tsukaima F                   | 1 | 5  | 1    | 5    | 
| Zero no Tsukaima F                   | 1 | 5  | 4    | 5    | 
| Zero no Tsukaima F                   | 1 | 6  | 1    | 5    | 
| Zero no Tsukaima F                   | 1 | 6  | 1    | 6    | 
| Zero no Tsukaima F                   | 1 | 6  | 4    | 6    | 
| Zero no Tsukaima F                   | 1 | 7  | 1    | 7    | 
| Zero no Tsukaima F                   | 1 | 7  | 2    | 1    | 
| Zero no Tsukaima F                   | 1 | 7  | 4    | 7    | 
| Zero no Tsukaima F                   | 1 | 8  | 1    | 8    | 
| Zero no Tsukaima F                   | 1 | 8  | 2    | 2    | 
| Zero no Tsukaima F                   | 1 | 8  | 4    | 8    | 
| Zero no Tsukaima F                   | 1 | 9  | 1    | 9    | 
| Zero no Tsukaima F                   | 1 | 9  | 2    | 4    | 
| Zero no Tsukaima F                   | 1 | 9  | 4    | 9    | 
| Zero no Tsukaima F                   | 1 | 10 | 1    | 10   | 
| Zero no Tsukaima F                   | 1 | 10 | 3    | 1    | 
| Zero no Tsukaima F                   | 1 | 10 | 4    | 10   | 
| Zero no Tsukaima F                   | 1 | 11 | 1    | 11   | 
| Zero no Tsukaima F                   | 1 | 11 | 3    | 2    | 
| Zero no Tsukaima F                   | 1 | 11 | 4    | 11   | 
| Zero no Tsukaima F                   | 1 | 12 | 1    | 12   | 
| Zero no Tsukaima F                   | 1 | 12 | 3    | 4    | 
| Zero no Tsukaima F                   | 1 | 12 | 4    | 12   |

**Comment by da3dsoul** [comment]
https://github.com/ShokoAnime/ShokoServer/commit/aae50a8423266ac96e63fa3aaf8429d1c8ba03f7

**Comment by hidden4003** [comment]
| MainTitle                            | AniType | AniNumber | TVSeason | TVNumber | 
|----------------------------------------|-----|------|--------|--------| 
| "Zero no Tsukaima"                     | "1" | "1"  | "NULL" | "NULL" | 
| "Zero no Tsukaima"                     | "1" | "2"  | "NULL" | "NULL" | 
| "Zero no Tsukaima"                     | "1" | "3"  | "NULL" | "NULL" | 
| "Zero no Tsukaima"                     | "1" | "4"  | "NULL" | "NULL" | 
| "Zero no Tsukaima"                     | "1" | "5"  | "NULL" | "NULL" | 
| "Zero no Tsukaima"                     | "1" | "6"  | "NULL" | "NULL" | 
| "Zero no Tsukaima"                     | "1" | "7"  | "NULL" | "NULL" | 
| "Zero no Tsukaima"                     | "1" | "8"  | "NULL" | "NULL" | 
| "Zero no Tsukaima"                     | "1" | "9"  | "NULL" | "NULL" | 
| "Zero no Tsukaima"                     | "1" | "10" | "NULL" | "NULL" | 
| "Zero no Tsukaima"                     | "1" | "11" | "NULL" | "NULL" | 
| "Zero no Tsukaima"                     | "1" | "12" | "NULL" | "NULL" | 
| "Zero no Tsukaima"                     | "1" | "13" | "NULL" | "NULL" | 
| "Zero no Tsukaima"                     | "3" | "1"  | "NULL" | "NULL" | 
| "Zero no Tsukaima"                     | "3" | "2"  | "NULL" | "NULL" | 
| "Zero no Tsukaima"                     | "3" | "3"  | "NULL" | "NULL" | 
| "Zero no Tsukaima"                     | "3" | "4"  | "NULL" | "NULL" | 
| "Zero no Tsukaima"                     | "3" | "5"  | "NULL" | "NULL" | 
| "Zero no Tsukaima"                     | "3" | "6"  | "NULL" | "NULL" | 
| "Zero no Tsukaima"                     | "3" | "7"  | "NULL" | "NULL" | 
| "Zero no Tsukaima"                     | "3" | "8"  | "NULL" | "NULL" | 
| "Zero no Tsukaima"                     | "3" | "9"  | "NULL" | "NULL" | 
| "Zero no Tsukaima"                     | "3" | "10" | "NULL" | "NULL" | 
| "Zero no Tsukaima"                     | "3" | "11" | "NULL" | "NULL" | 
| "Zero no Tsukaima"                     | "3" | "12" | "NULL" | "NULL" | 
| "Zero no Tsukaima: Futatsuki no Kishi" | "1" | "1"  | "2"    | "1"    | 
| "Zero no Tsukaima: Futatsuki no Kishi" | "1" | "2"  | "2"    | "2"    | 
| "Zero no Tsukaima: Futatsuki no Kishi" | "1" | "3"  | "2"    | "3"    | 
| "Zero no Tsukaima: Futatsuki no Kishi" | "1" | "4"  | "2"    | "4"    | 
| "Zero no Tsukaima: Futatsuki no Kishi" | "1" | "5"  | "2"    | "5"    | 
| "Zero no Tsukaima: Futatsuki no Kishi" | "1" | "6"  | "2"    | "6"    | 
| "Zero no Tsukaima: Futatsuki no Kishi" | "1" | "7"  | "2"    | "7"    | 
| "Zero no Tsukaima: Futatsuki no Kishi" | "1" | "8"  | "2"    | "8"    | 
| "Zero no Tsukaima: Futatsuki no Kishi" | "1" | "9"  | "2"    | "9"    | 
| "Zero no Tsukaima: Futatsuki no Kishi" | "1" | "10" | "2"    | "10"   | 
| "Zero no Tsukaima: Futatsuki no Kishi" | "1" | "11" | "2"    | "11"   | 
| "Zero no Tsukaima: Futatsuki no Kishi" | "1" | "12" | "2"    | "12"   | 
| "Zero no Tsukaima: Princess no Rondo"  | "1" | "1"  | "3"    | "1"    | 
| "Zero no Tsukaima: Princess no Rondo"  | "1" | "2"  | "3"    | "2"    | 
| "Zero no Tsukaima: Princess no Rondo"  | "1" | "3"  | "3"    | "3"    | 
| "Zero no Tsukaima: Princess no Rondo"  | "1" | "4"  | "3"    | "4"    | 
| "Zero no Tsukaima: Princess no Rondo"  | "1" | "5"  | "3"    | "5"    | 
| "Zero no Tsukaima: Princess no Rondo"  | "1" | "6"  | "3"    | "6"    | 
| "Zero no Tsukaima: Princess no Rondo"  | "1" | "7"  | "3"    | "7"    | 
| "Zero no Tsukaima: Princess no Rondo"  | "1" | "8"  | "3"    | "8"    | 
| "Zero no Tsukaima: Princess no Rondo"  | "1" | "9"  | "3"    | "9"    | 
| "Zero no Tsukaima: Princess no Rondo"  | "1" | "10" | "3"    | "10"   | 
| "Zero no Tsukaima: Princess no Rondo"  | "1" | "11" | "3"    | "11"   | 
| "Zero no Tsukaima: Princess no Rondo"  | "1" | "12" | "3"    | "12"   | 
| "Zero no Tsukaima: Princess no Rondo"  | "3" | "1"  | "0"    | "1"    | 
| "Zero no Tsukaima: Princess no Rondo"  | "3" | "2"  | "0"    | "2"    | 
| "Zero no Tsukaima: Princess no Rondo"  | "3" | "3"  | "0"    | "3"    | 
| "Zero no Tsukaima: Princess no Rondo"  | "3" | "4"  | "0"    | "4"    | 
| "Zero no Tsukaima: Princess no Rondo"  | "3" | "5"  | "0"    | "5"    | 
| "Zero no Tsukaima: Princess no Rondo"  | "3" | "6"  | "0"    | "6"    | 
| "Zero no Tsukaima: Princess no Rondo"  | "3" | "7"  | "0"    | "7"    | 
| "Zero no Tsukaima: Princess no Rondo"  | "3" | "8"  | "0"    | "8"    | 
| "Zero no Tsukaima: Princess no Rondo"  | "3" | "9"  | "NULL" | "NULL" | 
| "Zero no Tsukaima F"                   | "1" | "1"  | "4"    | "1"    | 
| "Zero no Tsukaima F"                   | "1" | "2"  | "4"    | "2"    | 
| "Zero no Tsukaima F"                   | "1" | "3"  | "4"    | "3"    | 
| "Zero no Tsukaima F"                   | "1" | "4"  | "4"    | "4"    | 
| "Zero no Tsukaima F"                   | "1" | "5"  | "4"    | "5"    | 
| "Zero no Tsukaima F"                   | "1" | "6"  | "4"    | "6"    | 
| "Zero no Tsukaima F"                   | "1" | "7"  | "4"    | "7"    | 
| "Zero no Tsukaima F"                   | "1" | "8"  | "4"    | "8"    | 
| "Zero no Tsukaima F"                   | "1" | "9"  | "4"    | "9"    | 
| "Zero no Tsukaima F"                   | "1" | "10" | "4"    | "10"   | 
| "Zero no Tsukaima F"                   | "1" | "11" | "4"    | "11"   | 
| "Zero no Tsukaima F"                   | "1" | "12" | "4"    | "12"   |

**Comment by hidden4003** [comment]
while trying to force update anidb info I've noticed that it is super slow 
```
[2018-04-17 22:47:51:490] Trace|BaseCachedRepository`2.Delete => BaseCachedRepository`2.Delete => <>c.<.ctor>b__7_1 Updating group stats by anime from CrossRef_File_EpisodeRepository.Delete: 5635
[2018-04-17 22:47:57:974] Info|<>c.<.ctor>b__7_1 => SVR_AniDB_Anime.UpdateStatsByAnimeID => SVR_AnimeSeries.UpdateStats Starting Updating STATS for SERIES 276 (True - True - True)
```

**Comment by hidden4003** [comment]
force update Anidb didn't fix it

**Comment by da3dsoul** [comment]
For the sake of documentation, this was found to not have a link (Anime to Series)

**Comment by hidden4003** [comment]
/api/tvdb/regenlinks still took 10 minutes

**Comment by da3dsoul** [comment]
Does it still

**Comment by hidden4003** [comment]
It means something is very broken performance wise

**Comment by da3dsoul** [comment]
Saves and deletes take the longest. I don't why all of a sudden those are super slow
