### ISSUE TITLE
Docker path issue, unable to start server

### ISSUE THREAD

**Issue by nspiegl** [ShokoAnime/ShokoServer#743]
## VERSION INFORMATION

Server Version: 3.9.0

Desktop Version: 3.9.0

## LOG FILE

```
Before I changed the path >>
-------------------------------------
OLD SHOKO INSTALL DETECTED

Please change the volume for shoko
OLD directory: /root/.shoko
New directory: /home/shoko/.shoko
-------------------------------------

After I made the recommended change >>

12:52:00| --- Starting Server: New Version detected. Database Backup in progress...

12:52:00| --- Starting Server: New Version detected. Database Backup in progress...

12:52:00| --- Could not init database: System.IO.DirectoryNotFoundException: Could not find a part of the path "/root/.shoko/Shoko.CLI/DatabaseBackup/_080_201806231252.sql".
```

## DESCRIPTION

The settings path has been changed but it seems there is still some things referencing the old path. Hopefully I should be able to work around it by tying to map another location.

**Comment by Cazzar** [comment]
You need to update the settings.json for the following keys:

`ImagesPath`, `MySqliteDirectory`, `MyListDirectory` & `AnimeXmlDirectory`

**Comment by nspiegl** [comment]
Ah I see, thanks @Cazzar . There is also "DatabaseBackupDirectory": "/root/.shoko/Shoko.CLI/DatabaseBackup"

I will go through and change them all.

**Comment by Cazzar** [comment]
Cool, if you need any help feel free to pop in the discord, I can help there too.
