### ISSUE TITLE
Episodes are randomly set to "not watched"

### ISSUE THREAD

**Issue by claudiogenta** [ShokoAnime/ShokoServer#745]
## VERSION INFORMATION

Server Version: 3.8.3.42091 (from about dialog)

Desktop Version: 3.8.3.0 (from executable version)

## DESCRIPTION

Once every 2/3 days, I find a number of random episodes (from random series) which are switched to "not watched" (they were watched before). I notice since they are put in the "continue watching" list in the dashboard. The affected series could be either something I have seen 2 days ago, or something I'm not touching in ages.

## STEPS TO REPRODUCE

I have no way to reproduce this, it simply happens every 2/3 days. I shut down the server every evening and start it again in the morning. Almost always I close the server by right clicking in the taskbar icon and choosing "shutdown". It happened to me in the last year at least, so I think it is an issue which is not tied to the last versions

**Comment by da3dsoul** [comment]
Randomly is rarely a circumstance in computing.
Things I would try:
In Desktop, go to Settings -> AniDB
Uncheck Read Unwatched
Set Automatically Sync MyList Information to Never
Set Automatically Get MyList Stats from AniDB to Never

Those are only useful if you manually set states on AniDB's website

**Comment by da3dsoul** [comment]
I also recommend updating to 3.9, as I'm always fixing stuff.

**Comment by claudiogenta** [comment]
Thank you very much for the immediate answer.
I've tried to set the option you suggested as well as updating to 3.9

In a few days I'll now if it works

Thanks
Claudio

Il giorno dom 1 lug 2018 alle ore 10:44 da3dsoul <notifications@github.com>
ha scritto:

**Comment by da3dsoul** [comment]
You are welcome. Close this in a few days if you it seems to work. The Sync MyList command doesn't always work perfectly.
