### ISSUE TITLE
Error when recreating groups

### ISSUE THREAD

**Issue by CtrlAltDefeat94** [ShokoAnime/ShokoServer#752]
Make somethingDictionary a ConcurrentDictionary<int, ConcurrentDictionary<string, HashSet<int>>> or lock the internal dictionary and HashSet
![image](https://user-images.githubusercontent.com/5640470/43364882-b0f45032-9323-11e8-9ad7-fa4a341472c7.png)

https://gist.github.com/CtrlAltDefeat94/11155d3cb94bf1c1a1dcb72c1c8eabae

**Comment by ElementalCrisis** [comment]
Why did you create a new issue instead of using the old one?

**Comment by da3dsoul** [comment]
Because I was tired and told him to

**Comment by da3dsoul** [comment]
I don't remember if I fixed this....

**Comment by da3dsoul** [comment]
I did
