### ISSUE TITLE
Rescan files and move appropriately when they are moved on AniDB

### ISSUE THREAD

**Issue by da3dsoul** [ShokoAnime/ShokoServer#758]
This will require aid from AniDB, as I'm not sure if we receive notification of this in UPDATE or what. Regardless, it is annoying that files may be moved and we need to manually find the file and rescan it, then move it.

**Comment by da3dsoul** [comment]
I've left a post on AniDB [here](http://anidb.net/perl-bin/animedb.pl?show=84293)

**Comment by bigretromike** [comment]
This could be a game changer.
Because if there is aid on that list you can getinfo, and if not prevent from asking for it because nothing changed.

**Comment by da3dsoul** [comment]
...we wouldn't want aid. We want fid

**Comment by da3dsoul** [comment]
If it's aid, then what happens when a file in One Piece moves? We rescan every file? No we just get a list of fids and update those if we have them

**Comment by bigretromike** [comment]
yeah i meant fid, also if aid changed we would like to scan series for updated info

**Comment by da3dsoul** [comment]
We have another endpoint for that, but yeah

**Comment by revam** [comment]
Just leaving a comment for future lurkers, but this can be done by subscribing to general AniDB notifications updates in the UDP API, then reacting to the file moved notifications sent by the system.

But to do this properly we first should lay the ground work to add support for AniDB notifications. And maybe even server notifications in general and hook the AniDB notifications into the general notification system.

Or we could just do it quick and dirty and only add some code to check the AniDB notifications and react to the file move events, but that will mean we will lose any and all notifications we went through to check for file events into the void of time, lost forever in the UDP API. (The users can still check the notifications on AniDB themselves, we just can't check them in the UDP API again.)

**Comment by bigretromike** [comment]
@revam also if anidb notifications are global there could web-worker that would fetch that and those information could be fetched from cache first ? if notifications are private/account linked then sorry.

**Comment by revam** [comment]
Notifications are only through the udp api, and are tied to the user. There is no api where a "web-worker" would be useful, as we would need to coordinate it using our anidb udp api handler. Neither is there any cache for us to use, because again, the notifications are tied to the user and only (officially) accessible to us through the UDP API.

**Comment by revam** [comment]
Closed and implemented by #1129. Just forgot there was an issue for this. Thanks @Terrails for implementing it.
