### ISSUE TITLE
Ability to tweak system filters

### ISSUE THREAD

**Issue by bigretromike** [ShokoAnime/ShokoServer#760]
With `Continue Watching (System)` the down side is that you cannot edit the conditions.
For `System` filters there should be option to edit those + option to reset to default settings.

Currently when you are watching something that you didn't fully download you will lose it from there until you add missing episodes - which is bad when you watch multiply series at once.

**Comment by da3dsoul** [comment]
That is the intended functionality, but I understand why you may want to change it. This will probably not happen any time soon

**Comment by bigretromike** [comment]
just make EF working I can deal with it ;-) if that's a problem.
but yeah probably not soon, but would be a nice thing.

**Comment by ElementalCrisis** [comment]
With the filter rewrite, this is no longer an issue.
