### ISSUE TITLE
Epiodes of currently airing Shows are missing their titles

### ISSUE THREAD

**Issue by Baine** [ShokoAnime/ShokoServer#762]
## VERSION INFORMATION

Server Version: 
5dd125315b1be40c7d782c57e4ffc97145cf25bb

Desktop Version: 
e60bea38c4ee6788d251802cc102b8ff5f607eef

## LOG FILE

no related log entries, omitted

## DESCRIPTION

Currently airing animes are missing their updated episode titles.
This is due to the fact, that only the first 200 returned IDs for animes with updates
(as requested via AniDB API) are processed, none after that.

## STEPS TO REPRODUCE

1. Have currently airing anime in shoko, for which the titles are named "Episode X" on their creation.
2. Wait for the episodes to get updated names on AniDB
3. ???
4. Profit (erm, Titles in Shoko not updated)

**Comment by da3dsoul** [comment]
Good to know. Documenting here as well, but if that worked, then my commit to handle updates >200 should work as well

**Comment by da3dsoul** [comment]
May be related to #734 and both may be fixed

**Comment by bigretromike** [comment]
Maybe cache is not populated after update ? does this happens after update and after restarting server?

**Comment by da3dsoul** [comment]
... Read and click links. This doesn't need investigation

**Comment by bigretromike** [comment]
yes senpai, I will do as you say

**Comment by da3dsoul** [comment]
This might be fixed now

**Comment by ElementalCrisis** [comment]
This is no longer an issue; API returns the series and episode name.
