### ISSUE TITLE
Cache not updated when renaming files

### ISSUE THREAD

**Issue by da3dsoul** [ShokoAnime/ShokoServer#763]
It took a bit to diagnose, and it could be wrong. A file is imported, it is renamed, then it says that there is no change from two clearly different filenames. It tries to move, but can't find the old path. Restarting the server makes it playable (name is updated), but it is still not moved.

**Comment by da3dsoul** [comment]
Possibly fixed in hotfix branch now

**Comment by bigretromike** [comment]
Similar but I don't use renaming. 

On November 1, 2018 1:09:15 AM GMT+01:00, da3dsoul <notifications@github.com> wrote:
>It took a bit to diagnose, and it could be wrong. A file is imported,
>it is renamed, then it says that there is no change from two clearly
>different filenames. It tries to move, but can't find the old path.
>Restarting the server makes it playable (name is updated), but it is
>still not moved.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ShokoAnime/ShokoServer/issues/763

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by da3dsoul** [comment]
What? I'm not talking about you. It's an issue that a user reported

**Comment by revam** [comment]
Was this ever fixed? @da3dsoul

**Comment by da3dsoul** [comment]
I think so. I've not heard of it being an issue
