### ISSUE TITLE
"Set file as watched if episode is watched" - Setting not working

### ISSUE THREAD

**Issue by xmodx10** [ShokoAnime/ShokoServer#764]
## VERSION INFORMATION

Server Version: 3.9.3

Desktop Version: 3.9.3

## DESCRIPTION

When disabling the option "Set file as watched if episode is watched" my files are still getting marked as watched.

![image](https://user-images.githubusercontent.com/25097788/47999957-15384a80-e13f-11e8-9584-df00cb3cdd3e.png)

## STEPS TO REPRODUCE

1. Disable "Set file as watched if episode is watched" in shoko desktop client
2. Import new files against an episode that is already marked as watched
3. Files are now marked as watched when they should not be

**Comment by da3dsoul** [comment]
I'm still figuring out who to punch and/or teach English and UI design. I'll look at it in a moment

**Comment by da3dsoul** [comment]
Huh.... Apparently it's been there for more than 2 years, and I never noticed. It's funny because the server functionality was written by me...only a few months ago, and I didn't know that a setting existed.

**Comment by da3dsoul** [comment]
It is in fact older than the GitHub account.... I am afraid that I can't punch the original author. He's not easy to contact.

**Comment by da3dsoul** [comment]
I implemented it for the first time on June 14th of this year. It is fixed for 3.9.4. Now I need to fix it for 4.0

**Comment by da3dsoul** [comment]
Done.

**Comment by xmodx10** [comment]
Thanks :)
