### ISSUE TITLE
Entire Series being marked as unwatched "randomly"

### ISSUE THREAD

**Issue by da3dsoul** [ShokoAnime/ShokoServer#765]
Obviously, in computing, there is no such thing as random, but I've yet to figure out the trigger.
There is no useful mention in the logs when it happens.

Interestingly, it does not erase ResumeTime, only WatchedDate, which means that it is not calling ToggleWatched

This could be several things, some of which are completely unrelated to Shoko.
- I moved to SQL Server on Linux. That could've done it, as who knows what bugs might exist there.
- I separated my storage into a samba share on a Linux machine. So, far, I've not seen any issues, but who knows.
- I updated ShokoServer on my Desktop to latest hotfix commit, was previously at the introduction to File Modified checking
- I got a new job. Not related at all, but it happened

Has anyone else experienced this recently? It happens to new shows more, so I wonder if it's on info update.

**Comment by bigretromike** [comment]
maybe if its for new, you 'cache' or 'save' status in db, but when its updated info (the one that trigger once per 24h) overwrite status too ?

**Comment by da3dsoul** [comment]
It's probably SQL Server on Linux.
I forgot to mention, but it wipes when I restart Shoko, so it's in cache, but not persisted.

**Comment by da3dsoul** [comment]
I fixed this a while back. It was an error with updating anime erasing episode info, and in turn the user data for episodes, as well
