### ISSUE TITLE
MediaInfo Issues with DTS

### ISSUE THREAD

**Issue by da3dsoul** [ShokoAnime/ShokoServer#778]
This isn't me reporting it. I know it's there.

"
Dear MediaInfo users (and developers!),

Due to the increasing complexity, while keeping compatibility with legacy decoders, of audio formats, the way MediaInfo was displaying audio related information was worse and worse.
This was actually becoming difficult when we implement a better support of E-AC-3 in Bluray (mixed with core AC-3) and also Atmos (can be in E-AC-3, or TrueHD, TrueHd may be mixed with AC-3 or alone...), and DTS-HD features were not well displayed enough.

We change how we display formats with support of legacy decoders:
- the Format line in the text output contains now the name of the base format + list of features needed for outputting the best result.
- the "Format" field in XML or API (or "full" text output) contains the base format, "Format_AdditionalFeatures" field in XML or API contains the list of features, "Format/String" for the sum of both.
- Note that there are sometimes some differences between "Format/String" and the 2 other fields for commercial reasons.
- "Profile" field has changed for AAC, now contains the profile/level as found in MP4_IOD_Tag MP4 descriptor.
- We don't display anymore by default information about how legacy decoders would play the file.
- We change the way we display channel layout, with a list of channels. The previous method was not sustainable with the incoming 3D audio (16 or 24 channels). Note that issue with having channel names is that each format stipulates different channel names, we listed the mapping we do at https://mediaarea.net/AudioChannelLayout . Channel layout names will be in MediaInfo 18.08 and above, with a list ordered by the expected output order from the decoder, the former method is still available with "full" text, XML or API (list is ordered by "layer" so comparison is doable between formats, but similar channels have the same name and/or it is not well implemented, be careful with this field if you work with 16- or 24-channel content)
- We do the difference between technical name and the marketing name, e.g. "E-AC-3 JOC" for Dolby Atmos in E-AC-3, "MLP FBA" for TrueHD and "MLP FBA 16ch" for Atmos in TrueHD.
- We support now the channel configuration and the count of objects in an Atmos stream, either in E-AC-3 or TrueHD. But we don't "merge" the Atmos channels in the core channel count, we display Atmos channel info in separate fields.

Example of new output with a Dolby Atmos "9.1.4" stream with 1 dynamic object:
```
There was stuff here
```
Most of changes are reversible through options (" --File_HighestFormat=0 --File_ChannelLayout=0 --LegacyStreamDisplay=1" on the command line) but I hope that these option are used not so much.

We would like that you test the development snapshots at https://mediaarea.net/download/snaps...mediainfo-gui/ and also check the channel layout mapping at https://mediaarea.net/AudioChannelLayout ; due to sponsors behind these changes (they have priority), we will not change a lot the output but we would like to anticipate issues and bugs for advanced users like people here before we do a more public release.
"

https://forum.doom9.org/showthread.php?s=10650f142c86979faa5e964a8bef2f6c&p=1849644#post1849644

**Comment by da3dsoul** [comment]
I previously discovered it when writing Nakamori. It said 24 channels, and I was like WTF no?

**Comment by ElementalCrisis** [comment]
@da3dsoul still an issue?

**Comment by da3dsoul** [comment]
No longer relevant
