### ISSUE TITLE
Expand api call ep/getbyfullpath to return file path/multiple files

### ISSUE THREAD

**Issue by Suika** [ShokoAnime/ShokoServer#781]
The API call `ep/getbyfilename` is limited to only a file name.
If the there are multiple files named `E1.mp4` only the first result will be returned as the function [GetByFilename](https://github.com/ShokoAnime/ShokoServer/blob/master/Shoko.Server/Repositories/Cached/AnimeEpisodeRepository.cs#L98) only returns first found result.

I would suggest to extend the API with the call `ep/getbyfullpath`, as it would limit the request to one specific file and allow precise extraction of information.

Or add an extra query option to the `ep/getbyfilename` which would return **ALL FILES** that match the name and return the file path to each file.

**Comment by Cazzar** [comment]
You can now do this by specifying the `api-version: 2.1:` header to the `/api/ep/getbyfilename` 

It will return an array of all matches.
