### ISSUE TITLE
docker error: mono_w32file_find_first: error creating find handle

### ISSUE THREAD

**Issue by Andy2244** [ShokoAnime/ShokoServer#782]
## VERSION INFORMATION

Server Version:  3.9.4

## LOG FILE
```
-------------------------------------,
User uid:    1000,
User gid:    100,
-------------------------------------,

mono_w32file_find_first: error creating find handle,
Stacktrace:,
```
## DESCRIPTION

A month ago the docker version just stopped starting with the above error.

## STEPS TO REPRODUCE
Docker version: 18.06.2

Created via:
`docker create --name=shoko --restart unless-stopped --network=host -v shoko_config:/home/shoko/.shoko -v shoko_webui:/usr/src/app/build/webui -v /mnt:/mnt cazzar/shokoserver:v3.9.4`

Started via:
`docker start -a shoko`

Environment:
Host OS: Win10 Pro 1809 via a HyperV (config 9.0) VM
VM OS: ClearLinux distro (29440/HyperV version)

**Comment by Cazzar** [comment]
Did you previously create `shoko_config` and `shoko_webui` as directories, or did you let docker create them?

Since it will default as files in that format, assuming it is passing as a local file.

Or are they created as a volume within docker?
plus webui is optional, as it comes preinstalled.

Feel free to jump on discord and I can help out btw

**Comment by Andy2244** [comment]
> Or are they created as a volume within docker?
I created them via `docker volume create` and i think docker by default via `-v` will create volumes.

PS: I just accidentally pruned my volumes, while having no shoko container created. Was trying the daily version and removed it than pruned... now my config + db is gone :)
Trying to recover or setup all from scratch and will report back.

**Comment by Cazzar** [comment]
Yeah, that's real fun, had to do with my mysql db at one point, running those commands and looking at docker inspect ran fine on my ArchLinux box, creating as volumes.

**Comment by Andy2244** [comment]
Ok here is what i got without any external volumes:
`docker run --rm -ti --name=shoko --network=host cazzar/shokoserver:v3.9.4`

```
-------------------------------------,
User uid:    1000,
User gid:    100,
-------------------------------------,
,
*** Error in `mono': corrupted double-linked list: 0x0000000002c91820 ***,
Stacktrace:,
,
mono_w32file_find_first: error creating find handle,
```

**Comment by Andy2244** [comment]
Ok seems to-be some weird mono/docker/vm problem, will fiddle around with different mono versions for the docker file and see if this fixes it and report back.

**Comment by Cazzar** [comment]
Careful for the latest compile, since mono doesn't like to build it.

**Comment by Andy2244** [comment]
ok updated docker to `Docker version 18.09.6, build 481bc77`
now `cazzar/shokoserver:daily` starts, while `cazzar/shokoserver:v3.9.4` still fails, via:
`docker run --rm -ti --name=shoko cazzar/shokoserver:daily`

What mono version is daily using?

**Comment by Cazzar** [comment]
```FROM mono:5.20```
Though 3.9.4 should work fine... could be an old bug that was affecting your system, as we had used an outdated version for a while, due to a bug with newer (which seems to be fixed)

**Comment by Andy2244** [comment]
ok tested all docker versions, maybe this helps on what mono versions causes the problem:
3.8.2 -> fail
3.8.3 -> fail
3.9.0 -> ok
3.9.1 -> fail
3.9.2 -> fail
3.9.3 -> fail
3.9.4 -> fail
daily -> ok

**Comment by Andy2244** [comment]
Since 3.9.5 uses mono 5.20, which fixes this issue i'm closing this.
