### ISSUE TITLE
Avdump not working (docker)

### ISSUE THREAD

**Issue by Dexil123** [ShokoAnime/ShokoServer#784]
I keep getting error messages every time I want to dump something using latest docker version.

`<?xml version="1.0" encoding="utf-8"?>
<System.DllNotFoundException>
  <Message>libMediaInfo_x64</Message>
  <StackTrace>
    <Frame>at (wrapper managed-to-native) AVDump2Lib.InfoGathering.Parser.MediaInfoLib.MediaInfo_x64.MediaInfo_Delete(intptr)</Frame>
    <Frame>at AVDump2Lib.InfoGathering.Parser.MediaInfoLib.MediaInfo_x64.Finalize () [0x00000] in &lt;9f7cf55ec9da492d90922290dc7b7e25&gt;:0</Frame>
  </StackTrace>
</System.DllNotFoundException>`

**Comment by Cazzar** [comment]
What tag on docker are you using right now?

**Comment by Dexil123** [comment]
Daily



Verzonden vanaf mijn Samsung Galaxy-smartphone.


-------- Oorspronkelijk bericht --------
Van: Cayde Dixon <notifications@github.com>
Datum: 30-05-19 12:05 (GMT+01:00)
Aan: ShokoAnime/ShokoServer <ShokoServer@noreply.github.com>
Cc: Dexil123 <dexil_me@hotmail.com>, Author <author@noreply.github.com>
Onderwerp: Re: [ShokoAnime/ShokoServer] Avdump not working (docker) (#784)


What tag on docker are you using right now?

**Comment by Cazzar** [comment]
I just rebuilt the daily tag as I was having another error but testing with that version seems to work fine, are you able to try pulling the latest version?

**Comment by Dexil123** [comment]
Same problem, I have to say though. I can't remember AVdump ever working for me since I have used docker. 

`<?xml version="1.0" encoding="utf-8"?>
<System.DllNotFoundException>
  <Message>libMediaInfo_x64</Message>
  <StackTrace>
    <Frame>at (wrapper managed-to-native) AVDump2Lib.InfoGathering.Parser.MediaInfoLib.MediaInfo_x64.MediaInfo_Delete(intptr)</Frame>
    <Frame>at AVDump2Lib.InfoGathering.Parser.MediaInfoLib.MediaInfo_x64.Finalize () [0x00000] in &lt;9f7cf55ec9da492d90922290dc7b7e25&gt;:0</Frame>
  </StackTrace>
</System.DllNotFoundException>`

**Comment by Dexil123** [comment]
Okay, I managed to solve it. It was a specific issue with my system. noexec needs to be replace in Fstab. Plex has the same issue with transcoding.  

https://forums.plex.tv/t/solution-conversion-failed-the-transcoder-exited-due-to-an-error/234363/317
