### ISSUE TITLE
`Continue watching` group is not recalculating

### ISSUE THREAD

**Issue by bigretromike** [ShokoAnime/ShokoServer#788]
I have been using: daily build (https://github.com/ShokoAnime/ShokoServer/commit/58ec14edc3914349e0ec36c3e42d8901cc40c411) 

Whenever I watch episode of new series it does not get pulled into `Continue Watching` group.

I double check its same for apiv2 and ShokoDesktop.

I don't know if its limited to only `Continue Watching` group/filter or to all of them.

edit: restarts/reboots don't fix the issue.

**Comment by da3dsoul** [comment]
You closed it. What was it?

**Comment by bigretromike** [comment]
> 
> 
> You closed it. What was it?

A simple error from my end, I was looking for different name then it was displayed as.

**Comment by bigretromike** [comment]
Oh, yeah. It is a issue, I'm watching second season of Kuroko No Baske, but only first season is in `Continue Watching' so my bad, it is an issue;

**Comment by bigretromike** [comment]
@da3dsoul you asked for details.
What I expect:
- mark video as watched
- that series should now be in 'continue watching'

What happens instead:
- mark video as watched
- series is not in 'continue watching' even after closing both server/kodi.

**Comment by bigretromike** [comment]
fix'd
