### ISSUE TITLE
Recently Added /apiv2/ return only newly added series instead of episodes from owned series

### ISSUE THREAD

**Issue by bigretromike** [ShokoAnime/ShokoServer#789]
/api/ should return also series (or even better episodes) that were added even if series for those episodes was already in database.

Currently it returns only series that were added but weren't in database already.

**Comment by da3dsoul** [comment]
That's different. Apiv2 only provides the filter. APIv3 will provide both in a separate endpoint to avoid dependency on the filter existing.

**Comment by bigretromike** [comment]
Is the endpoint for apiv3 ready?

**Comment by da3dsoul** [comment]
Nope

**Comment by bigretromike** [comment]
So still requesting. No matter if thats for v2 or v3.
Also I probably quicker add it to v2 anyway.

**Comment by da3dsoul** [comment]
I noticed that it doesn't give proper results, though

**Comment by revam** [comment]
> Is the endpoint for apiv3 ready?

It exists for the dashboard

@bigretromike
