### ISSUE TITLE
Unable to install/run shoko in win server 2012

### ISSUE THREAD

**Issue by Pontuzz** [ShokoAnime/ShokoServer#792]
Hi. I recently tried to install shoko 3.9.5 from version 3.9.4. 
Now the program refuses to start. 

Running on windows server 2012 it gives me the following error: 

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	ShokoServer.exe
  Problem Signature 02:	3.9.5.43053
  Problem Signature 03:	5d355dca
  Problem Signature 04:	mscorlib
  Problem Signature 05:	4.7.3416.0
  Problem Signature 06:	5cabfaa3
  Problem Signature 07:	1099
  Problem Signature 08:	96
  Problem Signature 09:	System.FormatException
  OS Version:	6.3.9600.2.0.0.400.8
  Locale ID:	1053
  Additional Information 1:	46a1
  Additional Information 2:	46a18fad94cf0815e071819dd10d144d
  Additional Information 3:	bbc4
  Additional Information 4:	bbc4abfbe4dccbf55b36d7c6443f1500

I've tried running as admin both the install and the program itself. Clean install of shoko etc. 

I also noticed a CMD window pop up during install and it seemed to be referencing inheritance. 
This does not occur when installing / running on win10 as far as I can tell.

**Comment by da3dsoul** [comment]
What's your system locale?

**Comment by Pontuzz** [comment]
> What's your system locale?

My system locale is: 

LCID             Name             DisplayName
----             ----             -----------
1053             sv-SE            Swedish (Sweden)

**Comment by da3dsoul** [comment]
Okay. We've had this reported before, and it complains about locale, but knowing which ones helps figure out why.

**Comment by Cazzar** [comment]
Has this been tested with the latest daily?
Since I resolved an issue like this

**Comment by Pontuzz** [comment]
I downloaded a fresh copy of the daily just now. 
Same CMD window shows up during install, it runs without error and then closes. 

Running shoko after the install results in the same error as before. 

What I find strange is that it worked perfectly with server 2012 in version 3.9.4

**Comment by Pontuzz** [comment]
I seem to have solved the issue. 3.9.5 now runs.
The solution was deleting the contents of program data/shokoserver
