### ISSUE TITLE
Image API has been changed

### ISSUE THREAD

**Issue by bigretromike** [ShokoAnime/ShokoServer#795]
For as long as remamber this link would worked:
~~http://<shoko_ip>:8111/api/image/Shoko/Static/plex_404.png~~
http://<shoko_ip>:8111/api/image/support/plex_404.png   <-- this should work, but it doesn't 

~~For some time now it doesn't, where is this resource placed now ?~~
the url constructor is corrupted and returns half v2 half v3 value for url which is unavailable 
also the apiv2 url is parsed by apiv3 helper

**Comment by bigretromike** [comment]
Also this value is return from shokoserver itself, so if should work or the return value should be changed

**Comment by Cazzar** [comment]
What "value" is returned?

**Comment by bigretromike** [comment]
`url=/api/image/Shoko/Static/plex_404.png`

**Comment by bigretromike** [comment]
Also its included with art that do exist there they should only be added where there was missing art.

**Comment by bigretromike** [comment]
While asking 'apiv2' for data one would expect it returns apiv2 values
```
public static string ConstructSupportImageLink(HttpContext ctx, string name, bool short_url = true)
        {
            return APIHelper.ProperURL(ctx, "/api/image/support/" + name, short_url);
        }
```
This ApiHelperConstructor get overwrite by something from v3 and returns half v2 half v3 value:
v2: `/api/image/`  v3:`Shoko/Static/plex_404.png`

Which results in broken url.

**Comment by bigretromike** [comment]
```
{"errors":{"imageid":["The value 'support' is not valid."],"imageType":["The value 'plex_404.png' is not valid."]},"title":"One or more validation errors occurred.","status":400,"traceId":"0HLOMCH1HE29A:0000000D"}
```

this is return error for url that should work

**Comment by Cazzar** [comment]
I think we shouldn't actually be providing image results when we have no image to actually provide, instead we just allow whichever plugin to handle it's own invalid images.

**Comment by bigretromike** [comment]
If the picture we speak of no more then API shouldn't put that invalid URL in series,episode results, I agree 

On August 14, 2019 4:20:45 PM GMT+02:00, Cayde Dixon <notifications@github.com> wrote:
>I think we shouldn't actually be providing image results when we have
>no image to actually provide, instead we just allow whichever plugin to
>handle it's own invalid images.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ShokoAnime/ShokoServer/issues/795#issuecomment-521266307

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Cazzar** [comment]
@bigretromike What I am saying, is if it should generate "plex_404.png" it shouldn't even be provided.
Most scripts these days will go out of their way to explicitly ignore it.

**Comment by bigretromike** [comment]
Why generate, it was always a part of core. It has been with jmm long before kodi support was added. If I recall it was included in resources 

On August 14, 2019 4:29:59 PM GMT+02:00, Cayde Dixon <notifications@github.com> wrote:
>@bigretromike What I am saying, is if it should generate "plex_404.png"
>it shouldn't even be provided.
>Most scripts these days will go out of their way to explicitly ignore
>it.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/ShokoAnime/ShokoServer/issues/795#issuecomment-521270157

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by bigretromike** [comment]
if I recall it is saved as 'plex_404.bin' and it worked flawless before.

But I agree that missing images should be cared by clients.
But also endpoint is broken and helper function trigger incorrectly.
