### ISSUE TITLE
Core Net Standard guidelines 

### ISSUE THREAD

**Issue by bigretromike** [ShokoAnime/ShokoServer#797]
- Effectively keep in mind, "everything is a plugin" including AniDB
- Each thing should in general only depend on the core
- DB is core
- Discovery of files is a plugin
- you would call Shoko saying "Provide be with information from this provider"

**Comment by bigretromike** [comment]
notes from discord for future reference

**Comment by da3dsoul** [comment]
Discovery of files is not a plugin. The filesystem support is.

**Comment by bigretromike** [comment]
> 
> 
> Discovery of files is not a plugin. The filesystem support is.

that was the same I said, but Cazzar insist on it being same as Max's CloudFile

**Comment by Cazzar** [comment]
This is going to simply be closed in lieu of incremental refactors to parts we need to do major reworks on.

DI and that will help with our modularity.
