### ISSUE TITLE
Compile on Linux (by @wispers)

### ISSUE THREAD

**Issue by bigretromike** [ShokoAnime/ShokoServer#800]
1. Install the dotnet 2.2 Runtime and SDKs
2. Install Mono and it's Dev SDKs. ATM I can only confirm Mono 6 will compile.
3. Grab Shoko from https://github.com/ShokoAnime/ShokoServer :
	git clone https://github.com/ShokoAnime/ShokoServer
	cd ShokoServer
	git submodule update --init --recursive
4. Export Mono :
	export FrameworkPathOverride=/usr/lib/mono/
5  While in the ShokoServer Directory run:
	nuget restore
6. Compile With :
	msbuild /property:Configuration=CLI
	
	
	
	
	
NOTES:

~~1. I had to Remove the Com referance starting on line 1619 on Shoko.Server.csproj in /Shokoserver/Shoko.Server/~~
~~2. There is a typo on line 692 in that same file. On that line System.Configuration is written as System.configuration. This breaks compiling as Linux is case sensitive.~~

**Comment by Cazzar** [comment]
This is no longer needed.
