### ISSUE TITLE
Voting for episode is not being send to AniDB

### ISSUE THREAD

**Issue by bigretromike** [ShokoAnime/ShokoServer#803]
Voted on many-many episodes, non is send to anidb.

My profile: https://anidb.net/user/687959/vote/?do=episode&epp=30

No single vote on episode is there, and I just voted on few to test it. 

Should it send data or episode voting is local and no-one notice it ? because starting fresh shoko would nuke all votes that way.

its been confirma by @Baine that this is not send anywhere.

**Comment by bigretromike** [comment]
@da3dsoul while you on your done-shit-while-in-bed code-spree, it would be good for both shoko and nakamori that we could send our vote to anidb and not store them only in shoko cache.

**Comment by da3dsoul** [comment]
Closing this, for one because it's been known for years, but mostly because I was in the process of fixing it anyway

**Comment by bigretromike** [comment]
so maybe close it when it's working ?

**Comment by bigretromike** [comment]
so maybe close it when it's working ?

**Comment by da3dsoul** [comment]
Haha GitHub is having issues. It's fixed, but not implemented into running code. I'm closing it because I see no need to look at it when it's finished

**Comment by bigretromike** [comment]
thats what milestone are for
but do what you want.
I just would like to vote from shoko on episode and that was the issue.

**Comment by da3dsoul** [comment]
Don't worry, I'll definitely tell you when it's ready to test

**Comment by revam** [comment]
Will look at it or bug @da3dsoul about it tomorrow about it. We're past the anidb rewrite now.

**Comment by ElementalCrisis** [comment]
@revam following up.

**Comment by da3dsoul** [comment]
I honestly don't remember, but it probably works now and needs API or something

**Comment by revam** [comment]
@da3dsoul you removed the command to do it. it needs to be re-added after the anidb rewrite.

**Comment by harshithmohan** [comment]
Fixed in v3 API
