### ISSUE TITLE
Shoko server 3.9.5 crashing on start

### ISSUE THREAD

**Issue by nonoodev** [ShokoAnime/ShokoServer#804]
Hello,
I did 2 fresh installations of shoko server on a windows 2019 server.
Added a path and started the import task and after some time, the server crashes.
After this, the server keep crashing on startup.

[2019-09-25.log](https://github.com/ShokoAnime/ShokoServer/files/3651887/2019-09-25.log)

**Comment by da3dsoul** [comment]
That's a MediaInfo error. As far as I know, an update that is in the works fixes it. @Cazzar would know better

**Comment by Cazzar** [comment]
I would suggest trying the latest daily as I believe that error has already been fixed.

**Comment by nonoodev** [comment]
@Cazzar the latest daily of MediaInfo library or shoko server? (if it's mediainfo, where can I find it?)

**Comment by Cazzar** [comment]
Shoko should do.

**Comment by nonoodev** [comment]
@Cazzar it fixed it, thank you :)
