### ISSUE TITLE
TvDB Image Issues

### ISSUE THREAD

**Issue by da3dsoul** [ShokoAnime/ShokoServer#808]
Cowboy Bebop
```
06:15:07| --- Processing CommandRequest_DownloadImage: 35945
06:15:10| --- Error processing CommandRequest_DownloadImage: https://artworks.thetvdb.com/banners/1037375 (35945) - The remote server returned an error: (403) Forbidden.
06:15:12| --- Error processing CommandRequest_DownloadImage: https://artworks.thetvdb.com/banners/1037375 (35945) - The remote server returned an error: (403) Forbidden.   
06:15:12| --- Processing CommandRequest_DownloadImage: 35946
06:15:15| --- Error processing CommandRequest_DownloadImage: https://artworks.thetvdb.com/banners/1109638 (35946) - The remote server returned an error: (403) Forbidden.
06:15:17| --- Error processing CommandRequest_DownloadImage: https://artworks.thetvdb.com/banners/1109638 (35946) - The remote server returned an error: (403) Forbidden.   
06:15:17| --- Processing CommandRequest_DownloadImage: 35947
06:15:20| --- Error processing CommandRequest_DownloadImage: https://artworks.thetvdb.com/banners/1216238 (35947) - The remote server returned an error: (403) Forbidden.
06:15:22| --- Error processing CommandRequest_DownloadImage: https://artworks.thetvdb.com/banners/1216238 (35947) - The remote server returned an error: (403) Forbidden.   
06:15:22| --- Processing CommandRequest_DownloadImage: 35948
06:15:25| --- Error processing CommandRequest_DownloadImage: https://artworks.thetvdb.com/banners/1390587 (35948) - The remote server returned an error: (403) Forbidden.
06:15:27| --- Error processing CommandRequest_DownloadImage: https://artworks.thetvdb.com/banners/1390587 (35948) - The remote server returned an error: (403) Forbidden.   
06:15:27| --- Processing CommandRequest_DownloadImage: 35949
06:15:30| --- Error processing CommandRequest_DownloadImage: https://artworks.thetvdb.com/banners/1390588 (35949) - The remote server returned an error: (403) Forbidden.
06:15:32| --- Error processing CommandRequest_DownloadImage: https://artworks.thetvdb.com/banners/1390588 (35949) - The remote server returned an error: (403) Forbidden.   
06:15:32| --- Processing CommandRequest_DownloadImage: 61098
```
Getting a lot of that.

DB Table (Filename is added to `https://thetvdb.com/banners/`:

| Id | SeasonNumber | EpisodeNumber | EpisodeName | AirDate | Filename |
| :--- | :--- | :--- | :--- | :--- | :--- |
| 4478966 | 0 | 4 | Ein's Summer Vacation | 2012-12-21 00:00:00.000 | episodes/76885/4478966.jpg |
| 360926 | 0 | 1 | Knockin' on Heaven's Door | 2001-09-01 00:00:00.000 | episodes/76885/360926.jpg |
| 300648 | 1 | 26 | The Real Folk Blues \(2\) | 1999-04-24 00:00:00.000 | episodes/76885/300648.jpg |
| 300647 | 1 | 25 | The Real Folk Blues \(1\) | 1999-04-17 00:00:00.000 | episodes/76885/300647.jpg |
| 300646 | 1 | 24 | Hard Luck Woman | 1999-04-10 00:00:00.000 | episodes/76885/300646.jpg |
| 300645 | 1 | 23 | Brain Scratch | 1999-04-03 00:00:00.000 | episodes/76885/300645.jpg |
| 300644 | 1 | 22 | Cowboy Funk | 1999-03-27 00:00:00.000 | episodes/76885/300644.jpg |
| 300643 | 1 | 21 | Boogie-Woogie Feng-Shui | 1999-03-20 00:00:00.000 | episodes/76885/300643.jpg |
| 300642 | 1 | 20 | Pierrot Le Fou | 1999-03-13 00:00:00.000 | episodes/76885/300642.jpg |
| 300641 | 1 | 19 | Wild Horses | 1999-03-06 00:00:00.000 | episodes/76885/300641.jpg |
| 300639 | 1 | 17 | Mushroom Samba | 1999-02-20 00:00:00.000 | episodes/76885/300639.jpg |
| 300638 | 1 | 16 | Black Dog Serenade | 1999-02-13 00:00:00.000 | episodes/76885/300638.jpg |
| 219125 | 1 | 6 | Sympathy for the Devil | 1998-11-28 00:00:00.000 | episodes/76885/219125.jpg |
| 219124 | 1 | 5 | Ballad of Fallen Angels | 1998-11-21 00:00:00.000 | episodes/76885/219124.jpg |
| 219123 | 1 | 4 | Gateway Shuffle | 1998-11-14 00:00:00.000 | episodes/76885/219123.jpg |
| 219120 | 1 | 1 | Asteroid Blues | 1998-10-24 00:00:00.000 | episodes/76885/219120.jpg |
| 937401 | 0 | 3 | Session #0 | 1998-08-25 00:00:00.000 | episodes/76885/937401.jpg |
| 722371 | 0 | 2 | Session XX; Mish-Mash Blues | 1998-06-26 00:00:00.000 | episodes/76885/722371.jpg |
| 300640 | 1 | 18 | Speak Like a Child | 1998-06-19 00:00:00.000 | episodes/76885/300640.jpg |
| 300637 | 1 | 15 | My Funny Valentine | 1998-06-12 00:00:00.000 | episodes/76885/300637.jpg |
| 300636 | 1 | 14 | Bohemian Rhapsody | 1998-06-05 00:00:00.000 | episodes/76885/300636.jpg |
| 219132 | 1 | 13 | Jupiter Jazz, Part II | 1998-05-29 00:00:00.000 | episodes/76885/219132.jpg |
| 219131 | 1 | 12 | Jupiter Jazz, Part I | 1998-05-22 00:00:00.000 | episodes/76885/219131.jpg |
| 219130 | 1 | 11 | Toys in the Attic | 1998-05-15 00:00:00.000 | episodes/76885/219130.jpg |
| 219129 | 1 | 10 | Ganymede Elegy | 1998-05-08 00:00:00.000 | episodes/76885/219129.jpg |
| 219128 | 1 | 9 | Jamming with Edward | 1998-05-01 00:00:00.000 | episodes/76885/219128.jpg |
| 219127 | 1 | 8 | Waltz For Venus | 1998-04-24 00:00:00.000 | episodes/76885/219127.jpg |
| 219126 | 1 | 7 | Heavy Metal Queen | 1998-04-17 00:00:00.000 | episodes/76885/219126.jpg |
| 219122 | 1 | 3 | Honky Tonk Women | 1998-04-10 00:00:00.000 | episodes/76885/219122.jpg |
| 219121 | 1 | 2 | Stray Dog Strut | 1998-04-03 00:00:00.000 | episodes/76885/219121.jpg |

**Comment by hidden4003** [comment]
Was confirmed on discord as working.
