### ISSUE TITLE
TVDb integration not working anymore

### ISSUE THREAD

**Issue by t0815** [ShokoAnime/ShokoServer#809]
## VERSION INFORMATION

Server Version: 3.9.6.0

Desktop Version: 3.9.6.0

If you've compiled your own version, please use the last commit you compiled.

## LOG FILE

ATTACH YOUR LOGS HERE
[2020-01-03.log](https://github.com/ShokoAnime/ShokoServer/files/4019053/2020-01-03.log)

## DESCRIPTION

Updating a series TVDB Data does not work anymore.
The URL for the site has changed too from https://www.thetvdb.org/ to www.thetvdb.com . https://www.thetvdb.org/ redirects now to https://www.themoviedb.org/.  So im assuming its just an url issue.

## STEPS TO REPRODUCE

1. Pick a series
2. click update tvdb data
3. no data will be updated and no images will be downloaded

**Comment by da3dsoul** [comment]
Daily should already have it fixed. We've been using thetvdb.com for a long time. They changed their API URL, though, because they are...smart people who make smart decisions.....

**Comment by t0815** [comment]
:D  Alrighty. Tnx, can be closed then i think.
