### ISSUE TITLE
TvDB episode image issue with TvDB API v3

### ISSUE THREAD

**Issue by hidden4003** [ShokoAnime/ShokoServer#810]
`01:34:42| --- Error processing CommandRequest_DownloadImage: https://thetvdb.com/banners/episodes/71742/5450007.jpg (575) - The image download stream returned an invalid image`

Shoko attempts to use:
https://thetvdb.com/banners/episodes/71742/5450007.jpg
According to 
https://thetvdb.com/series/boogiepop-phantom/allseasons/official
correct urls for this ones are
https://artworks.thetvdb.com/banners/episodes/71742/57612.jpg

have to look into api to pull that from the response instead of guessing

**Comment by hidden4003** [comment]
![image](https://user-images.githubusercontent.com/197087/71814314-b04eec00-3084-11ea-91d9-bbbb2400d3cd.png)
path is now combination of subtype  and id

**Comment by Cazzar** [comment]
Given TvDB support is being dropped, I am going to close this off.
