### ISSUE TITLE
Directory name is different than expected for serie

### ISSUE THREAD

**Issue by bigretromike** [ShokoAnime/ShokoServer#816]
﻿## PLEASE READ BEFORE POSTING YOUR ISSUE

Please create GitHub issues only for bugs and feature requests. If you need help with using Shoko or have a question, join us on Discord.

https://discord.gg/vpeHDsg

===== Guidelines ====

- Make sure you are using the latest **Stable** or **Daily** version of Shoko Server otherwise your issue will be closed.
- Search this repository (top of the page) for the issue or feature you are reporting, make sure it has not been fixed or reported before.
- If reporting an issue, then you must attach the relevant Shoko Server and Shoko Desktop **LOG FILE**. 
- If requesting a new feature, please explain in detail the feature itself and the benefits of it being added.
- If requesting cosmetic changes, please explain in detail why they should be made. 
- The template below **MUST BE USED** when submitting an issue, no exceptions.

## VERSION INFORMATION

Server Version: 3.9.6.40

Desktop Version: -

If you've compiled your own version, please use the last commit you compiled.

## LOG FILE

ATTACH YOUR LOGS HERE
```
[2020-04-21 07:41:30:486] Error|Importer.RunImport_ScanFolder => SVR_VideoLocal_Place.RenameAndMoveAsRequired => SVR_VideoLocal_Place.MoveFileIfRequired Unable to MOVE file: \\shoko\photo\NewNew\[Quetzal] Yuusha ni Narenakatta Ore wa Shibushibu Shuushoku wo Ketsui Shimashita 13 OVA (BD 1080p x264 FLAC) [b9d88e1e].mkv to \\shoko\anime\Yuusha ni Narenakatta Ore wa Shibushibu Shuushoku o Ketsui Shimashita.: Yuusha ni Narenakatta Ore no Imouto ga Joukyou Shite Kimashita·\[Quetzal] Yuusha ni Narenakatta Ore wa Shibushibu Shuushoku wo Ketsui Shimashita 13 OVA (BD 1080p x264 FLAC) [b9d88e1e].mkv error Could not find a part of the path.
```

## DESCRIPTION

Describe the problem you've encountered. What caused the issue, and what you expected to happen. Screenshot’s, Videos and any additional information is welcomed and will help us fix the problem.

File is recognized but not moved to to issue with path name.
The issue is in path name notice the dot at end.
Shoko want `Kimashita·` yet create (on Windows10) path: `Kimashita.`
Renaming folder don't help. Maybe something is converting that middle dot to normal dot?

## STEPS TO REPRODUCE

Being as detailed as possible, please list all steps need to reproduce the issue, if we can't reproduce it then we can't fix it.

Download Yuusha ni Narenakatta Ore wa Shibushibu Shuushoku wo Ketsui Shimashita OVA

**Comment by da3dsoul** [comment]
I think the issue here is that you are using UNC paths, which are like half network and half Windows. Can you try it with \\shoko\ mounted as a drive letter?

**Comment by da3dsoul** [comment]
I say because I have this show with drop folders (on Linux)

**Comment by da3dsoul** [comment]
I know the issue, actually. I had it happen for another series. It's a long path issue, though I thought we solved those.
