### ISSUE TITLE
broken /api/user/password, /api/user/password/{uid} 

### ISSUE THREAD

**Issue by hidden4003** [ShokoAnime/ShokoServer#818]
https://github.com/ShokoAnime/ShokoServer/blob/cd0bf2e43ffea43d5a9557a9931b144e1b8f3ff6/Shoko.Server/API/v2/Modules/Core.cs#L600-L619

This thing is completely broken, security aside it tries to instantiate the user object from the post data and if you omit the JmmUserID it crashes.

![image](https://user-images.githubusercontent.com/197087/80367279-7bfd7680-8893-11ea-863f-bc0b198b1648.png)
![image](https://user-images.githubusercontent.com/197087/80367293-80c22a80-8893-11ea-96fa-071fc98cb260.png)

I think it should only accept a string for new password and grab user from the session, or the uid as done in second command.

**Comment by da3dsoul** [comment]
Noted, but everything is kind of broken atm

**Comment by da3dsoul** [comment]
See APIv3
