### ISSUE TITLE
/api/rescan queues single file for rescan not a folder

### ISSUE THREAD

**Issue by hidden4003** [ShokoAnime/ShokoServer#819]
As you can see below description says it is supposed to rescan a folder but it tries to queue command for a single file, also id seems broken, at least I don't understand why uri doesn't list it like password endpoint does, i.e. /rescan/{folderId} or smth. Do I just send it as POST/GET id=xx and it will be passed?

https://github.com/ShokoAnime/ShokoServer/blob/c69a218e80c079587886005bf1a84bc6337f18ea/Shoko.Server/API/v2/Modules/Common.cs#L200-L223

**Comment by harshithmohan** [comment]
You have to send a get request to it with 'id' as a query param. But as @hidden4003 said, it scans a single file and not a folder as the description says.
![Screenshot_20200428_041822](https://user-images.githubusercontent.com/26010946/80428658-01bb0980-8908-11ea-8023-c26c95663db1.png)
![Screenshot_20200428_042438](https://user-images.githubusercontent.com/26010946/80428728-2f07b780-8908-11ea-9a09-5bbade1082ff.png)

**Comment by da3dsoul** [comment]
api/v3/Filter{id}/Scan does this now

**Comment by harshithmohan** [comment]
`/api/v3/ImportFolder/{id}/Scan` you mean.

**Comment by da3dsoul** [comment]
Yes it's way past sleepy time
