### ISSUE TITLE
Shoko docker container 3.9.7 does no start

### ISSUE THREAD

**Issue by miracle152005** [ShokoAnime/ShokoServer#821]
## VERSION INFORMATION

Server Version:  Shoko.CLI.exe 3.9.6.876 (strange I have downloaded the container with the v3.9.7 tag and the version is still 3.9.6.x)

## LOG FILE

ATTACH YOUR LOGS HERE
[2020-05-01.log](https://github.com/ShokoAnime/ShokoServer/files/4562900/2020-05-01.log)

## DESCRIPTION
Using the latests docker container the container hangs in a restart loop.

## STEPS TO REPRODUCE
On ubuntu 18.04 using docker 19.03.6 
I used the following docker-compose to create the docker container:
version: "3"
services:
    shoko_server:
        container_name: shokoserver
        image: cazzar/shokoserver:v3.9.7
        restart: always
        ports:
            - "8111:8111/tcp"
        volumes:
         {List of 8 Volumes}

Could you please take a look.
Thanks.

**Comment by Cazzar** [comment]
Thanks for the report, someone else on the discord had also mentioned it as an issue though I haven't had time to investigate, though will be doing soon

**Comment by Cazzar** [comment]
Hi @miracle152004 

This should be resolved now.

You may need to do `docker pull cazzar/shokoserver:v3.9.7` for it to update.
