### ISSUE TITLE
Feature Request: Add Shoko Server to Hama as metadata source

### ISSUE THREAD

**Issue by runecalico** [ShokoAnime/ShokoServer#822]
While it may not be exactly what the Shoko team would like as far as an intergrated Plex experience, I wonder if instead of competing with Hama for features (Because you need to either use the Shoko Plex  Agent OR the Hama agent), that either support for pulling metadata from Shoko is added to Hama or the Shoko metadata agent be updated so you can use it with Hama/Absolute Series Scanner.

As least for me, the Shoko metadata agent does not seem to work very well (The Scanner doesn't discover as much as Absolute Series Scanner does), and the matching doesn't seem to work well.

While Hama/ASS works very well on elucidating the files/series, it also pulls much of the same data that is already in Shoko from various sources (including anidb), which can result in a ban.  Placing Shoko in the agent's order list doesn't work as it seems that Hama/ASS doesn't query in a format that Shoko understands :(

**Comment by Cazzar** [comment]
Ultimately adding support for HAMA would be up for the HAMA devs, and while I know ShokoMetadata isn't a perfect solution, it is something that I have always been happy to work on and take feedback on.

If you have experience with Python and want to help out for ShokoMetadata, I am more than happy for you to help out, as there are undoubtedly improvements that can be made there, and if there are any specific issues you want to raise about ShokoMetadata best to do it on the github there ([Cazzar/ShokoMetadata.bundle](https://github.com/Cazzar/ShokoMetadata.bundle)) or chat with us on discord.

**Comment by runecalico** [comment]
Fair enough, I figured I would start on the Shoko side and see if there was interest before going to the Hama side and requesting the feature there.
Thanks.

**Comment by Cazzar** [comment]
As I'm said I'm happy to try and improve issues with ShokoMetadata, I just generally need specific information to try and reproduce it
