### ISSUE TITLE
Ongoing APIv3 Request Thread

### ISSUE THREAD

**Issue by harshithmohan** [ShokoAnime/ShokoServer#823]
- [x] Return count of missing episodes (collecting), missing episodes (total). Count as in count of episodes and not count of groups.

- [x] Return count of unreconized files, multiple files and duplicate files.

- [x] Return breakdown of series by type (Series, OVA, Movie, Others)<details><summary>Reference image</summary>
![Screenshot_20200518_151345](https://user-images.githubusercontent.com/26010946/82198623-33792c00-991a-11ea-81b1-fae3536686d8.png)</details>

- [x] Return `epname` and `series name` for recognized files in `recent files`. Not very important as we could query `/api/ep/getbyfilename` but that takes a lot of queries. It would be very faster if everything's returned in a single call.

- [x] Return `size` and `number of series` in `/api/v3/ImportFolder`

- [x] Fix `/api/modules` to return proper counts of `watched_files`, `watched_series`, `hours_watched`. Currently, it returns 0 for all three of then. EDIT: Fixed in v3 with a new endpoint

- [x] Fix `/api/file/recent` to return datetime values for `created` and `updated` fields. Currently it only returns date and it should return datetime according to Swagger.

- [x] ~~Make `/api/file/recent` return only the filename instead of the relative path for key `filename`. Maybe keep the relative path but rename it accordingly.~~ Just use Substring(LastIndexOf(pathSeparator)) in whatever language

- [x] Return src info (BD, HDTV, www, etc) in `/api/ep`. In `level=3` I guess, as it's different for each file. EDIT: Fixed in v3 with new endpoint `/api/v3/File/{id}/AniDB`

- [x] v3 equivalent of `/api/file/recent`

- [x] Fix the endpoint for changing password. The current needs the jmmuserid (#818 )

**Comment by da3dsoul** [comment]
Need clarification on `Return count of missing episodes (collecting), missing episodes (total). Count as in count of episodes and not count of groups.`

**Comment by da3dsoul** [comment]
As for the Import Folder stuff, it was copy and pasted from APIv1, so it's a mess that I need to rewrite from square one

**Comment by harshithmohan** [comment]
> Need clarification on:
> `Return count of missing episodes (collecting), missing episodes (total). Count as in count of episodes and not count of groups.`
> `Return count of unreconized files, multiple files and duplicate files.`
> Just want an endpoint with that data? Is there a place you expected it that doesn't have it.

Just send that data in the dashboard endpoint, that's the only place it's needed.

**Comment by da3dsoul** [comment]
The number of multiple files was scrapped, because it's confusing at its very concept. I know the system, and coming up with math that made sense wasn't easy. So, I gave Percentage of Multiples/Duplicates: how much of the collection is a multiple or duplicate.

**Comment by da3dsoul** [comment]
Essentially, because totalling these gives very skewed data, based on the fact that Kaguya has anywhere from 1-3 files per episode, and all of A Dude and His Cat has exactly 2 files/ep.
<details>
<summary>Screenie</summary>

![ShokoDesktop_2020-05-19_18-29-09](https://user-images.githubusercontent.com/5205810/82384971-02bef280-99ff-11ea-84d6-baa7c2f8637e.png)
</details>

**Comment by Cazzar** [comment]
Just a quick one, I think
```
Make /api/file/recent return only the filename instead of the relative path for key filename. Maybe keep the relative path but rename it accordingly.
```
Isn't too needed, if you have the path, there are many libraries to extract the filename/basename from it.

**Comment by da3dsoul** [comment]
I agree

**Comment by da3dsoul** [comment]
Trying to figure out how to have certain properties have one DateTime style and the rest something different.

**Comment by harshithmohan** [comment]
Why didn't I think of that? _proving I'm stupid_

**Comment by harshithmohan** [comment]
@da3dsoul Did you complete the 4th one (Return epname and series name)? You marked it as complete but I still don't see it in the endpoint response.

**Comment by da3dsoul** [comment]
I gave you ID, as names are user configurable and language dependent, plus you could use that to link to the series/episode in ClientV2. Though, in the future you'll want to use APIv3 anyway

**Comment by harshithmohan** [comment]
Well, fair enough. At least saves me one API request of getting the ID.

**Comment by da3dsoul** [comment]
APIv3 models are made light so you can grab a bunch really quick

**Comment by da3dsoul** [comment]
For File/Recent, I would have it return the new FileDetailed model, which includes the relevant xrefs. If there are none, then it's unrecognized

**Comment by harshithmohan** [comment]
The reason I asked that is, currently I have to run a for loop to separate out the recognized and unrecognized files. If I'm not wrong, the server can differentiate them without a loop? So having different endpoints would be better. The loop isn't slow in anyway, just trying to avoid unneeded things. But I can work with it, no problem.

**Comment by da3dsoul** [comment]
No the server just runs a loop, too.

**Comment by harshithmohan** [comment]
Ok then. I was wrong.

**Comment by da3dsoul** [comment]
Those are done now.

**Comment by harshithmohan** [comment]
API v3 equivalents needed
- [ ] `/version`
- [ ] `/webui/update` and `/webui/latest`
- [ ] All `init` endpoints
- [ ] `/os/drives` and `/os/folder`
- [ ] Queue status and commands related endpoints
- [ ] `/serie/infobyfolder`
- [ ] `/folder/import`, `/folder/scan`
- [ ] Actions: `/rescanunlinked`, `/avdumpmismatchedfiles`, `/anidb/updatemissingcache`, `/trakt/scan`, `/tvdb/regenlinks`, `/tvdb/checklinks`, `/moviedb/update`, `/images/update`, `/image/validateall`

**Comment by da3dsoul** [comment]
\* I can do this, but it should be in a separate menu for power users, alongside several other dangerous commands

**Comment by da3dsoul** [comment]
Just for your info, Run Import checks for new files, hashes them etc, Scans Drop Folders, Checks and Scans for community site links (tvdb, trakt, moviedb, etc), and Downloads missing images

**Comment by harshithmohan** [comment]
> * I can do this, but it should be in a separate menu for power users, alongside several other dangerous commands

Those actions will be hidden until and unless the user specifically goes and enables them to show up on the dashboard. So that's okay.

**Comment by harshithmohan** [comment]
#### For ShokoMetadata and future Jellyfin plugin
- [ ] `/ep/getbyfilename`
- [ ] `/serie/fromep`

**Comment by da3dsoul** [comment]
@Cazzar Can you get the Filesystem endpoints (os/drives and os/folder)? The point of them is to be able to remotely browse for an import folder when adding them, but linux and docker stuff gets in the way there. Feel free to not use CloudFileSystem there. I have tried that and didn't have much luck, but I know you are more familiar with the implications.

**Comment by da3dsoul** [comment]
Init is done. Note that you need to use the settings controller during init for settings things. init user should have access

**Comment by harshithmohan** [comment]
Need v3 of `/api/trakt/code` or just copy-paste the trakt ones to v3.

**Comment by harshithmohan** [comment]
Need an endpoint for getting the list of unrecognized files. The current way I was doing it is very stupid.

**Comment by revam** [comment]
* [ ] Add a new property property `Name` (or `Title`) on `Shoko.Server.API.v3.Models.Shoko.Episode`, where Shoko decides what the preferred name/title of the episode is.

**Comment by revam** [comment]
Closing this for now, it's easier to ask/be-asked on discord, and we haven't used this issue in... a while.
