### ISSUE TITLE
Setting `ismovie=1` on `/api/serie/search` returns non-movies too.

### ISSUE THREAD

**Issue by harshithmohan** [ShokoAnime/ShokoServer#825]
As the title says, according to swagger, querying `/api/serie/search` by passing `ismovie=1` in the arguments should only search for movies, but it ends up searching everything.

That's not a movie.
![Screenshot_20200524_223447](https://user-images.githubusercontent.com/26010946/82760052-cc261500-9e0e-11ea-9a4b-c93b7fc8c3c5.png)

**Comment by da3dsoul** [comment]
APIv2 is stupid. It does not support filtering like that. You can change this to request type filtering on APIv3, if you'd like

**Comment by harshithmohan** [comment]
I didn't understand.. :neutral_face:

**Comment by da3dsoul** [comment]
The only thing you can search by in APIv2 is names and tags. No other parameters are relevant to searching

**Comment by bigretromike** [comment]
`ismovie` was used in track.
The search endpoint does not support one: https://github.com/ShokoAnime/ShokoServer/blob/c69a218e80c079587886005bf1a84bc6337f18ea/Shoko.Server/API/v2/Models/common/SearchResult.cs
