### ISSUE TITLE
Shoko daily no longer able to start

### ISSUE THREAD

**Issue by miracle152005** [ShokoAnime/ShokoServer#831]
VERSION INFORMATION

Server Version: 3.10.0.0 docker container on ubuntu 18.04

## LOG FILE

ATTACH YOUR LOGS HERE
[2020-07-07.log](https://github.com/ShokoAnime/ShokoServer/files/4885748/2020-07-07.log)

## DESCRIPTION

After updating the daily container (40 minutes ago) the container crashes on startup.
Logfiles show a directory not found exception in Shoko.Server.Plugin.Loader.Load
Do we need to add another directory to the container mount points?

Could you please take a look.
Thanks.

Best regards
miracle152005

## STEPS TO REPRODUCE
Starting the container

**Comment by Cazzar** [comment]
That was me doing some debug stuff for the plugin loader.

Generally for daily, especially if it was last updated recently, it's best to ask in the discord.
Fixed in the next build
