### ISSUE TITLE
Missing Episode count is including specials, trailers,OP/EDs....

### ISSUE THREAD

**Issue by t0815** [ShokoAnime/ShokoServer#832]
## VERSION INFORMATION

Server Version: 
3.9.7 release

Desktop Version: 
3.9.7 release

If you've compiled your own version, please use the last commit you compiled.

## LOG FILE

N/A

## DESCRIPTION

Missing Episode counts now takes all types of files into account (specials, trailers, OP/EDs, and so on) which leads to almost every Series now having missing episodes.

## STEPS TO REPRODUCE

1.) Have a Series with all Episodes present but not all specials, ops/eds....
2.) Check missing episodes filter on Dashboard or groupfilter. 
3.) There should now be Series listed, with all regular episodes present, but still marked as having missing episodes

**Comment by da3dsoul** [comment]
I could have sworn we had an issue for this already. It's fixed. The next release (planning on a beta this weekend, I think) will have it.

**Comment by t0815** [comment]
Oh, really? Hm, maybe in Desktop board then... i did not search there....  :)

**Comment by da3dsoul** [comment]
Idk. I do know that I've heard it several times on discord, so it could have just been that
