### ISSUE TITLE
Plex unlinking doesn't work

### ISSUE THREAD

**Issue by harshithmohan** [ShokoAnime/ShokoServer#836]
Server Version: f1e68d9 (daily)

Calling the endpoint `/plex/token/invalidate` returns true but the change is not reflected anywhere. The server still thinks that plex is linked. Trying the same thing from Desktop doesn't work either.
However, unlinking and then restarting the Sever fixes everything.

**Comment by Cazzar** [comment]
Possibly response caching in that case, I am not sure why we use it specifically, need to investigate optionally disabling it in certain cases where the responses are not computationally expensive.
