### ISSUE TITLE
Impossible to restore Window from system tray

### ISSUE THREAD

**Issue by t0815** [ShokoAnime/ShokoServer#839]
## VERSION INFORMATION

Server Version: 
4.0.1

Desktop Version: 
4.0.0

If you've compiled your own version, please use the last commit you compiled.

## LOG FILE
N/A

## DESCRIPTION

When left-clicking or double-clicking at the tray-icon, the context menu always opens up instead of the main window being restored. So its impossible to restore the server window to edit settings or view status.

## STEPS TO REPRODUCE

1.) Minimize Server to tray or have setting on "start minimized"
2.) Try to restore the app from tray

**Comment by da3dsoul** [comment]
That's not a bug.
From the release post:

Goodbye Native UI, Hello Web UI

Arguably the biggest visual change for Windows users is the replacement of the longstanding Shoko UI that we’ve been using for nearly a decade with our Web UI.

**Comment by t0815** [comment]
oh, well didnt read changelog, alright tnx.

**Comment by t0815** [comment]
> Arguably the biggest visual change for Windows users is the replacement of the longstanding Shoko UI that we’ve been using for nearly a decade with our Web UI.

Yes, and tbh a change for the better! That way, you can control shoko server from any system! GJ 👍
