### ISSUE TITLE
Import cant move files and also unable to use renaming

### ISSUE THREAD

**Issue by Yukkun** [ShokoAnime/ShokoServer#841]
Server Version:  4.0.1

Desktop Version: 4.0.0

## LOG FILE

[https://pastebin.com/raw/1TkWntdC](https://pastebin.com/raw/1TkWntdC)

## DESCRIPTION

When importing new files, they dont get moved from drop source to drop destination. Trying to rename files also does not work. Could be related to each other?

I have my files on second PC and have mapped it as network drive on my main PC, just to organize the files for Plex but that shouldn't matter because its worked fine until 3.9.7, only this 4.x has brought these issues

## STEPS TO REPRODUCE
1. Set up Drop Destination and Drop Source
2. Import Files
Optional:
3. Try to rename them using Shoko Desktop

**Comment by da3dsoul** [comment]
Fixed in dailies
