### ISSUE TITLE
WebUi-->ShokoServer-->Logs-->Better Readability

### ISSUE THREAD

**Issue by SuzuyaJuuzoudesu** [ShokoAnime/ShokoServer#842]
Turn stuff like
```
Added File to MyList. File: [ChoeyXD] Deadman Wonderland 04 720p BD (Dual Audio) [907C0F04].mkv Manual Link: False Watched Locally: False Watched AniDB: False Local State: HDD AniDB State: HDD ReadStates: True ReadWatched Setting: True ReadUnwatched Setting: True
```

into stuff like

```
Added File to MyList. File: [ChoeyXD] Deadman Wonderland 04 720p BD (Dual Audio) [907C0F04].mkv
Manual Link: False; Watched Locally: False; Watched AniDB: False; Local State: HDD; AniDB State: HDD; ReadStates: True; ReadWatched Setting: True; ReadUnwatched Setting: True;
```

**Comment by Cazzar** [comment]
Needs to be in https://github.com/ShokoAnime/ShokoServer-WebUI

**Comment by Cazzar** [comment]
Logging is more for diagnostic stuff. In this case, without adding extra padding if you have multiple instances of that log, it takes a lot more to read exactly what it is going on, typically people will not need to be diving into their logs constantly.

Is there much benefit for this past a few seconds of comprehension timing?
