### ISSUE TITLE
WebUi-->ShokoServer-->Logs-->Timestamp

### ISSUE THREAD

**Issue by SuzuyaJuuzoudesu** [ShokoAnime/ShokoServer#844]
My Windows time is 16:51 right now
The timestamp of a new log line is 2020-09-14T14:51:31.4668455Z

Is that 2 hour time difference WAD?

**Comment by Cazzar** [comment]
This might to be better to raise up on our discord (When Cloudflare stops having issues) as some of the issues need to be in different projects, and even some of them can be explained.
The time format you are seeing is [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) and the Z at the end is designating the time as GMT+0, so if there is a difference time would say you're in GMT+2
