### ISSUE TITLE
Shoko Server-->Drop Destination Directory Names and Structure

### ISSUE THREAD

**Issue by SuzuyaJuuzoudesu** [ShokoAnime/ShokoServer#845]
When Shoko automatically creates directories when moving and sorting stuff to the drop destination, can we get the option to add some technical information to the directory names?
Instead of the directory being simply named "Anime name" something like this
"Anime name [Incomplete] [BD720]"
"Anime name [Complete] [DA] [BD1080] [10bit]"

The Option to place related series into the same directory
Example: Instead of having 300.000 directories for the Dragonball series
Dragonball/
- Dragonball/
- Dragonball Z/
- Movies
- OVA
- Dragonball GT/

**Comment by Cazzar** [comment]
This can be solved with a custom renamer.
