### ISSUE TITLE
Feature request: Relation graphs

### ISSUE THREAD

**Issue by revam** [ShokoAnime/ShokoServer#846]
Posting here because I was told to in Discord.

I think it would be cool to query once for a relation-graph containing all relations (both directly and indirectly) to a series.

# Suggested implemention
Expose an endpoint that returns all relations that touch the series at some point (directly or indirectly), made possible by grouping all relations stored `AniDB_Anime_Relation` in a new table (`AniDB_Anime_Relation_List`?) and querying for the group/list that contain the series id, then returning all relations (from `AniDB_Anime_Relation`) in that group/list.

## Example endpoint
`/api/v3/Series/{id}/Graph` or maybe `/api/v3/Graph/FromSeries/{seriesId}`

## Example responses
1) A graph was found
`GET /api/v3/Series/1/Graph`, or `GET /api/v3/Series/2/Graph`, or `GET /api/v3/Series/3/Graph`
```json
[
  { "seriesId": 1, "relatedSeriesId": 2, "relationType": "sequel" },
  { "seriesId": 2, "relatedSeriesId": 1, "relationType": "preequel" },
  { "seriesId": 1, "relatedSeriesId": 3, "relationType": "spin-off" },
  { "seriesId": 3, "relatedSeriesId": 1, "relationType": "main story" }
]
```
2) A graph was not found
`GET /api/v3/Series/0/Graph`
```json
[]
```
### General use-cases (e.g. media server integrations. desktop)
- Creating session order in front-end UI (Jellyfin, Plex(?)) - without relaying on TvDB - with custom sort order (e.g. based on release year, or based on chronological order)
- Show directly related series (you have in your collection)
- ...and more.
### Offline use-cases (e.g. desktop, or LAN _only_)
- Generate a graph to show all series related to the series, and how they relate to the series, _offline_. (So we don't need to browse AniDB to do this)
- ...and more.

**Comment by maxpiva** [comment]
Please notice, that getting the whole graph from anidb requires multiple anidb API calls, one for every relation the series has.
If I'm not wrong. Currently, Shoko graphs only the ones that already have.

**Comment by revam** [comment]
So, what would be best, 1) expose only local relations, or 2) map the rest of the graph, potentially downloading the metadata for series not stored on disk, or 3) expose all relations in Shoko's database, with a setting to download all metadata for series not stored on disk. Personally I lean on option three or one.

@maxpiva What do you think?

**Comment by maxpiva** [comment]
Number three is great, but we already discussed this: Please check 
[Shoko.Server/Models/SVR_AniDB_Anime.cs#L1342](https://github.com/ShokoAnime/ShokoServer/blob/6861d0125fba6ec0e46d34307c85d8bb74bac9c2/Shoko.Server/Models/SVR_AniDB_Anime.cs#L1342)

**Comment by da3dsoul** [comment]
Personally, I use a depth of 3, and since I usually have at least all of the seasons (and maybe not all ovas), I'll have the entire tree

**Comment by revam** [comment]
We have `/api/v3/Series/<shoko series id>/Relations`, `/api/v3/Series/AniDB/<anidb series id>/Relations`, and `/api/v3/Group/<shoko group id>/Relations`, which is good enough and can be used to crawl the relations client-side to create a graph, so closing this for now. I'm actually using the first endpoint I mentioned already in Shokofin to get the relations for the series.
