### ISSUE TITLE
Watch for New Files no longer working

### ISSUE THREAD

**Issue by ablakers** [ShokoAnime/ShokoServer#849]
## VERSION INFORMATION

Server Version: 4.0.1.0

Desktop Version: 4.0.0.0

on the same Windows 10 PC

If you've compiled your own version, please use the last commit you compiled.

## LOG FILE

[2020-10-01.log](https://github.com/ShokoAnime/ShokoServer/files/5314173/2020-10-01.log)

## DESCRIPTION

At some point Shoko has stopped watching for new files in my folder. This has persisted across turning the setting off and on, and restarts of Shoko Server and my computer. My folder is on a pool made by [StableBit DrivePool](https://stablebit.com/DrivePool) but Shoko had been watching this file fine on both 4.0.0.0 and 4.0.1.0 for a while before it stopped working, and I haven't made any settings changes or installed any updates to DrivePool since before folder watching stopped.

## STEPS TO REPRODUCE

I don't know exactly when it stopped working or what caused it so I cannot give these steps.

**Comment by da3dsoul** [comment]
My guess is netcore changed something. Our code hasn't changed, but it wasn't reported until the switch to netcore

**Comment by ElementalCrisis** [comment]
Seems this was fixed as I have the same setup and Shoko imports newly added files without issue.
