### ISSUE TITLE
Network Drives no longer recognized

### ISSUE THREAD

**Issue by t0815** [ShokoAnime/ShokoServer#852]
## VERSION INFORMATION

Server Version:  4.0.1

Desktop Version: 4.0.0

## LOG FILE
N/A

## DESCRIPTION

Shoko Server no longer recognizes Mounted Network drives as import folder. In the drive list for import folder selection, only local disks are shown. If i edit the path manually, and hit save - an internal server error is thrown. Problem extends to Shoko desktop too, since its impossible to link local system networkpath to server import folder.

## STEPS TO REPRODUCE

1.) Have a network drive connected and mounted on shoko server host system
2.) Try to add the networkdrive as a new importfolder
3.) (optional) Edit importfolder manually and hit save

**Comment by Cazzar** [comment]
![image](https://user-images.githubusercontent.com/994214/107877013-c1bc2600-6f1d-11eb-93e5-2ff4b25df946.png)
I have just tested this in the latest release and can confirm it is working as my Z drive is a network drive.
