### ISSUE TITLE
Could not init database: System.DllNotFoundException

### ISSUE THREAD

**Issue by Spounge** [ShokoAnime/ShokoServer#855]
## VERSION INFORMATION

Server Version: 4.0.1.0

## LOG FILE

[server.txt](https://github.com/ShokoAnime/ShokoServer/files/5433104/server.txt)
[webui.txt](https://github.com/ShokoAnime/ShokoServer/files/5433105/webui.txt)

## DESCRIPTION

I have a dll error when I try to start the server for the first time from the webui at the database initialization stage.

## STEPS TO REPRODUCE

- Start the docker container
- Keep the default database parameters (SQLite)
- Click on start server

**Comment by Cazzar** [comment]
Running docker seem to run fine with the default setup, try again? And if it does continue, are you able to provide more details on environment/startup params to docker?

**Comment by Cazzar** [comment]
If this is still an issue, please respond with more information, I am closing this until further information is obtained.
