### ISSUE TITLE
Unhandled exception when attempting to use Delete by Preferences (Multiple Files)

### ISSUE THREAD

**Issue by runecalico** [ShokoAnime/ShokoServer#859]
﻿## PLEASE READ BEFORE POSTING YOUR ISSUE

Please create GitHub issues only for bugs and feature requests. If you need help with using Shoko or have a question, join us on Discord.

https://discord.gg/vpeHDsg

===== Guidelines ====

- Make sure you are using the latest **Stable** or **Daily** version of Shoko Server otherwise your issue will be closed.
- Search this repository (top of the page) for the issue or feature you are reporting, make sure it has not been fixed or reported before.
- If reporting an issue, then you must attach the relevant Shoko Server and Shoko Desktop **LOG FILE**. 
- If requesting a new feature, please explain in detail the feature itself and the benefits of it being added.
- If requesting cosmetic changes, please explain in detail why they should be made. 
- The template below **MUST BE USED** when submitting an issue, no exceptions.

## VERSION INFORMATION

Server Version: 4.0.1.0

Desktop Version: 4.0.0.0

If you've compiled your own version, please use the last commit you compiled.

## LOG FILE
ShokoServer Log file:
[2020-12-03.log](https://github.com/ShokoAnime/ShokoServer/files/5637543/2020-12-03.log)

## DESCRIPTION

I am attempting to use Shoko Desktop's "Delete by Preferences" feature in 4.x. This is a fresh installation, with both Desktop and Server on the same machine. This is the first time trying this on a 4.x installation. Unfortunately clicking on the Delete by Preferences button doesn't do anything as there seems to be an unhandled exception on the Server.

There is no indication of the failure in Shoko Desktop, Desktop pauses for a bit and then nothing. But looking at the logs indicates there is an error ..

2020-12-03T16:32:19.3269794Z
System.InvalidOperationException: Failed to compare two elements in the array. ---> System.NullReferenceException: Object reference not set to an instance of an object. at Shoko.Server.FileQualityFilter.<>c.<CompareVideoCodecTo>b__21_3(Stream a) in E:\Documents\GitHub\ShokoServer\Shoko.Server\Import\FileQualityFilter.cs:line 465 at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext() at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray() at System.Linq.Buffer`1..ctor(IEnumerable`1 source) at System.Linq.OrderedEnumerable`1.ToArray() at Shoko.Server.FileQualityFilter.CompareVideoCodecTo(SVR_VideoLocal newLocal, SVR_VideoLocal oldLocal) in E:\Documents\GitHub\ShokoServer\Shoko.Server\Import\FileQualityFilter.cs:line 464 at Shoko.Server.FileQualityFilter.CompareTo(SVR_VideoLocal newFile, SVR_VideoLocal oldFile) in E:\Documents\GitHub\ShokoServer\Shoko.Server\Import\FileQualityFilter.cs:line 336 at System.Collections.Generic.ArraySortHelper`1.InsertionSort(T[] keys, Int32 lo, Int32 hi, Comparison`1 comparer) at System.Collections.Generic.ArraySortHelper`1.IntrospectiveSort(T[] keys, Int32 left, Int32 length, Comparison`1 comparer) at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, Comparison`1 comparer) --- End of inner exception stack trace --- at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, Comparison`1 comparer) at System.Collections.Generic.List`1.Sort(Comparison`1 comparison) at Shoko.Server.ShokoServiceImplementation.GetMultipleFilesForDeletionByPreferences(Int32 userID) in E:\Documents\GitHub\ShokoServer\Shoko.Server\API\v1\Implementations\ShokoServiceImplementation\ShokoServiceImplementation_Utilities.cs:line 237 at lambda_method(Closure , Object , Object[] ) at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments) at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync() at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync() at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context) at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted) at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync() at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter() at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context) at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted) at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync() at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync() at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext) at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext) at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext) at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context) at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext) at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider) at Shoko.Server.API.Startup.<>c.<<Configure>b__9_0>d.MoveNext() in E:\Documents\GitHub\ShokoServer\Shoko.Server\API\Startup.cs:line 184
2020-12-03T16:32:19.3269794Z
Connection id "0HM4JL7NSO7FG", Request id "0HM4JL7NSO7FG:00000001": An unhandled exception was thrown by the application.

## STEPS TO REPRODUCE

Being as detailed as possible, please list all steps need to reproduce the issue, if we can't reproduce it then we can't fix it.

Click on the "Delete by Preferences" button in the Multiple Files section (under Utilities) in the Desktop Client.  Seems to generate an error every time.

**Comment by da3dsoul** [comment]
VideoCodec, huh. Fiiiine, I guess I'll fix it.

**Comment by da3dsoul** [comment]
Later.... I'm at work

**Comment by runecalico** [comment]
<laugh>
I am certainly not expecting you to fix it while at work, or even immediately..
I wouldn't mind "soon" (whatever that means), but I'll take whatever I get 👍 

Anyway, I did try running an "update all MediaInfo" action, which didn't help if that makes any difference.

**Comment by da3dsoul** [comment]
Good job timing your reminder/response. I'm now just sitting here next to a computer.

**Comment by da3dsoul** [comment]
Dailies are building. Whichever OS you use, give a daily a try. You can get them in the actions tab on github for windows, and for docker, you just add `:daily` to the image and re-pull, assuming I remember correctly.

**Comment by runecalico** [comment]
That looks to do the trick as it no longer spits out that error. Thanks.
