### ISSUE TITLE
Daily build for linux?

### ISSUE THREAD

**Issue by GNY-001F2** [ShokoAnime/ShokoServer#861]
I understand that a stable Linux build is available and there are stable and daily builds for Windows.

I wanted to try out the new Shokofin plugin but since that requires a daily build (which is unavailable for Linux), should I just download and compile the master branch of ShokoServer?

**Comment by Cazzar** [comment]
The recommendation for daily builds on Linux is the daily tag in docker, that is automatically updated.

**Comment by ElementalCrisis** [comment]
I'll change the links on the site so stable pulls from the latest tag and daily pulls from the daily tag.

**Comment by GNY-001F2** [comment]
@Cazzar @ElementalCrisis Thank you for your replies. I don't use docker and prefer to run all my programs natively so what method should I use?

**Comment by da3dsoul** [comment]
If that's the case, just look at the docker file to see the required libraries. Should just be a couple like mediainfo. After that, it compiles with the command in the docker file

**Comment by Cazzar** [comment]
Officially, docker is the only supported setup for Linux.
Though we do have people that run it outside of docker, though they have to diagnose any dependency issues.
Given that the docker install is just ubuntu/debian base, you can look at the Dockerfile for a setup example.
