### ISSUE TITLE
Dealing with unrecognized files?

### ISSUE THREAD

**Issue by GNY-001F2** [ShokoAnime/ShokoServer#862]
I understand that Shoko Desktop is only available on Windows, and that it contains some features that allow it to manually link mis-identified or unidentified files to the correct series.

Is there something similar I can do directly on the linux server with the webui?

**Comment by da3dsoul** [comment]
No. Desktop does work in wine, though, with a bit of effort. I don't know the details, but it's listed in wine's community thing

**Comment by GNY-001F2** [comment]
@da3dsoul: So I followed the instructions given, but apparently there is a problem with wine-mono on wine v6 so the Shoko Desktop program doesn't work.

**Comment by da3dsoul** [comment]
I wouldn't know. I just know people have gotten it to work before. If you hop in our discord and post a question about it in #support, then people more knowledgeable than me may be able to help with it.

**Comment by Cazzar** [comment]
I'm just going to close this, as it's not an active discussion, it would be best to jump into the #support channel in our discord, as we do have multiple linux users that have managed to get it working in one way or another.
