### ISSUE TITLE
Renaming now always runs on import even when the script is disabled

### ISSUE THREAD

**Issue by miracle152005** [ShokoAnime/ShokoServer#865]
## VERSION INFORMATION

Server Version: 4.0.1.0

## LOG FILE
[2021-01-09.log](https://github.com/ShokoAnime/ShokoServer/files/5792429/2021-01-09.log)

## DESCRIPTION

Since I am using a naming for the series files that allows me to use tvdb as the metadata provider for plex I deactivated the renaming of files. Since the laste update (for which I ran an import on 9th of January) this settings seems to be ignored and the files are renamed regardless of this option.
It worked fine on the previous import at the end of december.

## STEPS TO REPRODUCE

Deactivate "Run this script when importing files..." using the desktop client. Import files in the collection.

Could you please take a look?

Thanks.
Best regards
miracle152005

**Comment by Cazzar** [comment]
This was actually changed in regards to the latest version.
There is now a setting in the Import key "RenameOnImport" which is default `false` that will disable this.

This can be controlled by the latest preview release of webui

**Comment by Cazzar** [comment]
![image](https://user-images.githubusercontent.com/994214/104119131-aa6ba500-5381-11eb-8f43-2efbd63ea2ac.png)

**Comment by miracle152005** [comment]
I hope this is the relevant setting and it is read from the settings-server.json file.
"RenameOnImport": false,

Since I am running the server in a docker container I am not able to easily switch the webui.

**Comment by Cazzar** [comment]
You can easily update WebUI in docker, and you need to set "Update channel" to Unstable and click the green circle beside the version, it will prompt you to update.

But yes, that is the right configuration variable.
