### ISSUE TITLE
Wrong Link but I can't manually link to the right file

### ISSUE THREAD

**Issue by Andor233** [ShokoAnime/ShokoServer#885]
Shoko: 4.1

![image](https://user-images.githubusercontent.com/16273755/123849231-21562380-d94b-11eb-9a21-5cf816b1e764.png)

8.5 and 17.5 are linked to the 5 because somebody uploads the wrong hash to Anidb(I don't know)?
But I cannot manually link the 8.5 to 8.5

**Comment by ElementalCrisis** [comment]
You'll need to fix it on AniDB since there is a hash match.
