### ISSUE TITLE
Docker multi-arch support (arm/raspberry pi)

### ISSUE THREAD

**Issue by kristianvld** [ShokoAnime/ShokoServer#886]
## DESCRIPTION

Currently only `linux/amd64` images are pushed to docker hub. It would be nice if multiple architectures, such as arm also could be pushed, so that the shoko server also could be run on units such as the Raspberry Pi.

Pushing multiple architectures to docker hub can be automated to a single step through stuff like buildx or similar, and there are github actions to simply this process further.

**Comment by da3dsoul** [comment]
It's not there for a reason. Shoko runs terribly on Pi, some dependencies need to be manually resolved, and some features may not work

**Comment by Cazzar** [comment]
There are a few things here, we have decided to support x64 only for now because firstly Shoko Doesn't run well on a rPi & other dependencies and functions of the server inherently become unusable on non x86/x64

**Comment by nstrelow** [comment]
Just out of curiosity, what things don't work well with a raspberry pi 4?

Where is the performance suffering?

**Comment by da3dsoul** [comment]
Hashing will be really slow. Because of SQLite and memory caches, you might run out of RAM or have poor performance in general from low disk speed

**Comment by revam** [comment]
The poor disc performance depends on where it is loading the files from. As for RAM... as long as you're running on a 4GB or 8GB midel then it should be fine, even with a big collection.

**Comment by nstrelow** [comment]
My setup is 4GB RAM with a big NVMe SSD, that could be good enough then.

Any chance you could include ARM into your docker images?
Otherwise I'll have to look into how to built from source.

**Comment by da3dsoul** [comment]
Supported on daily. Not yet on stable

**Comment by harshithmohan** [comment]
Just to add one more thing. AVDump won't work on ARM images
