### ISSUE TITLE
Deploying without Docker (Debian 10)

### ISSUE THREAD

**Issue by Tropaion** [ShokoAnime/ShokoServer#887]
Is there a way to deploy the server without docker?
I don't like docker and want to run the shoko server und an debian 10 lxc but didn't find anything about it

**Comment by da3dsoul** [comment]
Yeah. I'll warn you that any dependency or updated issues are on you. Look at the dockerfile and the RUN commands are what you need to spin it up. We don't do anything too crazy.

**Comment by Tropaion** [comment]
Ok thanks, maybe I'll try it when I have time.
