### ISSUE TITLE
Error when I click Download missing AniDB Data: Synchrous operations are disallowed. Call WriteAsync or set AllowSynchrousIO instead.

### ISSUE THREAD

**Issue by Ariane-B** [ShokoAnime/ShokoServer#888]
﻿## PLEASE READ BEFORE POSTING YOUR ISSUE

Please create GitHub issues only for bugs and feature requests. If you need help with using Shoko or have a question, join us on Discord.

https://discord.gg/vpeHDsg

===== Guidelines ====

- Make sure you are using the latest **Stable** or **Daily** version of Shoko Server otherwise your issue will be closed.
- Search this repository (top of the page) for the issue or feature you are reporting, make sure it has not been fixed or reported before.
- If reporting an issue, then you must attach the relevant Shoko Server and Shoko Desktop **LOG FILE**. 
- If requesting a new feature, please explain in detail the feature itself and the benefits of it being added.
- If requesting cosmetic changes, please explain in detail why they should be made. 
- The template below **MUST BE USED** when submitting an issue, no exceptions.

## VERSION INFORMATION

Server Version: 4.1.0.0

Desktop Version: 4.1.0.0

If you've compiled your own version, please use the last commit you compiled.

## LOG FILE

I can't find a button to get a log file, but here's a copy-paste of all I can see in the web UI's log page.... is what I wanted to say, but actually the web UI also doesn't allow me to select anything more than one screen's worth of text, so this will have to do. :(

Thankfully, it probably includes all the info you need about this issue.

<details>
<summary>Server logs</summary>

2021-08-09T03:08:19.015214Z
Starting the check for 97 anime XML files
2021-08-09T03:08:19.015214Z
Checking anime 2/97 for XML file
2021-08-09T03:08:19.015214Z
Checking anime 12/97 for XML file
2021-08-09T03:08:19.0306015Z
Checking anime 22/97 for XML file
2021-08-09T03:08:19.0456373Z
Checking anime 32/97 for XML file
2021-08-09T03:08:19.0456373Z
Checking anime 42/97 for XML file
2021-08-09T03:08:19.0620592Z
Checking anime 52/97 for XML file
2021-08-09T03:08:19.0620592Z
Checking anime 62/97 for XML file
2021-08-09T03:08:19.0620592Z
Checking anime 72/97 for XML file
2021-08-09T03:08:19.0793456Z
Checking anime 82/97 for XML file
2021-08-09T03:08:19.0793456Z
Checking anime 92/97 for XML file
2021-08-09T03:08:19.0793456Z
Updating 0 anime
2021-08-09T03:08:19.0793456Z
System.InvalidOperationException: Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead. at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseStream.Write(Byte[] buffer, Int32 offset, Int32 count) at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder) at System.IO.StreamWriter.Dispose(Boolean disposing) at System.IO.TextWriter.Dispose() at Shoko.Server.API.v2.Models.core.APIMessage.ExecuteResult(ActionContext context) in E:\Documents\GitHub\ShokoServer\Shoko.Server\API\v2\Models\core\APIMessage.cs:line 66 at Microsoft.AspNetCore.Mvc.ActionResult.ExecuteResultAsync(ActionContext context) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]() --- End of stack trace from previous location --- at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters() --- End of stack trace from previous location --- at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync() --- End of stack trace from previous location --- at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope) at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext) at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context) at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext) at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider) at Shoko.Server.API.Startup.<>c.<<Configure>b__9_0>d.MoveNext() in E:\Documents\GitHub\ShokoServer\Shoko.Server\API\Startup.cs:line 191
2021-08-09T03:08:19.0793456Z
Connection id "0HMAQQOEC53AT", Request id "0HMAQQOEC53AT:00000010": An unhandled exception was thrown by the application.
2021-08-09T03:08:56.0377597Z
Processing CommandRequest_SyncMyList
2021-08-09T03:08:56.3966767Z
MYLIST Missing Files: 0 Added to queue for inclusion
2021-08-09T03:08:56.3966767Z
Process MyList: 217 Items, 0 Added, 0 Deleted, 0 Watched, 0 Modified
2021-08-09T03:08:56.4237129Z
Processing CommandRequest_UpdateMyListStats

</details>

## DESCRIPTION

When clicking Download missing AniDB data, an error occurs, and no action is performed. See steps below for details.

## STEPS TO REPRODUCE

I have some unrecognized files that I want to fix:

![image](https://user-images.githubusercontent.com/6244273/128657241-a90330f5-2c13-4372-837d-33b6a00c327f.png)

I went to Shoko Desktop in hopes of doing that, but in the search interface, it was only offering me shows I already have, weirdly.

![image](https://user-images.githubusercontent.com/6244273/128657306-7eaec3c9-0e8c-4110-af9d-8389eccdac59.png)

So I figured "oh, maybe I have to tell the server to update its AniDB data".

So I went to the server's web UI's actions page, and clicked "Download missing AniDB data", but I immediately got an error 500 notification.

![image](https://user-images.githubusercontent.com/6244273/128657401-39752df2-4de7-46b4-a623-a926b98c5bd0.png)

So I came here to report the issue.

PS: I noticed while making this post that you actually have to press a button when the series you're looking for isn't already present on your PC. Either I'm blind or there's a UX issue here. Either way, I've found it now.

**Comment by da3dsoul** [comment]
Try with a daily

**Comment by Ariane-B** [comment]
If I change the update channel to Unstable, I get a WebUI update, but nothing for the server itself. The WebUI update doesn't fix the issue.

**Comment by da3dsoul** [comment]
Shoko can't update itself. You can find Windows dailies on the downloads page, and docker dailies by simply adding `:daily` to the image name

**Comment by Ariane-B** [comment]
I did the following:

- Download Shoko Server Daily zip
- Get a little confused by the absence of an installer.
- Open it and see something called "publish". Open it and see a bunch of files.
- Throw those into the Shoko Server folder.
- Break my Shoko Server installation.
- **(I really think you need better instructions for idiots like me)**
- Uninstall and restart
- Reinstall the stable version
- Stop Shoko Server
- This time, throw the publish folder itself into the Shoko Server folder. Replace files.
- This time, it seems the installation isn't broken. Restart Shoko Server.
- Open Actions; try the button again.
- **Still the same error**

**Comment by da3dsoul** [comment]
You did it right the first time. What broke?

**Comment by Ariane-B** [comment]
I tried to launch Shoko Server and it said I needed to install the .Net runtime 5.0. I downloaded the installer for that, but I already had it. I ran the repair install tool regardless and restarted my PC... but Shoko Server still wouldn't start.

**Comment by da3dsoul** [comment]
Hmm I've had that reported, but I can't reproduce it myself

**Comment by Ariane-B** [comment]
Anything I can do to help?

**Comment by da3dsoul** [comment]
Nah I think I found the issue with the daily deployment. I'm working on it now

**Comment by da3dsoul** [comment]
Okay, I think I fixed the daily.
As requested, sorry I assume a much higher computer literacy level than there is at times.

Download Daily from https://shokoanime.com/files/shoko-server/daily/ShokoServer.zip
Extract somewhere
Close Shoko Server entirely, it may go to the system tray, so right click it and hit shutdown or exit or whatever
![image](https://user-images.githubusercontent.com/5205810/128805454-7bed3988-7f24-487a-abf1-b57f354be97e.png)
Copy the contents of `publish` to the shoko installation folder. Overwrite it
Start Shoko.

See if the problem persists.

**Comment by Ariane-B** [comment]
Thanks for the new build and instructions! I can't guarantee it actually *works* because every time I restart Shoko Server it takes it a good half-hour to process 232 files all over again, but I clicked the button and this time there was a green toast and no error. It's a good sign!

**Comment by Ariane-B** [comment]
Confirmed! When I press the button, it says "Checking anime 999/999 for XML file" several times. The issue seems fixed.

**Comment by da3dsoul** [comment]
Cool
