### ISSUE TITLE
Graphical Progress Bars Summary for Series/Collections

### ISSUE THREAD

**Issue by misakitchi** [ShokoAnime/ShokoServer#89]
Hello!
Can you add a new feature:
Graphical Progress Bars for each Series or/and Collection

Like this:
![](http://www.uibox.in/img/thumbs/155.png)

Example: Collection is "Anime 2014 Fall" and each line is a serie

Thanks! :)

**Comment by misakitchi** [comment]
Hello!
Any news for this feature? ^_^
Thx!

**Comment by ElementalCrisis** [comment]
Part of the Web UI.
