### ISSUE TITLE
Server - No script available for renamer for [...]

### ISSUE THREAD

**Issue by Ariane-B** [ShokoAnime/ShokoServer#890]
## VERSION INFORMATION

Server Version: 4.1.0.0 (+ daily from 2021-08-10)

Desktop Version: 4.1.0.0

If you've compiled your own version, please use the last commit you compiled.

## LOG FILE

[2021-08-10.log](https://github.com/ShokoAnime/ShokoServer/files/6965762/2021-08-10.log)

## DESCRIPTION

I restarted Shoko Server, which caused it to start rehashing everything. I noticed the logs were full of errors for each file:

```
2021-08-11T03:58:34.6537253Z
Could not find a valid destination: C:\Users\azma\Videos\Anime\Tensei Shitara Slime Datta Ken (2021 Dai 2 Bu)\[SubsPlease]_That_Time_I_Got_Reincarnated_as_a_Slime_(2021_Part_2)_-_01_(1920x1080_H264)_[1FE9B194].mkv
2021-08-11T03:58:34.6537253Z
System.Exception: *Error: No script available for renamer at Shoko.Server.Renamer.LegacyRenamer.GetFilename(RenameEventArgs args) in D:\a\ShokoServer\ShokoServer\Shoko.Server\Renamer\LegacyRenamer.cs:line 30 at Shoko.Server.RenameFileHelper.GetFilename(SVR_VideoLocal_Place place, String scriptName) in D:\a\ShokoServer\ShokoServer\Shoko.Server\Renamer\RenameFileHelper.cs:line 60 at Shoko.Server.Models.SVR_VideoLocal_Place.RenameFile(Boolean preview, String scriptName) in D:\a\ShokoServer\ShokoServer\Shoko.Server\Models\SVR_VideoLocal_Place.cs:line 65 at Shoko.Server.Models.SVR_VideoLocal_Place.RenameIfRequired() in D:\a\ShokoServer\ShokoServer\Shoko.Server\Models\SVR_VideoLocal_Place.cs:line 535
```
## STEPS TO REPRODUCE

1. Have a folder set as both source and destination that looks like this:
![image](https://user-images.githubusercontent.com/6244273/128967618-4a57e27e-684f-4574-95d6-9cf64926299b.png)
![image](https://user-images.githubusercontent.com/6244273/128967660-984a2d8c-3f5f-4559-8623-2f59f3e34c59.png)
2. Restart Shoko Server. The server will start hashing.
3. Look at the logs and see lots of errors.

**Comment by da3dsoul** [comment]
Screenie your import folder settings

**Comment by Ariane-B** [comment]
![image](https://user-images.githubusercontent.com/6244273/129116455-cc549306-13e7-4a65-8b03-0fbbfa42f177.png)
![image](https://user-images.githubusercontent.com/6244273/129116476-608f02b3-43ca-42f9-8e84-04037fe3e1f1.png)

**Comment by da3dsoul** [comment]
Are you trying to move files or just rename?

**Comment by Ariane-B** [comment]
I'm not sure. I just want it to organize my folder, and what most of those options do is unclear to me.

What it basically is: qBittorrent downloads anime straight into the folder (the files in the bottom of this screenshot)

![image](https://user-images.githubusercontent.com/6244273/129118034-4a63bb15-b764-48f2-94e4-2d5933ee304c.png)

...and I want them to be organized in a way Jellyfin will understand. I don't *really* care how. But I supposed "move" is probably somewhat required since Jellyfin has a lot less trouble figuring out what belongs together as a series if they're grouped into subfolders.

...So, I guess, both rename and move so that it makes subfolders?

**Comment by da3dsoul** [comment]
Then you want two folders. One is a source. The other is a destination.
qbittorrent can get in the way if it's seeding from the folder. I recommend things like deluge's copy on complete plugin to avoid shoko and the torrent client fighting over the files. There may be a similar thing for qbittorrent. Idk I don't use it.
The both option for import folders is more meant for custom renamer plugins.

**Comment by Ariane-B** [comment]
Thanks for your help! In case someone else has my problem, here's what I did in detail.

- Create three folders like this:
  ![image](https://user-images.githubusercontent.com/6244273/129123256-d2daebca-b474-4170-a53f-7a66c2000dd4.png)
  - Anime (The final destination for everything in its well-organized version. Only Shoko and Jellyfin touch this.)
  - anime-downloads-raw (Where qbittorrent downloads and seeds stuff. Shoko and Jellyfin don't even know this folder exists.)
  - anime-downloads-complete (Where qbittorrent copies finished files, and Shoko's source folder. Files only stay here for a second before Shoko grabs them. Jellyfin doesn't know this folder exists.)
- Set anime-downloads-complete as a **source** import folder in Shoko Server. Watch for new files is **enabled**.
- Set Anime as a **destination** import folder in Shoko Server. Watch for new files is **disabled**.
  ![image](https://user-images.githubusercontent.com/6244273/129123317-7087fec5-988f-4a75-bb25-b741f55fc386.png)
- In qbittorrent > Settings > Downloads, set the default save path to anime-downloads-raw if anime is the main thing you download. If not, you can set the folder as the destination for a category. [More info on qbittorrent categories](https://www.ghacks.net/2016/06/20/qbittorrent-advanced-saving-management/)
  ![image](https://user-images.githubusercontent.com/6244273/129123339-02f39cc6-0208-4717-aa1e-03a0f2a67cab.png)
- In qbittorrent > Settings > Downloads (at the very bottom), turn on "Run external program on torrent completion". You may also want to turn on "Show console window" so there's SOME visual feedback of the copy happening. Use the following command (or a variation of it for your specific folder structure) to copy your completed anime into anime-downloads-complete.
  ```cmd
  cmd /c robocopy "%D" "%UserProfile%\Videos\anime-downloads-complete" "%N"
  ```
  ![image](https://user-images.githubusercontent.com/6244273/129123376-03d3c519-8a0f-4c5c-9a9a-4956b0089d60.png)

*Note: Change `/c` to `/k` in the command line if you want the console window to remain open even after the copy has ended.*

**Comment by da3dsoul** [comment]
You can also use hardlinks in that case, and the files will only take the space of one copy of the file. Mklink on Windows can do it, I believe

**Comment by Ariane-B** [comment]
Then qbittorrent and Shoko wouldn't interfere with each other even though they would be using the same file? That's interesting. Less space taken up. The advantage of easier cleanup when the system drive gets full is attractive too.

It really has to be a hard link though? A symbolic link wouldn't do?

**Comment by da3dsoul** [comment]
Yeah, after it's finished, both only actually read the data itself. Shoko needs to be able to move it, but moving a link won't change the underlying data. libtorrrent just gets locks that can interfere with other things, probably on purpose, as you wouldn't want to seed corrupt files

**Comment by Ariane-B** [comment]
I tried it manually at first. I created a hardlink like this:

```cmd
cmd /c mklink /h "%UserProfile%\Videos\anime-downloads-complete\[SubsPlease] Heion Sedai no Idaten-tachi - 05 (1080p) [945D7FEB].mkv" "%UserProfile%\Videos\anime-downloads-raw\[SubsPlease] Heion Sedai no Idaten-tachi - 05 (1080p) [945D7FEB].mkv"
```

But in the server's logs, it said this:
```
2021-08-12T22:36:51.4705728Z
New file detected: C:\Users\azma\Videos\anime-downloads-complete\[SubsPlease] Heion Sedai no Idaten-tachi - 05 (1080p) [945D7FEB].mkv: Created
2021-08-12T22:36:51.4705728Z
Found file C:\Users\azma\Videos\anime-downloads-complete\[SubsPlease] Heion Sedai no Idaten-tachi - 05 (1080p) [945D7FEB].mkv
2021-08-12T22:36:57.4584786Z
Could not access file: C:\Users\azma\Videos\anime-downloads-complete\[SubsPlease] Heion Sedai no Idaten-tachi - 05 (1080p) [945D7FEB].mkv
2021-08-12T22:36:57.4584786Z
```

**Comment by Ariane-B** [comment]
I manually copied a file into my source folder, and while it did move it, it threw an error in the logs, and seems to have failed at renaming it.

The logs look like this:

```
2021-08-12T23:50:20.8321073Z
New file detected: C:\Users\azma\Videos\anime-downloads-complete\[SubsPlease] Heion Sedai no Idaten-tachi - 05 (1080p) [945D7FEB].mkv: Created
2021-08-12T23:50:20.8321073Z
Found file C:\Users\azma\Videos\anime-downloads-complete\[SubsPlease] Heion Sedai no Idaten-tachi - 05 (1080p) [945D7FEB].mkv
2021-08-12T23:50:26.8852696Z
Hashing File: C:\Users\azma\Videos\anime-downloads-complete\[SubsPlease] Heion Sedai no Idaten-tachi - 05 (1080p) [945D7FEB].mkv
2021-08-12T23:50:40.3064514Z
Starting Updating STATS for SERIES Heion Sedai no Idaten-tachi - Watched Stats: True, Missing Episodes: True, Update Group Stats: True
2021-08-12T23:50:40.5123898Z
Starting Updating STATS for GROUP Heion Sedai no Idaten-tachi from Top Level (recursively) - Watched Stats: True, Missing Episodes: True, Groups Only: True
2021-08-12T23:50:40.5123898Z
Starting Updating STATS for GROUP Heion Sedai no Idaten-tachi - Watched Stats: True, Missing Episodes: True
2021-08-12T23:50:40.5474352Z
Paused Filesystem Watching
2021-08-12T23:50:40.5474352Z
Moving file from C:\Users\azma\Videos\anime-downloads-complete\[SubsPlease] Heion Sedai no Idaten-tachi - 05 (1080p) [945D7FEB].mkv to C:\Users\azma\Videos\Anime\Heion Sedai no Idaten-tachi\[SubsPlease] Heion Sedai no Idaten-tachi - 05 (1080p) [945D7FEB].mkv
2021-08-12T23:50:40.5605198Z
Unpaused Filesystem Watching
2021-08-12T23:50:40.5605198Z
System.Exception: *Error: No script available for renamer at Shoko.Server.Renamer.LegacyRenamer.GetFilename(RenameEventArgs args) in D:\a\ShokoServer\ShokoServer\Shoko.Server\Renamer\LegacyRenamer.cs:line 30 at Shoko.Server.RenameFileHelper.GetFilename(SVR_VideoLocal_Place place, String scriptName) in D:\a\ShokoServer\ShokoServer\Shoko.Server\Renamer\RenameFileHelper.cs:line 60 at Shoko.Server.Models.SVR_VideoLocal_Place.RenameFile(Boolean preview, String scriptName) in D:\a\ShokoServer\ShokoServer\Shoko.Server\Models\SVR_VideoLocal_Place.cs:line 65 at Shoko.Server.Models.SVR_VideoLocal_Place.RenameIfRequired() in D:\a\ShokoServer\ShokoServer\Shoko.Server\Models\SVR_VideoLocal_Place.cs:line 535
2021-08-12T23:50:40.5925426Z
Processing CommandRequest_AddFileToMyList: [SubsPlease] Heion Sedai no Idaten-tachi - 05 (1080p) [945D7FEB].mkv - 8B4D02B4213AB4AC1A9BD009431C281B - True
2021-08-12T23:50:42.2540057Z
Added File to MyList. File: [SubsPlease] Heion Sedai no Idaten-tachi - 05 (1080p) [945D7FEB].mkv Manual Link: False Watched Locally: False Watched AniDB: False Local State: HDD AniDB State: HDD ReadStates: True ReadWatched Setting: True ReadUnwatched Setting: True
2021-08-12T23:50:42.4246977Z
Starting Updating STATS for SERIES Heion Sedai no Idaten-tachi - Watched Stats: True, Missing Episodes: True, Update Group Stats: True
2021-08-12T23:50:42.6233204Z
Starting Updating STATS for GROUP Heion Sedai no Idaten-tachi from Top Level (recursively) - Watched Stats: True, Missing Episodes: True, Groups Only: True
2021-08-12T23:50:42.6233204Z
Starting Updating STATS for GROUP Heion Sedai no Idaten-tachi - Watched Stats: True, Missing Episodes: True
```

My folder for that show looks like this currently:

![image](https://user-images.githubusercontent.com/6244273/129284343-f4fd2826-ee24-4025-8004-2b1f405e4953.png)

**Comment by Cazzar** [comment]
That error you are mentioning there is simply the fact you have renaming enabled, but the Legacy Renamer that is selected has an empty script.

Are you able to show the renamer section in Shoko Desktop to confirm this?

**Comment by Ariane-B** [comment]
Found it!

![image](https://user-images.githubusercontent.com/6244273/129426522-367e3867-3fae-4abd-b695-535353c851e7.png)

So, is that bad? How do I get renaming back to how it was before I split my folders into two?

**Comment by chocoboSan** [comment]
A bit grave digging on your issue but hoping it may help. I was facing the same problem and it got solved by (on the screen of the screenshot you provided) click save (I also had a checkbox and checked it). Then it could find the script to run !

Weird.

**Comment by revam** [comment]
Closing this as it seems to be resolved. 

@Ariane-B did you ever manage to merge the two split libraries back together, or do you still need help with that? If yes, then we can continue in this issue (but please keep it closed, since it's unrelated to the issue title), continue in a new issue, or hop into the #support channe in discord (if you haven't already received help over there).

**Comment by Ariane-B** [comment]
It was a while ago and I forgot, but I think it ended up being fine! Well, it works fine these days, so it's probably okay.
