### ISSUE TITLE
AniDB (110): Connection timed out

### ISSUE THREAD

**Issue by orophix** [ShokoAnime/ShokoServer#891]
- ﻿## PLEASE READ BEFORE POSTING YOUR ISSUE

Please create GitHub issues only for bugs and feature requests. If you need help with using Shoko or have a question, join us on Discord.

https://discord.gg/vpeHDsg

===== Guidelines ====

- Make sure you are using the latest **Stable** or **Daily** version of Shoko Server otherwise your issue will be closed.
- Search this repository (top of the page) for the issue or feature you are reporting, make sure it has not been fixed or reported before.
- If reporting an issue, then you must attach the relevant Shoko Server and Shoko Desktop **LOG FILE**. 
- If requesting a new feature, please explain in detail the feature itself and the benefits of it being added.
- If requesting cosmetic changes, please explain in detail why they should be made. 
- The template below **MUST BE USED** when submitting an issue, no exceptions.

## VERSION INFORMATION

Server Version: Shoko Server Version: v4.1.0.0

Desktop Version: 

If you've compiled your own version, please use the last commit you compiled.

## LOG FILE

```
shokoserver     | 09:58:11| --- Time since last request is 60998 ms, not throttling.
shokoserver     | 09:58:42| --- System.Net.Sockets.SocketException (110): Connection timed out
shokoserver     |    at System.Net.Sockets.Socket.ReceiveFrom(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint& remoteEP)
shokoserver     |    at AniDBAPI.Commands.AniDBUDPCommand.ProcessCommand(Socket& soUDP, IPEndPoint& remoteIpEndPoint, String sessionID, Encoding enc) in /usr/src/app/source/Shoko.Server/AniDB_API/Commands/AniDBUDPCommand.cs:line 39
shokoserver     | 09:58:42| --- error in login: System.Net.Sockets.SocketException (110): Connection timed out
shokoserver     |    at System.Net.Sockets.Socket.ReceiveFrom(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint& remoteEP)
shokoserver     |    at AniDBAPI.Commands.AniDBUDPCommand.ProcessCommand(Socket& soUDP, IPEndPoint& remoteIpEndPoint, String sessionID, Encoding enc) in /usr/src/app/source/Shoko.Server/AniDB_API/Commands/AniDBUDPCommand.cs:line 39
shokoserver     | 09:58:44| --- AniDB Login Failed: error connecting to AniDB: System.Net.Sockets.SocketException (110): Connection timed out
shokoserver     |    at System.Net.Sockets.Socket.ReceiveFrom(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint& remoteEP)
shokoserver     |    at AniDBAPI.Commands.AniDBUDPCommand.ProcessCommand(Socket& soUDP, IPEndPoint& remoteIpEndPoint, String sessionID, Encoding enc) in /usr/src/app/source/Shoko.Server/AniDB_API/Commands/AniDBUDPCommand.cs:line 39

```
## DESCRIPTION

Unable to login to anidb for first time setup. Tested both latest and daily. Turned off firewall with DMZ.

## STEPS TO REPRODUCE

As above

**Comment by Cazzar** [comment]
Likely cause of this could be the fact of a UDP ban from AniDB, which are generally temporary, if you fail logging in too many times, they just don't respond to the request.

If the issue is going on, get in touch with us on discord.
