### ISSUE TITLE
Mediainfo error when filename contains quotes

### ISSUE THREAD

**Issue by arucard21** [ShokoAnime/ShokoServer#892]
Server Version: 4.1.0.0 (on Linux, using Docker image through docker-compose)

## LOG FILE

```
2021-08-26 13:56:08
MediaInfo threw an error on /mnt/anime/Gintama/Gintama - 075 - Someone Said "Don`t Complain About Your Job at Home, Do It Somewhere Else" So Let Me Complain. It`s Already Been a Year Since This Anime, Which Began with....mkv: No message
2021-08-26 13:56:08
File /mnt/anime/Gintama/Gintama - 075 - Someone Said "Don`t Complain About Your Job at Home, Do It Somewhere Else" So Let Me Complain. It`s Already Been a Year Since This Anime, Which Began with....mkv failed to read MediaInfo
```

## DESCRIPTION

When importing the files, the log shows that MediaInfo could not be run. This seems to occur when the file contains quotes in the filename. I confirmed this with a filename containing double-quotes ,i.e. `"`,  (not the file from the log provided above) by removing the quotes. After removing the quotes and importing it again, the error no longer occurs. So it seems like the filename would need to be escaped correctly. This is on a Linux system so the filenames allow more characters than on Windows (I think).

## STEPS TO REPRODUCE
* Create an import folder with a file containing double-quotes
* Scan the import folder
  * Without renaming or moving the files. I'm not sure if this matters but this is how I have it configured
* Check the log for the error similar to the log provided above. 
Being as detailed as possible, please list all steps need to reproduce the issue, if we can't reproduce it then we can't fix it.

**Comment by arucard21** [comment]
Yeah, this is the episode with the really long title. But it did get truncated because that's just what any sane renaming tool should do. In the logs and stuff I posted, you'll see that the title in my filename is less than a third of the full title on AniDB. So the filename length shouldn't be the problem, it really seems to be due to the quotes. I've also seen this with other files. I just happened to post the log for what's apparently the most problematic episode title in anime history :smile: 

So I'm hoping you can still fix the problem with the quotes.

**Comment by da3dsoul** [comment]
what sub group is that?

**Comment by arucard21** [comment]
You mean the fansub group for this episode? It's called "DB", this is their AniDB group page:
https://anidb.net/group/14643
The file I have should be this one:
https://anidb.net/file/1994671

**Comment by arucard21** [comment]
I actually tried reproducing the bug with the code here:
https://dotnetfiddle.net/7r0ox1
I tried creating a JSON from the field with the filename and the other field which has a really long value, from the MediaInfo JSON output I posted above.

I don't know that much C# though, and I can't even figure out how to read the `@ref` field from the JSON (due to the `@` character which I assume you can't use as a variable. But it still seems to parse it and is able to return the other field. So I'm not sure what the problem is, really.

**Comment by da3dsoul** [comment]
Yeah you can't use that as a variable. You use an attribute to apply a name for that. I don't think it's the name or the encoder settings causing it, but I'll grab that file and test with it.

**Comment by da3dsoul** [comment]
https://dotnetfiddle.net/DtLBny
Yeah, that's not the issue.

**Comment by harshithmohan** [comment]
I was looking into it because I was bored.
So nothing's wrong with parsing. There is nothing to parse.. That's the JSON output from mediainfo

```
02:26:15| --- Getting media info for: /downloads/Gintama - 075 - Someone Said "Don`t Complain About Your Job at Home, Do It Somewhere Else" So Let Me Complain. It`s Already Been a Year Since This Anime, Which Began with....mkv
02:26:15| --- {
"creatingLibrary": {
"name": "MediaInfoLib",
"version": "21.09",
"url": "https://mediaarea.net/MediaInfo"
},
"media": null
}
02:26:15| --- MediaInfo threw an error on /downloads/Gintama - 075 - Someone Said "Don`t Complain About Your Job at Home, Do It Somewhere Else" So Let Me Complain. It`s Already Been a Year Since This Anime, Which Began with....mkv: System.NullReferenceException: Object reference not set to an instance of an object.
   at Shoko.Server.Utilities.MediaInfoLib.MediaInfo.GetMediaInfo_New(String filename) in /usr/src/app/source/Shoko.Server/Utilities/MediaInfoLib/MediaInfo.cs:line 65
```

**Comment by harshithmohan** [comment]
... that was not supposed to be closed

**Comment by harshithmohan** [comment]
Anyway,
@arucard21 Test the latest daily

@da3dsoul The backtick is not supposed to be escaped. Shoko should've thrown this error.
![image](https://user-images.githubusercontent.com/26010946/134825339-9ff0b875-2ea1-4ba8-a484-a5cfbc153311.png)

**Comment by arucard21** [comment]
@harshithmohan Just tested it with the latest daily and that indeed seems to have fixed it. Thank you for the help. 
```
Getting media info for: /mnt/anime/Gintama/Gintama - 075 - Someone Said "Don`t Complain About Your Job at Home, Do It Somewhere Else" So Let Me Complain. It`s Already Been a Year Since This Anime, Which Began with....mkv
```
Got this in the log with no error being thrown.
