### ISSUE TITLE
WebUI is lying about FirstRun while API is in booting mode.

### ISSUE THREAD

**Issue by bigretromike** [ShokoAnime/ShokoServer#910]
## VERSION INFORMATION

Server Version: 4.1.1.0 (WebUI 1.1.1-dev7)

Desktop Version: -

If you've compiled your own version, please use the last commit you compiled.

## LOG FILE

ATTACH YOUR LOGS HERE

## DESCRIPTION

After upgrading from 4.1.0.0 to 4.1.1.0 (probably doesn't matter which version), server is telling me thru webui that he need to FirstRun. Webui is up and running but any attempt to login results in "
"The Server is not running. Use the First Time Setup Wizard or check your settings and logs to ensure the server is starting correctly." which is wrong because server is still booting. I had this issue once or twice before, also I saw normal "booting" status in webui few times, so there is something wrong because I would expect to work 100%.
![obraz](https://user-images.githubusercontent.com/6052025/140623886-5b795460-9fb1-4adb-98fe-ed7987963ac4.png)

While API is clearly telling me that server is doing something, in Nakamori I can see that servers is booting up:
![obraz](https://user-images.githubusercontent.com/6052025/140623873-759c666c-649b-45a4-8a8d-11e10768911f.png)

edit: I tried refreshing, i tried deleting cache and refreshing, only entering with different browser that I dont use as daily driver results in proper "server is starting. please wait" tried on 3 computers - only on same results, daily driver have broken login screen, "edge" is fine - something with routing/caching ?

## STEPS TO REPRODUCE

Being as detailed as possible, please list all steps need to reproduce the issue, if we can't reproduce it then we can't fix it.

**Comment by Cazzar** [comment]
If it’s a webui thing, this needs to be logged in the webui repo, not the server repo
