### ISSUE TITLE
Auxiliary items like BD menu files or files otherwise not admitted to anidb should be recognized by Shoko using a secondary DB

### ISSUE THREAD

**Issue by GlassedSilver** [ShokoAnime/ShokoServer#925]
## DESCRIPTION

It would be quite a lovely feature to be able to use BD menu files either through manual linking or by having a secondary DB for those file hashes not admitted to anidb (because they are BD menu files or because mods don't want them or whatever but that are legitimate parts of a BD or such) so we could later on make use of them in various ways.

BD Menu files could be used for backdrops for example. Alternatively ads could be handy to include in media managers for pre-rolled videos like how you can pre-roll trailers in Plex.

There's plenty of stuff that doesn't get recognized by anidb all the time, lots of which might not make the cut there, but could serve for theming the experience within media managers like Jellyfin, Plex and Emby.

## STEPS TO REPRODUCE

n/a

___

**Reference:** As Discussed on our Discord [here](https://discord.com/channels/96234011612958720/96234011612958720/952248451540848691). (topic starts a little before it, gets to the gist of it a little bit after that message - it was a bit of an brainstorming process in that moment)

**Comment by Cazzar** [comment]
The initial and immediate thought that comes to mind, is where would we even get said data? AniDB works so well for us because we already have known good hashes, but I am aware of nowhere else that would give us such a reliable source for things like BD/DVD Menus

**Comment by GlassedSilver** [comment]
> The initial and immediate thought that comes to mind, is where would we even get said data? AniDB works so well for us because we already have known good hashes, but I am aware of nowhere else that would give us such a reliable source for things like BD/DVD Menus

I was thinking that Shoko could run a DB like this itself... PURELY for non-anidb hashes. Also except for manual, personal links for the hash to become part of a DB it would need to be submitted by various users, so it should be somewhat legit before you tell every user a given hash is this or that.

Full-on moderation might not be worth it, but having basically "swarm intellligence" should be reasonable for what is not mission-critical metadata. Again, this is ONLY for non-essential files like BD menus and such.

**Comment by ElementalCrisis** [comment]
This would be a lot of work for a relatively obscure feature. 

I don't think the time and actual monetary cost for hosting what essentially is a web cache would be worth it.

**Comment by bigretromike** [comment]
@GlassedSilver that would be awesome. I been fighting with anidb about being able to submit ads that contains games/toys from many many series, sadly they always remove them (but for a brief moment you can add them, sync them and have them "cached" in shoko - but that is not a solution). Same thing with series that are not treated as anime, but animation. 

You have a good point with this "secondary database" but that could also be done by community, not shoko directly. 

You would have to end up with almost anidb-clone for non-anidb data, that or adding to shoko ability to make yourself those "manual link for non existing episodes that you can name of"

**Comment by GlassedSilver** [comment]
> @GlassedSilver that would be awesome. I been fighting with anidb about being able to submit ads that contains games/toys from many many series, sadly they always remove them (but for a brief moment you can add them, sync them and have them "cached" in shoko - but that is not a solution). Same thing with series that are not treated as anime, but animation.
> 
> You have a good point with this "secondary database" but that could also be done by community, not shoko directly.
> 
> You would have to end up with almost anidb-clone for non-anidb data, that or adding to shoko ability to make yourself those "manual link for non existing episodes that you can name of"

The database could also be an SQLite or set of JSON that you download once every few weeks rather than keeping a constant API-accessible platform running.

Submissions might be done through a GitHub repo?

I mean just throwing out ideas here. I'm not versed enough to really give advice on implementation here, it's mostly about the swarm intelligence aspect.

A first start (and a precursor to having a crowd-powered db at all) could be to be able to mark unrecognized files as these sorts of files from Shoko. Shoko keeps a local track record of them and store links to anidb IDs, item type, hashes and possibly other needed info. Then when a platform is conceptualized you could start off with dedicated users who cherish this concept as beta testers and initial source for data.

If only the most popular shows and their most frequently used releases (which often lead in users flogging to them by a long shot) populate this kind of data you may disproportionally improve the metadata and theming experience in media managers like Plex/JF/Emby. :)
