### ISSUE TITLE
Unable to get Episode Error

### ISSUE THREAD

**Issue by SomeRandomDude870** [ShokoAnime/ShokoServer#926]
﻿## PLEASE READ BEFORE POSTING YOUR ISSUE

Please create GitHub issues only for bugs and feature requests. If you need help with using Shoko or have a question, join us on Discord.

https://discord.gg/vpeHDsg

===== Guidelines ====

- Make sure you are using the latest **Stable** or **Daily** version of Shoko Server otherwise your issue will be closed.
- Search this repository (top of the page) for the issue or feature you are reporting, make sure it has not been fixed or reported before.
- If reporting an issue, then you must attach the relevant Shoko Server and Shoko Desktop **LOG FILE**. 
- If requesting a new feature, please explain in detail the feature itself and the benefits of it being added.
- If requesting cosmetic changes, please explain in detail why they should be made. 
- The template below **MUST BE USED** when submitting an issue, no exceptions.

## VERSION INFORMATION

Server Version: 4.1.1

Desktop Version: 1.1.1

## LOG FILE

ATTACH YOUR LOGS HERE

## DESCRIPTION

HI, I have the problem that Shoko wants to index/rename Files that are not there anymore. We are talking here about dozens of files.

BTW: Shoko shows me that the Drop Source has 100GB, but in the Filesystem it only has 84GB.

>  2022-04-18T17:20:37.4242462Z
> File D:\3xxxxx.mp4 failed to read MediaInfo
> 2022-04-18T17:20:37.8226668Z
> Could not find a valid destination: D:\xxxx\xxxxx\xxxx.mp4
> 2022-04-18T17:20:37.8226668Z
> System.Exception: *Error: Unable to get episode for file at Shoko.Server.Renamer.LegacyRenamer.GetNewFileName(RenameEventArgs args, String script) in E:\Documents\GitHub\ShokoServer\Shoko.Server\Renamer\LegacyRenamer.cs:line 1335 at Shoko.Server.Renamer.LegacyRenamer.GetFilename(RenameEventArgs args) in E:\Documents\GitHub\ShokoServer\Shoko.Server\Renamer\LegacyRenamer.cs:line 33 at Shoko.Server.RenameFileHelper.GetFilename(SVR_VideoLocal_Place place, String scriptName) in E:\Documents\GitHub\ShokoServer\Shoko.Server\Renamer\RenameFileHelper.cs:line 60 at Shoko.Server.Models.SVR_VideoLocal_Place.RenameFile(Boolean preview, String scriptName) in E:\Documents\GitHub\ShokoServer\Shoko.Server\Models\SVR_VideoLocal_Place.cs:line 65 at Shoko.Server.Models.SVR_VideoLocal_Place.RenameIfRequired() in E:\Documents\GitHub\ShokoServer\Shoko.Server\Models\SVR_VideoLocal_Place.cs:line 528
> 2022-04-18T17:20:39.9488088Z
> Could not find a valid destination: D:\xxxx\Bxxx[x\xxx.mp4
> 2022-04-18T17:20:39.9488088Z
> System.Exception: *Error: Unable to get episode for file at Shoko.Server.Renamer.LegacyRenamer.GetNewFileName(RenameEventArgs args, String script) in E:\Documents\GitHub\ShokoServer\Shoko.Server\Renamer\LegacyRenamer.cs:line 1335 at Shoko.Server.Renamer.LegacyRenamer.GetFilename(RenameEventArgs args) in E:\Documents\GitHub\ShokoServer\Shoko.Server\Renamer\LegacyRenamer.cs:line 33 at Shoko.Server.RenameFileHelper.GetFilename(SVR_VideoLocal_Place place, String scriptName) in E:\Documents\GitHub\ShokoServer\Shoko.Server\Renamer\RenameFileHelper.cs:line 60 at Shoko.Server.Models.SVR_VideoLocal_Place.RenameFile(Boolean preview, String scriptName) in E:\Documents\GitHub\ShokoServer\Shoko.Server\Models\SVR_VideoLocal_Place.cs:line 65 at Shoko.Server.Models.SVR_VideoLocal_Place.RenameIfRequired() in E:\Documents\GitHub\ShokoServer\Shoko.Server\Models\SVR_VideoLocal_Place.cs:line 528
> 2022-04-18T17:20:42.0013287Z

The problem is that those files don´t exist anymore in this Location. I am not sure why it still wants to move/index them. That happens even after a restart.

> Could not find a valid destination: D:\new\xxxxxmkv
> 2022-04-18T17:25:53.4143347Z
> System.Exception: *Error: Unable to get episode for file at Shoko.Server.Renamer.LegacyRenamer.GetNewFileName(RenameEventArgs args, String script) in E:\Documents\GitHub\ShokoServer\Shoko.Server\Renamer\LegacyRenamer.cs:line 1335 at Shoko.Server.RenameFileHelper.GetFilename(SVR_VideoLocal_Place place, String scriptName) in E:\Documents\GitHub\ShokoServer\Shoko.Server\Renamer\RenameFileHelper.cs:line 60 at Shoko.Server.Models.SVR_VideoLocal_Place.RenameFile(Boolean preview, String scriptName) in E:\Documents\GitHub\ShokoServer\Shoko.Server\Models\SVR_VideoLocal_Place.cs:line 65 at Shoko.Server.Models.SVR_VideoLocal_Place.RenameIfRequired() in E:\Documents\GitHub\ShokoServer\Shoko.Server\Models\SVR_VideoLocal_Place.cs:line 535
> 2022-04-18T17:25:55.4710688Z
> Could not find a valid destination: D:\new i\xxxxxx.mkv
> 2022-04-18T17:25:55.4783355Z
> System.Exception: *Error: Unable to get episode for file at Shoko.Server.Renamer.LegacyRenamer.GetNewFileName(RenameEventArgs args, String script) in E:\Documents\GitHub\ShokoServer\Shoko.Server\Renamer\LegacyRenamer.cs:line 1335 at Shoko.Server.RenameFileHelper.GetFilename(SVR_VideoLocal_Place place, String scriptName) in E:\Documents\GitHub\ShokoServer\Shoko.Server\Renamer\RenameFileHelper.cs:line 60 at Shoko.Server.Models.SVR_VideoLocal_Place.RenameFile(Boolean preview, String scriptName) in E:\Documents\GitHub\ShokoServer\Shoko.Server\Models\SVR_VideoLocal_Place.cs:line 65 at Shoko.Server.Models.SVR_VideoLocal_Place.RenameIfRequired() in E:\Documents\GitHub\ShokoServer\Shoko.Server\Models\SVR_VideoLocal_Place.cs:line 535

And this part happens when the files do not have a hash on anidb. Should there be an error thrown? 

## STEPS TO REPRODUCE

For the first... When it wants to move files that are not here any longer.
And the 2nd.. When it wants to move files that have no matching Hash. But I believe that this shouldn´t be an Error, just a Notification.

**Comment by da3dsoul** [comment]
I agree that your suggestions are probably better.
The renaming system has gone through a few design changes in beta recently, and we're trying to figure out how to do it better in general.

Hit Remove Missing Files to clean up the entries that no longer exist on the disk. Change your deletion settings if you don't want them removed or marked as deleted from AniDB.
