### ISSUE TITLE
Mass Delete Duplicates?

### ISSUE THREAD

**Issue by SomeRandomDude870** [ShokoAnime/ShokoServer#927]
## VERSION INFORMATION

Server Version: 4.1.1

Desktop Version: 1.1.1

## LOG FILE

..

## DESCRIPTION

Yeah, so. I have 400 duplicate Files and since Shoko already renamed them I can´t just filter them out with a simple cmd command.
There is already an "automatically delete multiple files" Function. Would it be possible to add something like that for Duplicates? That should be even easier since those are just the same Files...

...Do you have any idea how I could delete all those Duplicates now?..

## STEPS TO REPRODUCE

-

**Comment by da3dsoul** [comment]
The easy way is with drop folders, as shoko will delete incoming duplicates instead of moving them. Otherwise, I don't think there's a nice delete all button

**Comment by SomeRandomDude870** [comment]
You  mean setting my Drop Destination as Both and then rerun Import?

**Comment by da3dsoul** [comment]
No, it needs to be a valid setup. The easiest one I can think of is, assuming you don't use them already, setting your current folder as a destination, then a random other place as a source, tell it to watch for new files, then moving the files into the source. It'll automatically reprocess them and clean it up. If it didn't put things where you want them, then you can move them to the desired place and run an import. It'll fix the paths.

**Comment by SomeRandomDude870** [comment]
I have done what you said, but it just copies the duplicate Files too.
Is there a Setting I have to change?

**Comment by da3dsoul** [comment]
No, I assume if the they are copying, then they aren't duplicates. Duplicate is the same file, bit for bit.

**Comment by SomeRandomDude870** [comment]
I have done what you said, but it just copies the duplicate Files too.
Is there a Setting I have to change?

l just used an external Programm to find Dupes.

**Comment by da3dsoul** [comment]
To be fair, external programs have their own way of doing things. Shoko won't count a dupe if it's even a single bit different. It's hard to say what it's doing. There isn't a setting or anything. It'll tell you what it's doing in the log. You can enable trace logging in the json for even more info.

**Comment by revam** [comment]
Don't we have utilities to manually visualise any multiple entries  (soft duplicates) or bit-for-bit copies (hard duplicates)?

Can i close this?

**Comment by da3dsoul** [comment]
Yeah the problem and solution were inconclusive. I expect that it was a problem with the setup
