### ISSUE TITLE
How to move Shoko Database and Settings?

### ISSUE THREAD

**Issue by SomeRandomDude870** [ShokoAnime/ShokoServer#932]
Hi, yeah not an Issue, but kinda...

I currently have everything on Win10 and I would like to migrate to my Unraid Server.
What would I have to do to do so?

I would rather not begin anew since I already defined several unmatched Anime..

**Comment by revam** [comment]
> I'm not going to hold anyone's hand in a GitHub issue. It's not a great place for back and forth chatting.

He will hold your hand in the discord #support channel though.

**Comment by revam** [comment]
Didn't mean to close it

**Comment by SomeRandomDude870** [comment]
I mean, I need time to execute your Instructions anyway...

First, Where is the database File? Neither in the Shoko Installation Path nor in Appdata is a sqlite or db File.

**Comment by bigretromike** [comment]
`c:\programdata\ShokoServer\SQLite\`  database if you didnt change anything
`c:\programdata\ShokoServer\` config file

**Comment by SomeRandomDude870** [comment]
Uff, sorry for ghosting. I got ill and then forgot about this...

Do I need anything else than to change the Path of the Files? Couldn´t I just copy the Anime Tables without the pictures and then reload them in the program?

**Comment by ElementalCrisis** [comment]
I'll assume they joined Discord for additional help or figured out any additional issue on their own.
