### ISSUE TITLE
Better "Continue Watching..."

### ISSUE THREAD

**Issue by misakitchi** [ShokoAnime/ShokoServer#94]
In JMM Desktop, in list "Continue Watching..."
We don't know if its a "normal episode", a "special" or other

Is it possible to add information on what it is? Like E18, S1, C2, T3...

And can you add an option to show only "normal episode" in "Continue Watching..."?
Or to select what we want to see: episode, normal, trailer, credits...

Its possible to have a global option or better if by each serie

Lots of Thanks! :)

**Comment by bigretromike** [comment]
@ElementalCrisis this should probably be in ShokoDesktop :P

**Comment by ElementalCrisis** [comment]
Probably but this might have been a bug, @misakitchi can you check on latest version and tell me if Continue Watching lists a Credit or Special after you've marked all episodes as watched?
