### ISSUE TITLE
Missing MyList files tool not working properly

### ISSUE THREAD

**Issue by jmediamanager** [ShokoAnime/ShokoServer#957]
**Reported by themountain632, Today (9 hours ago)**

_What steps will reproduce the problem?_
1. Scan for missing files
2. Remove ALL entries

_What is the expected output? What do you see instead?_
Should have removed all bad my list entries. Instead nothing happened

_Please provide any additional information below._
I ran out of space on a couple of my HDD's so I moved some data around. I went through the process of re-hashing my entire collection and adding the data to my list.

However, I noticed afterwards there were 200 or so entries that the tool would not remove.

I also noticed some of the information the tool was generating was suspect (included in jpg). 

Please fix at your earliest convenience.

![missing data](https://cloud.githubusercontent.com/assets/6645153/3977232/f5fbeb76-2834-11e4-8e41-60f33ecb9f72.jpg)

**Comment by ElementalCrisis** [comment]
@da3dsoul are we brining over the utility?

**Comment by da3dsoul** [comment]
We might fully redesign it, but that's a future thing
