### ISSUE TITLE
Feature Request: New Filter Condition - Filter by Import Folder/Folder

### ISSUE THREAD

**Issue by Darken5** [ShokoAnime/ShokoServer#958]
Filter option to show/not show series by which "Import Folder" or just what "Folder" they are in.

**Comment by revam** [comment]
\*_7 years later_\*

Still no time to take a look at it? Or is it too involved? @da3dsoul 

And on a more serious not; should I close this issue or do you want to implement it?

**Comment by da3dsoul** [comment]
Adding group filters is a pita, so I've not done it in 7 years. Leave it open, because it's not done, and it should be eventually.
