### ISSUE TITLE
host playstates on server after file deletion (or not importing at all)

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoServer#959]
i think JMM should keep all playstates from AniDB, MAL and Trakt on its server at all time, not just when you have the files add to the server. the playstates should be there even if you delete the file, or havent imported it (like if you watched it before this install of JMM or something like that).
this will require a full sync of all these sites from the user tho. ofc they only need to do it once.

**Comment by harshithmohan** [comment]
"feature creep and worthless to 99% of our users." - EC, 2022
