### ISSUE TITLE
hid-able/block custom tags per user

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoServer#961]
we should be able to hide or block all content with certain tags (like custom tags) on a per user basis, this should also work across all clients (fails to work with the plex app ATM)

great for content that isnt for everyone. ok the family pre-made user works at times, but it also blocks alot of stuff that is Anime and not H content, things that might have a sex scene even tho its not H and other stuff. thats why custom tags are great, the user can tag it themself so everything is just right for that user. ofc it doesnt help if you can hide/block the content from other users IMO

**Comment by revam** [comment]
Can confirm that the internals ~~are a mess~~ _tightly tied to a single user_ and will need some refactoring to move the client contracts from the base series/group entries to the user series/group contracts.

**Comment by ElementalCrisis** [comment]
Closing this ticket, this would be a ton of work and not even on the dream list of work we currently have.
