### ISSUE TITLE
renaming to contain CRC code for unknown files?

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoServer#962]
we should be able to have JMM to rename files to contain CRC codes of the file ATM, this is handy for encodes and releases you make yourself.
if you know the file is good and got no issues, but dont have an crc in the name, why not let JMM rename the file so it contains one, makes it easier when you dump the file IMO instead of checking the crc with an external program and renaming before import or using JMM for the crc and then reimport.

**Comment by ElementalCrisis** [comment]
@revam I believe you made it so unrecognized files can be renamed right?

**Comment by revam** [comment]
I made @da3dsoul add it. Though you need a custom renamer that supports it.

**Comment by revam** [comment]
Closing it since it's now possible to do this (provided you use a renamer that supports it)
