### ISSUE TITLE
create series in Related/Similar Tab ask for a search over just adding the one you clicked.

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoServer#963]
create series in Related/Similar Tab ask for a search over just adding the one you clicked.

ATM the add series button shows a search screen instead of just having the search already filled out, or just add it with the name settings you already have.

you already click the add series button that is next to an series, it should add that series and/or atleast auto fill the AniDB ID search. 

this isnt much, but it does add more steps to the process that should be simpler and/or faster.

**Comment by revam** [comment]
I see a point of having empty series, and it's technically possible to do this in the api, but i don't think this will be exposed in (the next veraion of) the web ui.

**Comment by harshithmohan** [comment]
I don't see a point.
You would add an empty series in something like sonarr because otherwise it wouldn't detect the files.
But in shoko, if you have the file, the series will added automatically and if you want to manually link, the series will added while linking.

**Comment by harshithmohan** [comment]
Oops, accidentally closed. 😂

**Comment by revam** [comment]
Then yu have Shokofin while it's generating season entries based on series available in the local collection and part of the shoko groups. If you're missing some series entries in shoko while you add the library in Jellyfin and later add the missing series then it will shift all the season numbers. At least in it's current state.

**Comment by revam** [comment]
Hench why it's better to just have the missing entries in the local collection even if it doesn't contain any files **yet**.
