### ISSUE TITLE
absolute TVDB/Trakt order in Continue watching tile.

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoServer#964]
i noticed the Continue Watching tile (the one in the Collection tab aswell as Pinned tab for each series (the one that shows you the next episode to watch))

like in the screenshot bellow, the Movie got a Prologue that is suppose to be before the Movie itself, its even placed before the Movie in the TVDB/Trakt Special Season as also show in the Screen.

but the Movie is shown before the special (when chronologically it would be the other way IMO (we should atleast have an option for that)) 
![](http://i.imgur.com/GEDkX73.png)

**Comment by ElementalCrisis** [comment]
Something to look into either as default or a setting.

**Comment by harshithmohan** [comment]
This might not be possible, I'm not sure if anidb has the relation data between episodes of a single series saying which comes first and we can't use the airdate to sort because the airdate of the specials might be after the movie air date which is true in this case for One Piece Z

**Comment by revam** [comment]
Welcome to the nightmare known as "episode ordering." 👍 
Also,  we have tvdb data for some series that can be used if it's available.
