### ISSUE TITLE
File Renaming: Remember original file name

### ISSUE THREAD

**Issue by naarcissus** [ShokoAnime/ShokoServer#967]
I would like the **File Renamer** to log and store the original file names before renaming, or(possibly better) to have JMM log and store the original file name on import. This would be useful for **Manually Linked** files.

I have added many files that aren't in _AniDB_ and have renamed them(for consistency and ordering). Recently I've decided I would like to add files to AniDB, but having renamed the files with the **File Renamer**(I have it set up to rename on import) the original designations for **Release Group** are missing. This complicates finding the source and add correct information to _AniDB_.

Having to do with the existing file name it is/could be related to:
- japanesemediamanager/jmmserver#234

**Comment by ElementalCrisis** [comment]
I feel like this was added by @da3dsoul.

**Comment by revam** [comment]
It is stored in the file/episode cross ref table once a ref is made between a file and episode. Also the default anidb file name is stored in the anidb file table.
