### ISSUE TITLE
A place to associate clips and related media to a **Series**

### ISSUE THREAD

**Issue by naarcissus** [ShokoAnime/ShokoServer#968]
I would like a place(or **Type**) to add "unofficial" files to a series entry. To be used for clips downloaded from the internet or homemade clips that may not be associated with a particular episode. For example, I occasionally create clips where I combine all the episodes and cut the all the parts that don't fit my theme. Then I usually add clips from various series to a themed playlist to enjoy on random.

While not ideal, I could just associate my clips with the first episode, but then run into issues like ShokoAnime/ShokoDesktop#311.

Could possibly also be used for music. I know many people are also fans of anime music and may appreciate being able to manage/play their OSTs and custom mixes in JMM.

**Comment by ElementalCrisis** [comment]
Discussed before, not something we will be supporting. They will just show as unrecognized.

**Comment by revam** [comment]
From a functional standpoint it would mayne make sense to add this so we can rely the information to clients (e.g. jellyfin, plex, etc.). But not right now when we're so heavily tied into using anidb as the only data source.
