### ISSUE TITLE
JMM able to manage streamed content

### ISSUE THREAD

**Issue by SL-Gundam** [ShokoAnime/ShokoServer#970]
I like JMM. I use it to manage my watchlists.

One of the issues i have with it is that crunchyroll content which i added to my mylist as "generic file" with the "streamed" type in anidb does not appear in JMM.

I don't need JMM to stream or download, i only need it to see those "generic files" and be able to see them in groups and filters and mark them as watched when applicable

From the discord support chat i heard that there was something in development along these lines. Couldn't find any support ticket about it though so thought i would add it and let you guys know that there are people interested in this functionality

**Comment by harshithmohan** [comment]
Not to be implemented/not possible
