### ISSUE TITLE
Tag Management 

### ISSUE THREAD

**Issue by ElementalCrisis** [ShokoAnime/ShokoServer#972]
As discussed on Discord, I'd like to request additional options for managing our tags, at the moment we can only exclude certain ones from view. 

Here are my suggestions for improving tags:
- The ability to check and remove empty tags.
- Sort options (Alphabetical, Weighted).
- Tag Cloud (Not sure on the location) .

**Comment by revam** [comment]
1. No idea what you mean by empty tags. They shouldn't exist in shoko.
2. We already have that for series tags
3. Didn't you say you didn't want one recently? 

Also, closing this now. Feel free to open it if you still think it's relevant.

**Comment by ElementalCrisis** [comment]
I created this issue 8 years ago, this was still when Desktop was in active development, and we were looking into improving the current block of tags that still exists in Desktop to this day.
