### ISSUE TITLE
Delete all previous/watched episodes? (like Mark as Watched)

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoServer#973]
after just realizing that i hoard Anime at this point without actually watching much anymore i came too that i should delete everything i have already seen but i found that JMM does not actually have a simple way of mass deletion if its an file already in the JMM library (Unrecognized files can do this now but not files that is Recognized by JMM)

we can mark all previous (from what highlighted) episodes as watched like we could now for some time, but we have no way of deleting them. i think this should be an option.
delete all previous episodes (non specials) (highlighted)
delete all watched episodes (non specials) 

with an option like this i think we should use Custom Tags for something good while we are at it, have an official custom tag called Keep that will not be deleted in such ways. and/or let us add a filter ourselfs.

this will work great with these two IMO: https://github.com/japanesemediamanager/jmmclient/issues/170 https://github.com/japanesemediamanager/jmmclient/issues/172

also on the note of space saving/cleaning.
how about a filename parser for the unrecognized files and let JMM compare it to what you have in library already when the times you have dupes that is corrupt. at this point my unrecognized list where to big for me to care and bother getting into to it again (like 2k) so i just deleted them all...... hope i dont regret it XD

**Comment by ElementalCrisis** [comment]
A cataloging system with an option to delete its contents doesn't make sense to me.
