### ISSUE TITLE
Wonky behaviour in "Unrecognized" utility

### ISSUE THREAD

**Issue by Baine** [ShokoAnime/ShokoServer#974]
## VERSION INFORMATION

Server Version: 
docker cazzar/shokoserver:latest
Desktop Version: 
5c0fa8cafc4567ebd6d7a449285640765902eded

## LOG FILE

no logs since no errors or actions logged by desktop

## DESCRIPTION

Using Utilities -> Unrecognized
After adding a new Group/Series the form used to refresh the series list and filter it by the title of the newly added group.
Currently this does not happen.

Also, the sorting of the series list seems to be a bit strange atm,
see the screenshot below as reference
![image](https://user-images.githubusercontent.com/6566469/30118058-4fa7c2a2-9322-11e7-97fb-b164fd88d72e.png)

## STEPS TO REPRODUCE

Open ShokoDesktop, connect to server of choice
Go to Utilities, select Unrecognized
On the right side, click on new Series, follow the steps in the newly opened form

**Comment by harshithmohan** [comment]
@ElementalCrisis can we close this as it'll move to the webui?
Distance calculation in v3 api works properly
