### ISSUE TITLE
Manual Trakt linking does not work anymore

### ISSUE THREAD

**Issue by t0815** [ShokoAnime/ShokoServer#975]
Hi,

i just noticed, that manual Trakt linking does not work anymore. The search function is working, but once you have to select a season and episode, the dropdowns are always empty and nothing can be selected.

![image](https://user-images.githubusercontent.com/10379828/27993618-de89b7bc-64ad-11e7-9872-e71c386e3fc9.png)

Server Log (Desktop log didnt generate any data for that action):

[2017-07-09.txt](https://github.com/japanesemediamanager/ShokoDesktop/files/1133711/2017-07-09.txt)

**Comment by harshithmohan** [comment]
It's working on the latest daily server and stable desktop
