### ISSUE TITLE
Add utility to display files where the local file info and anidb file info are inconsistent

### ISSUE THREAD

**Issue by Kezxo** [ShokoAnime/ShokoServer#976]
Nice to have if you want to fix incorrect stuff on anidb.

**Comment by revam** [comment]
@da3dsoul was dropping a lot of metadata from the anidb file table that was also available locally (there among the resolution) so this will be a lot harder to dp if it's possible at all now.

**Comment by da3dsoul** [comment]
Yeah irrelevant now
