### ISSUE TITLE
Displaying the wrong seiyuu

### ISSUE THREAD

**Issue by SubaruSumeragi** [ShokoAnime/ShokoServer#979]
The UI seems to display the most recent seiyuu for the character instead of the voice actor who played in the show.

Example : Lupin Sansei 
Displayed : 
- Lupin : Kurita Kan`ichi
- Jigen : Kobayashi Kiyoshi
- Goemon : Namikawa Daisuke
- Mine : Sawashiro Miyuki

Right ones : 
- Lupin : Yamada Yasuo
- Jigen : Kobayashi Kiyoshi
- Goemon : Ootsuka Chikao
- Mine : Nikaidou Yukiko

ShokoClient :
![seiyuu](https://cloud.githubusercontent.com/assets/4798290/20237405/6d32e6e4-a8d1-11e6-854d-9ef3dd9bba26.PNG)
Anidb : 
![seiyuu2](https://cloud.githubusercontent.com/assets/4798290/20237407/8a1fa1fc-a8d1-11e6-9530-637e1880741b.PNG)

**Comment by revam** [comment]
Can't we use the data stored in the CrossRef_Anime_Staff table (and correct it if it's not correct)?

**Comment by harshithmohan** [comment]
Desktop/v1 issue.
Working properly in v3 api.
