### ISSUE TITLE
a Deprecated files list

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoServer#980]
i think we need a list of this, files that get a new version (v2 and so on) will push the older file into this list. 
the renamer already supports it, we just need to have a neat list of it so people can update the files they already have to the best version :D 

https://wiki.anidb.info/w/Files:Deprecated_files

the list should contain links to the old file and new file in anidb aswell as the group link (or group site in the anidb page)
version numbering could also be nice to be on display.

**Comment by revam** [comment]
I can look into it

**Comment by harshithmohan** [comment]
A big issue with this is not all anidb files are marked with a different version. People just upload it without specifying a version and now you have two v1(s). Personally, I don't think it's worth it, we can just use the multiple files utility, that shows exactly the same info
