### ISSUE TITLE
Renaming issue with episode numbers

### ISSUE THREAD

**Issue by SL-Gundam** [ShokoAnime/ShokoServer#981]
See the selected file in the screenshot below.
This file is actually episode 1 and special 2 of Ghost in the Shell 2nd GIG
So the episode number should have been: 01-S02
This applies to all files of GITS SAC and GITS 2nd GIG

GITS Arise also has episode number issues because some files are connected to both GITS Arise and GITS Arise alternative architecture. This can be seen in the top 2 files in the screenshot below
Might be better in this case to only mention multiple episode numbers within the same series

![normal_entire collection](https://cloud.githubusercontent.com/assets/912973/18225423/422f5642-71f1-11e6-84bb-314b291adcac.png)

**Comment by revam** [comment]
> Could be an issue your with your renaming script but I think the issue is that we currently lack the ability to link the same file to two different episodes.

I don't know about the renamer scripts, but we technically support linking manual files to multiple episode entries (in the v3 api) as long as the episodes are listed on anidb (and made available locally).

**Comment by revam** [comment]
And i mean multiple episodes from different series.

**Comment by da3dsoul** [comment]
I don't remember, but a lot has changed there
