### ISSUE TITLE
auto naming parent group renames only group order and not display name

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoServer#984]
as the title says, when you rename a subgroup in a group of multiple series it will ask you if you want to rename the parent aswell to match what you just named the sub.
this will then rename the sorting name but not the display name to match.
which is many eyes might be more important as that is what you see and read.

![unknown](https://user-images.githubusercontent.com/8496821/35765954-f052cd24-08ce-11e8-935d-ea877be899db.png)

ofc when the client asks you it should rename both to match... unless an overwrite is already manually set (but thats for another issue)

**Comment by revam** [comment]
Fixed in https://github.com/ShokoAnime/ShokoServer/commit/ba21513fe568b4e671b6b8f73c542f151c5f59a5 and

**Comment by revam** [comment]
Nvm me. It was another issue

**Comment by harshithmohan** [comment]
This might be a desktop-only issue, have to check. 🤔

**Comment by revam** [comment]
It might be.  Haven't seen code to rename a parent group in Shoko Server yet.

**Comment by ElementalCrisis** [comment]
Desktop only issue, closing.
