### ISSUE TITLE
Error Message appearing in log file

### ISSUE THREAD

**Issue by vyressi** [ShokoAnime/ShokoServer#987]
Server Version: 
4.1.2.0

Desktop Version: 
4.1.1.0

Log files are non-informative aside from this entry.

Just received an error message, most likely related to the filename.  When I can replicate it I'll update this ticket.

```
12:46:42| --- MediaInfo threw an error on /anime/Trigun/01 - v2 The $$60,000,000,000.00 Man (KAA)   (640x480 DVD VC-1) (43FDAA29).avi: System.NullReferenceException: Object reference not set to an instance of an object.
   at Shoko.Server.Utilities.MediaInfoLib.MediaInfo.GetMediaInfo_New(String filename) in /usr/src/app/source/Shoko.Server/Utilities/MediaInfoLib/MediaInfo.cs:line 64

```
## STEPS TO REPRODUCE

This popped up when I was restarting shoko-server after a large rescan of my drop destination folder and adding the luarenamer plugin, doesn't seem to be impinging on normal functionality so far, but figured it might be notable.

**Comment by da3dsoul** [comment]
This is now fixed in dailies. If you aren't running dailies, I would wait for a stable release.
