### ISSUE TITLE
Have auto-linking respect purposely removed links from anime

### ISSUE THREAD

**Issue by krbrs** [ShokoAnime/ShokoServer#995]
## VERSION INFORMATION

Server Version: lastest daily

Desktop Version: latest daily

## DESCRIPTION

I am not using TVDB auto-matching, because it would just re-match removed false entries e.g. that "re:zero matched to 13 reasons why" or music videos (connected, etc.) to wrong entries it thinks are right, when TVDB data is updated.

I would love to have Shoko respect that I removed a TVDB match a.k.a. overridden match and not try to match it again whenever or why ever it tries to do it.

**Comment by da3dsoul** [comment]
It'll try to link things that aren't linked (yes, a problem), but if you link it correctly, then it shouldn't overwrite the link. Can you confirm or deny?

**Comment by krbrs** [comment]
I can confirm that if a link is present it does not overwrite it.

It just links to tvdb again, where a (wrong) link is removed from the entry.

**Comment by revam** [comment]
Done. In 4.2.0
