### ISSUE TITLE
Filter issues in Desktop

### ISSUE THREAD

**Issue by krbrs** [ShokoAnime/ShokoServer#996]
## VERSION INFORMATION

Server Version: latest daily

Desktop Version: latest daily

## DESCRIPTION

I depend on Filters which tell me that a Link is missing, because I don't use auto-linking for reasons (separate Issue in Server).

This doesn't seem to work (correctly) as newly added shows without a match don't show up with the filter in desktop.
The same happens for some shows, if others in the same parent group have a link present but not the child group with the new show.

e.g. this only shows 2 shows but not "Chiikawa" which was added recently 

<img width="404" alt="linking" src="https://user-images.githubusercontent.com/57227244/185639061-7bd0767e-b5c4-46ed-91a4-99020ee698cb.png">

(I re-created the "Link missing" filter to have not 18-restricted in and also if i tagged it should not nag anymore, lol)
but the same goes for the original filter "TvDB/MovieDB Link Missing"

I work my way around right now with using "All Groups" and sorting them by "Series Added Date".
But as this seems to check when the Parent Group was added, not the child group

## STEPS TO REPRODUCE

see above :-)

If you need further Information, please let me know!

**Comment by ElementalCrisis** [comment]
With the filter rewrite, this should no longer be an issue. I'm going to close for now but @krbrs once filtering is added in Web-UI, please try again and re-open if needed.

**Comment by krbrs** [comment]
It's still a caching issue in Desktop as it is fine on webui, so it's alright to close; thought I left a note on another issue which PR closed it and on dev chat
